// functions/knowledge/mistakes/concepts.js
// CATEGORY: mistakes (NEW, Phase 2) — common trader errors + why losing.

export const MISTAKES_CONCEPTS = [
  {
    id: 'why-traders-lose', category: 'mistakes', topic: 'Why Most Traders Lose', level: 'beginner',
    title: 'Why Most Traders Lose Money', intent: 'whylosing',
    concepts: ['why traders lose', 'mistakes', 'risk', 'psychology', 'mistakes'],
    questionPatterns: ['why do most traders lose money', 'why do traders fail', 'why am i losing money trading', 'reasons traders lose', 'why do 90 percent of traders lose'],
    canonical: {
      short: 'Most traders lose not from bad analysis but from poor risk and psychology: oversizing, no stop, revenge trading, and jumping strategies. The market is hard, but the account is usually killed by the trader, not the chart.',
      deep: 'The recurring causes are remarkably consistent — risking too much per trade, trading without a defined stop, chasing losses with bigger size, abandoning a plan after a couple of losses, and over-leveraging a small account. Notice none of these are "I picked the wrong indicator." Survival, fixed small risk, and emotional discipline fix the majority of losing. Naming the specific habit that is costing you is the first real step out of the losing column.',
    },
    responseObjective: 'mentor', desiredOutcome: 'see that losses are usually behavioural, then name the habit',
    relevanceTags: ['mistakes', 'why losing', 'psychology'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['overtrading', 'overleveraging', 'becoming-profitable'], prerequisites: [],
    nextSteps: ['trader-assessment'], followups: ['overtrading', 'revenge-trading'],
    riskNote: 'The account is usually killed by risk and psychology, not analysis.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'overtrading', category: 'mistakes', topic: 'Overtrading', level: 'beginner',
    title: 'Overtrading', intent: 'psychology',
    concepts: ['overtrading', 'boredom', 'discipline', 'patience', 'mistakes'],
    questionPatterns: ['what is overtrading', 'how do i stop overtrading', 'why do i overtrade', 'am i overtrading', 'overtrading explained'],
    canonical: {
      short: 'Overtrading is taking trades that are not really there — out of boredom, FOMO, or the urge to "make something happen." Each forced trade adds risk and cost for no edge, quietly bleeding the account.',
      deep: 'The market only offers your setup sometimes; the rest is waiting. Overtrading fills that wait with low-quality trades that dilute your edge and rack up spread/commission. The fixes are structural: a checklist that most ideas fail, a cap on trades per day, defined sessions, and reframing patience as active discipline. Fewer, higher-quality trades almost always beat a busy screen.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade only valid setups, not boredom',
    relevanceTags: ['mistakes', 'overtrading', 'discipline'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['patience', 'checklist', 'why-traders-lose'], prerequisites: ['trading-psychology'],
    nextSteps: ['checklist'], followups: ['patience', 'fomo'],
    riskNote: 'Every forced trade adds risk and cost with no edge — wait for the setup.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'overleveraging', category: 'mistakes', topic: 'Overleveraging', level: 'beginner',
    title: 'Overleveraging', intent: 'riskmgmt',
    concepts: ['overleveraging', 'oversizing', 'leverage', 'blow up', 'mistakes'],
    questionPatterns: ['what is overleveraging', 'why is overleveraging dangerous', 'how do i stop oversizing', 'am i using too much leverage', 'overleveraging explained'],
    canonical: {
      short: 'Overleveraging is putting on a position too big for the account — the fastest way to blow up. It turns a normal losing streak into a margin call and makes fear hijack every decision.',
      deep: 'Big size feels like the route to fast money but it is the route to zero: a few normal losses at oversized risk cause unrecoverable drawdown, and the emotional pressure of a large position destroys execution. The fix is mechanical — fix risk at ~1% per trade and let position size fall out of the stop distance, never the other way around. Small size is what keeps both the account and your judgement intact.',
    },
    responseObjective: 'warn', desiredOutcome: 'size from risk, never from greed',
    relevanceTags: ['mistakes', 'leverage', 'risk'],
    guidance: { tradeProblem: true },
    related: ['leverage', 'position-sizing', 'why-traders-lose'], prerequisites: ['position-sizing'],
    nextSteps: ['position-sizing'], followups: ['leverage', 'margin'],
    riskNote: 'Oversizing turns a normal losing streak into a blown account — cap risk at ~1%.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'no-stop-loss', category: 'mistakes', topic: 'Trading Without a Stop', level: 'beginner',
    title: 'Trading Without a Stop Loss', intent: 'riskmgmt',
    concepts: ['no stop loss', 'unlimited risk', 'hope', 'discipline', 'mistakes'],
    questionPatterns: ['why do i need a stop loss', 'is trading without a stop loss bad', 'what happens without a stop loss', 'should i always use a stop loss', 'trading without stop loss'],
    canonical: {
      short: 'Trading without a stop turns a small loss into an open-ended one — you are now relying on hope, the worst risk tool there is. One stop-less trade in the wrong direction can erase weeks of gains.',
      deep: 'A stop defines where your idea is wrong and caps the loss before you enter; without it, a losing trade can run until it threatens the whole account, and the temptation becomes "hold and hope it comes back." That is how single trades blow accounts. Always define invalidation first, place the stop beyond it, and size so that distance equals ~1% — the stop is not optional, it is the foundation of every trade.',
    },
    responseObjective: 'warn', desiredOutcome: 'always cap risk with a defined stop',
    relevanceTags: ['mistakes', 'stop loss', 'risk'],
    guidance: { tradeProblem: true },
    related: ['moving-stop-loss', 'position-sizing', 'why-traders-lose'], prerequisites: ['risk-per-trade'],
    nextSteps: ['moving-stop-loss'], followups: ['position-sizing', 'risk-per-trade'],
    riskNote: 'No stop = unlimited risk — define invalidation before every entry.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'moving-stop-loss', category: 'mistakes', topic: 'Moving the Stop Loss', level: 'beginner',
    title: 'Moving Your Stop Loss', intent: 'psychology',
    concepts: ['moving stop', 'widening stop', 'discipline', 'denial', 'mistakes'],
    questionPatterns: ['why shouldnt i move my stop loss', 'is it bad to move my stop', 'i keep moving my stop loss', 'should i widen my stop', 'moving stop loss mistake'],
    canonical: {
      short: 'Moving a stop further away to avoid being wrong converts a planned small loss into a large one — it is denial dressed up as flexibility. The market does not care about your hope; the original invalidation was the truth.',
      deep: 'When price approaches your stop, the urge to widen it "just a bit" feels protective but is the classic account-killer: you are increasing risk on a trade already going wrong. The only acceptable stop move is toward breakeven once the trade proves itself, never away from entry. If you find yourself widening stops, it is usually a sizing problem — smaller positions make honouring the stop emotionally easy.',
    },
    responseObjective: 'warn', desiredOutcome: 'honour the original stop; only ever tighten',
    relevanceTags: ['mistakes', 'stop loss', 'discipline'],
    guidance: { traderProblem: true },
    related: ['no-stop-loss', 'execution-discipline', 'trade-management'], prerequisites: ['execution-discipline'],
    nextSteps: ['execution-discipline'], followups: ['trade-management', 'fear-of-loss'],
    riskNote: 'Only move a stop toward breakeven, never away — widening is denial.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'chasing-price', category: 'mistakes', topic: 'Chasing Price', level: 'beginner',
    title: 'Chasing Price', intent: 'psychology',
    concepts: ['chasing', 'late entry', 'fomo', 'impulse', 'mistakes'],
    questionPatterns: ['what is chasing price', 'why do i enter late', 'how do i stop chasing trades', 'chasing the market', 'why do i buy the top'],
    canonical: {
      short: 'Chasing is entering after the move has already run, usually from FOMO — which means buying high or selling low with a huge stop or none. The fix is to let missed trades go; there is always another setup.',
      deep: 'When price is already extended, the good entry has passed and the risk-to-reward is upside down — yet FOMO screams to get in. Chasers routinely enter right before the pullback that stops them out. The discipline is to wait for price to come back to your level on a retracement, or simply skip it: a missed trade costs nothing, a chased one costs money. Patience and pre-defined entries dissolve the urge.',
    },
    responseObjective: 'mentor', desiredOutcome: 'wait for the level instead of chasing the move',
    relevanceTags: ['mistakes', 'chasing', 'fomo'],
    guidance: { traderProblem: true },
    related: ['fomo', 'overtrading', 'trend-continuation'], prerequisites: ['trading-psychology'],
    nextSteps: ['patience'], followups: ['fomo', 'trend-continuation'],
    riskNote: 'A missed trade costs nothing; a chased one costs money.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'averaging-down', category: 'mistakes', topic: 'Averaging Down', level: 'intermediate',
    title: 'Averaging Down Into Losers', intent: 'riskmgmt',
    concepts: ['averaging down', 'adding to losers', 'martingale', 'risk', 'mistakes'],
    questionPatterns: ['what is averaging down', 'is averaging down bad', 'why shouldnt i add to a losing trade', 'averaging down trading', 'should i average down'],
    canonical: {
      short: 'Averaging down — adding to a losing position to lower your average price — increases risk on a trade already proven wrong. It feels clever and occasionally rescues you, which is exactly what makes it so dangerous.',
      deep: 'Each add-on grows your exposure precisely when the market is disagreeing with you, so the eventual loss (when it does not bounce) is magnified. The occasional save reinforces the habit until one trend wipes the account — this is the martingale trap. If a trade hits its stop, it is over; take the small loss. Scaling IN is only valid as a planned, pre-defined entry method with total risk fixed, never as a reaction to being underwater.',
    },
    responseObjective: 'warn', desiredOutcome: 'take the planned loss instead of adding to it',
    relevanceTags: ['mistakes', 'averaging down', 'risk'],
    guidance: { tradeProblem: true },
    related: ['no-stop-loss', 'capital-protection', 'overleveraging'], prerequisites: ['risk-per-trade'],
    nextSteps: ['capital-protection'], followups: ['overleveraging', 'why-traders-lose'],
    riskNote: 'Adding to a loser magnifies risk when the market disagrees — take the stop.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'cutting-winners-early', category: 'mistakes', topic: 'Cutting Winners Early', level: 'intermediate',
    title: 'Cutting Winners Too Early', intent: 'psychology',
    concepts: ['cutting winners', 'fear', 'risk reward', 'discipline', 'mistakes'],
    questionPatterns: ['why do i exit winners too early', 'how do i stop cutting winners short', 'i take profit too soon', 'cutting winners early', 'how to let winners run'],
    canonical: {
      short: 'Cutting winners early — snatching tiny profits from fear of giving them back — wrecks your risk-to-reward and leaves you with small wins and full-sized losses. It is the mirror image of letting losers run.',
      deep: 'The fear of a winner turning into a loser makes traders exit at +0.5R, but if losses are -1R, the math never works. The fix is a pre-set target from structure and a rule to let the trade reach it (or trail by structure), removing the in-the-moment urge to grab profit. Often the root is oversizing — when the position is too big, every fluctuation feels threatening; smaller size lets winners breathe.',
    },
    responseObjective: 'mentor', desiredOutcome: 'let winners reach planned targets for proper R:R',
    relevanceTags: ['mistakes', 'risk reward', 'discipline'],
    guidance: { traderProblem: true },
    related: ['risk-reward', 'trade-management', 'greed'], prerequisites: ['risk-reward'],
    nextSteps: ['trade-management'], followups: ['risk-reward', 'fear-of-loss'],
    riskNote: 'Small wins with full-size losses never add up — let winners reach target.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'no-trading-plan', category: 'mistakes', topic: 'Trading Without a Plan', level: 'beginner',
    title: 'Trading Without a Plan', intent: 'strategy',
    concepts: ['no plan', 'improvising', 'random', 'discipline', 'mistakes'],
    questionPatterns: ['why do i need a trading plan', 'what happens if i trade without a plan', 'is trading without a plan bad', 'trading without a plan', 'why is improvising bad in trading'],
    canonical: {
      short: 'Trading without a plan means every decision is made under pressure in real time — which is when emotion wins. Without written rules you cannot be consistent, and without consistency you cannot improve.',
      deep: 'A plan converts trading from gambling into a process you can measure and refine. Without one, you take random setups, vary your risk by mood, and have nothing to review — so the same mistakes repeat invisibly. Even a one-page plan (setup, risk, limits, sessions) transforms results, because it pre-makes the decisions that emotion would otherwise hijack. The plan is the difference between practising a skill and just reacting.',
    },
    responseObjective: 'mentor', desiredOutcome: 'replace improvisation with a written process',
    relevanceTags: ['mistakes', 'planning'],
    guidance: { traderProblem: true },
    related: ['trading-plan', 'consistency', 'why-traders-lose'], prerequisites: [],
    nextSteps: ['trading-plan'], followups: ['consistency', 'trading-journal'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'ignoring-news', category: 'mistakes', topic: 'Ignoring Economic News', level: 'beginner',
    title: 'Ignoring High-Impact News', intent: 'macro',
    concepts: ['ignoring news', 'volatility', 'nfp', 'spread', 'mistakes'],
    questionPatterns: ['should i check news before trading', 'why did news blow past my stop', 'is it bad to trade during news', 'ignoring economic news mistake', 'why check the economic calendar'],
    canonical: {
      short: 'Ignoring the economic calendar gets traders caught holding into high-impact news, where spreads blow out and price gaps past stops. A ten-second calendar check prevents most of these avoidable losses.',
      deep: 'Releases like NFP, CPI and FOMC can move markets violently in seconds, and a stop may fill far from where you placed it. The mistake is not checking what is scheduled and getting blindsided while oversized. Build it into your routine: scan the calendar before each session, be flat or reduced into red-folder events, and only trade the aftermath once structure reforms. Awareness, not prediction, is the goal.',
    },
    responseObjective: 'warn', desiredOutcome: 'check the calendar and avoid being caught in news',
    relevanceTags: ['mistakes', 'news', 'macro'],
    guidance: { tradeProblem: true },
    related: ['economic-news-impact', 'gold-news-reactions', 'trading-routine'], prerequisites: [],
    nextSteps: ['economic-news-impact'], followups: ['gold-news-reactions', 'trading-routine'],
    riskNote: 'Spreads widen and stops slip in news — check the calendar, be flat or reduced.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
