// functions/knowledge/macro/concepts.js
// CATEGORY: macro (NEW, Phase 7) — central banks, rates, intermarket, order-flow tools.

export const MACRO_CONCEPTS = [
  {
    id: 'central-banks', category: 'macro', topic: 'Central Banks', level: 'intermediate',
    title: 'How Central Banks Move Markets', intent: 'macro',
    concepts: ['central banks', 'fed', 'monetary policy', 'rates'],
    questionPatterns: ['how do central banks affect markets', 'what does the fed do', 'why do central banks matter for trading', 'central bank impact on gold', 'how does monetary policy work'],
    canonical: {
      short: 'Central banks set interest rates and steer money supply, making them the biggest macro force in markets. Rate decisions and their tone (hawkish vs dovish) move the dollar, yields, and gold for weeks.',
      deep: 'When a central bank raises rates or signals it will, its currency tends to strengthen and non-yielding assets like gold come under pressure; dovish shifts do the reverse. Beyond the decision itself, the statement and press conference set expectations that drive the following weeks. You do not predict them — you respect them: know the schedule, expect volatility, and trade with the macro lean rather than against it.',
    },
    responseObjective: 'educate', desiredOutcome: 'respect central-bank policy as the dominant macro driver',
    relevanceTags: ['macro', 'central banks'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading normally through a rate decision', 'ignoring the statement tone and only watching the number'],
    misconceptions: ['the rate number alone moves price — actually the tone vs expectations matters more'],
    related: ['interest-rates', 'inflation', 'monetary-policy'], prerequisites: ['economic-news-impact'],
    nextSteps: ['interest-rates'], followups: ['inflation', 'economic-calendar'],
    riskNote: 'Be flat or reduced into rate decisions — volatility and slippage spike.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'interest-rates', category: 'macro', topic: 'Interest Rates', level: 'intermediate',
    title: 'Interest Rates and Trading', intent: 'macro',
    concepts: ['interest rates', 'rate hikes', 'yields', 'dollar'],
    questionPatterns: ['how do interest rates affect trading', 'why do rate hikes matter', 'interest rates and gold', 'how do rates move the dollar', 'what happens when rates rise'],
    canonical: {
      short: 'Interest rates are the price of money: higher rates strengthen a currency and pressure non-yielding gold; lower rates do the opposite. Rate expectations, not just current levels, drive the moves.',
      deep: 'Markets price rate expectations constantly, so a hike that was fully expected may barely move price, while a surprise shift is explosive. Higher rates raise the opportunity cost of holding gold and tend to lift the dollar; cuts ease both. Track the direction of expectations to know the macro current beneath your trades — fighting it with short-term setups is low-probability.',
    },
    responseObjective: 'educate', desiredOutcome: 'read rate expectations as the macro current',
    relevanceTags: ['macro', 'interest rates'],
    guidance: { tradeProblem: true },
    commonMistakes: ['reacting to the rate level instead of the change in expectations'],
    misconceptions: ['a rate hike always lifts the currency — it depends on whether it was expected'],
    related: ['central-banks', 'yield-curve', 'gold-yields-correlation'], prerequisites: ['central-banks'],
    nextSteps: ['yield-curve'], followups: ['inflation', 'bond-market'],
    riskNote: 'Macro context improves odds; it never replaces a defined stop and 1% risk.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'inflation', category: 'macro', topic: 'Inflation', level: 'intermediate',
    title: 'Inflation and Markets', intent: 'macro',
    concepts: ['inflation', 'cpi', 'purchasing power', 'gold'],
    questionPatterns: ['how does inflation affect trading', 'what is cpi', 'inflation and gold', 'why does inflation matter for markets', 'how does inflation move the dollar'],
    canonical: {
      short: 'Inflation (often read via CPI) drives central-bank policy: hot inflation pushes rates higher, which lifts the dollar and pressures gold short-term, though gold is a long-run inflation hedge. CPI days are high-volatility events.',
      deep: 'Inflation data shapes rate expectations more than almost anything, so CPI releases routinely move gold, the dollar, and yields sharply. The relationship is nuanced: hot inflation can pressure gold via higher expected rates in the short term, even as gold is viewed as an inflation store of value over years. For trading, the key is the volatility around the release — be flat or reduced into CPI and trade the aftermath.',
    },
    responseObjective: 'educate', desiredOutcome: 'understand inflation as the driver of rate expectations',
    relevanceTags: ['macro', 'inflation', 'cpi'],
    guidance: { tradeProblem: true },
    commonMistakes: ['holding full size through a CPI release'],
    misconceptions: ['high inflation always lifts gold immediately — short-term rate effects can pressure it first'],
    related: ['interest-rates', 'central-banks', 'economic-news-impact'], prerequisites: ['central-banks'],
    nextSteps: ['intermarket-analysis'], followups: ['interest-rates', 'economic-calendar'],
    riskNote: 'CPI is a red-folder event — reduce size or stand aside.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'monetary-policy', category: 'macro', topic: 'Monetary Policy', level: 'advanced',
    title: 'Monetary Policy Cycles', intent: 'macro',
    concepts: ['monetary policy', 'tightening', 'easing', 'liquidity'],
    questionPatterns: ['what is monetary policy', 'what is tightening and easing', 'how does monetary policy affect markets', 'monetary policy cycle', 'what is quantitative easing'],
    canonical: {
      short: 'Monetary policy swings between tightening (higher rates, draining liquidity) and easing (lower rates, adding liquidity). Knowing which regime you are in tells you the macro tailwind or headwind for risk assets and gold.',
      deep: 'Tightening cycles typically strengthen the currency and pressure risk assets and non-yielding gold; easing cycles flood liquidity and tend to lift them. These regimes last months to years and set the backdrop for every shorter-term trade. You do not trade policy directly, but aligning your bias with the prevailing regime — and respecting the volatility at policy turning points — keeps you on the right side of the tide.',
    },
    responseObjective: 'educate', desiredOutcome: 'align bias with the prevailing policy regime',
    relevanceTags: ['macro', 'monetary policy'],
    guidance: { tradeProblem: true },
    commonMistakes: ['fighting the policy regime with counter-trend swing trades'],
    related: ['central-banks', 'interest-rates', 'market-cycles'], prerequisites: ['interest-rates'],
    nextSteps: ['intermarket-analysis'], followups: ['market-cycles', 'risk-on-risk-off'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'yield-curve', category: 'macro', topic: 'The Yield Curve', level: 'advanced',
    title: 'Reading the Yield Curve', intent: 'macro',
    concepts: ['yield curve', 'inversion', 'recession', 'bonds'],
    questionPatterns: ['what is the yield curve', 'what is a yield curve inversion', 'why does the yield curve matter', 'yield curve and recession', 'how to read the yield curve'],
    canonical: {
      short: 'The yield curve plots bond yields across maturities; its shape signals growth expectations. An inversion (short rates above long) has historically warned of recession — a slow-moving macro context, not a trade trigger.',
      deep: 'Normally longer maturities yield more; when short yields exceed long ones (inversion), the market expects slowing growth and future cuts — a classic recession warning. For traders this is background regime information that shapes risk appetite over months, not an entry signal. Use it to understand the macro mood (risk-on vs risk-off tendencies) rather than to time individual trades.',
    },
    responseObjective: 'educate', desiredOutcome: 'use the curve as slow macro context, not a trigger',
    relevanceTags: ['macro', 'yield curve'],
    guidance: { tradeProblem: true },
    commonMistakes: ['treating a yield-curve inversion as a short-term trade signal'],
    related: ['bond-market', 'interest-rates', 'intermarket-analysis'], prerequisites: ['bond-market'],
    nextSteps: ['intermarket-analysis'], followups: ['monetary-policy', 'risk-on-risk-off'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'intermarket-analysis', category: 'macro', topic: 'Intermarket Analysis', level: 'advanced',
    title: 'Intermarket Analysis', intent: 'macro',
    concepts: ['intermarket', 'correlation', 'dollar', 'yields', 'stocks'],
    questionPatterns: ['what is intermarket analysis', 'how do markets affect each other', 'intermarket analysis explained', 'how do stocks bonds and gold relate', 'how to use intermarket correlations'],
    canonical: {
      short: 'Intermarket analysis reads how asset classes interact — dollar, yields, equities, commodities — to confirm a bias. When several markets agree (e.g. weak dollar + falling yields supporting gold), conviction rises.',
      deep: 'No market trades in isolation: the dollar and yields move gold, risk sentiment links equities and currencies, and commodities reflect growth. Checking whether related markets confirm your idea is powerful confluence — if you want to buy gold and the dollar and yields are falling, the macro picture agrees. It is context, not a trigger; combine it with structure and a defined entry rather than trading correlations alone.',
    },
    responseObjective: 'educate', desiredOutcome: 'confirm bias by reading related markets together',
    relevanceTags: ['macro', 'intermarket', 'correlation'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading a correlation directly without a structural entry'],
    misconceptions: ['correlations are fixed — they shift with the macro regime'],
    related: ['dollar-index', 'bond-market', 'risk-on-risk-off'], prerequisites: ['dollar-index'],
    nextSteps: ['risk-on-risk-off'], followups: ['gold-dxy-correlation', 'cot-report'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'risk-on-risk-off', category: 'macro', topic: 'Risk-On / Risk-Off', level: 'intermediate',
    title: 'Risk-On and Risk-Off Sentiment', intent: 'macro',
    concepts: ['risk on', 'risk off', 'sentiment', 'safe haven'],
    questionPatterns: ['what is risk on risk off', 'what does risk off mean', 'risk on risk off explained', 'how does sentiment affect gold', 'what is a safe haven trade'],
    canonical: {
      short: 'Risk-on means money flows to growth assets; risk-off means it flees to safe havens like the dollar, yen, and sometimes gold. Reading the prevailing mood tells you which way capital is leaning across markets.',
      deep: 'In risk-on, equities and higher-yielding currencies rise as investors seek return; in risk-off, capital rushes to safety, lifting the dollar, yen, bonds, and often gold. Knowing the mood explains otherwise confusing moves and sharpens bias — gold can rally in risk-off panic even when rates argue against it. It is a sentiment lens layered over structure, not a standalone signal.',
    },
    responseObjective: 'educate', desiredOutcome: 'read market mood to anticipate capital flows',
    relevanceTags: ['macro', 'sentiment'],
    guidance: { tradeProblem: true },
    commonMistakes: ['ignoring risk-off flows and trading gold purely on rates'],
    related: ['intermarket-analysis', 'dollar-index', 'gold-dxy-correlation'], prerequisites: ['intermarket-analysis'],
    nextSteps: ['cot-report'], followups: ['dollar-index', 'monetary-policy'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'cot-report', category: 'macro', topic: 'COT Reports', level: 'advanced',
    title: 'Commitment of Traders (COT) Reports', intent: 'macro',
    concepts: ['cot report', 'positioning', 'institutional', 'sentiment'],
    questionPatterns: ['what is the cot report', 'how to use commitment of traders', 'cot report explained', 'what does cot tell you', 'how to read positioning data'],
    canonical: {
      short: 'The COT report shows how large institutional traders are positioned in futures. Extreme positioning can hint at crowded trades vulnerable to reversal — a slow sentiment gauge, not a timing tool.',
      deep: 'Published weekly, COT reveals whether big speculators and commercials are net long or short. Crowded extremes (everyone leaning one way) often precede reversals as the trade runs out of new buyers. It is positional context measured in weeks, useful for bias and spotting stretched sentiment, but far too slow for entries — pair it with structure and timing tools for actual trades.',
    },
    responseObjective: 'educate', desiredOutcome: 'use positioning extremes as slow sentiment context',
    relevanceTags: ['macro', 'cot', 'positioning'],
    guidance: { tradeProblem: true },
    commonMistakes: ['using COT positioning to time intraday entries'],
    related: ['risk-on-risk-off', 'intermarket-analysis', 'institutional-order-flow'], prerequisites: ['intermarket-analysis'],
    nextSteps: ['volume-profile'], followups: ['institutional-order-flow', 'auction-market-theory'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'volume-profile', category: 'macro', topic: 'Volume Profile', level: 'advanced',
    title: 'Volume Profile', intent: 'technical',
    concepts: ['volume profile', 'value area', 'point of control', 'auction'],
    questionPatterns: ['what is volume profile', 'how to use volume profile', 'what is point of control', 'volume profile explained', 'what is the value area'],
    canonical: {
      short: 'Volume profile shows how much trading happened at each price, revealing high-volume nodes (acceptance) and low-volume gaps (rejection). The point of control and value area mark where price is "fair" and where it moves fast.',
      deep: 'Rather than time, volume profile maps volume by price: the point of control is the most-traded price, the value area holds the bulk of activity, and low-volume nodes are areas price tends to move through quickly. High-volume nodes act like magnets and support/resistance; low-volume gaps get traversed fast. Use it to place targets and stops around where the market actually accepted or rejected price.',
    },
    responseObjective: 'educate', desiredOutcome: 'read acceptance/rejection from volume by price',
    relevanceTags: ['macro', 'volume profile'],
    guidance: { tradeProblem: true },
    commonMistakes: ['treating every volume node as a guaranteed reversal'],
    related: ['auction-market-theory', 'support-resistance', 'liquidity-void'], prerequisites: ['support-resistance'],
    nextSteps: ['auction-market-theory'], followups: ['liquidity-void', 'market-cycles'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'auction-market-theory', category: 'macro', topic: 'Auction Market Theory', level: 'advanced',
    title: 'Auction Market Theory', intent: 'technical',
    concepts: ['auction market theory', 'value', 'balance', 'imbalance'],
    questionPatterns: ['what is auction market theory', 'how does auction market theory work', 'auction market theory explained', 'what is value in trading', 'balance vs imbalance market'],
    canonical: {
      short: 'Auction Market Theory views price as a continuous auction seeking value: markets balance (range) when buyers and sellers agree, and imbalance (trend) when they do not. It is the logic beneath ranges, breakouts, and volume profile.',
      deep: 'Price probes higher to find sellers and lower to find buyers, building value where trade is accepted (balance/range) and expanding when one side dominates (imbalance/trend). This framework unifies many concepts: ranges are balance, breakouts are imbalance, volume profile maps accepted value. Thinking in auction terms helps you anticipate whether the market wants to rotate within value or expand away from it.',
    },
    responseObjective: 'educate', desiredOutcome: 'read markets as a value-seeking auction',
    relevanceTags: ['macro', 'auction', 'value'],
    guidance: { tradeProblem: true },
    commonMistakes: ['forcing trend tactics during a balanced (range) auction'],
    related: ['volume-profile', 'market-cycles', 'range-market'], prerequisites: ['volume-profile', 'market-cycles'],
    nextSteps: ['algorithmic-behaviour'], followups: ['range-market', 'accumulation-distribution'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'algorithmic-behaviour', category: 'macro', topic: 'Algorithmic Behaviour', level: 'advanced',
    title: 'Algorithmic Market Behaviour', intent: 'technical',
    concepts: ['algorithms', 'hft', 'liquidity', 'institutional'],
    questionPatterns: ['how do algorithms affect markets', 'what is algorithmic trading behaviour', 'how do bots move price', 'algorithmic behaviour explained', 'do algos hunt stops'],
    canonical: {
      short: 'Much of modern volume is algorithmic: programs that provide liquidity, chase momentum, and target obvious stop clusters. Understanding this explains why price spikes through obvious levels and reverses so cleanly.',
      deep: 'Algorithms react in milliseconds to liquidity and order flow, often probing obvious highs/lows where stops sit, then reversing — the mechanical reality behind "stop hunts." They also reinforce momentum once a level breaks. You will not out-speed them, but you can stop being their liquidity: avoid placing stops on obvious levels, expect sweeps before real moves, and trade the reclaim. It reframes erratic price as rational liquidity-seeking.',
    },
    responseObjective: 'educate', desiredOutcome: 'stop being algorithmic liquidity; trade the reclaim',
    relevanceTags: ['macro', 'algorithms', 'liquidity'],
    guidance: { tradeProblem: true },
    commonMistakes: ['placing stops exactly on the obvious level algos target'],
    related: ['liquidity-engineering', 'institutional-order-flow', 'stop-hunt-model'], prerequisites: ['liquidity-engineering'],
    nextSteps: ['intermarket-analysis'], followups: ['stop-hunt-model', 'institutional-order-flow'],
    riskNote: 'Hide stops away from obvious levels — that is exactly what algos target.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'macro-fundamentals', category: 'macro', topic: 'Macro Fundamentals', level: 'intermediate',
    title: 'Macro Fundamentals for Traders', intent: 'macro',
    concepts: ['macro', 'fundamentals', 'big picture', 'drivers'],
    questionPatterns: ['what are macro fundamentals', 'how much fundamentals do i need to trade', 'do technical traders need macro', 'macro fundamentals for trading', 'how to use fundamentals'],
    canonical: {
      short: 'Macro fundamentals are the big-picture drivers — rates, inflation, growth, and sentiment — that set the tide your technical trades swim in. You do not need to be an economist, just aware of which way the current flows.',
      deep: 'Even a pure technical trader benefits from knowing the dominant macro theme: which way rates and the dollar lean, what major events are scheduled, and whether sentiment is risk-on or risk-off. This stops you from fighting a strong current with counter-trend setups and from getting blindsided by news. The goal is awareness and bias, not forecasting — let structure time the trade, and let macro tell you which side has the wind.',
    },
    responseObjective: 'educate', desiredOutcome: 'use macro for bias and awareness, not forecasting',
    relevanceTags: ['macro', 'fundamentals'],
    guidance: { tradeProblem: true },
    commonMistakes: ['ignoring macro entirely and getting blindsided by scheduled news'],
    related: ['central-banks', 'intermarket-analysis', 'economic-calendar'], prerequisites: [],
    nextSteps: ['central-banks'], followups: ['intermarket-analysis', 'economic-calendar'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
