// functions/knowledge/markets/concepts.js
// CATEGORY: markets (NEW, Phase 5) — macro drivers, cycles, volatility, styles.

export const MARKETS_CONCEPTS = [
  {
    id: 'dollar-index', category: 'markets', topic: 'The Dollar Index (DXY)', level: 'intermediate',
    title: 'The Dollar Index (DXY)', intent: 'macro',
    concepts: ['dxy', 'dollar index', 'usd strength', 'correlation'],
    questionPatterns: ['what is the dollar index', 'what is dxy', 'how does dxy affect trading', 'why does dxy matter', 'dollar index explained'],
    canonical: {
      short: 'The Dollar Index (DXY) measures the US dollar against a basket of major currencies. It is a fast read on dollar strength — and since gold and many pairs move inverse to it, DXY is a powerful confluence tool.',
      deep: 'When DXY rises, the dollar is broadly strong, which typically pressures gold and dollar-quoted assets; when it falls, they tend to rise. Use it as a second opinion: if you want to buy gold, a weakening DXY supports the idea. It is confluence, not a signal, and the relationship can loosen in pure risk-off panics — so weigh it alongside structure, never alone.',
    },
    responseObjective: 'educate', desiredOutcome: 'use DXY as macro confluence',
    relevanceTags: ['markets', 'dxy', 'correlation'],
    guidance: { tradeProblem: true },
    related: ['gold-dxy-correlation', 'bond-market', 'correlation'], prerequisites: [],
    nextSteps: ['bond-market'], followups: ['gold-dxy-correlation', 'correlation'],
    riskNote: 'DXY is confluence, not a guarantee — it can decouple in risk-off moves.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'bond-market', category: 'markets', topic: 'Bonds and Yields', level: 'advanced',
    title: 'The Bond Market and Yields', intent: 'macro',
    concepts: ['bonds', 'yields', 'interest rates', 'macro'],
    questionPatterns: ['how does the bond market affect trading', 'what are bond yields', 'why do yields matter for gold', 'how do interest rates affect markets', 'bond market explained'],
    canonical: {
      short: 'Bond yields reflect the cost of money and the market\'s rate expectations. Rising real yields pressure non-yielding assets like gold; falling yields support them — so yields set the macro tide beneath your trades.',
      deep: 'Yields rise when markets expect higher rates or inflation premium; since gold pays no interest, higher real yields raise its opportunity cost and weigh on it. You do not need to trade bonds, but knowing the yield direction tells you whether you are trading with or against the macro current — and fighting that current with short-term setups is how good charts still lose.',
    },
    responseObjective: 'educate', desiredOutcome: 'read the macro tide via yields',
    relevanceTags: ['markets', 'yields', 'macro'],
    guidance: { tradeProblem: true },
    related: ['dollar-index', 'gold-yields-correlation', 'economic-calendar'], prerequisites: ['dollar-index'],
    nextSteps: ['economic-calendar'], followups: ['gold-yields-correlation', 'market-cycles'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'economic-calendar', category: 'markets', topic: 'The Economic Calendar', level: 'beginner',
    title: 'Using the Economic Calendar', intent: 'macro',
    concepts: ['economic calendar', 'news', 'events', 'preparation'],
    questionPatterns: ['what is the economic calendar', 'how to use the economic calendar', 'why check the economic calendar', 'what news events matter', 'economic calendar for trading'],
    canonical: {
      short: 'The economic calendar lists scheduled releases and their expected impact. A ten-second check before each session tells you when volatility is coming so news never blindsides you mid-trade.',
      deep: 'Filter for high-impact events (NFP, CPI, FOMC, central-bank decisions) on your instruments and note the times in your timezone. Be flat or reduced into red-folder events, and trade the aftermath once structure reforms. The calendar is about awareness, not prediction — knowing when the storm hits is enough to avoid being caught oversized in it.',
    },
    responseObjective: 'educate', desiredOutcome: 'prepare for scheduled volatility',
    relevanceTags: ['markets', 'calendar', 'news'],
    guidance: { tradeProblem: true },
    related: ['economic-news-impact', 'ignoring-news', 'daily-routine'], prerequisites: [],
    nextSteps: ['economic-news-impact'], followups: ['daily-routine', 'bond-market'],
    riskNote: 'Be flat or reduced into high-impact news — spreads widen and stops slip.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'market-cycles', category: 'markets', topic: 'Market Cycles', level: 'advanced',
    title: 'Understanding Market Cycles', intent: 'technical',
    concepts: ['market cycles', 'phases', 'trend range', 'macro'],
    questionPatterns: ['what are market cycles', 'how do market cycles work', 'phases of a market cycle', 'market cycle explained', 'how to trade different market phases'],
    canonical: {
      short: 'Markets cycle between expansion (trending) and consolidation (ranging). Knowing the current phase tells you which playbook to run — trend-following in expansion, range/breakout tactics in consolidation.',
      deep: 'Price alternates between trending legs and balancing ranges where positions are built before the next expansion. Trying to trend-trade a range gets chopped; trying to fade a strong expansion gets run over. Identify the phase first — then apply trend, range, or breakout models accordingly. Matching tactic to cycle phase is a higher-order edge that sits above any single setup.',
    },
    responseObjective: 'educate', desiredOutcome: 'match tactics to the current market phase',
    relevanceTags: ['markets', 'cycles'],
    guidance: { tradeProblem: true },
    related: ['trending-market', 'range-market', 'volatility-regimes'], prerequisites: ['trending-market', 'range-market'],
    nextSteps: ['volatility-regimes'], followups: ['trend-trading', 'range-trading'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'volatility-regimes', category: 'markets', topic: 'Volatility Regimes', level: 'advanced',
    title: 'Trading Different Volatility Regimes', intent: 'technical',
    concepts: ['volatility', 'atr', 'regime', 'risk'],
    questionPatterns: ['what is a volatility regime', 'how does volatility affect trading', 'high vs low volatility trading', 'how to adapt to volatility', 'volatility regimes explained'],
    canonical: {
      short: 'Volatility regimes are stretches of calm or turbulence, and they should change how you trade: wider stops and smaller size in high volatility, tighter ranges and patience in low. The same fixed size in every regime quietly over-risks the wild ones.',
      deep: 'Measure typical range (ATR is a quick proxy) and adapt: in high volatility, widen stops to survive the noise and shrink lots so risk stays ~1%; in low volatility, expect smaller moves and ranges. News and session opens spike volatility temporarily. Adapting size and stop to the regime keeps your risk constant and your edge intact across very different conditions.',
    },
    responseObjective: 'educate', desiredOutcome: 'adapt stop and size to the volatility regime',
    relevanceTags: ['markets', 'volatility', 'risk'],
    guidance: { tradeProblem: true },
    related: ['forex-volatility', 'gold-volatility', 'market-cycles'], prerequisites: [],
    nextSteps: ['portfolio-risk'], followups: ['market-cycles', 'gold-volatility'],
    riskNote: 'Match size to volatility so 1% risk stays 1% in every regime.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'portfolio-risk', category: 'markets', topic: 'Portfolio Risk', level: 'advanced',
    title: 'Managing Portfolio Risk', intent: 'riskmgmt',
    concepts: ['portfolio risk', 'correlation', 'total exposure', 'risk'],
    questionPatterns: ['what is portfolio risk', 'how to manage total exposure', 'how many trades at once', 'correlated trades risk', 'portfolio risk management'],
    canonical: {
      short: 'Portfolio risk is your TOTAL exposure across all open trades, not the risk of one. Two correlated positions are secretly one bigger bet, so cap combined risk to avoid a single market move hitting everything at once.',
      deep: 'If you risk 1% on five correlated longs, a single adverse move can cost 5% — that is hidden concentration. Manage it by capping total open risk (e.g. 2–3% across all trades) and counting correlated positions as one. Diversify across uncorrelated ideas, or reduce size when stacking related trades. Thinking in portfolio terms prevents the "many small trades, one big loss" trap.',
    },
    responseObjective: 'warn', desiredOutcome: 'cap total correlated exposure, not just per-trade risk',
    relevanceTags: ['markets', 'portfolio', 'risk'],
    guidance: { tradeProblem: true },
    related: ['correlation', 'risk-per-trade', 'volatility-regimes'], prerequisites: ['correlation', 'risk-per-trade'],
    nextSteps: ['risk-scaling'], followups: ['correlation', 'max-drawdown'],
    riskNote: 'Correlated trades compound risk — cap total open exposure, not just each trade.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'day-trading', category: 'markets', topic: 'Day Trading', level: 'intermediate',
    title: 'Day Trading Explained', intent: 'strategy',
    concepts: ['day trading', 'intraday', 'no overnight', 'style'],
    questionPatterns: ['what is day trading', 'how does day trading work', 'is day trading good for beginners', 'day trading vs swing trading', 'day trading explained'],
    canonical: {
      short: 'Day trading opens and closes positions within the same day, avoiding overnight risk but demanding focus during active sessions. It sits between scalping and swing trading in pace and screen time.',
      deep: 'Intraday traders work the London and New York sessions, taking a handful of quality setups and flattening before the close to avoid overnight gaps and swap. It needs discipline and availability during the right hours, plus tight cost control since trades are frequent. It is viable for those who can focus in-session, but the same fixed-risk rules apply — frequency must never become overtrading.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge whether intraday pace fits you',
    relevanceTags: ['markets', 'day trading', 'style'],
    guidance: { tradeProblem: true },
    related: ['scalping', 'swing-trading', 'position-trading'], prerequisites: ['trading-style-fit'],
    nextSteps: ['position-trading'], followups: ['swing-trading', 'forex-sessions'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'position-trading', category: 'markets', topic: 'Position Trading', level: 'advanced',
    title: 'Position Trading Explained', intent: 'strategy',
    concepts: ['position trading', 'long term', 'macro', 'style'],
    questionPatterns: ['what is position trading', 'how does position trading work', 'position trading vs swing trading', 'long term trading style', 'position trading explained'],
    canonical: {
      short: 'Position trading holds for weeks to months, riding major trends driven by macro themes. It needs the widest stops, the smallest relative size, and the patience to ignore daily noise entirely.',
      deep: 'Position traders align with big-picture drivers (rates, yields, macro cycles) and weekly structure, accepting deep pullbacks for very large moves. It demands strong conviction, robust capital to weather swings, and minimal screen time. Swap and overnight exposure matter over long holds. It suits patient, macro-minded traders and is the opposite temperament to scalping — the key is matching style to your nature.',
    },
    responseObjective: 'educate', desiredOutcome: 'understand the longest-horizon trading style',
    relevanceTags: ['markets', 'position trading', 'style'],
    guidance: { tradeProblem: true },
    related: ['day-trading', 'swing-trading', 'market-cycles'], prerequisites: ['trading-style-fit'],
    nextSteps: ['market-cycles'], followups: ['swing-trading', 'carry-trade'],
    riskNote: 'Long holds need the smallest relative size and account for swap.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
