// functions/knowledge/desk/concepts.js
// CATEGORY: desk (NEW, Phase 11) — professional trading-desk operations & protocols.

export const DESK_CONCEPTS = [
  {
    id: 'trading-desk-operations', category: 'desk', topic: 'Trading Desk Operations', level: 'advanced',
    title: 'How a Trading Desk Operates', intent: 'psychology',
    concepts: ['trading desk', 'operations', 'process', 'professional'],
    questionPatterns: ['how does a trading desk operate', 'what is a trading desk routine', 'trading desk operations', 'how do professional desks work', 'how to run my trading like a desk'],
    canonical: {
      short: 'A trading desk runs on process, not impulse: pre-market prep, defined session protocols, strict risk budgets, live execution discipline, and structured review. Treating your own trading like a desk replaces emotion with operations.',
      deep: 'Desks operate as a repeatable pipeline — recon and bias before the open, checklists for each session, a risk budget allocated across ideas, mechanical execution, and a debrief after. Every step removes a place where emotion could leak in. Adopting this operational mindset solo is the single biggest upgrade from hobby trading: you stop reacting and start running a system.',
    },
    marketContext: 'Bank and prop desks run the same tight daily loop for years — the consistency of process, not flashes of brilliance, is what compounds their results.',
    responseObjective: 'mentor', desiredOutcome: 'run trading as a process-driven desk operation',
    relevanceTags: ['desk', 'operations', 'process'],
    guidance: { traderProblem: true },
    commonMistakes: ['trading reactively with no pre-defined daily process'],
    related: ['trading-routine-mastery', 'daily-routine', 'risk-budgeting'], prerequisites: ['trading-routine-mastery'],
    nextSteps: ['market-recon'], followups: ['daily-routine', 'desk-discipline'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'market-recon', category: 'desk', topic: 'Market Reconnaissance', level: 'intermediate',
    title: 'Pre-Market Reconnaissance', intent: 'strategy',
    concepts: ['recon', 'preparation', 'levels', 'bias'],
    questionPatterns: ['what is market reconnaissance', 'how to do pre-market analysis', 'what to check before the market opens', 'market recon explained', 'pre-market preparation'],
    canonical: {
      short: 'Market recon is the desk’s pre-open scan: mark key levels, read higher-timeframe structure, check the economic calendar, and set today’s bias and risk budget. Five focused minutes here prevents most reactive mistakes.',
      deep: 'Before any trade, the desk gathers intelligence: where are the key zones and liquidity, what is the higher-timeframe bias, what news is scheduled and when, and what is the risk budget for the day. This recon turns the session into a plan to execute rather than a screen to react to. Skipping it is how traders get blindsided by news or trade against the bigger picture.',
    },
    marketContext: 'Desks circulate a morning note with key levels and the day’s events before the open — every trader executes against the same prepared map.',
    responseObjective: 'mentor', desiredOutcome: 'prepare a session map before trading',
    relevanceTags: ['desk', 'preparation', 'recon'],
    guidance: { tradeProblem: true },
    commonMistakes: ['opening charts and trading without scanning levels and the calendar first'],
    related: ['daily-bias-formation', 'economic-calendar', 'daily-routine'], prerequisites: ['daily-routine'],
    nextSteps: ['daily-bias-formation'], followups: ['economic-calendar', 'watchlist-building'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'daily-bias-formation', category: 'desk', topic: 'Daily Bias Formation', level: 'intermediate',
    title: 'Forming a Daily Bias', intent: 'technical',
    concepts: ['daily bias', 'direction', 'top down', 'lean'],
    questionPatterns: ['how do i form a daily bias', 'what is daily bias formation', 'how to set my directional lean', 'daily bias for trading', 'how to decide market direction today'],
    canonical: {
      short: 'Daily bias is your directional lean for the session, set top-down from higher-timeframe structure and the day’s liquidity targets. It keeps you on one side instead of flip-flopping with every candle.',
      deep: 'Build bias before the open: read the daily/4H structure, identify which liquidity the market is likely drawing toward, and note key levels. That gives you a lean — looking for longs or shorts today — which lower-timeframe entries must agree with. A bias is a guide, not a vow; update it if structure breaks. But starting with one prevents scattered, contradictory trades within a session.',
    },
    marketContext: 'A trader with a clear "daily wants the buy-side above yesterday’s high" bias avoids the trap of shorting into that draw on a tempting 5-minute signal.',
    responseObjective: 'educate', desiredOutcome: 'set a top-down directional lean for the day',
    relevanceTags: ['desk', 'bias', 'direction'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading both directions within an hour with no daily lean'],
    related: ['structural-bias', 'multi-timeframe-analysis', 'market-recon'], prerequisites: ['structural-bias'],
    nextSteps: ['watchlist-building'], followups: ['multi-timeframe-analysis', 'session-models'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'watchlist-building', category: 'desk', topic: 'Building a Watchlist', level: 'beginner',
    title: 'Building a Trading Watchlist', intent: 'strategy',
    concepts: ['watchlist', 'focus', 'preparation', 'setups'],
    questionPatterns: ['how do i build a watchlist', 'what is a trading watchlist', 'how to choose what to trade today', 'watchlist building', 'how many instruments to watch'],
    canonical: {
      short: 'A watchlist narrows your focus to a few instruments showing potential setups, so you trade quality over chaos. Watching everything means executing nothing well — pick the handful where your edge is forming.',
      deep: 'Each session, shortlist the two or three instruments where your setup is developing near key levels, and ignore the rest. This concentrates attention, reduces overtrading, and lets you prepare specific plans (level, trigger, invalidation) rather than scanning dozens of charts reactively. A focused watchlist is a desk’s way of allocating its scarcest resource — attention — to the highest-probability opportunities.',
    },
    marketContext: 'A trader watching 20 pairs takes mediocre trades from FOMO; the same trader on a 3-name watchlist waits for A+ setups and overtrades far less.',
    responseObjective: 'mentor', desiredOutcome: 'focus attention on a few high-probability instruments',
    relevanceTags: ['desk', 'watchlist', 'focus'],
    guidance: { traderProblem: true },
    commonMistakes: ['watching too many instruments and forcing low-quality trades'],
    related: ['daily-bias-formation', 'screen-time-quality', 'overtrading'], prerequisites: [],
    nextSteps: ['risk-budgeting'], followups: ['screen-time-quality', 'market-recon'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'risk-budgeting', category: 'desk', topic: 'Risk Budgeting', level: 'advanced',
    title: 'Daily Risk Budgeting', intent: 'riskmgmt',
    concepts: ['risk budget', 'daily limit', 'allocation', 'discipline'],
    questionPatterns: ['what is a risk budget', 'how to set a daily risk budget', 'how much total risk per day', 'risk budgeting explained', 'how to allocate risk across trades'],
    canonical: {
      short: 'A risk budget is the total risk you will spend in a day or week, allocated across trades — for example 2% total, split as two 1% ideas. It caps the damage of a bad session before it starts.',
      deep: 'Rather than treating each trade in isolation, the desk sets a daily/weekly risk budget and allocates it: a fixed total open risk, a hard daily loss limit, and per-idea sizing within that. Once the budget is spent — whether via losses or open exposure — trading stops. This converts vague "risk management" into a concrete spending limit, preventing the death-by-a-thousand-trades that fixed per-trade risk alone can miss.',
    },
    marketContext: 'Prop desks assign each trader a daily loss limit; hit it and you are done for the day — a hard risk budget enforced as policy.',
    responseObjective: 'warn', desiredOutcome: 'cap total daily/weekly risk as a budget',
    relevanceTags: ['desk', 'risk budget', 'limit'],
    guidance: { tradeProblem: true },
    commonMistakes: ['managing only per-trade risk and ignoring total daily exposure'],
    related: ['daily-loss-limit', 'portfolio-risk', 'capital-allocation'], prerequisites: ['daily-loss-limit', 'portfolio-risk'],
    nextSteps: ['trade-allocation'], followups: ['capital-allocation', 'drawdown-protocol'],
    riskNote: 'When the daily risk budget is spent, stop — protect tomorrow.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'trade-allocation', category: 'desk', topic: 'Trade Allocation', level: 'advanced',
    title: 'Allocating Risk Across Trades', intent: 'riskmgmt',
    concepts: ['trade allocation', 'sizing', 'conviction', 'diversification'],
    questionPatterns: ['how do i allocate risk across trades', 'how much to risk on each setup', 'trade allocation explained', 'should i risk more on high conviction trades', 'how to size by conviction'],
    canonical: {
      short: 'Trade allocation distributes your risk budget across ideas — weighting higher-conviction, A+ setups a little more and capping correlated exposure. It is portfolio thinking applied to the day’s trades.',
      deep: 'Within the risk budget, not all trades deserve equal size: a clean, high-confluence setup may warrant your standard 1% while a marginal one gets half, and two correlated ideas should share, not double, the risk. This keeps your best edges weighted while preventing hidden concentration. Done consistently, allocation turns a pile of trades into a managed book where no single idea or theme can dominate the outcome.',
    },
    marketContext: 'A desk trader scaling a high-conviction trend setup slightly larger than a marginal counter-trend scalp is allocating risk by edge quality.',
    responseObjective: 'educate', desiredOutcome: 'weight risk by conviction within the budget',
    relevanceTags: ['desk', 'allocation', 'sizing'],
    guidance: { tradeProblem: true },
    commonMistakes: ['risking identically on weak and strong setups, or doubling correlated risk'],
    related: ['risk-budgeting', 'capital-allocation', 'professional-risk-models'], prerequisites: ['risk-budgeting'],
    nextSteps: ['scaling-protocol'], followups: ['capital-allocation', 'portfolio-risk'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'news-desk-protocol', category: 'desk', topic: 'News Event Protocol', level: 'intermediate',
    title: 'News Event Protocol', intent: 'macro',
    concepts: ['news protocol', 'high impact', 'volatility', 'rules'],
    questionPatterns: ['what is a news trading protocol', 'how to handle high impact news', 'rules for trading around news', 'news event protocol', 'should i close trades before news'],
    canonical: {
      short: 'A news protocol is your fixed rulebook for high-impact events: be flat or protected before the release, no new trades into it, and only trade the aftermath once structure reforms. It removes in-the-moment gambling around volatility.',
      deep: 'Define it once and follow it always: check the calendar in recon, reduce or close exposure before red-folder events (NFP, CPI, FOMC), never open fresh risk into the print, and wait for spreads to normalise and structure to form before trading the reaction. This protocol turns the most dangerous, gappy moments of the day into either a stand-aside or a disciplined post-event opportunity.',
    },
    marketContext: 'Desks routinely flatten or hedge into FOMC and trade only the post-conference move — a protocol, not a gut call each time.',
    responseObjective: 'warn', desiredOutcome: 'follow a fixed rulebook around high-impact news',
    relevanceTags: ['desk', 'news', 'protocol'],
    guidance: { tradeProblem: true },
    commonMistakes: ['opening fresh trades into a high-impact release'],
    related: ['economic-news-impact', 'fomc', 'gold-news-reactions'], prerequisites: ['economic-news-impact'],
    nextSteps: ['session-handover'], followups: ['fomc', 'economic-calendar'],
    riskNote: 'No new risk into red-folder news — flat or protected, trade the aftermath.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'session-handover', category: 'desk', topic: 'Session Handover', level: 'advanced',
    title: 'Session Handover and Continuity', intent: 'technical',
    concepts: ['session handover', 'continuity', 'levels', 'sessions'],
    questionPatterns: ['what is session handover', 'how do sessions connect', 'carrying bias between sessions', 'session handover explained', 'how to trade across london and new york'],
    canonical: {
      short: 'Session handover is carrying context forward — the levels London left, the liquidity still resting, the bias still valid — into the next session. Markets do not reset at each open; the story continues.',
      deep: 'A desk treats the day as continuous: the Asian range feeds London, London’s move and unfilled liquidity set up New York, and overnight levels matter the next day. Noting what each session left undone (untaken liquidity, open imbalances, the prevailing bias) lets you anticipate the next session rather than starting blind. Continuity of context is how multi-session traders stay aligned with the dominant move.',
    },
    marketContext: 'Liquidity left untouched at the London high is frequently targeted in New York — a handover the prepared trader anticipates.',
    responseObjective: 'educate', desiredOutcome: 'carry context across sessions for continuity',
    relevanceTags: ['desk', 'sessions', 'continuity'],
    guidance: { tradeProblem: true },
    commonMistakes: ['treating each session as a fresh start and ignoring prior levels'],
    related: ['session-models', 'killzones', 'liquidity-sweep'], prerequisites: ['session-models'],
    nextSteps: ['performance-attribution'], followups: ['killzones', 'liquidity-engineering'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'drawdown-protocol', category: 'desk', topic: 'Drawdown Protocol', level: 'advanced',
    title: 'Drawdown Protocol', intent: 'riskmgmt',
    concepts: ['drawdown protocol', 'rules', 'de-risk', 'recovery'],
    questionPatterns: ['what is a drawdown protocol', 'what to do in a drawdown', 'rules for handling drawdown', 'drawdown protocol explained', 'how to recover from a losing period'],
    canonical: {
      short: 'A drawdown protocol is a pre-set plan for losing periods: at defined drawdown levels you cut size, reduce frequency, or stop and review — automatically, before emotion takes over. It turns a slump into a controlled pause, not a spiral.',
      deep: 'Decide in advance: at, say, -5% cut size in half; at -8% drop to demo and review the week; never increase risk to "win it back." Because the rules are set when calm, you follow them when stressed. This converts the dangerous emotional response to losses — revenge and oversizing — into a mechanical de-risking that preserves capital and composure until conditions and execution improve.',
    },
    marketContext: 'Funds automatically cut gross exposure as drawdown deepens; the disciplined retail equivalent is halving size after a defined loss threshold.',
    responseObjective: 'recover', desiredOutcome: 'follow pre-set de-risking rules in a drawdown',
    relevanceTags: ['desk', 'drawdown', 'protocol'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    commonMistakes: ['increasing risk to win back losses during a drawdown'],
    related: ['max-drawdown', 'risk-after-losing-streak', 'risk-budgeting'], prerequisites: ['max-drawdown'],
    nextSteps: ['scaling-protocol'], followups: ['risk-after-losing-streak', 'account-recovery'],
    riskNote: 'Never increase risk to recover — cut size by rule and review.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'scaling-protocol', category: 'desk', topic: 'Scaling Protocol', level: 'advanced',
    title: 'Risk Scaling Protocol', intent: 'riskmgmt',
    concepts: ['scaling protocol', 'increase size', 'milestones', 'discipline'],
    questionPatterns: ['what is a scaling protocol', 'when do i increase my risk', 'rules for scaling up size', 'scaling protocol explained', 'how to grow size safely'],
    canonical: {
      short: 'A scaling protocol defines, in advance, the evidence required to increase size — a sustained equity-curve milestone with no rule breaches — and the small step you take. Size follows proven results, never confidence.',
      deep: 'Set objective triggers: after a defined stretch of consistent, disciplined profit at the current size, increase risk by a small increment (e.g. toward a planned ceiling), and step back down immediately if results wobble. Because the criteria are pre-set, scaling becomes a calm, evidence-based decision rather than an emotional one after a hot streak. It is the mirror of the drawdown protocol — both keep size tied to performance.',
    },
    marketContext: 'Prop scaling plans embody this — capital increases only after consistent milestones, never after a single big week.',
    responseObjective: 'mentor', desiredOutcome: 'scale size by pre-set, evidence-based rules',
    relevanceTags: ['desk', 'scaling', 'protocol'],
    guidance: { tradeProblem: true },
    commonMistakes: ['increasing size on the emotional high of a winning streak'],
    related: ['risk-scaling', 'drawdown-protocol', 'prop-scaling'], prerequisites: ['risk-scaling'],
    nextSteps: ['performance-attribution'], followups: ['prop-scaling', 'account-growth'],
    riskNote: 'Scale only on proven, rule-clean results — never on a hot-streak high.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'performance-attribution', category: 'desk', topic: 'Performance Attribution', level: 'advanced',
    title: 'Performance Attribution', intent: 'psychology',
    concepts: ['attribution', 'analysis', 'metrics', 'segments'],
    questionPatterns: ['what is performance attribution', 'how to attribute my trading results', 'where do my profits and losses come from', 'performance attribution explained', 'how to find what drives my returns'],
    canonical: {
      short: 'Performance attribution breaks your results down by source — setup, session, instrument, and behaviour — to see exactly what is making and losing money. You optimise by cutting the losing segment, not by guessing.',
      deep: 'Rather than a single P&L number, attribute results: which setups, sessions, and instruments are net positive, and which behaviours (revenge trades, oversized days) drag the curve. Often one segment quietly accounts for most losses; removing it transforms performance. Attribution turns the journal into actionable intelligence — it tells the desk precisely where the edge lives and where to stop bleeding.',
    },
    marketContext: 'Attribution frequently reveals a trader’s "favourite" setup is a net loser while an overlooked one carries the account — invisible without segmenting the data.',
    responseObjective: 'mentor', desiredOutcome: 'attribute results by segment and cut the leaks',
    relevanceTags: ['desk', 'attribution', 'analysis'],
    guidance: { traderProblem: true },
    commonMistakes: ['judging by total P&L instead of attributing it by setup/session/behaviour'],
    related: ['performance-analysis', 'professional-journaling', 'trading-statistics'], prerequisites: ['performance-analysis'],
    nextSteps: ['desk-discipline'], followups: ['professional-journaling', 'trading-statistics'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'desk-discipline', category: 'desk', topic: 'Desk Discipline', level: 'advanced',
    title: 'Professional Desk Discipline', intent: 'psychology',
    concepts: ['desk discipline', 'rules', 'accountability', 'consistency'],
    questionPatterns: ['what is desk discipline', 'how do professional traders stay disciplined', 'desk discipline explained', 'how to enforce trading rules', 'professional discipline trading'],
    canonical: {
      short: 'Desk discipline is the non-negotiable enforcement of process: risk limits, protocols, and routines followed every day, with accountability for breaches. It is the culture that makes the whole operating system actually work.',
      deep: 'Strategy and tools are worthless without enforcement. Desk discipline means the risk budget, news protocol, drawdown rules, and routine are followed without exception, and breaches are reviewed honestly rather than excused. Solo traders create accountability through journaling and rule-adherence grading. This discipline — not any single setup — is the through-line that turns a collection of features into a reliable trading operation.',
    },
    marketContext: 'Desks remove traders who breach risk limits regardless of P&L — discipline is enforced as culture, because one undisciplined trader can sink the book.',
    responseObjective: 'mentor', desiredOutcome: 'enforce process and accountability without exception',
    relevanceTags: ['desk', 'discipline', 'accountability'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    commonMistakes: ['excusing rule breaches when the trade happened to work'],
    related: ['trading-routine-mastery', 'professional-habits', 'rule-following'], prerequisites: ['professional-habits'],
    nextSteps: ['trading-desk-operations'], followups: ['rule-following', 'consistency-system'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
