// functions/knowledge/professional/concepts.js
// CATEGORY: professional (NEW, Phase 10) — mastery: fund/business, performance
// psychology, multi-timeframe, sessions, ICT/SMC premium, risk-of-ruin.

export const PROFESSIONAL_CONCEPTS = [
  {
    id: 'fund-management', category: 'professional', topic: 'Fund Management', level: 'advanced',
    title: 'Managing Other People’s Capital', intent: 'career',
    concepts: ['fund management', 'capital', 'mandate', 'professional'],
    questionPatterns: ['what is fund management', 'how do fund managers trade', 'how to manage other peoples money', 'fund management explained', 'how to become a fund manager'],
    canonical: {
      short: 'Managing outside capital adds a duty layer on top of trading: a defined mandate, strict risk limits, transparent reporting, and lower-volatility returns. The priority shifts from maximising return to never breaching the agreed risk.',
      deep: 'A fund manager trades within a mandate (allowed instruments, max drawdown, leverage limits) and is judged on risk-adjusted returns, not raw profit. Drawdown control and consistency matter more than home runs because clients redeem after losses. The skills are the same edge plus institutional-grade risk models, reporting, and emotional discipline at larger size. It is a business of trust, so capital preservation is the product.',
    },
    marketContext: 'Most professional allocators screen managers on max drawdown and Sharpe before raw return — a smooth 15% beats a volatile 40% for raising capital.',
    responseObjective: 'educate', desiredOutcome: 'understand the duty and risk focus of managing capital',
    relevanceTags: ['professional', 'fund management'],
    guidance: { tradeProblem: true },
    commonMistakes: ['chasing high returns instead of controlling drawdown for clients'],
    related: ['trading-business-models', 'professional-risk-models', 'capital-allocation'], prerequisites: ['trading-business-models'],
    nextSteps: ['trading-business-growth'], followups: ['professional-risk-models', 'capital-allocation'],
    riskNote: 'With outside capital, breaching the mandate risk limit is the cardinal sin.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'trading-business-growth', category: 'professional', topic: 'Trading Business Growth', level: 'advanced',
    title: 'Growing a Trading Business', intent: 'career',
    concepts: ['business growth', 'scaling', 'income', 'professional'],
    questionPatterns: ['how to grow a trading business', 'how to scale trading income', 'trading business growth', 'how do traders increase income', 'scaling a trading career'],
    canonical: {
      short: 'A trading business grows through proven consistency, then scale: bigger size on a tested edge, funded capital, or multiple uncorrelated strategies. Growth follows evidence, never hope — and never at the cost of risk discipline.',
      deep: 'The levers are clear: compound personal capital, add prop/funded accounts for more buying power without personal risk, or diversify into a second uncorrelated edge. Each requires a documented track record first. The failure mode is scaling size or complexity ahead of skill — ego outrunning process. Treat growth as a deliberate, evidence-gated decision, protecting the downside even harder as the numbers rise.',
    },
    marketContext: 'Funded-account programs let consistent traders scale buying power into six figures without risking personal savings — a common growth path for retail-to-professional.',
    responseObjective: 'mentor', desiredOutcome: 'scale a trading business from evidence, not ego',
    relevanceTags: ['professional', 'business', 'growth'],
    guidance: { traderProblem: true },
    commonMistakes: ['scaling size before a documented, consistent track record exists'],
    related: ['trading-business-models', 'prop-scaling', 'account-growth'], prerequisites: ['trading-business-models'],
    nextSteps: ['performance-psychology'], followups: ['prop-scaling', 'fund-management'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'performance-psychology', category: 'professional', topic: 'Performance Psychology', level: 'advanced',
    title: 'Performance Psychology', intent: 'psychology',
    concepts: ['performance psychology', 'peak performance', 'pressure', 'focus'],
    questionPatterns: ['what is performance psychology', 'how to perform under pressure trading', 'peak performance for traders', 'performance psychology explained', 'how to trade at my best'],
    canonical: {
      short: 'Performance psychology is the athlete’s mindset applied to trading: managing arousal, focus, and routine so you execute at your best under pressure. It is what lets a proven edge survive bigger size and high-stakes moments.',
      deep: 'Like elite athletes, top traders manage state: pre-session routines, controlled arousal (neither flat nor frantic), full presence during execution, and recovery after intense sessions. The aim is repeatable peak performance, not occasional brilliance. This layer matters most at scale, where the same edge that worked small can crumble if focus and composure are not deliberately trained and protected.',
    },
    marketContext: 'Many traders execute flawlessly on demo but break down live — identical strategy, different performance state under real pressure.',
    responseObjective: 'mentor', desiredOutcome: 'execute at peak under pressure through state control',
    relevanceTags: ['professional', 'performance', 'psychology'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    commonMistakes: ['relying on motivation instead of routine to perform consistently'],
    related: ['advanced-psychology', 'mental-capital', 'trader-mindset'], prerequisites: ['advanced-psychology'],
    nextSteps: ['portfolio-psychology'], followups: ['mental-capital', 'professional-habits'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'portfolio-psychology', category: 'professional', topic: 'Portfolio Psychology', level: 'advanced',
    title: 'Portfolio Psychology', intent: 'psychology',
    concepts: ['portfolio psychology', 'multiple positions', 'detachment', 'stress'],
    questionPatterns: ['what is portfolio psychology', 'how to handle multiple open trades', 'psychology of managing a portfolio', 'how to stay calm with many positions', 'portfolio psychology explained'],
    canonical: {
      short: 'Portfolio psychology is managing the emotional load of several positions at once: thinking in total exposure, not individual trades, and not letting one red position hijack decisions on the others. Detachment scales with size.',
      deep: 'When multiple trades are open, watching each one individually breeds stress and reactive errors. The professional shift is to think at portfolio level — total risk, correlated exposure, overall drawdown — and to judge the book, not each ticker. This prevents one losing position from triggering revenge or panic across the account. It pairs with portfolio risk models: manage the whole, stay detached from the parts.',
    },
    marketContext: 'Traders who panic-close a whole winning book because one position turned red learn this the hard way — the portfolio was fine; their psychology was not.',
    responseObjective: 'mentor', desiredOutcome: 'manage emotion at portfolio level, not per trade',
    relevanceTags: ['professional', 'portfolio', 'psychology'],
    guidance: { traderProblem: true },
    commonMistakes: ['reacting to one red position instead of the portfolio as a whole'],
    related: ['portfolio-risk', 'performance-psychology', 'emotional-control'], prerequisites: ['portfolio-risk'],
    nextSteps: ['execution-psychology'], followups: ['performance-psychology', 'capital-allocation'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'execution-psychology', category: 'professional', topic: 'Execution Psychology', level: 'intermediate',
    title: 'Execution Psychology', intent: 'psychology',
    concepts: ['execution psychology', 'hesitation', 'trigger', 'discipline'],
    questionPatterns: ['what is execution psychology', 'why do i hesitate to execute', 'how to execute without fear', 'execution psychology explained', 'why cant i pull the trigger'],
    canonical: {
      short: 'Execution psychology is the gap between knowing the trade and actually placing and managing it cleanly. Hesitation, early exits, and stop-moving are execution failures — usually fixed with smaller size and a precise plan.',
      deep: 'A perfect plan fails if execution wobbles: freezing on valid setups, bailing winners early, or widening stops from fear. The roots are oversized positions (too much at stake) and vague rules (room for doubt). Shrink risk until a loss is trivial, define the trigger and management so precisely that action is obvious, and practise mechanical follow-through. Closing the knowing-doing gap is where many traders finally become consistent.',
    },
    marketContext: 'A trader with a 60% backtested edge can still lose live purely from execution errors — the strategy was never the problem.',
    responseObjective: 'mentor', desiredOutcome: 'close the knowing-doing gap in execution',
    relevanceTags: ['professional', 'execution', 'psychology'],
    guidance: { traderProblem: true },
    commonMistakes: ['hesitating on valid setups, then chasing the move late'],
    related: ['execution-discipline', 'hesitation', 'trade-management'], prerequisites: ['execution-discipline'],
    nextSteps: ['professional-journaling'], followups: ['hesitation', 'trade-management'],
    riskNote: 'If you hesitate or move stops, your size is likely too big — shrink it.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'professional-journaling', category: 'professional', topic: 'Professional Journaling', level: 'advanced',
    title: 'Professional-Grade Journaling', intent: 'psychology',
    concepts: ['journaling', 'data', 'review', 'metrics'],
    questionPatterns: ['how do professionals journal trades', 'what is professional journaling', 'advanced trading journal', 'what metrics to journal', 'professional journaling explained'],
    canonical: {
      short: 'Professional journaling goes beyond screenshots: it tags every trade by setup, session, emotion, and decision quality, then analyses the data to find exactly where the edge lives and where it leaks. The journal becomes the R&D department of your trading.',
      deep: 'A pro journal captures structured fields — setup type, R multiple, session, mistake tags, emotional state, and a good/poor decision label independent of outcome. Periodic analysis segments performance by these tags to reveal which setups, times, and behaviours make or lose money. That turns vague effort into precise improvement: cut the losing segment, reinforce the winning one. It is the difference between trading and studying your trading.',
    },
    marketContext: 'Reviewing journals by setup often reveals one "favourite" setup is actually a net loser — data the trader never saw without tagging.',
    responseObjective: 'mentor', desiredOutcome: 'turn the journal into a data-driven improvement engine',
    relevanceTags: ['professional', 'journaling', 'data'],
    guidance: { traderProblem: true },
    commonMistakes: ['logging only screenshots and never analysing the data by segment'],
    related: ['trading-journal', 'performance-analysis', 'decision-quality'], prerequisites: ['trading-journal'],
    nextSteps: ['multi-timeframe-analysis'], followups: ['performance-analysis', 'trading-statistics'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'multi-timeframe-analysis', category: 'professional', topic: 'Multi-Timeframe Analysis', level: 'intermediate',
    title: 'Multi-Timeframe Analysis', intent: 'technical',
    concepts: ['multi timeframe', 'top down', 'bias', 'entry'],
    questionPatterns: ['what is multi timeframe analysis', 'how to use multiple timeframes', 'top down analysis explained', 'how many timeframes should i use', 'multi timeframe analysis explained'],
    canonical: {
      short: 'Multi-timeframe analysis reads top-down: bias from a higher timeframe, the level/zone from a middle one, and the entry trigger from a lower one. It keeps you trading with the bigger picture instead of fighting it.',
      deep: 'A robust three-timeframe approach: the higher timeframe (daily/4H) sets directional bias and key zones; the middle (1H) refines the area of interest; the lower (15m/5m) times the precise entry that agrees with the bias. Beginners over-zoom into one tiny timeframe and drown in noise. Anchoring to the higher timeframe first filters most low-quality trades automatically and gives entries context.',
    },
    marketContext: 'A 15-minute "buy signal" against a clear daily downtrend is a low-probability counter-trend trade — multi-timeframe context would have flagged it.',
    responseObjective: 'educate', desiredOutcome: 'align entries with higher-timeframe bias top-down',
    relevanceTags: ['professional', 'timeframe', 'analysis'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading a low-timeframe signal against the higher-timeframe trend'],
    related: ['timeframe-selection', 'structural-bias', 'confluence'], prerequisites: ['timeframe-selection'],
    nextSteps: ['session-models'], followups: ['structural-bias', 'confluence'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'session-models', category: 'professional', topic: 'Session Models', level: 'advanced',
    title: 'Trading Session Models', intent: 'technical',
    concepts: ['session model', 'london', 'new york', 'asia range'],
    questionPatterns: ['what is a session model', 'how to trade by session', 'session based trading', 'session models explained', 'how do sessions affect setups'],
    canonical: {
      short: 'Session models exploit the daily rhythm: the Asian range builds liquidity, London often sweeps it and sets the trend, and New York continues or reverses around US data. Trading with the session character beats ignoring it.',
      deep: 'A common framework: mark the Asian range, expect London to run one side (liquidity sweep) and establish direction, then trade New York continuation or the post-data move. Each session has a personality — Asia quiet/ranging, London directional, NY news-driven. Aligning your setups to the session (range tactics in Asia, breakout/sweep tactics at London, caution around NY data) raises quality and reduces dead-hour trades.',
    },
    marketContext: 'The "London sweep of the Asian range, then reverse" pattern recurs on gold and majors often enough to be a core session-model setup.',
    responseObjective: 'educate', desiredOutcome: 'align setups to each session’s character',
    relevanceTags: ['professional', 'sessions', 'timing'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading breakout tactics in the quiet Asian range'],
    related: ['killzones', 'forex-sessions', 'liquidity-sweep'], prerequisites: ['forex-sessions'],
    nextSteps: ['ict-premium'], followups: ['killzones', 'london-session-gold'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'ict-premium', category: 'professional', topic: 'ICT Premium Concepts', level: 'advanced',
    title: 'ICT Premium Concepts', intent: 'technical',
    concepts: ['ict', 'premium discount', 'order block', 'optimal trade entry'],
    questionPatterns: ['what are advanced ict concepts', 'ict premium explained', 'how to combine ict concepts', 'advanced ict setups', 'ict premium concepts'],
    canonical: {
      short: 'ICT premium concepts combine the building blocks — liquidity sweeps, displacement, order blocks, fair value gaps, and optimal trade entry — into a single high-probability sequence at killzone timing. The edge is the confluence, not any one tool.',
      deep: 'A full ICT setup stacks pieces: during a killzone, price sweeps obvious liquidity, displaces to break structure (change of character), leaves a fair value gap and order block, then offers an optimal trade entry on the retracement into that zone. No single element is the edge; the sequence at the right time and place is. Mastery is recognising when enough pieces align to justify a precise, low-risk entry.',
    },
    marketContext: 'A classic gold long: London sweeps the Asian low, displaces up breaking structure, then retraces into the order block/FVG for an OTE entry toward buy-side liquidity.',
    responseObjective: 'educate', desiredOutcome: 'combine ICT building blocks into one confluent setup',
    relevanceTags: ['professional', 'ict', 'smart money'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading one ICT element alone instead of waiting for the full sequence'],
    misconceptions: ['any single ICT concept is the edge — it is the confluence of several that matters'],
    related: ['optimal-trade-entry', 'order-block', 'killzones'], prerequisites: ['optimal-trade-entry', 'killzones'],
    nextSteps: ['smc-advanced'], followups: ['order-block', 'fair-value-gap'],
    riskNote: 'Even a full ICT setup needs a stop beyond invalidation and 1% risk.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'smc-advanced', category: 'professional', topic: 'Advanced Smart Money Concepts', level: 'advanced',
    title: 'Advanced Smart Money Concepts', intent: 'technical',
    concepts: ['smc', 'smart money', 'structure', 'liquidity'],
    questionPatterns: ['what are advanced smc concepts', 'advanced smart money concepts', 'how to combine smc', 'smc advanced setups', 'advanced smart money explained'],
    canonical: {
      short: 'Advanced SMC ties structure, liquidity, and order flow into a top-down read: higher-timeframe bias and liquidity targets, then a lower-timeframe shift and order block for entry. It is a framework for reading where price must go and why.',
      deep: 'Beyond individual tools, advanced SMC works top-down: identify the higher-timeframe draw on liquidity (where price is likely headed), wait for a lower-timeframe market-structure shift confirming intent, then enter from the order block or imbalance with the bias. It unifies break of structure, change of character, liquidity, and imbalance into one coherent narrative. The skill is patience for the full read rather than trading isolated signals.',
    },
    marketContext: 'Reading "daily wants the buy-side liquidity above, so I wait for a 5m CHoCH and order block to go long" is the advanced-SMC thought process in action.',
    responseObjective: 'educate', desiredOutcome: 'read price top-down via structure + liquidity + order flow',
    relevanceTags: ['professional', 'smc', 'smart money'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading SMC signals without a higher-timeframe liquidity draw'],
    related: ['ict-premium', 'institutional-order-flow', 'structural-bias'], prerequisites: ['ict-premium', 'institutional-order-flow'],
    nextSteps: ['risk-of-ruin'], followups: ['break-of-structure', 'liquidity-engineering'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'risk-of-ruin', category: 'professional', topic: 'Risk of Ruin', level: 'advanced',
    title: 'Risk of Ruin', intent: 'riskmgmt',
    concepts: ['risk of ruin', 'probability', 'drawdown', 'survival'],
    questionPatterns: ['what is risk of ruin', 'how to calculate risk of ruin', 'risk of ruin explained', 'how to avoid blowing my account', 'what is the probability of ruin'],
    canonical: {
      short: 'Risk of ruin is the probability that a string of losses wipes your account, given your risk per trade and win rate. The lesson is stark: oversize and even a good edge can ruin you; risk small and survival is near-certain.',
      deep: 'Risk of ruin rises sharply with larger risk per trade and falls with a positive edge and small sizing. Risking 1% per trade with any real edge makes ruin extraordinarily unlikely; risking 10% makes it a near-certainty over enough trades, edge or not. This is the mathematical backbone of "risk small": it is not caution for its own sake, it is the difference between surviving variance and being eliminated by it.',
    },
    marketContext: 'Traders with a winning strategy still blow up by risking 10–20% per trade — a normal losing streak crosses their ruin threshold.',
    responseObjective: 'warn', desiredOutcome: 'size so a losing streak cannot ruin you',
    relevanceTags: ['professional', 'risk of ruin', 'survival'],
    guidance: { tradeProblem: true },
    commonMistakes: ['risking large per trade and assuming a good edge protects you'],
    misconceptions: ['a winning strategy cannot blow up — oversizing ruins even profitable edges'],
    related: ['max-drawdown', 'risk-per-trade', 'professional-risk-models'], prerequisites: ['risk-per-trade', 'max-drawdown'],
    nextSteps: ['trading-routine-mastery'], followups: ['professional-risk-models', 'account-preservation'],
    riskNote: 'Risking small is not caution — it is the math that keeps you alive.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'trading-routine-mastery', category: 'professional', topic: 'Trading Routine Mastery', level: 'advanced',
    title: 'Mastering Your Trading Routine', intent: 'psychology',
    concepts: ['routine mastery', 'system', 'consistency', 'professional'],
    questionPatterns: ['how to master my trading routine', 'what is an ideal trading routine', 'professional trading routine', 'routine mastery explained', 'how do pros structure their day'],
    canonical: {
      short: 'Routine mastery is when preparation, execution, and review run automatically every day, so discipline no longer depends on willpower. It is the operating system beneath every other professional skill.',
      deep: 'The mastered routine integrates daily prep (levels, calendar, bias, risk), in-session execution (checklist, valid setups only, limits honoured), and post-session review (journal, decision quality), plus weekly and monthly audits. Once these are habitual, good behaviour is the path of least resistance even when tired or emotional. This consistency of process — not any single setup — is what ultimately produces a consistent equity curve.',
    },
    marketContext: 'Professionals describe their edge as "boring": the same routine daily for years, which is exactly why their results compound while amateurs’ swing wildly.',
    responseObjective: 'mentor', desiredOutcome: 'make the full routine automatic and willpower-free',
    relevanceTags: ['professional', 'routine', 'consistency'],
    guidance: { traderProblem: true },
    commonMistakes: ['relying on motivation instead of an ingrained routine'],
    related: ['daily-routine', 'consistency-system', 'professional-habits'], prerequisites: ['consistency-system'],
    nextSteps: ['fund-management'], followups: ['professional-habits', 'monthly-review'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
