// functions/knowledge/review/concepts.js
// CATEGORY: review (NEW, Phase 4) — routines, performance analysis, statistics.

export const REVIEW_CONCEPTS = [
  {
    id: 'daily-routine', category: 'review', topic: 'Daily Trading Routine', level: 'beginner',
    title: 'A Daily Trading Routine', intent: 'psychology',
    concepts: ['daily routine', 'preparation', 'pre market', 'review'],
    questionPatterns: ['what is a daily trading routine', 'how should i prepare each day', 'daily routine for traders', 'what to do before trading', 'pre market routine'],
    canonical: {
      short: 'A daily routine has three beats: prepare (mark levels, check the calendar, set bias and risk), execute (checklist, only valid setups, honour limits), and review (journal trades and behaviour). The routine is what makes good habits automatic.',
      deep: 'Before the session, mark key levels and the economic calendar, define your bias and the day\'s risk. During it, take only checklist-valid setups and respect your daily loss limit. Afterwards, journal each trade and how you behaved. Running the same loop daily removes decision fatigue and exposes problems quickly when results slip — process consistency precedes performance consistency.',
    },
    responseObjective: 'mentor', desiredOutcome: 'run a repeatable prepare-execute-review loop',
    relevanceTags: ['review', 'routine'],
    guidance: { traderProblem: true },
    related: ['weekly-planning', 'trading-journal', 'trading-routine'], prerequisites: ['trading-discipline'],
    nextSteps: ['weekly-planning'], followups: ['trading-journal', 'monthly-review'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'weekly-planning', category: 'review', topic: 'Weekly Planning', level: 'intermediate',
    title: 'Weekly Trading Planning', intent: 'strategy',
    concepts: ['weekly planning', 'bias', 'preparation', 'review'],
    questionPatterns: ['what is weekly planning in trading', 'how do i plan my trading week', 'weekly preparation for traders', 'sunday trading prep', 'weekly bias planning'],
    canonical: {
      short: 'Weekly planning sets the higher-timeframe bias and key levels before the week starts, so daily decisions fit a bigger picture. It turns reactive day-to-day trading into a coherent, intentional week.',
      deep: 'Each weekend, review the daily/weekly structure on your instruments, mark the levels that matter, note the week\'s high-impact news, and write a directional lean for each market. During the week, your daily routine executes inside that plan rather than reacting to noise. The lean is a guide, not a vow — update it if structure breaks, but starting with a plan prevents scattered, contradictory trades.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade the week with a top-down plan',
    relevanceTags: ['review', 'planning'],
    guidance: { traderProblem: true },
    related: ['daily-routine', 'monthly-review', 'structural-bias'], prerequisites: ['structural-bias'],
    nextSteps: ['monthly-review'], followups: ['daily-routine', 'trading-plan'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'monthly-review', category: 'review', topic: 'Monthly Review', level: 'intermediate',
    title: 'Monthly Performance Review', intent: 'psychology',
    concepts: ['monthly review', 'reflection', 'improvement', 'review'],
    questionPatterns: ['what is a monthly trading review', 'how do i review my trading month', 'monthly review process', 'how to improve month over month', 'trading performance review'],
    canonical: {
      short: 'A monthly review zooms out from individual trades to patterns: your adherence to rules, your biggest repeating mistake, and whether your edge is holding. It is where real improvement is decided.',
      deep: 'Once a month, aggregate your journal: rule-adherence rate, win rate and average reward-to-risk, worst drawdown, and the single most costly recurring error. Pick one thing to fix next month and one strength to reinforce. Judging the month by process quality, not just P&L, keeps you improving the inputs you control rather than chasing outcomes you do not.',
    },
    responseObjective: 'mentor', desiredOutcome: 'improve by reviewing monthly patterns, not single trades',
    relevanceTags: ['review', 'reflection'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['weekly-planning', 'performance-analysis', 'trading-journal'], prerequisites: ['trading-journal'],
    nextSteps: ['performance-analysis'], followups: ['trader-assessment', 'trading-statistics'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'performance-analysis', category: 'review', topic: 'Performance Analysis', level: 'advanced',
    title: 'Analysing Your Trading Performance', intent: 'psychology',
    concepts: ['performance analysis', 'metrics', 'data', 'review'],
    questionPatterns: ['how do i analyse my trading performance', 'what metrics should i track', 'trading performance analysis', 'how to measure my trading', 'how to find what is hurting my results'],
    canonical: {
      short: 'Performance analysis turns your journal into decisions: which setups, sessions, and behaviours make or lose money. You optimise by cutting what loses, not by adding more setups.',
      deep: 'Segment results by setup, session, instrument, and day of week to find where your edge actually lives — and where it leaks. Often one setup or one bad habit (revenge trades, oversized days) accounts for most losses; removing it transforms the curve. Track decision quality alongside outcome so you reward good process, not luck. Analysis only helps if it ends in one concrete change.',
    },
    responseObjective: 'mentor', desiredOutcome: 'optimise by cutting what loses, from real data',
    relevanceTags: ['review', 'analysis'],
    guidance: { traderProblem: true },
    related: ['trading-statistics', 'monthly-review', 'decision-quality'], prerequisites: ['trading-journal'],
    nextSteps: ['trading-statistics'], followups: ['decision-quality', 'monthly-review'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'trading-statistics', category: 'review', topic: 'Trading Statistics', level: 'advanced',
    title: 'Key Trading Statistics', intent: 'strategy',
    concepts: ['trading statistics', 'expectancy', 'win rate', 'metrics', 'review'],
    questionPatterns: ['what trading statistics matter', 'what is expectancy', 'how to track trading stats', 'important trading metrics', 'win rate average rr drawdown'],
    canonical: {
      short: 'The statistics that matter are win rate, average reward-to-risk, expectancy, and max drawdown — together they tell you whether your edge is real and survivable. Single trades are noise; the sample is the signal.',
      deep: 'Expectancy = (win rate × average win) − (loss rate × average loss); a positive number over a meaningful sample is a genuine edge. Pair it with max drawdown to judge survivability — a high expectancy with brutal drawdowns is hard to trade. Track these honestly over many trades; they reveal whether to keep, refine, or drop a setup, and they keep you executing through normal losing streaks.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge the edge by expectancy and drawdown over a sample',
    relevanceTags: ['review', 'statistics', 'expectancy'],
    guidance: { tradeProblem: true },
    related: ['performance-analysis', 'win-rate-vs-rr', 'equity-curve'], prerequisites: ['risk-reward'],
    nextSteps: ['equity-curve'], followups: ['win-rate-vs-rr', 'performance-analysis'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'equity-curve', category: 'review', topic: 'Reading Your Equity Curve', level: 'advanced',
    title: 'Reading Your Equity Curve', intent: 'psychology',
    concepts: ['equity curve', 'drawdown', 'consistency', 'review'],
    questionPatterns: ['what is an equity curve', 'how to read my equity curve', 'what does my equity curve tell me', 'equity curve analysis', 'smooth vs jagged equity curve'],
    canonical: {
      short: 'Your equity curve is the honest picture of consistency: a smooth, gently rising line means stable risk and process; a jagged, spiky one signals inconsistent sizing or gambling. The shape matters as much as the endpoint.',
      deep: 'A healthy curve climbs steadily with shallow drawdowns, reflecting fixed risk and repeatable execution. Big spikes and deep valleys usually mean variable position sizing, revenge trades, or over-reliance on a few outsized wins — fragile even if currently up. Use the curve as feedback: rising and smooth, keep going; rising but jagged, tighten risk consistency before scaling. The goal is a curve you can trust to keep compounding.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge process health from the curve shape',
    relevanceTags: ['review', 'equity curve'],
    guidance: { tradeProblem: true },
    related: ['trading-statistics', 'compounding', 'max-drawdown'], prerequisites: ['max-drawdown'],
    nextSteps: ['compounding'], followups: ['trading-statistics', 'risk-scaling'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
