// functions/knowledge/crypto/concepts.js
// HOT-SEARCH ARTICLES — CRYPTO SPECIFICS (category: crypto)
// Auto-integrating article-concepts (KOS). Dedup note: crypto-basics already exists
// in markets; these add the specific high-search crypto topics it doesn't cover.

const F = (o) => ({
  level: 'beginner', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const CRYPTO_CONCEPTS = [
  F({
    id: 'spot-vs-futures', category: 'crypto', topic: 'Spot vs Futures', title: 'Spot vs Futures Trading',
    concepts: ['spot', 'futures', 'crypto', 'leverage'],
    questionPatterns: ['what is the difference between spot and futures', 'spot vs futures crypto', 'should i trade spot or futures', 'what is spot trading', 'what is futures trading'],
    canonical: {
      short: 'Spot means you buy the actual coin and own it — no leverage, no liquidation, lower risk. Futures are leveraged contracts on the price where you can go long or short and lose more than expected if liquidated. Beginners should start with spot.',
      deep: 'In spot trading you own the asset outright; your worst case is the coin going to zero, and there is no liquidation. Futures are derivative contracts that let you use leverage and short, amplifying both gains and losses — and if price moves against a leveraged position past your margin, you get liquidated (forced closed, often losing the whole margin). Futures also carry funding fees. The leverage is exactly why beginners blow up on futures; spot first, futures only once risk management is second nature.',
    },
    marketContext: 'A beginner who buys $100 of Bitcoin spot can only lose what BTC drops; the same $100 at 20x futures can be fully liquidated by a 5% move.',
    desiredOutcome: 'start with spot; understand futures leverage = liquidation risk',
    relevanceTags: ['spot', 'futures', 'crypto', 'beginner'],
    commonMistakes: ['jumping straight into high-leverage futures as a beginner'],
    misconceptions: ['that futures are just "spot with more profit"'],
    prerequisites: ['crypto-basics'], nextSteps: ['crypto-leverage', 'liquidation-explained'], related: ['leverage', 'crypto-risk-management'],
    followups: ['liquidation-explained'],
    riskNote: 'Futures leverage can liquidate your whole margin — start on spot.',
    seo: { title: 'Spot vs Futures Trading Explained (Crypto)', description: 'The difference between spot and futures, leverage, liquidation, and which beginners should use.', keywords: ['spot vs futures', 'spot trading', 'futures trading', 'crypto futures'] },
  }),
  F({
    id: 'funding-rate', category: 'crypto', topic: 'Funding Rate', title: 'What Is a Funding Rate',
    concepts: ['funding-rate', 'futures', 'crypto'],
    questionPatterns: ['what is funding rate', 'how does funding rate work', 'what is funding rate in crypto', 'why do i pay funding', 'is funding rate good or bad'],
    canonical: {
      short: 'A funding rate is a small fee paid between long and short traders on crypto perpetual futures to keep their price near spot. When most traders are long, longs pay shorts (positive funding); it is a cost of holding leveraged positions and a clue to crowd positioning.',
      deep: 'Perpetual futures never expire, so funding payments (usually every 8 hours) tether their price to spot: when the perp trades above spot, funding is positive and longs pay shorts; below, shorts pay longs. For you it is a recurring cost or rebate on open positions. It is also a sentiment gauge — very high positive funding means the crowd is heavily long and leveraged, which often precedes sharp long-squeeze pullbacks. Factor funding into the cost of any held futures position.',
    },
    marketContext: 'Extremely high positive funding on BTC perps often signals an over-leveraged long crowd, frequently followed by a sharp shakeout.',
    desiredOutcome: 'understand funding as a cost + sentiment signal on perpetuals',
    relevanceTags: ['funding-rate', 'futures', 'crypto'],
    commonMistakes: ['holding leveraged perps for days while funding quietly erodes the account'],
    misconceptions: ['that funding is a fee the exchange takes (it is between traders)'],
    prerequisites: ['spot-vs-futures'], nextSteps: ['liquidation-explained'], related: ['crypto-leverage', 'crypto-risk-management'],
    followups: ['liquidation-explained'],
    riskNote: 'High funding signals an over-leveraged crowd — squeezes are common.',
    seo: { title: 'Funding Rate Explained (Crypto Perpetuals)', description: 'What funding rates are, why longs pay shorts, and how funding signals crowd positioning.', keywords: ['funding rate', 'crypto funding rate', 'perpetual futures funding', 'funding rate explained'] },
  }),
  F({
    id: 'liquidation-explained', category: 'crypto', topic: 'Liquidation', title: 'Liquidation Explained',
    concepts: ['liquidation', 'leverage', 'crypto', 'risk'],
    questionPatterns: ['what is liquidation', 'what does liquidated mean in crypto', 'how does liquidation work', 'how to avoid liquidation', 'what is liquidation price'],
    canonical: {
      short: 'Liquidation is when a leveraged position loses so much that your margin can no longer support it, so the exchange force-closes it — usually wiping out that margin. The higher your leverage, the closer the liquidation price, which is why high leverage is so dangerous.',
      deep: 'When you trade with leverage, the exchange lends you exposure against your margin. If price moves against you to your liquidation price, the position is automatically closed to stop your balance going negative — and you lose the margin committed. Leverage sets how far that liquidation sits: at 100x a ~1% move liquidates you; at 5x it takes ~20%. Avoiding it is pure risk management: low leverage, a real stop loss well before the liquidation price, and small position size. Relying on liquidation as your "stop" is how accounts vanish.',
    },
    marketContext: 'At 50x leverage, a routine 2% Bitcoin wick can liquidate the entire position before the trade idea even plays out.',
    desiredOutcome: 'avoid liquidation via low leverage + a real stop before the liq price',
    relevanceTags: ['liquidation', 'leverage', 'risk', 'crypto'],
    commonMistakes: ['using liquidation as a stop instead of a real stop loss'],
    misconceptions: ['that high leverage just means bigger profits'],
    prerequisites: ['crypto-leverage'], nextSteps: ['crypto-risk-management', 'stop-loss-basics'], related: ['margin-call', 'spot-vs-futures'],
    followups: ['crypto-risk-management'],
    riskNote: 'Never let liquidation be your stop — set a real stop well before it.',
    seo: { title: 'Liquidation Explained (Crypto Leverage)', description: 'What liquidation is, how leverage sets your liquidation price, and how to avoid it.', keywords: ['liquidation', 'crypto liquidation', 'liquidation price', 'avoid liquidation'] },
  }),
  F({
    id: 'crypto-leverage', category: 'crypto', topic: 'Crypto Leverage', title: 'Crypto Leverage Explained',
    concepts: ['leverage', 'crypto', 'risk'],
    questionPatterns: ['what is leverage in crypto', 'how does crypto leverage work', 'is high leverage good', 'what leverage should i use crypto', 'why is leverage risky'],
    canonical: {
      short: 'Leverage lets you control a position bigger than your money — 10x means $100 controls $1,000. It multiplies profit AND loss equally, and brings liquidation risk. Crypto offers extreme leverage (up to 100x+), which is precisely why most leveraged beginners get wiped out.',
      deep: 'Leverage borrows exposure against your margin: 10x turns a 1% move into a 10% account swing, in both directions. Crypto exchanges offer dangerously high leverage (50–125x), making liquidation just a small wick away. The professional approach is the opposite of what the leverage allows — use low effective leverage, size from a 1–2% risk rule, and treat the maximum offered as a trap, not a target. Leverage does not increase your edge; it only increases the speed at which a lack of edge ruins you.',
    },
    marketContext: 'The same trade idea at 3x can survive a normal pullback; at 75x it is liquidated by noise before the move develops.',
    desiredOutcome: 'use low effective leverage; treat max leverage as a trap',
    relevanceTags: ['leverage', 'crypto', 'risk', 'beginner'],
    commonMistakes: ['maxing out leverage to make a small account grow fast'],
    misconceptions: ['that more leverage means a better chance of profit'],
    prerequisites: ['leverage'], nextSteps: ['liquidation-explained', 'crypto-risk-management'], related: ['spot-vs-futures', 'overleveraging'],
    followups: ['liquidation-explained'],
    riskNote: 'High leverage speeds up ruin — keep effective leverage low.',
    seo: { title: 'Crypto Leverage Explained (Risk Guide)', description: 'How crypto leverage multiplies losses, liquidation risk, and what leverage to actually use.', keywords: ['crypto leverage', 'leverage trading crypto', 'high leverage risk', 'what leverage to use'] },
  }),
  F({
    id: 'altcoins-basics', category: 'crypto', topic: 'Altcoins', title: 'What Are Altcoins',
    concepts: ['altcoins', 'crypto', 'basics'],
    questionPatterns: ['what are altcoins', 'what is an altcoin', 'should i trade altcoins', 'are altcoins riskier than bitcoin', 'what is altseason'],
    canonical: {
      short: 'Altcoins are all cryptocurrencies other than Bitcoin. They are generally smaller, more volatile, and less liquid than BTC — bigger pumps but also bigger and faster crashes. They tend to follow Bitcoin\'s direction, amplified, so beginners should size them smaller.',
      deep: 'An altcoin is any crypto besides Bitcoin, from large caps like Ethereum to tiny micro-caps. The further down the size scale, the more volatile and illiquid: thinner order books mean violent moves and wider spreads. Altcoins are highly correlated to Bitcoin — when BTC drops, most alts drop harder, and "altseason" is when capital rotates into them after BTC stabilises. The risk is the same money chasing 10x dreams in low-liquidity coins; size down, take profit, and treat micro-caps as speculation, not investment.',
    },
    marketContext: 'When Bitcoin falls 5%, small-cap altcoins routinely fall 15–25% in the same session due to thin liquidity.',
    desiredOutcome: 'treat altcoins as higher-risk, BTC-correlated; size smaller',
    relevanceTags: ['altcoins', 'crypto', 'beginner'],
    commonMistakes: ['putting large size into illiquid micro-cap altcoins'],
    misconceptions: ['that altcoins move independently of Bitcoin'],
    prerequisites: ['crypto-basics'], nextSteps: ['crypto-risk-management'], related: ['volatility-basics', 'spot-vs-futures'],
    followups: ['crypto-risk-management'],
    riskNote: 'Altcoins crash harder and faster than BTC — size down.',
    seo: { title: 'What Are Altcoins? (Beginner Guide)', description: 'What altcoins are, why they are riskier than Bitcoin, correlation, and altseason.', keywords: ['altcoins', 'what is an altcoin', 'altcoin trading', 'altseason'] },
  }),
  F({
    id: 'what-is-defi', category: 'crypto', topic: 'DeFi', title: 'What Is DeFi',
    concepts: ['defi', 'crypto', 'basics'],
    questionPatterns: ['what is defi', 'what does defi mean', 'how does defi work', 'is defi safe', 'what is decentralized finance'],
    canonical: {
      short: 'DeFi (Decentralised Finance) is financial services — lending, borrowing, trading, earning yield — run by code (smart contracts) instead of banks, mostly on Ethereum. It offers open access and high yields, but carries real risks: smart-contract bugs, scams, and no safety net if funds are lost.',
      deep: 'DeFi replaces intermediaries with smart contracts: decentralised exchanges, lending protocols, and yield platforms let anyone transact without a bank or broker. The appeal is permissionless access and sometimes high yields; the danger is that "high yield" usually means high risk — contract exploits, rug-pulls, impermanent loss, and zero recourse if something fails (no chargebacks, no support desk). For a trader, DeFi is mostly relevant as context and as a high-risk frontier — understand it before risking funds, and never chase a yield you can\'t explain.',
    },
    marketContext: 'Many "high-APY" DeFi farms have collapsed overnight from contract exploits, taking depositors\' funds with no recovery.',
    desiredOutcome: 'understand DeFi as open but high-risk; never chase unexplained yield',
    relevanceTags: ['defi', 'crypto', 'beginner'],
    commonMistakes: ['chasing high DeFi yields without understanding the risk'],
    misconceptions: ['that high DeFi yields are safe passive income'],
    prerequisites: ['crypto-basics'], nextSteps: ['crypto-risk-management'], related: ['altcoins-basics', 'broker-security'],
    followups: ['crypto-risk-management'],
    riskNote: 'In DeFi, high yield means high risk and there is no safety net.',
    seo: { title: 'What Is DeFi? (Decentralized Finance Explained)', description: 'What DeFi is, how smart contracts replace banks, the yields, and the real risks.', keywords: ['what is defi', 'decentralized finance', 'defi explained', 'defi risks'] },
  }),
  F({
    id: 'crypto-risk-management', category: 'crypto', topic: 'Crypto Risk Management', title: 'Crypto Risk Management',
    concepts: ['risk-management', 'crypto', 'volatility'],
    questionPatterns: ['how to manage risk in crypto', 'crypto risk management for beginners', 'how to not lose money in crypto', 'how much should i risk in crypto', 'how to trade crypto safely'],
    canonical: {
      short: 'Crypto risk management is the normal 1–2% rule made stricter for bigger volatility: smaller position sizes, low or no leverage, a real stop loss, and taking profit on the way up. Because crypto moves further and faster, the same percentage risk means a wider stop and a smaller position.',
      deep: 'The principles are identical to any market but the dials are turned down: risk 1–2% per trade, but because crypto\'s volatility (and gaps) are larger, that means wider structure-based stops and therefore smaller positions. Avoid or minimise leverage (it converts volatility into liquidation), scale out into strength to bank profit, and never invest more than you can afford to lose in an asset class that can drop 50%+. Survival first — crypto rewards the patient and ruins the over-leveraged faster than anywhere else.',
    },
    marketContext: 'A trader risking 1% with a wide, ATR-based stop survives a 20% Bitcoin drawdown; one at 25x leverage is liquidated by it.',
    desiredOutcome: 'apply 1–2% risk with wider stops, smaller size, minimal leverage',
    relevanceTags: ['risk-management', 'crypto', 'beginner'],
    commonMistakes: ['using forex-style position sizes despite crypto\'s larger swings'],
    misconceptions: ['that you need leverage to make crypto worthwhile'],
    prerequisites: ['risk-management-basics', 'volatility-basics'], nextSteps: ['one-percent-rule', 'position-sizing'], related: ['crypto-leverage', 'drawdown-basics'],
    followups: ['one-percent-rule'],
    riskNote: 'Crypto can halve — size for survival, minimise leverage.',
    seo: { title: 'Crypto Risk Management for Beginners', description: 'How to size positions, set stops, and use leverage safely in volatile crypto markets.', keywords: ['crypto risk management', 'how to trade crypto safely', 'crypto position sizing', 'crypto stop loss'] },
  }),
];
