// functions/knowledge/chart-patterns/concepts.js
// KNOWLEDGE EXPANSION — CLASSIC CHART PATTERN LIBRARY (category: chart-patterns)
// Fills the largest verified gap in the base: multi-bar chart patterns (reversal,
// continuation, harmonic) that were only referenced in passing, never held as
// dedicated concepts. Each concept auto-integrates into graph/retrieval/chips/SEO
// like every existing concept. Additive only; new category registered in index.js.

const F = (o) => ({
  level: 'intermediate', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const CHART_PATTERNS_CONCEPTS = [
  F({
    id: 'head-and-shoulders', category: 'chart-patterns', topic: 'Head and Shoulders', title: 'Head and Shoulders Pattern Explained', level: 'beginner',
    concepts: ['head-and-shoulders', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is the head and shoulders pattern', 'how to trade head and shoulders', 'head and shoulders neckline', 'is head and shoulders bearish', 'head and shoulders target'],
    canonical: {
      short: 'Head and shoulders is a topping reversal pattern: three peaks where the middle peak (head) is higher than the two on either side (shoulders), all resting on a support line called the neckline. A close below the neckline signals the uptrend may be reversing down.',
      deep: 'The pattern maps a trend losing strength: the left shoulder and head make higher highs, but the right shoulder fails to exceed the head, showing buyers weakening. The neckline connects the lows between the peaks. The confirmed signal is a decisive close below the neckline — before that, it is only a potential pattern. A common measured-move target projects the distance from the head to the neckline downward from the break. The inverse head and shoulders is the same structure flipped for bottoms.',
    },
    marketContext: 'On Gold, a head and shoulders that breaks its neckline after a long rally often precedes a meaningful correction, with the head-to-neckline distance as a rough target.',
    desiredOutcome: 'wait for a confirmed neckline break rather than anticipating the reversal on the right shoulder',
    relevanceTags: ['head-and-shoulders', 'chart-pattern', 'reversal', 'beginner'],
    commonMistakes: ['shorting the right shoulder before the neckline actually breaks'],
    misconceptions: ['that the pattern is valid before the neckline is broken'],
    prerequisites: ['support-resistance'], nextSteps: ['inverse-head-and-shoulders', 'double-top'], related: ['trend-reversal', 'breakout-trading'],
    followups: ['inverse-head-and-shoulders'],
    riskNote: 'Patterns fail — wait for the neckline close and keep a stop above the right shoulder.',
    seo: { title: 'Head and Shoulders Pattern Explained (Beginner Guide)', description: 'How the head and shoulders reversal works, where the neckline is, how to confirm the break, and how to measure a target.', keywords: ['head and shoulders pattern', 'head and shoulders trading', 'neckline break', 'bearish reversal pattern'] },
  }),
  F({
    id: 'inverse-head-and-shoulders', category: 'chart-patterns', topic: 'Inverse Head and Shoulders', title: 'Inverse Head and Shoulders Explained', level: 'beginner',
    concepts: ['inverse-head-and-shoulders', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is inverse head and shoulders', 'how to trade inverse head and shoulders', 'is inverse head and shoulders bullish', 'inverse head and shoulders target', 'reverse head and shoulders pattern'],
    canonical: {
      short: 'The inverse head and shoulders is a bottoming reversal: three troughs where the middle low (head) is deeper than the two shoulders, capped by a neckline resistance. A close above the neckline signals the downtrend may be turning up.',
      deep: 'This is the mirror of the classic head and shoulders and appears at the end of downtrends. The head makes the lowest low, but the right shoulder fails to break lower — a sign sellers are exhausting. The neckline connects the swing highs between the troughs, and a decisive close above it confirms the pattern. The measured target projects the head-to-neckline depth upward from the break. It is more reliable when the breakout comes with a pickup in momentum or volume.',
    },
    marketContext: 'An inverse head and shoulders forming at a Gold support base, breaking neckline resistance, is a common early sign of a trend turning bullish.',
    desiredOutcome: 'trade the confirmed neckline break, not the anticipated right shoulder',
    relevanceTags: ['inverse-head-and-shoulders', 'chart-pattern', 'reversal', 'beginner'],
    commonMistakes: ['buying the right shoulder before the neckline breaks'],
    misconceptions: ['that the bottom is in before the neckline is cleared'],
    prerequisites: ['head-and-shoulders'], nextSteps: ['double-bottom', 'cup-and-handle'], related: ['trend-reversal', 'breakout-trading'],
    followups: ['double-bottom'],
    riskNote: 'Confirm the neckline close and keep a stop below the right shoulder.',
    seo: { title: 'Inverse Head and Shoulders Pattern Explained', description: 'How the inverse head and shoulders bottoming reversal works, how to confirm the neckline break, and how to set a target.', keywords: ['inverse head and shoulders', 'reverse head and shoulders', 'bullish reversal pattern', 'neckline break'] },
  }),
  F({
    id: 'double-top', category: 'chart-patterns', topic: 'Double Top', title: 'The Double Top Pattern Explained', level: 'beginner',
    concepts: ['double-top', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a double top', 'how to trade a double top', 'is a double top bearish', 'double top neckline', 'double top target'],
    canonical: {
      short: 'A double top is a bearish reversal where price hits a resistance level twice, forming two roughly equal peaks with a dip between them. Breaking below the dip (the neckline) confirms buyers failed twice and sellers are taking over.',
      deep: 'The double top shows a level that rejected price on two attempts — the second peak failing to make a meaningful new high reveals fading demand. The valley between the peaks defines the neckline; a close below it confirms the reversal, and the height of the pattern projects a measured downside target. The pattern is stronger when the two tops align with a known resistance and when the second push shows momentum divergence. Trading it before the neckline breaks is anticipation, not confirmation.',
    },
    marketContext: 'Gold rejecting the same resistance twice and then losing the intervening low is a classic double top that often leads to a deeper pullback.',
    desiredOutcome: 'confirm the neckline break before trading a double top, and measure the target from pattern height',
    relevanceTags: ['double-top', 'chart-pattern', 'reversal', 'beginner'],
    commonMistakes: ['shorting the second peak before the neckline breaks and getting stopped on a breakout'],
    misconceptions: ['that two touches of resistance guarantee a reversal'],
    prerequisites: ['support-resistance'], nextSteps: ['double-bottom', 'triple-top'], related: ['false-breakout-trading', 'trend-reversal'],
    followups: ['double-bottom'],
    riskNote: 'Two tops can still break out — wait for the neckline and stop above the highs.',
    seo: { title: 'Double Top Pattern Explained for Beginners', description: 'How the double top reversal forms at resistance, why the neckline break confirms it, and how to measure a target.', keywords: ['double top pattern', 'double top trading', 'bearish reversal pattern', 'double top neckline'] },
  }),
  F({
    id: 'double-bottom', category: 'chart-patterns', topic: 'Double Bottom', title: 'The Double Bottom Pattern Explained', level: 'beginner',
    concepts: ['double-bottom', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a double bottom', 'how to trade a double bottom', 'is a double bottom bullish', 'double bottom neckline', 'double bottom target'],
    canonical: {
      short: 'A double bottom is a bullish reversal where price tests a support level twice, forming two roughly equal troughs with a peak between them. A close above that peak (the neckline) confirms sellers failed twice and buyers are taking control.',
      deep: 'The double bottom is the mirror of the double top. Two lows holding the same support show demand defending a level, and the second low failing to break lower signals sellers are exhausting. The peak between the lows is the neckline; a close above it confirms the reversal, with the pattern height projecting an upside target. It is stronger at a well-tested support and with bullish momentum divergence. As always, anticipation before the neckline break is a lower-probability trade.',
    },
    marketContext: 'Gold holding a support twice and then breaking the middle peak forms a double bottom that frequently launches a new leg up.',
    desiredOutcome: 'trade the confirmed neckline break of a double bottom and target the measured move',
    relevanceTags: ['double-bottom', 'chart-pattern', 'reversal', 'beginner'],
    commonMistakes: ['buying the second low before the neckline confirms and the level fails'],
    misconceptions: ['that two touches of support always hold'],
    prerequisites: ['support-resistance'], nextSteps: ['triple-bottom', 'cup-and-handle'], related: ['trend-reversal', 'breakout-trading'],
    followups: ['triple-bottom'],
    riskNote: 'Support can still break — confirm the neckline and keep a stop below the lows.',
    seo: { title: 'Double Bottom Pattern Explained for Beginners', description: 'How the double bottom reversal forms at support, why the neckline break confirms it, and how to measure the target.', keywords: ['double bottom pattern', 'double bottom trading', 'bullish reversal pattern', 'double bottom neckline'] },
  }),
  F({
    id: 'triple-top', category: 'chart-patterns', topic: 'Triple Top', title: 'The Triple Top Pattern Explained',
    concepts: ['triple-top', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a triple top', 'how to trade a triple top', 'is a triple top bearish', 'triple top vs double top', 'triple top pattern'],
    canonical: {
      short: 'A triple top is a bearish reversal where price is rejected at the same resistance three times, forming three roughly equal peaks. A break below the support connecting the pullbacks confirms repeated failure to break higher.',
      deep: 'The triple top extends the double top logic with a third rejection, which makes the resistance level more significant but also gives price more time to range. Each failed push at the same ceiling shows persistent supply. The confirming signal is a close below the support that connects the intervening lows, with a measured target equal to the pattern height. Because triple tops take longer to form, false breaks within the range are common — patience for the confirmed breakdown is key.',
    },
    marketContext: 'Gold stalling three times at the same resistance before breaking its range support is a triple top signalling strong, repeated supply.',
    desiredOutcome: 'treat the third rejection as stronger evidence but still wait for the support break to confirm',
    relevanceTags: ['triple-top', 'chart-pattern', 'reversal', 'intermediate'],
    commonMistakes: ['fading each touch of resistance inside the range and dying by a thousand cuts'],
    misconceptions: ['that a triple top cannot break out to the upside'],
    prerequisites: ['double-top'], nextSteps: ['triple-bottom', 'rectangle-pattern'], related: ['support-resistance', 'false-breakout-trading'],
    followups: ['triple-bottom'],
    riskNote: 'Ranges whipsaw — trade only the confirmed breakdown, not every touch of the ceiling.',
    seo: { title: 'Triple Top Pattern Explained (vs Double Top)', description: 'How the triple top reversal forms, why three rejections strengthen the level, and how to confirm the breakdown.', keywords: ['triple top pattern', 'triple top trading', 'bearish reversal', 'triple top vs double top'] },
  }),
  F({
    id: 'triple-bottom', category: 'chart-patterns', topic: 'Triple Bottom', title: 'The Triple Bottom Pattern Explained',
    concepts: ['triple-bottom', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a triple bottom', 'how to trade a triple bottom', 'is a triple bottom bullish', 'triple bottom vs double bottom', 'triple bottom pattern'],
    canonical: {
      short: 'A triple bottom is a bullish reversal where price holds the same support three times, forming three roughly equal troughs. A break above the resistance connecting the bounces confirms buyers repeatedly defended the level and are taking control.',
      deep: 'The triple bottom strengthens the double bottom idea with a third successful test of support, marking strong, persistent demand. The confirming signal is a close above the resistance connecting the intervening peaks, with a measured target equal to the pattern height projected upward. Like the triple top, it takes time to form and can produce false breaks inside the range, so the confirmed breakout — ideally with rising momentum — is the trigger, not the third bounce alone.',
    },
    marketContext: 'Gold defending the same floor three times and then breaking its range high forms a triple bottom pointing to accumulation and a potential new uptrend.',
    desiredOutcome: 'use the third defended low as strong evidence but enter on the confirmed resistance break',
    relevanceTags: ['triple-bottom', 'chart-pattern', 'reversal', 'intermediate'],
    commonMistakes: ['buying each bounce inside the range instead of waiting for the breakout'],
    misconceptions: ['that support that held three times can never fail'],
    prerequisites: ['double-bottom'], nextSteps: ['rectangle-pattern', 'ascending-triangle'], related: ['breakout-trading', 'support-resistance'],
    followups: ['rectangle-pattern'],
    riskNote: 'Support can still give way — confirm the breakout and keep a stop below the base.',
    seo: { title: 'Triple Bottom Pattern Explained (vs Double Bottom)', description: 'How the triple bottom reversal forms, why three defended lows strengthen support, and how to confirm the breakout.', keywords: ['triple bottom pattern', 'triple bottom trading', 'bullish reversal', 'triple bottom vs double bottom'] },
  }),
  F({
    id: 'ascending-triangle', category: 'chart-patterns', topic: 'Ascending Triangle', title: 'The Ascending Triangle Pattern Explained',
    concepts: ['ascending-triangle', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is an ascending triangle', 'how to trade an ascending triangle', 'is an ascending triangle bullish', 'ascending triangle breakout', 'ascending triangle target'],
    canonical: {
      short: 'An ascending triangle has a flat resistance line on top and a rising support line of higher lows beneath it. The higher lows show buyers getting more aggressive; a break above the flat resistance is typically bullish.',
      deep: 'The ascending triangle is usually a continuation pattern in an uptrend, though it can also mark a bottom. Higher lows pressing into a fixed ceiling reveal demand absorbing supply until the level finally gives way. The trade is the confirmed breakout above the horizontal resistance, with a measured target equal to the triangle\'s tallest height added to the break point. The main trap is anticipating the break — price can fake through and reverse, so a close beyond the level (and ideally a retest) improves the odds.',
    },
    marketContext: 'Gold grinding higher lows into a flat resistance and then breaking out is a textbook ascending triangle continuation.',
    desiredOutcome: 'trade the confirmed breakout of the flat resistance, not the anticipated move inside the triangle',
    relevanceTags: ['ascending-triangle', 'chart-pattern', 'continuation', 'intermediate'],
    commonMistakes: ['entering inside the triangle before a confirmed breakout'],
    misconceptions: ['that an ascending triangle always breaks upward — it can fail either way'],
    prerequisites: ['support-resistance'], nextSteps: ['descending-triangle', 'symmetrical-triangle'], related: ['breakout-trading', 'false-breakout-trading'],
    followups: ['descending-triangle'],
    riskNote: 'Triangles fake out often — wait for the close beyond the level and consider a retest entry.',
    seo: { title: 'Ascending Triangle Pattern Explained', description: 'How the ascending triangle continuation works, why higher lows matter, and how to trade the breakout with a target.', keywords: ['ascending triangle', 'ascending triangle breakout', 'bullish continuation pattern', 'triangle pattern'] },
  }),
  F({
    id: 'descending-triangle', category: 'chart-patterns', topic: 'Descending Triangle', title: 'The Descending Triangle Pattern Explained',
    concepts: ['descending-triangle', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a descending triangle', 'how to trade a descending triangle', 'is a descending triangle bearish', 'descending triangle breakdown', 'descending triangle target'],
    canonical: {
      short: 'A descending triangle has a flat support line on the bottom and a falling resistance line of lower highs above it. The lower highs show sellers getting more aggressive; a break below the flat support is typically bearish.',
      deep: 'The descending triangle is usually a continuation pattern in a downtrend. Lower highs pressing down onto a fixed floor reveal supply overwhelming demand until support breaks. The trade is the confirmed breakdown below the horizontal support, with a measured target equal to the triangle\'s height subtracted from the break. It can occasionally resolve upward, so a close below the level — ideally with a failed retest back into it — is what confirms the bearish resolution rather than anticipating it early.',
    },
    marketContext: 'Gold printing lower highs into a flat support and then breaking down is a classic descending triangle continuation lower.',
    desiredOutcome: 'trade the confirmed breakdown of flat support and avoid anticipating inside the triangle',
    relevanceTags: ['descending-triangle', 'chart-pattern', 'continuation', 'intermediate'],
    commonMistakes: ['shorting inside the triangle before support actually breaks'],
    misconceptions: ['that a descending triangle can only break downward'],
    prerequisites: ['support-resistance'], nextSteps: ['symmetrical-triangle', 'bear-flag'], related: ['breakout-trading', 'trend-continuation'],
    followups: ['symmetrical-triangle'],
    riskNote: 'Confirm the breakdown close and keep a stop above the last lower high.',
    seo: { title: 'Descending Triangle Pattern Explained', description: 'How the descending triangle continuation works, why lower highs matter, and how to trade the breakdown with a target.', keywords: ['descending triangle', 'descending triangle breakdown', 'bearish continuation pattern', 'triangle pattern'] },
  }),
  F({
    id: 'symmetrical-triangle', category: 'chart-patterns', topic: 'Symmetrical Triangle', title: 'The Symmetrical Triangle Pattern Explained',
    concepts: ['symmetrical-triangle', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a symmetrical triangle', 'how to trade a symmetrical triangle', 'symmetrical triangle breakout', 'is a symmetrical triangle bullish or bearish', 'symmetrical triangle target'],
    canonical: {
      short: 'A symmetrical triangle forms as price makes lower highs and higher lows that converge toward a point, creating a coil of tightening range. It is a neutral pattern — the breakout direction, not the shape, tells you which way to trade.',
      deep: 'A symmetrical triangle represents a balance between buyers and sellers as volatility compresses. Unlike ascending or descending triangles it has no directional bias built in, so it usually resolves in the direction of the prevailing trend but must be traded on the confirmed breakout either way. The measured target is the triangle\'s widest height projected from the break point. Because the apex draws price into a squeeze, false breaks are common near the tip — earlier breaks (around two-thirds through the triangle) tend to be cleaner.',
    },
    marketContext: 'Gold coiling into a symmetrical triangle during consolidation often continues its prior trend once it breaks — but only the breakout confirms the direction.',
    desiredOutcome: 'let the breakout define direction and trade it with a measured target, rather than guessing inside the coil',
    relevanceTags: ['symmetrical-triangle', 'chart-pattern', 'continuation', 'intermediate'],
    commonMistakes: ['picking a direction inside the triangle before the breakout confirms'],
    misconceptions: ['that the pattern itself is bullish or bearish'],
    prerequisites: ['ascending-triangle'], nextSteps: ['pennant-pattern', 'symmetrical-triangle'], related: ['breakout-trading', 'volatility-expansion'],
    followups: ['pennant-pattern'],
    riskNote: 'Near the apex, fakeouts spike — wait for the confirmed break and avoid the tip.',
    seo: { title: 'Symmetrical Triangle Pattern Explained', description: 'How the symmetrical triangle coil works, why it is direction-neutral, and how to trade the breakout with a target.', keywords: ['symmetrical triangle', 'symmetrical triangle breakout', 'triangle pattern', 'consolidation pattern'] },
  }),
  F({
    id: 'bull-flag', category: 'chart-patterns', topic: 'Bull Flag', title: 'The Bull Flag Pattern Explained', level: 'beginner',
    concepts: ['bull-flag', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a bull flag', 'how to trade a bull flag', 'is a bull flag bullish', 'bull flag breakout', 'bull flag target'],
    canonical: {
      short: 'A bull flag is a continuation pattern: a strong upward move (the pole) followed by a small, downward-drifting consolidation (the flag). A break above the flag signals the uptrend is likely resuming.',
      deep: 'The bull flag captures a healthy pause within an uptrend. The sharp pole shows aggressive buying; the gently sloping pullback shows profit-taking on low energy rather than a real reversal. The confirmed trade is the breakout above the flag\'s upper boundary, with a measured target often equal to the pole\'s height added to the breakout. Flags that pull back too deeply (beyond about half the pole) or drift too long start to lose their bullish character and may be reversals instead.',
    },
    marketContext: 'After a strong Gold rally, a shallow, orderly pullback that breaks out again is a bull flag that often delivers a second leg equal to the first.',
    desiredOutcome: 'trade the flag breakout in the direction of the trend and target the measured pole move',
    relevanceTags: ['bull-flag', 'chart-pattern', 'continuation', 'beginner'],
    commonMistakes: ['calling a deep, sloppy pullback a bull flag when it is really a reversal'],
    misconceptions: ['that any pullback in an uptrend is a bull flag'],
    prerequisites: ['trend-continuation'], nextSteps: ['bear-flag', 'pennant-pattern'], related: ['breakout-trading', 'pullback-trading'],
    followups: ['bear-flag'],
    riskNote: 'A flag that retraces too far is a warning — keep a stop below the flag low.',
    seo: { title: 'Bull Flag Pattern Explained for Beginners', description: 'How the bull flag continuation works, why the pullback should be shallow, and how to trade the breakout with a target.', keywords: ['bull flag pattern', 'bull flag trading', 'bullish continuation', 'flag breakout'] },
  }),
  F({
    id: 'bear-flag', category: 'chart-patterns', topic: 'Bear Flag', title: 'The Bear Flag Pattern Explained', level: 'beginner',
    concepts: ['bear-flag', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a bear flag', 'how to trade a bear flag', 'is a bear flag bearish', 'bear flag breakdown', 'bear flag target'],
    canonical: {
      short: 'A bear flag is a continuation pattern: a sharp downward move (the pole) followed by a small, upward-drifting consolidation (the flag). A break below the flag signals the downtrend is likely resuming.',
      deep: 'The bear flag is the mirror of the bull flag within a downtrend. The steep pole shows aggressive selling; the mild upward drift is short-covering and weak dip-buying rather than a true reversal. The confirmed trade is the breakdown below the flag\'s lower boundary, targeting roughly the pole\'s height projected down from the break. A flag that rallies back more than about half the pole, or grinds sideways too long, weakens the bearish case and may signal a base forming instead.',
    },
    marketContext: 'After a sharp Gold sell-off, a weak, drifting bounce that breaks down again is a bear flag that often produces a second leg lower.',
    desiredOutcome: 'trade the flag breakdown with the trend and target the measured pole move',
    relevanceTags: ['bear-flag', 'chart-pattern', 'continuation', 'beginner'],
    commonMistakes: ['mistaking a strong recovery bounce for a bear flag'],
    misconceptions: ['that every bounce in a downtrend is a bear flag'],
    prerequisites: ['trend-continuation'], nextSteps: ['pennant-pattern', 'falling-wedge'], related: ['breakout-trading', 'trend-models'],
    followups: ['pennant-pattern'],
    riskNote: 'A flag that recovers too much invalidates the setup — keep a stop above the flag high.',
    seo: { title: 'Bear Flag Pattern Explained for Beginners', description: 'How the bear flag continuation works, why the bounce should be weak, and how to trade the breakdown with a target.', keywords: ['bear flag pattern', 'bear flag trading', 'bearish continuation', 'flag breakdown'] },
  }),
  F({
    id: 'pennant-pattern', category: 'chart-patterns', topic: 'Pennant', title: 'The Pennant Pattern Explained',
    concepts: ['pennant', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a pennant pattern', 'how to trade a pennant', 'pennant vs flag', 'is a pennant bullish or bearish', 'pennant breakout'],
    canonical: {
      short: 'A pennant is a continuation pattern like a flag, but the consolidation forms a small symmetrical triangle instead of a rectangle. After a strong move (the pole), price coils into a tiny converging range before breaking out in the original direction.',
      deep: 'The pennant combines the pole of a flag with the converging shape of a symmetrical triangle. It reflects a brief, sharp pause where volatility compresses right after a powerful move. The confirmed trade is the breakout in the direction of the pole, with a target of roughly the pole height projected from the break. Pennants are short-lived — a coil that drags on for many bars is really a larger triangle and should be treated as one. The difference from a flag is purely the converging (vs parallel) consolidation.',
    },
    marketContext: 'A quick Gold surge followed by a tight converging coil that breaks the same way is a pennant continuation.',
    desiredOutcome: 'distinguish a pennant (converging) from a flag (parallel) and trade the pole-direction breakout',
    relevanceTags: ['pennant', 'chart-pattern', 'continuation', 'intermediate'],
    commonMistakes: ['treating a long-lasting coil as a pennant instead of a full triangle'],
    misconceptions: ['that a pennant and a flag are exactly the same pattern'],
    prerequisites: ['bull-flag'], nextSteps: ['symmetrical-triangle', 'rising-wedge'], related: ['breakout-trading', 'volatility-expansion'],
    followups: ['symmetrical-triangle'],
    riskNote: 'Keep pennant trades tight and time-bounded — a stalling coil loses its momentum edge.',
    seo: { title: 'Pennant Pattern Explained (vs Flag)', description: 'How the pennant continuation works, how it differs from a flag, and how to trade the breakout after a strong move.', keywords: ['pennant pattern', 'pennant vs flag', 'continuation pattern', 'pennant breakout'] },
  }),
  F({
    id: 'rising-wedge', category: 'chart-patterns', topic: 'Rising Wedge', title: 'The Rising Wedge Pattern Explained',
    concepts: ['rising-wedge', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a rising wedge', 'how to trade a rising wedge', 'is a rising wedge bearish', 'rising wedge breakout', 'rising wedge pattern'],
    canonical: {
      short: 'A rising wedge is a pattern of higher highs and higher lows where both trendlines slope up but converge, with the lows rising faster than the highs. Despite the upward slope it is usually bearish — a break below the lower line signals a likely reversal or continuation lower.',
      deep: 'The rising wedge reveals a rally losing momentum: price keeps grinding higher but each push covers less ground as buyers weaken into the narrowing range. It acts as a reversal at the top of an uptrend and as a continuation (lower) within a downtrend. The confirmed signal is a break below the lower trendline, with a target often near the wedge\'s start. Its deceptive upward slope traps breakout buyers, which is exactly why the downside break can be sharp.',
    },
    marketContext: 'Gold creeping higher inside a narrowing rising wedge after a big run often breaks down hard once the lower line gives way.',
    desiredOutcome: 'read the rising wedge as a weakening rally and trade the confirmed downside break',
    relevanceTags: ['rising-wedge', 'chart-pattern', 'reversal', 'intermediate'],
    commonMistakes: ['buying the upward slope and ignoring the loss of momentum'],
    misconceptions: ['that an upward-sloping pattern must be bullish'],
    prerequisites: ['trendline'], nextSteps: ['falling-wedge', 'head-and-shoulders'], related: ['trend-reversal', 'false-breakout-trading'],
    followups: ['falling-wedge'],
    riskNote: 'Wedges can break either way — wait for the confirmed break and stop beyond the opposite line.',
    seo: { title: 'Rising Wedge Pattern Explained (Bearish)', description: 'Why the rising wedge is usually bearish despite its upward slope, and how to trade the breakdown.', keywords: ['rising wedge', 'rising wedge pattern', 'bearish reversal', 'wedge breakout'] },
  }),
  F({
    id: 'falling-wedge', category: 'chart-patterns', topic: 'Falling Wedge', title: 'The Falling Wedge Pattern Explained',
    concepts: ['falling-wedge', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a falling wedge', 'how to trade a falling wedge', 'is a falling wedge bullish', 'falling wedge breakout', 'falling wedge pattern'],
    canonical: {
      short: 'A falling wedge is a pattern of lower highs and lower lows where both trendlines slope down but converge, with the highs falling faster than the lows. Despite the downward slope it is usually bullish — a break above the upper line signals a likely reversal or continuation higher.',
      deep: 'The falling wedge shows a decline running out of energy: price keeps sliding, but each drop is shallower as sellers weaken into the narrowing range. It acts as a reversal at the bottom of a downtrend and as a continuation (higher) within an uptrend. The confirmed signal is a break above the upper trendline, often targeting the wedge\'s origin. Its downward slope traps breakout sellers, which is why the upside break can be swift once buyers step in.',
    },
    marketContext: 'Gold drifting lower inside a narrowing falling wedge during a correction frequently breaks upward once the upper line is cleared.',
    desiredOutcome: 'read the falling wedge as a weakening decline and trade the confirmed upside break',
    relevanceTags: ['falling-wedge', 'chart-pattern', 'reversal', 'intermediate'],
    commonMistakes: ['shorting the downward slope into a weakening decline'],
    misconceptions: ['that a downward-sloping pattern must be bearish'],
    prerequisites: ['rising-wedge'], nextSteps: ['cup-and-handle', 'inverse-head-and-shoulders'], related: ['trend-reversal', 'breakout-trading'],
    followups: ['cup-and-handle'],
    riskNote: 'Confirm the upside break and keep a stop below the last lower low.',
    seo: { title: 'Falling Wedge Pattern Explained (Bullish)', description: 'Why the falling wedge is usually bullish despite its downward slope, and how to trade the breakout.', keywords: ['falling wedge', 'falling wedge pattern', 'bullish reversal', 'wedge breakout'] },
  }),
  F({
    id: 'cup-and-handle', category: 'chart-patterns', topic: 'Cup and Handle', title: 'The Cup and Handle Pattern Explained',
    concepts: ['cup-and-handle', 'chart-pattern', 'continuation'],
    questionPatterns: ['what is a cup and handle', 'how to trade a cup and handle', 'is a cup and handle bullish', 'cup and handle breakout', 'cup and handle target'],
    canonical: {
      short: 'A cup and handle is a bullish continuation pattern shaped like a rounded "U" (the cup) followed by a small pullback (the handle). A break above the handle\'s resistance signals the uptrend is likely to continue.',
      deep: 'The cup forms as price makes a gradual, rounded recovery from a dip — a slow shift from selling to accumulation — while the handle is a modest, orderly pullback near the prior highs that shakes out weak hands before the breakout. The confirmed trade is the break above the handle\'s resistance (often near the cup\'s rim), with a target of roughly the cup\'s depth added to the breakout. V-shaped, sharp recoveries make lower-quality cups; a smooth, rounded base is the higher-probability version.',
    },
    marketContext: 'Gold carving a rounded base and then a shallow handle before breaking to new highs is a classic cup and handle continuation.',
    desiredOutcome: 'trade the handle breakout of a well-rounded cup and target the measured cup depth',
    relevanceTags: ['cup-and-handle', 'chart-pattern', 'continuation', 'intermediate'],
    commonMistakes: ['buying a sharp V-recovery and calling it a cup, or entering before the handle breaks'],
    misconceptions: ['that any rounded bottom is a valid cup and handle'],
    prerequisites: ['double-bottom'], nextSteps: ['rounding-bottom', 'rectangle-pattern'], related: ['breakout-trading', 'trend-continuation'],
    followups: ['rounding-bottom'],
    riskNote: 'Wait for the handle breakout and keep a stop below the handle low.',
    seo: { title: 'Cup and Handle Pattern Explained', description: 'How the cup and handle continuation forms, what makes a high-quality cup, and how to trade the handle breakout.', keywords: ['cup and handle', 'cup and handle pattern', 'bullish continuation', 'cup and handle breakout'] },
  }),
  F({
    id: 'rounding-bottom', category: 'chart-patterns', topic: 'Rounding Bottom', title: 'The Rounding Bottom Pattern Explained',
    concepts: ['rounding-bottom', 'chart-pattern', 'reversal'],
    questionPatterns: ['what is a rounding bottom', 'how to trade a rounding bottom', 'is a rounding bottom bullish', 'saucer bottom pattern', 'rounding bottom breakout'],
    canonical: {
      short: 'A rounding bottom (or saucer) is a slow, U-shaped reversal where a downtrend gradually flattens and curves back up. It reflects a patient shift from selling to buying, and a break above the pattern\'s rim confirms the new uptrend.',
      deep: 'The rounding bottom is a gradual accumulation pattern with no sharp low — momentum eases, price bases out over an extended period, then slowly turns up as demand rebuilds. Because it forms slowly it is easy to miss in real time, but it produces durable reversals when confirmed. The trigger is a close above the horizontal resistance at the pattern\'s rim, with a target roughly equal to the pattern\'s depth. It is essentially the cup without the handle, and works on higher timeframes where patience is rewarded.',
    },
    marketContext: 'Gold slowly carving a saucer base over weeks and then breaking its rim resistance signals a patient, durable trend change.',
    desiredOutcome: 'recognise the slow rounding-bottom reversal and enter on the confirmed rim break',
    relevanceTags: ['rounding-bottom', 'chart-pattern', 'reversal', 'intermediate'],
    commonMistakes: ['anticipating the turn during the base instead of waiting for the rim break'],
    misconceptions: ['that a rounding bottom must be perfectly symmetrical to be valid'],
    prerequisites: ['cup-and-handle'], nextSteps: ['double-bottom', 'rectangle-pattern'], related: ['trend-reversal', 'breakout-trading'],
    followups: ['rectangle-pattern'],
    riskNote: 'Confirm the rim breakout — a flat base can still roll back over before it turns.',
    seo: { title: 'Rounding Bottom (Saucer) Pattern Explained', description: 'How the rounding bottom reversal forms as a slow saucer base, and how to trade the rim breakout.', keywords: ['rounding bottom', 'saucer bottom', 'rounding bottom pattern', 'bullish reversal'] },
  }),
  F({
    id: 'rectangle-pattern', category: 'chart-patterns', topic: 'Rectangle Pattern', title: 'The Rectangle (Range) Pattern Explained',
    concepts: ['rectangle', 'chart-pattern', 'range'],
    questionPatterns: ['what is a rectangle pattern', 'how to trade a rectangle pattern', 'is a rectangle bullish or bearish', 'trading range breakout', 'rectangle pattern target'],
    canonical: {
      short: 'A rectangle is a sideways range between horizontal support and resistance where price bounces between the two boundaries. It is neutral until it breaks — traders either fade the edges inside the range or trade the confirmed breakout.',
      deep: 'The rectangle marks a period of equilibrium where buyers and sellers repeatedly defend the same two levels. There are two ways to trade it: range-trading (buying support, selling resistance with tight stops beyond each edge) while it holds, and breakout-trading once price closes decisively outside the box, with a measured target equal to the range height. The pattern usually resolves in the direction of the prior trend, but the confirmed break — not a guess — defines the direction. False breaks at the edges are the main hazard.',
    },
    marketContext: 'Gold oscillating between a clear floor and ceiling forms a rectangle that can be range-traded until a confirmed breakout takes it out of the box.',
    desiredOutcome: 'range-trade the edges with tight stops or wait for a confirmed breakout with a measured target',
    relevanceTags: ['rectangle', 'chart-pattern', 'range', 'intermediate'],
    commonMistakes: ['chasing false breaks at the range edges instead of waiting for a close outside'],
    misconceptions: ['that a rectangle has a built-in directional bias'],
    prerequisites: ['support-resistance'], nextSteps: ['range-trading', 'symmetrical-triangle'], related: ['breakout-trading', 'false-breakout-trading'],
    followups: ['range-trading'],
    riskNote: 'Edges produce fakeouts — use tight stops just beyond support/resistance and confirm breakouts on a close.',
    seo: { title: 'Rectangle (Range) Pattern Explained', description: 'How the rectangle range pattern works, how to range-trade the edges, and how to trade the confirmed breakout.', keywords: ['rectangle pattern', 'trading range', 'range breakout', 'consolidation pattern'] },
  }),
  F({
    id: 'harmonic-patterns', category: 'chart-patterns', topic: 'Harmonic Patterns', title: 'Harmonic Patterns Explained', level: 'advanced',
    concepts: ['harmonic-patterns', 'chart-pattern', 'fibonacci'],
    questionPatterns: ['what are harmonic patterns', 'how to trade harmonic patterns', 'harmonic patterns explained', 'are harmonic patterns reliable', 'fibonacci harmonic patterns'],
    canonical: {
      short: 'Harmonic patterns are precise, Fibonacci-based chart shapes (like the Gartley, Bat, Butterfly, and Crab) that use specific retracement and extension ratios to define potential reversal zones. They aim to identify high-probability turning points where several Fibonacci levels cluster.',
      deep: 'Harmonic trading maps price swings into geometric patterns whose legs must hit defined Fibonacci ratios (for example the Gartley\'s 0.618 and 0.786 retracements). When a pattern completes, it projects a "potential reversal zone" (PRZ) where the trader looks for a turn with confirmation. The appeal is precise, rule-based entries and stops; the drawback is subjectivity in drawing the swings and a high failure rate when ratios are forced. Harmonics work best as a confluence tool alongside structure and momentum, never as a mechanical guarantee.',
    },
    marketContext: 'A Gartley completing into a Gold support zone where its Fibonacci PRZ overlaps a structural level can offer a defined reversal trade with a tight stop.',
    desiredOutcome: 'treat harmonic patterns as Fibonacci-confluence tools needing confirmation, not mechanical certainties',
    relevanceTags: ['harmonic-patterns', 'chart-pattern', 'fibonacci', 'advanced'],
    commonMistakes: ['forcing Fibonacci ratios to fit and trading the PRZ with no confirmation'],
    misconceptions: ['that harmonic patterns are a precise, high-certainty system on their own'],
    prerequisites: ['fibonacci-retracement'], nextSteps: ['gartley-pattern', 'abcd-pattern'], related: ['support-resistance', 'confluence'],
    followups: ['gartley-pattern'],
    riskNote: 'Harmonics fail often — require confirmation at the PRZ and keep a defined stop beyond it.',
    seo: { title: 'Harmonic Patterns Explained (Gartley, Bat, Butterfly)', description: 'What harmonic patterns are, how Fibonacci ratios define the reversal zone, and why confirmation matters.', keywords: ['harmonic patterns', 'harmonic trading', 'gartley pattern', 'fibonacci patterns'] },
  }),
  F({
    id: 'gartley-pattern', category: 'chart-patterns', topic: 'Gartley Pattern', title: 'The Gartley Pattern Explained', level: 'advanced',
    concepts: ['gartley', 'harmonic-patterns', 'fibonacci'],
    questionPatterns: ['what is the gartley pattern', 'how to trade the gartley', 'gartley pattern rules', 'gartley fibonacci ratios', 'is the gartley reliable'],
    canonical: {
      short: 'The Gartley is a harmonic reversal pattern with five points (X-A-B-C-D) defined by specific Fibonacci ratios — notably a B point at the 0.618 retracement of XA and a D completion at the 0.786 retracement. The D point is where traders look for a reversal.',
      deep: 'The Gartley maps an initial impulse (XA), a retracement (AB to ~0.618), a partial move (BC), and a final leg (CD) that completes at the 0.786 retracement of XA, forming the potential reversal zone. A valid Gartley keeps D above X in a bullish setup, distinguishing it from the deeper Butterfly. The trade is entered at D with confirmation, a stop just beyond X, and targets at Fibonacci retracements of the AD leg. Precision in the ratios is what separates a real Gartley from a forced one, and confirmation at D is essential.',
    },
    marketContext: 'A bullish Gartley completing at the 0.786 retracement into a Gold support level offers a defined entry at D with a stop below X.',
    desiredOutcome: 'validate the Gartley\'s Fibonacci ratios and trade the D reversal with confirmation and a defined stop',
    relevanceTags: ['gartley', 'harmonic-patterns', 'fibonacci', 'advanced'],
    commonMistakes: ['entering at D with no confirmation, or accepting a pattern whose ratios do not truly fit'],
    misconceptions: ['that reaching the D point alone is a guaranteed reversal'],
    prerequisites: ['harmonic-patterns'], nextSteps: ['abcd-pattern', 'fibonacci-extensions'], related: ['fibonacci-retracement', 'confluence'],
    followups: ['abcd-pattern'],
    riskNote: 'Even a textbook Gartley fails — confirm at D and stop just beyond X.',
    seo: { title: 'Gartley Pattern Explained (Harmonic Trading)', description: 'The Gartley pattern\'s X-A-B-C-D structure, its key Fibonacci ratios, and how to trade the D reversal zone.', keywords: ['gartley pattern', 'gartley harmonic', 'harmonic trading', 'fibonacci reversal'] },
  }),
  F({
    id: 'abcd-pattern', category: 'chart-patterns', topic: 'ABCD Pattern', title: 'The ABCD Pattern Explained', level: 'intermediate',
    concepts: ['abcd-pattern', 'harmonic-patterns', 'fibonacci'],
    questionPatterns: ['what is the abcd pattern', 'how to trade the abcd pattern', 'abcd pattern rules', 'abcd harmonic pattern', 'is the abcd pattern reliable'],
    canonical: {
      short: 'The ABCD is the simplest harmonic pattern: a move (AB), a retracement (BC), and a final leg (CD) that mirrors AB in length and time, completing at point D where a reversal is expected. It is the building block of larger harmonic patterns.',
      deep: 'The ABCD consists of two similar legs (AB and CD) connected by a retracement (BC to roughly the 0.618 of AB), with CD often extending to a 1.27–1.618 projection of BC. When AB and CD are proportionate in price and time, D marks a symmetry point where the swing may reverse. Because it underlies patterns like the Gartley, mastering the ABCD helps read all harmonics. As with every harmonic, D is a zone to watch with confirmation — not a mechanical entry — and works best where it overlaps structure.',
    },
    marketContext: 'A bearish ABCD completing at D into Gold resistance, where CD equals AB, gives a symmetry-based short with a stop above D.',
    desiredOutcome: 'use the ABCD\'s leg symmetry to anticipate the D reversal zone and confirm before entering',
    relevanceTags: ['abcd-pattern', 'harmonic-patterns', 'fibonacci', 'intermediate'],
    commonMistakes: ['trading D without confirmation or ignoring that CD should be proportionate to AB'],
    misconceptions: ['that the pattern works without any Fibonacci proportion between the legs'],
    prerequisites: ['harmonic-patterns'], nextSteps: ['gartley-pattern', 'fibonacci-extensions'], related: ['fibonacci-retracement', 'confluence'],
    followups: ['gartley-pattern'],
    riskNote: 'Confirm the reaction at D and keep a stop beyond it — symmetry is a guide, not a guarantee.',
    seo: { title: 'ABCD Pattern Explained (Harmonic Basics)', description: 'The ABCD harmonic pattern\'s leg symmetry, its Fibonacci proportions, and how to trade the D reversal zone.', keywords: ['abcd pattern', 'abcd harmonic pattern', 'harmonic trading', 'fibonacci pattern'] },
  }),
];
