// functions/knowledge/liquidity/concepts.js
// CATEGORY: liquidity (NEW) — pools, sweeps, inducement, voids (smart-money lens).

export const LIQUIDITY_CONCEPTS = [
  {
    id: 'buy-side-liquidity', category: 'liquidity', topic: 'Buy-Side Liquidity', level: 'intermediate',
    title: 'Buy-Side Liquidity', intent: 'technical',
    concepts: ['buy side liquidity', 'stops above highs', 'liquidity pool', 'smart money', 'structure'],
    questionPatterns: ['what is buy side liquidity', 'where is buy side liquidity', 'buy side liquidity explained', 'how to find buy side liquidity', 'liquidity above highs'],
    canonical: {
      short: 'Buy-side liquidity is the cluster of stop orders sitting above obvious highs — the buy orders that get triggered if price runs up there. Price is often drawn to it because that is where willing counterparties are, which is why highs get swept before reversals.',
      deep: 'Above swing highs, equal highs and round numbers sit the stop-losses of sellers and the breakout-buy orders of new longs — collectively buy-side liquidity. Large participants need that liquidity to fill positions, so price frequently reaches up to "take" it before turning. Knowing where buy-side liquidity rests does two things: it warns you that an obvious high may get run (so do not put your stop right at it), and it gives you a target — price often travels from a discount area toward resting buy-side liquidity above. Reading the chart as a map of liquidity pools changes how you set both targets and stops.',
    },
    responseObjective: 'educate', desiredOutcome: 'see highs as liquidity targets, not safe stops',
    relevanceTags: ['liquidity', 'smart money', 'structure'],
    guidance: { tradeProblem: true },
    related: ['sell-side-liquidity', 'liquidity-sweep', 'equal-highs'], prerequisites: ['market-structure'],
    nextSteps: ['sell-side-liquidity'], followups: ['liquidity-sweep', 'stop-hunt'],
    riskNote: 'Do not rest stops right above an obvious high — that is exactly where the sweep aims.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'sell-side-liquidity', category: 'liquidity', topic: 'Sell-Side Liquidity', level: 'intermediate',
    title: 'Sell-Side Liquidity', intent: 'technical',
    concepts: ['sell side liquidity', 'stops below lows', 'liquidity pool', 'smart money', 'structure'],
    questionPatterns: ['what is sell side liquidity', 'where is sell side liquidity', 'sell side liquidity explained', 'how to find sell side liquidity', 'liquidity below lows'],
    canonical: {
      short: 'Sell-side liquidity is the pool of stop orders resting below obvious lows — the sell orders triggered if price drops there. Price often dips to grab it before reversing up, which is why so many longs get stopped right before the move they wanted.',
      deep: 'Below swing lows, equal lows and round numbers sit the stops of longs and the breakdown-sell orders of new shorts — sell-side liquidity. Because big players need that liquidity to fill buys, price frequently sweeps below an obvious low, fills orders, then reverses higher. For you this means two things: placing stops just under the obvious low invites a stop-hunt, and a sweep of sell-side liquidity followed by a reclaim is a high-quality long signal. Mapping where sell-side liquidity sits turns "why did it stop me then reverse" into a setup you can anticipate.',
    },
    responseObjective: 'educate', desiredOutcome: 'anticipate sweeps below lows instead of being trapped',
    relevanceTags: ['liquidity', 'smart money', 'structure'],
    guidance: { tradeProblem: true },
    related: ['buy-side-liquidity', 'liquidity-sweep', 'equal-lows'], prerequisites: ['market-structure'],
    nextSteps: ['liquidity-sweep'], followups: ['equal-lows', 'stop-hunt'],
    riskNote: 'Hide stops beyond the obvious low, not on it — sweeps target the obvious pool.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'liquidity-sweep', category: 'liquidity', topic: 'Liquidity Sweep', level: 'intermediate',
    title: 'The Liquidity Sweep', intent: 'technical',
    concepts: ['liquidity sweep', 'stop run', 'reversal', 'smart money', 'structure'],
    questionPatterns: ['what is a liquidity sweep', 'how to trade a liquidity sweep', 'liquidity grab explained', 'why does price sweep then reverse', 'liquidity sweep setup'],
    canonical: {
      short: 'A liquidity sweep is price spiking past an obvious high or low to trigger stops, then quickly reversing — the classic "stop run". Spotting a sweep-and-reclaim is one of the cleanest reversal triggers because you are entering right where the trapped traders are wrong.',
      deep: 'A sweep happens when price pushes just beyond a pool of resting orders (above a high or below a low), fills the big players who need that liquidity, then snaps back as the move was never about continuation. The tradable version is sweep-and-reclaim: price takes the liquidity, fails to follow through, and reclaims the level — your signal to enter in the reversal direction with a stop beyond the sweep\'s extreme. This reframes the very move that traps breakout traders into a high-probability entry. Combine it with structure and a level, and the sweep becomes a repeatable edge rather than a nasty surprise.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade sweep-and-reclaim instead of being trapped',
    relevanceTags: ['liquidity', 'sweep', 'reversal'],
    guidance: { tradeProblem: true },
    related: ['stop-hunt', 'buy-side-liquidity', 'gold-breakout-failure'], prerequisites: ['market-structure', 'support-resistance'],
    nextSteps: ['inducement'], followups: ['stop-hunt', 'gold-breakout-failure'],
    riskNote: 'Enter only on the reclaim, with the stop beyond the sweep extreme — not on the spike itself.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'equal-highs', category: 'liquidity', topic: 'Equal Highs', level: 'intermediate',
    title: 'Equal Highs as Liquidity', intent: 'technical',
    concepts: ['equal highs', 'double top', 'liquidity', 'stops', 'structure'],
    questionPatterns: ['what are equal highs', 'why do equal highs matter', 'equal highs liquidity', 'are equal highs a target', 'trading equal highs'],
    canonical: {
      short: 'Equal highs are two or more highs at nearly the same price — and they are a magnet for liquidity because traders pile stops just above them. Rather than a "double-top to sell", they often mark a level price wants to run before reversing.',
      deep: 'When price makes equal (or nearly equal) highs, everyone sees the same resistance and stacks stop-losses and breakout orders just above it, creating a dense buy-side liquidity pool. Counter-intuitively, that obviousness makes the level likely to be swept: price runs the equal highs to grab the liquidity, then frequently reverses. So instead of blindly shorting the "double top", many traders wait to see whether price sweeps the equal highs and fails — turning a textbook pattern into a liquidity-aware setup. Equal highs are best read as a target and a trap, not a guaranteed ceiling.',
    },
    responseObjective: 'educate', desiredOutcome: 'read equal highs as a liquidity target, not just resistance',
    relevanceTags: ['liquidity', 'equal highs', 'structure'],
    guidance: { tradeProblem: true },
    related: ['equal-lows', 'buy-side-liquidity', 'liquidity-sweep'], prerequisites: ['support-resistance'],
    nextSteps: ['equal-lows'], followups: ['liquidity-sweep', 'inducement'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'equal-lows', category: 'liquidity', topic: 'Equal Lows', level: 'intermediate',
    title: 'Equal Lows as Liquidity', intent: 'technical',
    concepts: ['equal lows', 'double bottom', 'liquidity', 'stops', 'structure'],
    questionPatterns: ['what are equal lows', 'why do equal lows matter', 'equal lows liquidity', 'are equal lows a target', 'trading equal lows'],
    canonical: {
      short: 'Equal lows are two or more lows at nearly the same price, with a pool of sell-side liquidity (stops) resting just beneath. They often act as a target price wants to sweep before reversing up, not a reliable "double-bottom" floor.',
      deep: 'Equal lows look like obvious support, so longs put stops just below and breakout sellers wait there too — a concentration of sell-side liquidity. That obviousness makes a sweep likely: price dips below the equal lows, fills orders, and frequently reverses higher. The liquidity-aware play is to wait for that sweep-and-reclaim rather than buying the "support" blindly or shorting the breakdown. Treating equal lows as a magnet and potential springboard, instead of a wall, keeps you from being the trader whose stop gets run two pips before the bounce.',
    },
    responseObjective: 'educate', desiredOutcome: 'read equal lows as a liquidity target, not firm support',
    relevanceTags: ['liquidity', 'equal lows', 'structure'],
    guidance: { tradeProblem: true },
    related: ['equal-highs', 'sell-side-liquidity', 'liquidity-sweep'], prerequisites: ['support-resistance'],
    nextSteps: ['liquidity-sweep'], followups: ['stop-hunt', 'inducement'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'stop-hunt', category: 'liquidity', topic: 'Stop Hunts', level: 'beginner',
    title: 'Understanding Stop Hunts', intent: 'technical',
    concepts: ['stop hunt', 'stop run', 'liquidity', 'trap', 'structure'],
    questionPatterns: ['what is a stop hunt', 'why does price hit my stop then reverse', 'how to avoid stop hunts', 'stop hunting explained', 'are stop hunts real'],
    canonical: {
      short: 'A stop hunt is price reaching for the obvious spot where stops sit, triggering them, then moving the other way. It feels personal, but it is just liquidity mechanics — and you avoid it by placing stops beyond the obvious level, not on it.',
      deep: 'Stops cluster in predictable places: just under support, just over resistance, beyond round numbers and equal highs/lows. Because large orders need that liquidity, price often pokes through those spots to fill, then reverses — leaving retail traders stopped out right before the move they wanted. The defence is twofold: place your invalidation beyond the obvious pool (where your idea is genuinely wrong, not where everyone else hides), and learn to use the sweep itself as a signal. Once you see the chart as a liquidity map, stop hunts stop feeling like bad luck and start looking like setups.',
    },
    responseObjective: 'educate', desiredOutcome: 'place stops away from obvious pools and read sweeps',
    relevanceTags: ['liquidity', 'stop hunt', 'structure'],
    guidance: { tradeProblem: true },
    related: ['liquidity-sweep', 'sell-side-liquidity', 'inducement'], prerequisites: ['support-resistance'],
    nextSteps: ['liquidity-sweep'], followups: ['inducement', 'gold-breakout-failure'],
    riskNote: 'Place stops where your idea is truly wrong, not on the obvious level everyone uses.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'inducement', category: 'liquidity', topic: 'Inducement', level: 'advanced',
    title: 'Inducement in Trading', intent: 'technical',
    concepts: ['inducement', 'trap', 'liquidity', 'fake move', 'smart money'],
    questionPatterns: ['what is inducement in trading', 'how does inducement work', 'inducement explained', 'what is an inducement liquidity grab', 'how to spot inducement'],
    canonical: {
      short: 'Inducement is a tempting move designed to lure traders in early — a small obvious high or low that pulls in breakout entries and stops, providing the liquidity for the real move. It is the bait before the genuine setup.',
      deep: 'Before a true move, price often creates an enticing minor structure — a small pullback high to short, or a tidy low to buy — that looks like the setup but is really bait. Traders enter there, their stops become the liquidity, and price sweeps them before the actual move begins from a deeper, less obvious level. Recognising inducement keeps you patient: instead of taking the first obvious entry, you wait to see if it gets swept, then enter from the genuine zone. It is an advanced read, but it explains why the "clean" entry so often fails right before the move you expected.',
    },
    responseObjective: 'educate', desiredOutcome: 'avoid the bait and enter from the genuine level',
    relevanceTags: ['liquidity', 'inducement', 'smart money'],
    guidance: { tradeProblem: true },
    related: ['stop-hunt', 'liquidity-sweep', 'liquidity-void'], prerequisites: ['market-structure', 'support-resistance'],
    nextSteps: ['liquidity-void'], followups: ['stop-hunt', 'liquidity-sweep'],
    riskNote: 'The first obvious entry is often bait — wait to see if it gets swept first.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'liquidity-void', category: 'liquidity', topic: 'Liquidity Void', level: 'advanced',
    title: 'Liquidity Voids and Imbalance', intent: 'technical',
    concepts: ['liquidity void', 'imbalance', 'fair value gap', 'inefficiency', 'structure'],
    questionPatterns: ['what is a liquidity void', 'what is an imbalance in trading', 'fair value gap explained', 'how to trade liquidity voids', 'what is price inefficiency'],
    canonical: {
      short: 'A liquidity void (or imbalance / fair value gap) is a fast move that leaves a gap with little trading inside it. Price often returns to "fill" that inefficiency before continuing, which makes voids useful as both targets and entry zones.',
      deep: 'When price moves so quickly that one side barely trades, it leaves an inefficiency — a void or fair value gap visible as a run of one-sided candles. Markets tend to revisit these areas to rebalance, so a void above or below current price acts like a magnet (a target), while a void that price pulls back into can serve as a precise entry zone in the direction of the trend. Combined with structure and liquidity reads, voids help answer "where will price go and where do I get in" with location-based logic rather than guesswork. It is an advanced tool, best layered onto solid structure basics.',
    },
    responseObjective: 'educate', desiredOutcome: 'use imbalances as targets and refined entries',
    relevanceTags: ['liquidity', 'imbalance', 'fair value gap'],
    guidance: { tradeProblem: true },
    related: ['inducement', 'premium-discount', 'liquidity-sweep'], prerequisites: ['market-structure'],
    nextSteps: ['premium-discount'], followups: ['inducement', 'liquidity-sweep'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
