// plan-page.js — the "See Complete Plan" page, two roadmaps behind two tabs:
//
//   IB Growth Master Plan — the 365-day execution roadmap generated by
//   /api/ceo/plan?section=growth from the locked research verdicts, week
//   rhythm, leave periods, and real completion history. 15 days per Load
//   More until the whole year is visible.
//
//   Physical IB Expansion — Pakistan → province → division → city → area →
//   institutes, from the live area queue + institute CRM. Each institute row
//   allows recording a visit (note / stage / follow-up / students) through
//   the EXISTING /api/ceo/institutes update action — no new write paths.

import { getJson, postJson } from '../shared/api.js';
import { showToast } from '../shared/components/toast.js';
import { wireGlossary } from '../shared/glossary.js';

const PAGE_SIZE = 15;
const STAGES = [
  'cold_contact', 'proposal_sent', 'meeting', 'negotiation',
  'accepted', 'rejected', 'classes_running', 'batch_complete', 'follow_up_later',
];
const state = {
  tab: 'growth',
  offset: { growth: 0, physical: 0, content: 0 },
  done: { growth: false, physical: false, content: false },
  queue: [], firstUpcoming: 0, contentCategory: '', lastProvince: null,
};

export function initPlanPage() {
  const params = new URLSearchParams(window.location.search);
  const t = params.get('tab');
  state.tab = ['physical', 'review', 'content'].includes(t) ? t : 'growth';
  for (const key of ['growth', 'physical', 'content', 'review']) {
    document.getElementById(`plan-tab-${key}`).addEventListener('click', () => switchTab(key));
  }
  document.getElementById('plan-load-more').addEventListener('click', () => loadMore());
  switchTab(state.tab);
}

const SUBTITLES = {
  growth: 'The 5-year (1,825-day) roadmap toward 50,000 active IB clients — sized by the feasibility model below, generated from the locked research (countries, brokers, platforms, languages, budget gates), shifted automatically around approved leave, re-weighted monthly by your own completion history. Loaded 15 days at a time.',
  physical: 'Pakistan-wide offline expansion: province → division → city → area → institutes. Type a position number to resequence upcoming areas; record every visit, proposal, and follow-up per institute.',
  review: 'The Monthly AI Review + Growth Intelligence Report — funnel, Pareto 80/20, trajectory toward 50,000 active IB clients, lessons, and next month\'s focus. Generated on demand from your real data.',
  content: 'The Content Engine — copy-ready packs for every channel (videos, ads, messages, scripts, objection handling, closes), each with targeting, hook, structure, CTA, and expected result. Execute, never invent.',
};

function switchTab(tab) {
  state.tab = tab;
  state.offset = { growth: 0, physical: 0, content: 0 };
  state.done = { growth: false, physical: false, content: false };
  state.lastProvince = null;
  for (const key of ['growth', 'physical', 'content', 'review']) {
    document.getElementById(`plan-tab-${key}`).className = 'ceo-btn ' + (tab === key ? 'ceo-btn-primary' : 'ceo-btn-secondary');
  }
  document.getElementById('plan-subtitle').textContent = SUBTITLES[tab];
  document.getElementById('plan-body').innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
  document.getElementById('plan-progress').textContent = '';
  if (tab === 'review') {
    document.getElementById('plan-load-more').style.display = 'none';
    loadReview(new Date().toISOString().slice(0, 7));
  } else {
    loadMore(true);
  }
}

async function loadMore(fresh) {
  const tab = state.tab;
  const btn = document.getElementById('plan-load-more');
  btn.disabled = true;
  try {
    const catParam = tab === 'content' && state.contentCategory ? `&category=${encodeURIComponent(state.contentCategory)}` : '';
    const res = await getJson(`/api/ceo/plan?section=${tab}&offset=${state.offset[tab]}&count=${PAGE_SIZE}${catParam}`);
    const body = document.getElementById('plan-body');
    if (fresh) body.innerHTML = '';
    if (tab === 'growth') {
      appendGrowth(body, res, fresh);
      state.offset.growth += (res.days || []).length;
      state.done.growth = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.growth} of ${res.totalDays} plan days`;
    } else if (tab === 'content') {
      appendContent(body, res, fresh);
      state.offset.content += (res.items || []).length;
      state.done.content = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.content} of ${res.total} content packs`;
    } else {
      appendPhysical(body, res, fresh);
      state.offset.physical += (res.rows || []).length;
      state.done.physical = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.physical} of ${res.totalEntries} areas/cities`;
    }
    btn.style.display = state.done[tab] ? 'none' : '';
    if (state.done[tab]) {
      document.getElementById('plan-progress').textContent += ' — complete roadmap visible';
    }
    wireGlossary(document.getElementById('plan-body'));
  } catch (err) {
    document.getElementById('plan-body').innerHTML =
      `<div class="ceo-alert ceo-alert-critical">Plan load fail: ${escapeHtml(err.message)}</div>`;
  } finally {
    btn.disabled = false;
  }
}

// --- Executive Overview (Section 1) -------------------------------------
function executiveOverviewHtml(res) {
  const o = res.executiveOverview;
  if (!o) return '';
  const live = res.overviewLive;
  const b = o.budget;
  const stat = (label, value, hint) => `
    <div class="ceo-card" style="flex: 1; min-width: 150px;">
      <div class="ceo-text-muted" style="font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.04em;">${escapeHtml(label)}</div>
      <div style="font-weight: 700; margin-top: 2px;">${escapeHtml(value)}</div>
      ${hint ? `<div class="ceo-text-muted" style="font-size: 0.72rem;">${escapeHtml(hint)}</div>` : ''}
    </div>`;
  const list = (title, rows) => `
    <div style="flex: 1; min-width: 240px;">
      <div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 2px;">${escapeHtml(title)}</div>
      <ul style="margin: 0; padding-left: 1.2em; font-size: var(--ceo-font-size-sm);">${rows.join('')}</ul>
    </div>`;
  return `
    <h3 style="margin-top: 0;">Executive Overview</h3>
    <div class="ceo-flex ceo-gap-3" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-3);">
      ${stat('Duration', o.durationLabel)}
      ${stat('Current progress', live ? `${live.progressPct}%` : '—', live ? `${live.activeClients} active IB clients` : '')}
      ${stat('Current phase', live ? `Day ${live.currentDay} / ${live.totalDays}` : '—', live ? live.currentPhase : '')}
      ${stat('Monthly target', live ? live.monthlyTarget : '—')}
      ${stat('Expected reach', o.expected.reach)}
      ${stat('Expected leads', o.expected.leads)}
      ${stat('Expected active IB', o.expected.activeClients)}
    </div>
    <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-3);">
      ${list('Budget', [
        `<li>Total: ${escapeHtml(b.totalEstimated)}</li>`,
        `<li>Monthly: ${escapeHtml(b.monthlyEnvelope)}</li>`,
        `<li>Organic: ${escapeHtml(b.organicMonthly)}</li>`,
        `<li>Paid: ${escapeHtml(b.paidGate)} ${escapeHtml(b.paidMonthlyWhenActive)}</li>`,
      ])}
      ${list('Country-wise budget', o.countryBudget.map((c) => `<li><strong>${escapeHtml(c.country)}:</strong> ${escapeHtml(c.spend)} <span class="ceo-text-muted">(${escapeHtml(c.note)})</span></li>`))}
      ${list('Platform-wise budget', o.platformBudget.map((p) => `<li><strong>${escapeHtml(p.platform)}:</strong> ${escapeHtml(p.spend)} <span class="ceo-text-muted">(${escapeHtml(p.note)})</span></li>`))}
    </div>
    <div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 2px;">Paid campaigns (the only paid channel is Facebook)</div>
    <div style="overflow-x: auto; margin-bottom: var(--ceo-space-2);">
      <table class="ceo-table" style="min-width: 900px;">
        <thead><tr><th>Platform</th><th>Country</th><th>Audience</th><th>Language</th><th>Budget</th><th>Duration</th><th>Expected Result</th></tr></thead>
        <tbody>
          ${o.paidCampaigns.map((p) => `<tr>
            <td>${escapeHtml(p.platform)}</td><td>${escapeHtml(p.country)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.audience)}</td><td>${escapeHtml(p.language)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.budget)}</td><td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.duration)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.expected)}</td></tr>`).join('')}
        </tbody>
      </table>
    </div>
    <p class="ceo-text-muted" style="font-size: 0.75rem; margin-bottom: var(--ceo-space-4);">${escapeHtml(o.assumptionNote)}</p>`;
}

// --- Social Media Strategy (Section 5) ----------------------------------
function socialStrategyHtml(res) {
  const s = res.socialStrategy;
  if (!s || !s.length) return '';
  return `
    <h3>Social Media Strategy</h3>
    <div style="overflow-x: auto; margin-bottom: var(--ceo-space-4);">
      <table class="ceo-table" style="min-width: 1200px;">
        <thead><tr><th>Platform</th><th>Country</th><th>Language</th><th>Audience</th><th>Organic Strategy</th><th>Paid Strategy</th><th>Budget</th><th>Duration</th><th>Expected KPI</th><th>Expected Result</th></tr></thead>
        <tbody>
          ${s.map((p) => `<tr>
            <td><strong>${escapeHtml(p.platform)}</strong></td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.country)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.language)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.audience)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.organic)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.paid)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.budget)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.duration)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.kpi)}</td>
            <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(p.result)}</td></tr>`).join('')}
        </tbody>
      </table>
    </div>`;
}

// --- Proven funnel workflow (Section 6) ---------------------------------
function provenWorkflowHtml(res) {
  const w = res.provenWorkflow;
  if (!w) return '';
  return `
    <h3>${escapeHtml(w.title)}</h3>
    <p class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin-top: 0;">${escapeHtml(w.note)}</p>
    <div style="margin-bottom: var(--ceo-space-4);">
      ${w.steps.map((s, i) => `
        <div class="ceo-flex ceo-gap-3" style="align-items: flex-start; padding: var(--ceo-space-2) 0; border-bottom: 1px solid var(--ceo-border);">
          <span class="ceo-badge ceo-badge-neutral" style="min-width: 1.6em; text-align: center;">${i + 1}</span>
          <div><strong>${escapeHtml(s.stage)}</strong><div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.detail)}</div></div>
          ${i < w.steps.length - 1 ? '<span class="ceo-text-muted" style="margin-left: auto;">↓</span>' : ''}
        </div>`).join('')}
    </div>`;
}

// --- IB Growth Master Plan table ----------------------------------------
function appendGrowth(body, res, fresh) {
  if (fresh && res.countryStrategy) {
    const f = res.feasibility;
    body.insertAdjacentHTML('beforeend', `
      ${executiveOverviewHtml(res)}
      ${res.autoLearn ? `<div class="ceo-alert ceo-alert-warning" style="margin-bottom: var(--ceo-space-3);">🧠 ${escapeHtml(res.autoLearn)}</div>` : ''}
      ${f ? `
        <h3 style="margin-top: 0;">Feasibility Model — the path to ${Number(f.target).toLocaleString()}</h3>
        <div class="ceo-alert" style="border: 1px solid var(--ceo-border); border-radius: var(--ceo-radius-sm); padding: var(--ceo-space-3); margin-bottom: var(--ceo-space-3);">
          <strong>Audit verdict:</strong> ${escapeHtml(f.verdict)}
        </div>
        <div style="overflow-x: auto; margin-bottom: var(--ceo-space-2);">
          <table class="ceo-table" style="min-width: 700px;">
            <thead><tr><th>Funnel Stage</th><th>Required</th><th>Basis</th><th>Assumption</th></tr></thead>
            <tbody>
              ${f.stages.map((s) => `
                <tr>
                  <td><strong>${escapeHtml(s.stage)}</strong></td>
                  <td>${escapeHtml(s.required)}</td>
                  <td><span class="ceo-badge ${s.basis === 'FOUNDER GOAL' ? 'ceo-badge-critical' : s.basis === 'VERIFIED RANGE' ? 'ceo-badge-success' : 'ceo-badge-neutral'}">${escapeHtml(s.basis)}</span></td>
                  <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.note)}</td>
                </tr>`).join('')}
            </tbody>
          </table>
        </div>
        <p class="ceo-text-muted" style="font-size: 0.75rem; margin-bottom: var(--ceo-space-4);">${escapeHtml(f.assumptionNote)}</p>` : ''}
      <h3 style="margin-top: 0;">Country Strategy — the multi-market master table (validated)</h3>
      ${res.countryValidationNote ? `<p class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin-top: 0;">${escapeHtml(res.countryValidationNote)}</p>` : ''}
      <div style="overflow-x: auto; margin-bottom: var(--ceo-space-4);">
        <table class="ceo-table" style="min-width: 1260px;">
          <thead><tr>
            <th>Country</th><th>Status</th><th>Priority / Gate</th><th>Preferred Broker</th><th>Language</th><th>Platform</th>
            <th>Content Type</th><th>Audience</th><th>Posting Frequency</th><th>Organic Strategy</th><th>Paid Strategy</th>
            <th>Expected Conversion</th><th>Budget / Expected CAC</th><th>Expected IB Growth</th>
          </tr></thead>
          <tbody>
            ${res.countryStrategy.map((c) => `
              <tr>
                <td><strong>${escapeHtml(c.country)}</strong></td>
                <td><span class="ceo-badge ${c.status === 'active' ? 'ceo-badge-success' : c.status === 'gated' ? 'ceo-badge-warning' : 'ceo-badge-neutral'}">${escapeHtml(c.status || '')}</span></td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.priority)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.broker)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.language)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.platform)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.contentType)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.audience)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.postingFrequency)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.organicStrategy || c.promotion)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.paidStrategy || '—')}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedConversion)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedCac)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedGrowth)}</td>
              </tr>`).join('')}
          </tbody>
        </table>
      </div>
      <p class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(res.assumptionNote || '')}</p>
      ${socialStrategyHtml(res)}
      ${provenWorkflowHtml(res)}
      <h3>Day-by-Day Roadmap</h3>`);
  }
  let tbody = body.querySelector('#plan-growth-tbody');
  if (fresh || !tbody) {
    body.insertAdjacentHTML('beforeend', `
      <div style="overflow-x: auto;">
        <table class="ceo-table" style="min-width: 1100px;">
          <thead>
            <tr>
              <th>Day</th><th>Date</th><th>Platform</th><th>Country</th><th>Language</th>
              <th style="min-width: 280px;">Activity</th><th>Budget</th><th>Expected Result</th><th>Status</th><th>Notes</th>
            </tr>
          </thead>
          <tbody id="plan-growth-tbody"></tbody>
        </table>
      </div>`);
    tbody = body.querySelector('#plan-growth-tbody');
  }
  tbody.insertAdjacentHTML('beforeend', (res.days || []).map((d) => `
    <tr>
      <td><strong>${d.day}</strong></td>
      <td style="white-space: nowrap;">${escapeHtml(d.date)}<div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: capitalize;">${escapeHtml(d.weekday)}</div>${d.estimatedLoad ? `<div class="ceo-text-muted" style="font-size: 0.7rem; white-space: normal; max-width: 9em;">${escapeHtml(d.estimatedLoad)}</div>` : ''}</td>
      <td>${escapeHtml(d.platform)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.country)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.language)}</td>
      <td>
        <ul style="margin: 0; padding-left: 1.1em; font-size: var(--ceo-font-size-sm);">${d.activities.map((a) => `<li>${escapeHtml(a)}</li>`).join('')}</ul>
        ${campaignDetailHtml(d.campaigns)}
      </td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.budget)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.expectedResult)}</td>
      <td style="white-space: nowrap;">${statusBadge(d.status)}</td>
      <td class="ceo-text-muted" style="font-size: 0.75rem; min-width: 160px;">${escapeHtml(d.note)}<div style="margin-top: 2px;">${escapeHtml(d.stage)}</div></td>
    </tr>`).join(''));
}

// Per-campaign execution detail inside the day row — country, researched
// audience interests, language, platform, organic/paid, budget, duration,
// CTA, KPI and expected result for every channel the day schedules. Collapsed
// so the table stays scannable; the founder never leaves the day to plan it.
function campaignDetailHtml(campaigns) {
  if (!campaigns || !campaigns.length) return '';
  const field = (label, value) => value
    ? `<div style="margin-top: 2px;"><span class="ceo-text-muted">${escapeHtml(label)}:</span> ${escapeHtml(value)}</div>` : '';
  return `
    <details style="margin-top: var(--ceo-space-2);">
      <summary class="ceo-text-secondary" style="cursor: pointer; font-size: 0.75rem;">📡 Campaign details (${campaigns.length}) — country, audience, budget, CTA, KPI</summary>
      <div style="margin-top: var(--ceo-space-1);">
        ${campaigns.map((c) => `
          <div style="border-top: 1px solid var(--ceo-border); padding: var(--ceo-space-2) 0; font-size: 0.75rem;">
            <div class="ceo-flex ceo-items-center ceo-gap-2" style="flex-wrap: wrap;">
              <strong>${escapeHtml(c.activity)}</strong>
              <span class="ceo-badge ${String(c.mode).toUpperCase().includes('PAID') ? 'ceo-badge-warning' : 'ceo-badge-neutral'}">${escapeHtml(c.mode)}</span>
              <span class="ceo-text-muted">${escapeHtml(c.platform)}</span>
            </div>
            ${field('Country', c.country)}
            ${field('Target audience', c.audience)}
            ${field('Language', c.language)}
            ${field('Budget', c.budget)}
            ${field('Campaign duration', c.duration)}
            ${field('CTA', c.cta)}
            ${field('KPI', c.kpi)}
            ${field('Expected result', c.expected)}
          </div>`).join('')}
      </div>
    </details>`;
}

function statusBadge(status) {
  const s = String(status || 'Planned');
  const cls = s === 'Planned' ? 'ceo-badge-neutral'
    : s.startsWith('In progress') || s === 'Today' ? 'ceo-badge-warning'
    : s === 'No log' ? 'ceo-badge-neutral'
    : 'ceo-badge-success';
  return `<span class="ceo-badge ${cls}">${escapeHtml(s)}</span>`;
}

// --- Content Engine library ----------------------------------------------
function appendContent(body, res, fresh) {
  if (fresh) {
    body.insertAdjacentHTML('beforeend', `
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-3);">
        <label class="ceo-label" style="margin: 0;">Category</label>
        <select class="ceo-input" id="content-category" style="max-width: 18em;">
          <option value="">All categories (${res.total})</option>
          ${(res.categories || []).map((c) => `<option value="${escapeAttr(c)}" ${state.contentCategory === c ? 'selected' : ''}>${escapeHtml(c)}</option>`).join('')}
        </select>
      </div>
      <div id="plan-content-rows"></div>`);
    body.querySelector('#content-category').addEventListener('change', (e) => {
      state.contentCategory = e.target.value;
      state.offset.content = 0;
      state.done.content = false;
      document.getElementById('plan-body').innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
      loadMore(true);
    });
  }
  const holder = body.querySelector('#plan-content-rows');
  holder.insertAdjacentHTML('beforeend', (res.items || []).map((i) => `
    <div class="ceo-card" style="margin-bottom: var(--ceo-space-3);">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <span class="ceo-badge ceo-badge-neutral">${escapeHtml(i.category)}</span>
        <strong style="flex: 1; min-width: 14em;">${escapeHtml(i.title)}</strong>
        <span class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm);">${escapeHtml(i.platform)}</span>
      </div>
      <div class="ceo-text-muted" style="font-size: 0.75rem; margin: var(--ceo-space-1) 0;">
        ${escapeHtml(i.country)} · ${escapeHtml(i.audience)} · ${escapeHtml(i.language)}
      </div>
      <div style="font-size: var(--ceo-font-size-sm);">
        <div><strong>Hook:</strong> ${escapeHtml(i.hook)}</div>
        <div><strong>Structure:</strong> ${escapeHtml(i.structure)}</div>
        <div><strong>CTA:</strong> ${escapeHtml(i.cta)}</div>
        <div class="ceo-text-secondary"><strong>Expected:</strong> ${escapeHtml(i.expected)} · <strong>Budget:</strong> ${escapeHtml(i.budget)}</div>
      </div>
    </div>`).join(''));
}

// --- Physical IB Expansion roadmap --------------------------------------
function appendPhysical(body, res, fresh) {
  if (Array.isArray(res.queue)) state.queue = res.queue;
  if (res.cycle && typeof res.cycle.firstUpcomingIndex === 'number') state.firstUpcoming = res.cycle.firstUpcomingIndex;
  if (fresh) {
    body.insertAdjacentHTML('beforeend', `
      <p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin-top: 0;">
        Country: <strong>Pakistan</strong> · cycle: ${res.cycle?.cycleDays || 15} days per area · current: <strong>${escapeHtml(res.cycle?.current || 'not started')}</strong>
        · type a position number to move an upcoming area (done/current areas stay in place)
      </p>
      <div id="plan-physical-rows"></div>`);
  }
  const holder = body.querySelector('#plan-physical-rows');
  holder.insertAdjacentHTML('beforeend', (res.rows || []).map((r) => `
    ${r.province !== state.lastProvince ? `<h3 style="margin: var(--ceo-space-4) 0 var(--ceo-space-2);">${escapeHtml((state.lastProvince = r.province))}</h3>` : ''}
    <div class="ceo-card" style="margin-bottom: var(--ceo-space-4);" data-area-index="${r.index}">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <span class="ceo-badge ${r.state === 'current' ? 'ceo-badge-warning' : r.state === 'done' ? 'ceo-badge-success' : 'ceo-badge-neutral'}">${escapeHtml(r.state)}</span>
        <strong style="flex: 1; min-width: 12em;">#${r.index + 1} — ${escapeHtml(r.entry)}</strong>
        ${r.state === 'upcoming' ? `
          <span class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm);">Move to #</span>
          <input class="ceo-input" type="number" data-pos-input min="1" max="${state.queue.length}" placeholder="${r.index + 1}" style="max-width: 5em;" title="Exact position in the execution sequence" />
          <button class="ceo-btn ceo-btn-secondary" data-move-to>Go</button>` : ''}
        <span class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm);">${r.windowStart ? `${escapeHtml(r.windowStart)} → ${escapeHtml(r.windowEnd)}` : 'not scheduled'}</span>
      </div>
      <div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin: var(--ceo-space-1) 0 var(--ceo-space-2);">
        ${escapeHtml(r.country)} → ${escapeHtml(r.province)} → ${escapeHtml(r.division)} → ${escapeHtml(r.city)} → ${escapeHtml(r.area)}
        ${r.studentsAcquired ? ` · <strong>${r.studentsAcquired} students acquired</strong>` : ''}
      </div>
      ${(r.institutes || []).length === 0
        ? '<p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin: 0;">No institutes logged yet — add them from the Growth page when the cycle reaches this area.</p>'
        : r.institutes.map((i) => instituteHtml(i)).join('')}
      <a class="ceo-btn ceo-btn-secondary" style="margin-top: var(--ceo-space-2);" href="/ai-ceo-os/src/presentation/growth/index.html">Open in CRM</a>
    </div>`).join(''));
  wireInstituteForms(holder);
  wireAreaReorder(holder);
}

// Exact-position move (Section 5) — "Move Area to Position 6": the entry is
// lifted out and re-inserted at the typed 1-based position; everything else
// shifts automatically. Posts the full new order to institutes.js's EXISTING
// reorder_queue action (a strict same-set permutation, so nothing can be
// lost). Positions before the first upcoming slot are history (done/current
// areas) and are refused, never rewritten.
function wireAreaReorder(holder) {
  holder.querySelectorAll('[data-move-to]:not([data-wired])').forEach((btn) => {
    btn.setAttribute('data-wired', '1');
    btn.addEventListener('click', async () => {
      const row = btn.closest('[data-area-index]');
      const idx = parseInt(row.getAttribute('data-area-index'), 10);
      const raw = parseInt(row.querySelector('[data-pos-input]').value, 10);
      if (!Number.isFinite(raw)) { showToast('Position number likhein pehle.', 'info'); return; }
      const target = raw - 1; // 1-based UI -> 0-based index
      const minPos = (state.firstUpcoming ?? 0);
      if (target < minPos) {
        showToast(`Position ${raw} guzar chuki hai — pehli available position #${minPos + 1} hai.`, 'info');
        return;
      }
      if (target >= state.queue.length) {
        showToast(`Aakhri position #${state.queue.length} hai.`, 'info');
        return;
      }
      if (target === idx) return;
      const newOrder = state.queue.slice();
      const [entry] = newOrder.splice(idx, 1);
      newOrder.splice(target, 0, entry);
      btn.disabled = true;
      try {
        await postJson('/api/ceo/institutes', { action: 'reorder_queue', order: newOrder });
        showToast(`"${entry}" moved to position ${raw} — windows recalculated.`, 'success');
        switchTab('physical'); // reload with the new order + fresh windows
      } catch (err) {
        btn.disabled = false;
        showToast('Reorder fail: ' + err.message, 'critical');
      }
    });
  });
}

function instituteHtml(i) {
  return `
    <div style="border-top: 1px solid var(--ceo-border); padding: var(--ceo-space-2) 0;" data-institute-id="${i.id}" data-notes="${escapeAttr(i.notes || '')}">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <strong>${escapeHtml(i.name)}</strong>
        <span class="ceo-badge ceo-badge-neutral">${escapeHtml(String(i.stage).replace(/_/g, ' '))}</span>
        ${i.contact_name ? `<span class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm);">${escapeHtml(i.contact_name)}${i.contact_phone ? ' · ' + escapeHtml(i.contact_phone) : ''}</span>` : ''}
        ${i.next_follow_up ? `<span class="ceo-badge ceo-badge-warning">Follow-up ${escapeHtml(i.next_follow_up)}</span>` : ''}
        ${i.students_registered ? `<span class="ceo-badge ceo-badge-success">${i.students_registered} students</span>` : ''}
        <span style="flex: 1;"></span>
        <button class="ceo-btn ceo-btn-secondary" data-log-visit>Log visit</button>
      </div>
      ${i.nextStep ? `<div class="ceo-text-muted" style="font-size: 0.75rem; margin-top: 2px;">Next step: ${escapeHtml(i.nextStep)}</div>` : ''}
      ${i.notes ? `<div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin-top: var(--ceo-space-1); white-space: pre-wrap;">History: ${escapeHtml(i.notes)}</div>` : ''}
      <div data-visit-form style="display: none; margin-top: var(--ceo-space-2);"></div>
    </div>`;
}

// Inline visit recorder — one POST to the existing institutes update action:
// appends a dated line to notes (visit note / meeting summary / proposal /
// outcome all live there, per the CRM's v1 design), optionally advances the
// stage, sets the follow-up date, and updates students acquired.
function wireInstituteForms(holder) {
  holder.querySelectorAll('[data-log-visit]:not([data-wired])').forEach((btn) => {
    btn.setAttribute('data-wired', '1');
    btn.addEventListener('click', () => {
      const row = btn.closest('[data-institute-id]');
      const form = row.querySelector('[data-visit-form]');
      if (form.style.display !== 'none') { form.style.display = 'none'; return; }
      form.style.display = '';
      form.innerHTML = `
        <div class="ceo-flex ceo-gap-3" style="flex-wrap: wrap; align-items: end;">
          <div class="ceo-field" style="margin: 0; flex: 2; min-width: 14em;"><label class="ceo-label">Visit note / meeting summary / proposal / outcome</label><input class="ceo-input" data-v-note maxlength="400" placeholder="e.g. Met principal, proposal handed over, wants demo class" /></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Stage</label><select class="ceo-input" data-v-stage><option value="">(keep)</option>${STAGES.map((s) => `<option value="${s}">${s.replace(/_/g, ' ')}</option>`).join('')}</select></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Next follow-up</label><input class="ceo-input" type="date" data-v-followup /></div>
          <div class="ceo-field" style="margin: 0; max-width: 8em;"><label class="ceo-label">Students</label><input class="ceo-input" type="number" min="0" data-v-students /></div>
          <button class="ceo-btn ceo-btn-primary" data-v-save>Save</button>
        </div>`;
      form.querySelector('[data-v-save]').addEventListener('click', async () => {
        const note = form.querySelector('[data-v-note]').value.trim();
        const stage = form.querySelector('[data-v-stage]').value;
        const followup = form.querySelector('[data-v-followup]').value;
        const students = form.querySelector('[data-v-students]').value;
        const patch = { action: 'update', id: row.getAttribute('data-institute-id') };
        if (note) {
          const existingNotes = row.getAttribute('data-notes') || '';
          const dated = `[${new Date().toISOString().slice(0, 10)}] ${note}`;
          patch.notes = existingNotes ? `${existingNotes}\n${dated}` : dated;
        }
        if (stage) patch.stage = stage;
        if (followup) patch.next_follow_up = followup;
        if (students !== '') patch.students_registered = parseInt(students, 10);
        if (!note && !stage && !followup && students === '') { showToast('Kuch likhein ya chunein pehle.', 'info'); return; }
        try {
          await postJson('/api/ceo/institutes', patch);
          if (patch.notes) row.setAttribute('data-notes', patch.notes);
          showToast('Visit logged.', 'success');
          form.style.display = 'none';
        } catch (err) {
          showToast('Save fail: ' + err.message, 'critical');
        }
      });
    });
  });
}

// --- Monthly AI Review + Growth Intelligence (Sections 5 + 8) ------------
async function loadReview(month) {
  const body = document.getElementById('plan-body');
  body.innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
  try {
    const r = await getJson(`/api/ceo/intelligence?month=${encodeURIComponent(month)}`);
    const t = r.trajectory;
    const pct = (v) => (v === null || v === undefined ? '—' : `${v}%`);
    const num = (v) => (v === null || v === undefined ? '—' : String(v));
    body.innerHTML = `
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        <label class="ceo-label" for="review-month" style="margin: 0;">Month</label>
        <input class="ceo-input" type="month" id="review-month" value="${escapeAttr(r.month)}" style="max-width: 11em;" />
      </div>

      <div class="ceo-alert ceo-alert-warning" style="margin-bottom: var(--ceo-space-4);">
        <strong>What should I focus on next month?</strong><br />${escapeHtml(r.executiveSummary)}
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        ${statCard('Progress to 50,000', `${t.progressPct}%`, `${t.activeClients} active IB clients`)}
        ${statCard('Target achievement score', `${t.targetScore}/100`, 'execution 40% · consistency 30% · momentum 30%')}
        ${statCard('50k probability', `${t.probability50k}%`, t.probabilityNote)}
        ${statCard('Activations', `${t.activationsThisMonth}`, `vs ${t.activationsLastMonth} last month (${t.trendPct >= 0 ? '+' : ''}${t.trendPct}%)`)}
        ${statCard('Execution quality (30d)', pct(r.executionQuality30), 'Critical-tier completion')}
        ${statCard('Consistency (30d)', pct(r.consistency30), 'daily anchor kept')}
      </div>

      <div class="ceo-card" style="margin-bottom: var(--ceo-space-4);">
        <h3 style="margin-top: 0;">Trajectory</h3>
        <p style="margin: 0;"><strong>Current:</strong> ${escapeHtml(t.currentTrajectory)}</p>
        <p style="margin: var(--ceo-space-2) 0 0;"><strong>Expected:</strong> ${escapeHtml(t.expectedTrajectory)}</p>
      </div>

      <h3>IB Acquisition Funnel</h3>
      <div style="overflow-x: auto; margin-bottom: var(--ceo-space-4);">
        <table class="ceo-table" style="min-width: 800px;">
          <thead><tr><th>Stage</th><th>Count</th><th>Conversion</th><th>Drop-off</th><th>Est. Cost</th><th>Est. ROI</th><th>Source</th></tr></thead>
          <tbody>
            ${r.funnel.map((s) => `
              <tr${r.biggestLeak && r.biggestLeak.stage === s.stage ? ' style="outline: 1px solid var(--ceo-border);"' : ''}>
                <td><strong>${escapeHtml(s.stage)}</strong>${r.biggestLeak && r.biggestLeak.stage === s.stage ? ' <span class="ceo-badge ceo-badge-critical">biggest leak</span>' : ''}</td>
                <td>${num(s.count)}</td><td>${pct(s.conversionRate)}</td><td>${pct(s.dropOffRate)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.estimatedCost)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.estimatedRoi)}</td>
                <td class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(s.source)}</td>
              </tr>`).join('')}
          </tbody>
        </table>
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Top 20% — kept &amp; doubled</h3>
          ${r.pareto.top.length === 0 ? '<p class="ceo-text-muted">No completed activities this month yet.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.pareto.top.map((x) => `<li>${escapeHtml(x.label)} — ${x.completed}× completed · ${x.share}% of impact</li>`).join('')}</ul>`}
        </div>
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Reduce / fix</h3>
          ${r.pareto.low.length === 0 ? '<p class="ceo-text-muted">No consistently-skipped activities — nothing to cut.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.pareto.low.map((x) => `<li>${escapeHtml(x.label)} — skipped ${x.skipped}×, done ${x.completed}×</li>`).join('')}</ul>`}
        </div>
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Monthly lessons</h3>
          ${(r.lessons || []).length === 0 ? '<p class="ceo-text-muted">No lessons yet.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.lessons.map((l) => `<li>${escapeHtml(l)}</li>`).join('')}</ul>`}
        </div>
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Recommended improvements <span class="ceo-text-muted" style="font-size: 0.72rem;">(auto-applied to the plan via FOCUS/REDUCE)</span></h3>
          ${(r.improvements || []).length === 0 ? '<p class="ceo-text-muted">No changes recommended.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.improvements.map((l) => `<li>${escapeHtml(l)}</li>`).join('')}</ul>`}
        </div>
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        ${dimCard('Brokers (by active clients)', r.dimensions.brokers.map((b) => `${b.name} — ${b.active} active / ${b.total} total`))}
        ${dimCard('Platforms (by referral source)', r.dimensions.platforms.map((p) => `${p.name} — ${p.active} active / ${p.total} total`))}
        ${dimCard('Content types (published)', r.dimensions.contentTypes.map((c) => `${c.name} — ${c.published} published`))}
        ${dimCard('Countries', r.dimensions.countries.map((c) => `${c.name}: ${c.note}`))}
        ${dimCard('Languages', r.dimensions.languages.map((l) => `${l.name}: ${l.note}`))}
      </div>
      <p class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(r.dimensions.dimensionNote)}</p>`;
    document.getElementById('review-month').addEventListener('change', (e) => {
      if (e.target.value) loadReview(e.target.value);
    });
    wireGlossary(body);
  } catch (err) {
    body.innerHTML = `<div class="ceo-alert ceo-alert-critical">Review load fail: ${escapeHtml(err.message)}</div>`;
  }
}

function statCard(label, value, hint) {
  return `
    <div class="ceo-card" style="flex: 1; min-width: 160px;">
      <div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em;">${escapeHtml(label)}</div>
      <div style="font-size: 1.6rem; font-weight: 700;">${escapeHtml(value)}</div>
      <div class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(hint)}</div>
    </div>`;
}

function dimCard(title, lines) {
  return `
    <div class="ceo-card" style="flex: 1; min-width: 240px;">
      <h4 style="margin: 0 0 var(--ceo-space-2);">${escapeHtml(title)}</h4>
      ${lines.length === 0 ? '<p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin: 0;">No data yet — fill this field on client records.</p>'
        : `<ul style="margin: 0; padding-left: 1.2em; font-size: var(--ceo-font-size-sm);">${lines.map((l) => `<li>${escapeHtml(l)}</li>`).join('')}</ul>`}
    </div>`;
}

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = String(str ?? '');
  return div.innerHTML;
}

function escapeAttr(str) {
  return escapeHtml(str).replace(/"/g, '&quot;');
}
