// plan-page.js — the "See Complete Plan" page, two roadmaps behind two tabs:
//
//   IB Growth Master Plan — the 365-day execution roadmap generated by
//   /api/ceo/plan?section=growth from the locked research verdicts, week
//   rhythm, leave periods, and real completion history. 15 days per Load
//   More until the whole year is visible.
//
//   Physical IB Expansion — Pakistan → province → division → city → area →
//   institutes, from the live area queue + institute CRM. Each institute row
//   allows recording a visit (note / stage / follow-up / students) through
//   the EXISTING /api/ceo/institutes update action — no new write paths.

import { getJson, postJson } from '../shared/api.js';
import { showToast } from '../shared/components/toast.js';

const PAGE_SIZE = 15;
const STAGES = [
  'cold_contact', 'proposal_sent', 'meeting', 'negotiation',
  'accepted', 'rejected', 'classes_running', 'batch_complete', 'follow_up_later',
];
const state = { tab: 'growth', offset: { growth: 0, physical: 0 }, done: { growth: false, physical: false }, queue: [] };

export function initPlanPage() {
  const params = new URLSearchParams(window.location.search);
  const t = params.get('tab');
  state.tab = t === 'physical' ? 'physical' : t === 'review' ? 'review' : 'growth';
  document.getElementById('plan-tab-growth').addEventListener('click', () => switchTab('growth'));
  document.getElementById('plan-tab-physical').addEventListener('click', () => switchTab('physical'));
  document.getElementById('plan-tab-review').addEventListener('click', () => switchTab('review'));
  document.getElementById('plan-load-more').addEventListener('click', () => loadMore());
  switchTab(state.tab);
}

const SUBTITLES = {
  growth: 'The yearly roadmap toward 50,000 IB clients — generated from the locked research (countries, brokers, platforms, languages, budget gates), shifted automatically around approved leave, re-weighted monthly by your own completion history. Loaded 15 days at a time.',
  physical: 'Pakistan-wide offline expansion: province → division → city → area → institutes. Reorder areas with ▲▼; record every visit, proposal, and follow-up per institute.',
  review: 'The Monthly AI Review + Growth Intelligence Report — funnel, Pareto 80/20, trajectory toward 50,000 active IB clients, and next month\'s focus. Generated on demand from your real data.',
};

function switchTab(tab) {
  state.tab = tab;
  state.offset = { growth: 0, physical: 0 };
  state.done = { growth: false, physical: false };
  for (const key of ['growth', 'physical', 'review']) {
    document.getElementById(`plan-tab-${key}`).className = 'ceo-btn ' + (tab === key ? 'ceo-btn-primary' : 'ceo-btn-secondary');
  }
  document.getElementById('plan-subtitle').textContent = SUBTITLES[tab];
  document.getElementById('plan-body').innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
  document.getElementById('plan-progress').textContent = '';
  if (tab === 'review') {
    document.getElementById('plan-load-more').style.display = 'none';
    loadReview(new Date().toISOString().slice(0, 7));
  } else {
    loadMore(true);
  }
}

async function loadMore(fresh) {
  const tab = state.tab;
  const btn = document.getElementById('plan-load-more');
  btn.disabled = true;
  try {
    const res = await getJson(`/api/ceo/plan?section=${tab}&offset=${state.offset[tab]}&count=${PAGE_SIZE}`);
    const body = document.getElementById('plan-body');
    if (fresh) body.innerHTML = '';
    if (tab === 'growth') {
      appendGrowth(body, res, fresh);
      state.offset.growth += (res.days || []).length;
      state.done.growth = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.growth} of ${res.totalDays} plan days`;
    } else {
      appendPhysical(body, res, fresh);
      state.offset.physical += (res.rows || []).length;
      state.done.physical = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.physical} of ${res.totalEntries} areas/cities`;
    }
    btn.style.display = state.done[tab] ? 'none' : '';
    if (state.done[tab]) {
      document.getElementById('plan-progress').textContent += ' — complete roadmap visible';
    }
  } catch (err) {
    document.getElementById('plan-body').innerHTML =
      `<div class="ceo-alert ceo-alert-critical">Plan load fail: ${escapeHtml(err.message)}</div>`;
  } finally {
    btn.disabled = false;
  }
}

// --- IB Growth Master Plan table ----------------------------------------
function appendGrowth(body, res, fresh) {
  if (fresh && res.countryStrategy) {
    body.insertAdjacentHTML('beforeend', `
      ${res.autoLearn ? `<div class="ceo-alert ceo-alert-warning" style="margin-bottom: var(--ceo-space-3);">🧠 ${escapeHtml(res.autoLearn)}</div>` : ''}
      <h3 style="margin-top: 0;">Country Strategy — the multi-market master table</h3>
      <div style="overflow-x: auto; margin-bottom: var(--ceo-space-4);">
        <table class="ceo-table" style="min-width: 1200px;">
          <thead><tr>
            <th>Country</th><th>Priority / Gate</th><th>Preferred Broker</th><th>Language</th><th>Platform</th>
            <th>Content Type</th><th>Audience</th><th>Posting Frequency</th><th>Promotion</th>
            <th>Expected Conversion</th><th>Budget / Expected CAC</th><th>Expected IB Growth</th>
          </tr></thead>
          <tbody>
            ${res.countryStrategy.map((c) => `
              <tr>
                <td><strong>${escapeHtml(c.country)}</strong></td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.priority)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.broker)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.language)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.platform)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.contentType)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.audience)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.postingFrequency)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.promotion)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedConversion)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedCac)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(c.expectedGrowth)}</td>
              </tr>`).join('')}
          </tbody>
        </table>
      </div>
      <p class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(res.assumptionNote || '')}</p>
      <h3>Day-by-Day Roadmap</h3>`);
  }
  let tbody = body.querySelector('#plan-growth-tbody');
  if (fresh || !tbody) {
    body.insertAdjacentHTML('beforeend', `
      <div style="overflow-x: auto;">
        <table class="ceo-table" style="min-width: 1100px;">
          <thead>
            <tr>
              <th>Day</th><th>Date</th><th>Platform</th><th>Country</th><th>Language</th>
              <th style="min-width: 280px;">Activity</th><th>Budget</th><th>Expected Result</th><th>Status</th><th>Notes</th>
            </tr>
          </thead>
          <tbody id="plan-growth-tbody"></tbody>
        </table>
      </div>`);
    tbody = body.querySelector('#plan-growth-tbody');
  }
  tbody.insertAdjacentHTML('beforeend', (res.days || []).map((d) => `
    <tr>
      <td><strong>${d.day}</strong></td>
      <td style="white-space: nowrap;">${escapeHtml(d.date)}<div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: capitalize;">${escapeHtml(d.weekday)}</div></td>
      <td>${escapeHtml(d.platform)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.country)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.language)}</td>
      <td><ul style="margin: 0; padding-left: 1.1em; font-size: var(--ceo-font-size-sm);">${d.activities.map((a) => `<li>${escapeHtml(a)}</li>`).join('')}</ul></td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.budget)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.expectedResult)}</td>
      <td style="white-space: nowrap;">${statusBadge(d.status)}</td>
      <td class="ceo-text-muted" style="font-size: 0.75rem; min-width: 160px;">${escapeHtml(d.note)}<div style="margin-top: 2px;">${escapeHtml(d.stage)}</div></td>
    </tr>`).join(''));
}

function statusBadge(status) {
  const s = String(status || 'Planned');
  const cls = s === 'Planned' ? 'ceo-badge-neutral'
    : s.startsWith('In progress') || s === 'Today' ? 'ceo-badge-warning'
    : s === 'No log' ? 'ceo-badge-neutral'
    : 'ceo-badge-success';
  return `<span class="ceo-badge ${cls}">${escapeHtml(s)}</span>`;
}

// --- Physical IB Expansion roadmap --------------------------------------
function appendPhysical(body, res, fresh) {
  if (Array.isArray(res.queue)) state.queue = res.queue;
  if (fresh) {
    body.insertAdjacentHTML('beforeend', `
      <p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin-top: 0;">
        Country: <strong>Pakistan</strong> · cycle: ${res.cycle?.cycleDays || 15} days per area · current: <strong>${escapeHtml(res.cycle?.current || 'not started')}</strong>
        · ▲▼ reorders the execution sequence (done areas stay in place)
      </p>
      <div id="plan-physical-rows"></div>`);
  }
  const holder = body.querySelector('#plan-physical-rows');
  holder.insertAdjacentHTML('beforeend', (res.rows || []).map((r) => `
    <div class="ceo-card" style="margin-bottom: var(--ceo-space-4);" data-area-index="${r.index}">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <span class="ceo-badge ${r.state === 'current' ? 'ceo-badge-warning' : r.state === 'done' ? 'ceo-badge-success' : 'ceo-badge-neutral'}">${escapeHtml(r.state)}</span>
        <strong style="flex: 1; min-width: 12em;">#${r.index + 1} — ${escapeHtml(r.entry)}</strong>
        ${r.state === 'upcoming' ? `
          <button class="ceo-btn ceo-btn-secondary" data-move-up title="Move this area earlier in the sequence">▲</button>
          <button class="ceo-btn ceo-btn-secondary" data-move-down title="Move this area later in the sequence">▼</button>` : ''}
        <span class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm);">${r.windowStart ? `${escapeHtml(r.windowStart)} → ${escapeHtml(r.windowEnd)}` : 'not scheduled'}</span>
      </div>
      <div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin: var(--ceo-space-1) 0 var(--ceo-space-2);">
        ${escapeHtml(r.country)} → ${escapeHtml(r.province)} → ${escapeHtml(r.division)} → ${escapeHtml(r.city)} → ${escapeHtml(r.area)}
        ${r.studentsAcquired ? ` · <strong>${r.studentsAcquired} students acquired</strong>` : ''}
      </div>
      ${(r.institutes || []).length === 0
        ? '<p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin: 0;">No institutes logged yet — add them from the Growth page when the cycle reaches this area.</p>'
        : r.institutes.map((i) => instituteHtml(i)).join('')}
      <a class="ceo-btn ceo-btn-secondary" style="margin-top: var(--ceo-space-2);" href="/ai-ceo-os/src/presentation/growth/index.html">Open in CRM</a>
    </div>`).join(''));
  wireInstituteForms(holder);
  wireAreaReorder(holder);
}

// Move Area Up/Down (Section 4) — builds the swapped order from the full
// queue and posts it to institutes.js's EXISTING reorder_queue action (a
// strict same-set permutation, so nothing can be lost). Done/current areas
// keep their position; only upcoming areas move.
function wireAreaReorder(holder) {
  holder.querySelectorAll('[data-move-up]:not([data-wired]), [data-move-down]:not([data-wired])').forEach((btn) => {
    btn.setAttribute('data-wired', '1');
    btn.addEventListener('click', async () => {
      const idx = parseInt(btn.closest('[data-area-index]').getAttribute('data-area-index'), 10);
      const dir = btn.hasAttribute('data-move-up') ? -1 : 1;
      const target = idx + dir;
      if (target < 0 || target >= state.queue.length) return;
      // Never swap into a done/current slot — position IS the schedule, so
      // that would rewrite history instead of resequencing the future.
      const targetRow = holder.querySelector(`[data-area-index="${target}"]`);
      if (targetRow && !targetRow.querySelector('[data-move-up]')) {
        showToast('Current/done area se pehle nahin le ja sakte — sirf aane wale areas resequence hote hain.', 'info');
        return;
      }
      const newOrder = state.queue.slice();
      [newOrder[idx], newOrder[target]] = [newOrder[target], newOrder[idx]];
      btn.disabled = true;
      try {
        await postJson('/api/ceo/institutes', { action: 'reorder_queue', order: newOrder });
        showToast('Sequence updated — windows recalculated.', 'success');
        switchTab('physical'); // reload with the new order + fresh windows
      } catch (err) {
        btn.disabled = false;
        showToast('Reorder fail: ' + err.message, 'critical');
      }
    });
  });
}

function instituteHtml(i) {
  return `
    <div style="border-top: 1px solid var(--ceo-border); padding: var(--ceo-space-2) 0;" data-institute-id="${i.id}" data-notes="${escapeAttr(i.notes || '')}">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <strong>${escapeHtml(i.name)}</strong>
        <span class="ceo-badge ceo-badge-neutral">${escapeHtml(String(i.stage).replace(/_/g, ' '))}</span>
        ${i.contact_name ? `<span class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm);">${escapeHtml(i.contact_name)}${i.contact_phone ? ' · ' + escapeHtml(i.contact_phone) : ''}</span>` : ''}
        ${i.next_follow_up ? `<span class="ceo-badge ceo-badge-warning">Follow-up ${escapeHtml(i.next_follow_up)}</span>` : ''}
        ${i.students_registered ? `<span class="ceo-badge ceo-badge-success">${i.students_registered} students</span>` : ''}
        <span style="flex: 1;"></span>
        <button class="ceo-btn ceo-btn-secondary" data-log-visit>Log visit</button>
      </div>
      ${i.nextStep ? `<div class="ceo-text-muted" style="font-size: 0.75rem; margin-top: 2px;">Next step: ${escapeHtml(i.nextStep)}</div>` : ''}
      ${i.notes ? `<div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin-top: var(--ceo-space-1); white-space: pre-wrap;">History: ${escapeHtml(i.notes)}</div>` : ''}
      <div data-visit-form style="display: none; margin-top: var(--ceo-space-2);"></div>
    </div>`;
}

// Inline visit recorder — one POST to the existing institutes update action:
// appends a dated line to notes (visit note / meeting summary / proposal /
// outcome all live there, per the CRM's v1 design), optionally advances the
// stage, sets the follow-up date, and updates students acquired.
function wireInstituteForms(holder) {
  holder.querySelectorAll('[data-log-visit]:not([data-wired])').forEach((btn) => {
    btn.setAttribute('data-wired', '1');
    btn.addEventListener('click', () => {
      const row = btn.closest('[data-institute-id]');
      const form = row.querySelector('[data-visit-form]');
      if (form.style.display !== 'none') { form.style.display = 'none'; return; }
      form.style.display = '';
      form.innerHTML = `
        <div class="ceo-flex ceo-gap-3" style="flex-wrap: wrap; align-items: end;">
          <div class="ceo-field" style="margin: 0; flex: 2; min-width: 14em;"><label class="ceo-label">Visit note / meeting summary / proposal / outcome</label><input class="ceo-input" data-v-note maxlength="400" placeholder="e.g. Met principal, proposal handed over, wants demo class" /></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Stage</label><select class="ceo-input" data-v-stage><option value="">(keep)</option>${STAGES.map((s) => `<option value="${s}">${s.replace(/_/g, ' ')}</option>`).join('')}</select></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Next follow-up</label><input class="ceo-input" type="date" data-v-followup /></div>
          <div class="ceo-field" style="margin: 0; max-width: 8em;"><label class="ceo-label">Students</label><input class="ceo-input" type="number" min="0" data-v-students /></div>
          <button class="ceo-btn ceo-btn-primary" data-v-save>Save</button>
        </div>`;
      form.querySelector('[data-v-save]').addEventListener('click', async () => {
        const note = form.querySelector('[data-v-note]').value.trim();
        const stage = form.querySelector('[data-v-stage]').value;
        const followup = form.querySelector('[data-v-followup]').value;
        const students = form.querySelector('[data-v-students]').value;
        const patch = { action: 'update', id: row.getAttribute('data-institute-id') };
        if (note) {
          const existingNotes = row.getAttribute('data-notes') || '';
          const dated = `[${new Date().toISOString().slice(0, 10)}] ${note}`;
          patch.notes = existingNotes ? `${existingNotes}\n${dated}` : dated;
        }
        if (stage) patch.stage = stage;
        if (followup) patch.next_follow_up = followup;
        if (students !== '') patch.students_registered = parseInt(students, 10);
        if (!note && !stage && !followup && students === '') { showToast('Kuch likhein ya chunein pehle.', 'info'); return; }
        try {
          await postJson('/api/ceo/institutes', patch);
          if (patch.notes) row.setAttribute('data-notes', patch.notes);
          showToast('Visit logged.', 'success');
          form.style.display = 'none';
        } catch (err) {
          showToast('Save fail: ' + err.message, 'critical');
        }
      });
    });
  });
}

// --- Monthly AI Review + Growth Intelligence (Sections 5 + 8) ------------
async function loadReview(month) {
  const body = document.getElementById('plan-body');
  body.innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
  try {
    const r = await getJson(`/api/ceo/intelligence?month=${encodeURIComponent(month)}`);
    const t = r.trajectory;
    const pct = (v) => (v === null || v === undefined ? '—' : `${v}%`);
    const num = (v) => (v === null || v === undefined ? '—' : String(v));
    body.innerHTML = `
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        <label class="ceo-label" for="review-month" style="margin: 0;">Month</label>
        <input class="ceo-input" type="month" id="review-month" value="${escapeAttr(r.month)}" style="max-width: 11em;" />
      </div>

      <div class="ceo-alert ceo-alert-warning" style="margin-bottom: var(--ceo-space-4);">
        <strong>What should I focus on next month?</strong><br />${escapeHtml(r.executiveSummary)}
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        ${statCard('Progress to 50,000', `${t.progressPct}%`, `${t.activeClients} active IB clients`)}
        ${statCard('Target achievement score', `${t.targetScore}/100`, 'execution 40% · consistency 30% · momentum 30%')}
        ${statCard('50k probability', `${t.probability50k}%`, t.probabilityNote)}
        ${statCard('Activations', `${t.activationsThisMonth}`, `vs ${t.activationsLastMonth} last month (${t.trendPct >= 0 ? '+' : ''}${t.trendPct}%)`)}
        ${statCard('Execution quality (30d)', pct(r.executionQuality30), 'Critical-tier completion')}
        ${statCard('Consistency (30d)', pct(r.consistency30), 'daily anchor kept')}
      </div>

      <div class="ceo-card" style="margin-bottom: var(--ceo-space-4);">
        <h3 style="margin-top: 0;">Trajectory</h3>
        <p style="margin: 0;"><strong>Current:</strong> ${escapeHtml(t.currentTrajectory)}</p>
        <p style="margin: var(--ceo-space-2) 0 0;"><strong>Expected:</strong> ${escapeHtml(t.expectedTrajectory)}</p>
      </div>

      <h3>IB Acquisition Funnel</h3>
      <div style="overflow-x: auto; margin-bottom: var(--ceo-space-4);">
        <table class="ceo-table" style="min-width: 800px;">
          <thead><tr><th>Stage</th><th>Count</th><th>Conversion</th><th>Drop-off</th><th>Est. Cost</th><th>Est. ROI</th><th>Source</th></tr></thead>
          <tbody>
            ${r.funnel.map((s) => `
              <tr${r.biggestLeak && r.biggestLeak.stage === s.stage ? ' style="outline: 1px solid var(--ceo-border);"' : ''}>
                <td><strong>${escapeHtml(s.stage)}</strong>${r.biggestLeak && r.biggestLeak.stage === s.stage ? ' <span class="ceo-badge ceo-badge-critical">biggest leak</span>' : ''}</td>
                <td>${num(s.count)}</td><td>${pct(s.conversionRate)}</td><td>${pct(s.dropOffRate)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.estimatedCost)}</td>
                <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(s.estimatedRoi)}</td>
                <td class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(s.source)}</td>
              </tr>`).join('')}
          </tbody>
        </table>
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Top 20% — kept &amp; doubled</h3>
          ${r.pareto.top.length === 0 ? '<p class="ceo-text-muted">No completed activities this month yet.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.pareto.top.map((x) => `<li>${escapeHtml(x.label)} — ${x.completed}× completed · ${x.share}% of impact</li>`).join('')}</ul>`}
        </div>
        <div class="ceo-card" style="flex: 1; min-width: 280px;">
          <h3 style="margin-top: 0;">Reduce / fix</h3>
          ${r.pareto.low.length === 0 ? '<p class="ceo-text-muted">No consistently-skipped activities — nothing to cut.</p>'
            : `<ul style="margin: 0; padding-left: 1.2em;">${r.pareto.low.map((x) => `<li>${escapeHtml(x.label)} — skipped ${x.skipped}×, done ${x.completed}×</li>`).join('')}</ul>`}
        </div>
      </div>

      <div class="ceo-flex ceo-gap-4" style="flex-wrap: wrap; margin-bottom: var(--ceo-space-4);">
        ${dimCard('Brokers (by active clients)', r.dimensions.brokers.map((b) => `${b.name} — ${b.active} active / ${b.total} total`))}
        ${dimCard('Platforms (by referral source)', r.dimensions.platforms.map((p) => `${p.name} — ${p.active} active / ${p.total} total`))}
        ${dimCard('Content types (published)', r.dimensions.contentTypes.map((c) => `${c.name} — ${c.published} published`))}
        ${dimCard('Countries', r.dimensions.countries.map((c) => `${c.name}: ${c.note}`))}
        ${dimCard('Languages', r.dimensions.languages.map((l) => `${l.name}: ${l.note}`))}
      </div>
      <p class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(r.dimensions.dimensionNote)}</p>`;
    document.getElementById('review-month').addEventListener('change', (e) => {
      if (e.target.value) loadReview(e.target.value);
    });
  } catch (err) {
    body.innerHTML = `<div class="ceo-alert ceo-alert-critical">Review load fail: ${escapeHtml(err.message)}</div>`;
  }
}

function statCard(label, value, hint) {
  return `
    <div class="ceo-card" style="flex: 1; min-width: 160px;">
      <div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em;">${escapeHtml(label)}</div>
      <div style="font-size: 1.6rem; font-weight: 700;">${escapeHtml(value)}</div>
      <div class="ceo-text-muted" style="font-size: 0.75rem;">${escapeHtml(hint)}</div>
    </div>`;
}

function dimCard(title, lines) {
  return `
    <div class="ceo-card" style="flex: 1; min-width: 240px;">
      <h4 style="margin: 0 0 var(--ceo-space-2);">${escapeHtml(title)}</h4>
      ${lines.length === 0 ? '<p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin: 0;">No data yet — fill this field on client records.</p>'
        : `<ul style="margin: 0; padding-left: 1.2em; font-size: var(--ceo-font-size-sm);">${lines.map((l) => `<li>${escapeHtml(l)}</li>`).join('')}</ul>`}
    </div>`;
}

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = String(str ?? '');
  return div.innerHTML;
}

function escapeAttr(str) {
  return escapeHtml(str).replace(/"/g, '&quot;');
}
