// plan-page.js — the "See Complete Plan" page, two roadmaps behind two tabs:
//
//   IB Growth Master Plan — the 365-day execution roadmap generated by
//   /api/ceo/plan?section=growth from the locked research verdicts, week
//   rhythm, leave periods, and real completion history. 15 days per Load
//   More until the whole year is visible.
//
//   Physical IB Expansion — Pakistan → province → division → city → area →
//   institutes, from the live area queue + institute CRM. Each institute row
//   allows recording a visit (note / stage / follow-up / students) through
//   the EXISTING /api/ceo/institutes update action — no new write paths.

import { getJson, postJson } from '../shared/api.js';
import { showToast } from '../shared/components/toast.js';

const PAGE_SIZE = 15;
const STAGES = [
  'cold_contact', 'proposal_sent', 'meeting', 'negotiation',
  'accepted', 'rejected', 'classes_running', 'batch_complete', 'follow_up_later',
];
const state = { tab: 'growth', offset: { growth: 0, physical: 0 }, done: { growth: false, physical: false } };

export function initPlanPage() {
  const params = new URLSearchParams(window.location.search);
  state.tab = params.get('tab') === 'physical' ? 'physical' : 'growth';
  document.getElementById('plan-tab-growth').addEventListener('click', () => switchTab('growth'));
  document.getElementById('plan-tab-physical').addEventListener('click', () => switchTab('physical'));
  document.getElementById('plan-load-more').addEventListener('click', () => loadMore());
  switchTab(state.tab);
}

function switchTab(tab) {
  state.tab = tab;
  state.offset = { growth: 0, physical: 0 };
  state.done = { growth: false, physical: false };
  document.getElementById('plan-tab-growth').className = 'ceo-btn ' + (tab === 'growth' ? 'ceo-btn-primary' : 'ceo-btn-secondary');
  document.getElementById('plan-tab-physical').className = 'ceo-btn ' + (tab === 'physical' ? 'ceo-btn-primary' : 'ceo-btn-secondary');
  document.getElementById('plan-subtitle').textContent = tab === 'growth'
    ? 'The yearly roadmap toward 50,000 IB clients — generated from the locked research (countries, platforms, languages, budget gates), shifted automatically around approved leave. Loaded 15 days at a time.'
    : 'Pakistan-wide offline expansion: province → division → city → area → institutes. Every visit, proposal, and follow-up recorded per institute.';
  document.getElementById('plan-body').innerHTML = '<div class="ceo-skeleton" style="height: 12em;"></div>';
  loadMore(true);
}

async function loadMore(fresh) {
  const tab = state.tab;
  const btn = document.getElementById('plan-load-more');
  btn.disabled = true;
  try {
    const res = await getJson(`/api/ceo/plan?section=${tab}&offset=${state.offset[tab]}&count=${PAGE_SIZE}`);
    const body = document.getElementById('plan-body');
    if (fresh) body.innerHTML = '';
    if (tab === 'growth') {
      appendGrowth(body, res, fresh);
      state.offset.growth += (res.days || []).length;
      state.done.growth = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.growth} of ${res.totalDays} plan days`;
    } else {
      appendPhysical(body, res, fresh);
      state.offset.physical += (res.rows || []).length;
      state.done.physical = !res.hasMore;
      document.getElementById('plan-progress').textContent = `Showing ${state.offset.physical} of ${res.totalEntries} areas/cities`;
    }
    btn.style.display = state.done[tab] ? 'none' : '';
    if (state.done[tab]) {
      document.getElementById('plan-progress').textContent += ' — complete roadmap visible';
    }
  } catch (err) {
    document.getElementById('plan-body').innerHTML =
      `<div class="ceo-alert ceo-alert-critical">Plan load fail: ${escapeHtml(err.message)}</div>`;
  } finally {
    btn.disabled = false;
  }
}

// --- IB Growth Master Plan table ----------------------------------------
function appendGrowth(body, res, fresh) {
  let tbody = body.querySelector('#plan-growth-tbody');
  if (fresh || !tbody) {
    body.insertAdjacentHTML('beforeend', `
      <div style="overflow-x: auto;">
        <table class="ceo-table" style="min-width: 1100px;">
          <thead>
            <tr>
              <th>Day</th><th>Date</th><th>Platform</th><th>Country</th><th>Language</th>
              <th style="min-width: 280px;">Activity</th><th>Budget</th><th>Expected Result</th><th>Status</th><th>Notes</th>
            </tr>
          </thead>
          <tbody id="plan-growth-tbody"></tbody>
        </table>
      </div>`);
    tbody = body.querySelector('#plan-growth-tbody');
  }
  tbody.insertAdjacentHTML('beforeend', (res.days || []).map((d) => `
    <tr>
      <td><strong>${d.day}</strong></td>
      <td style="white-space: nowrap;">${escapeHtml(d.date)}<div class="ceo-text-muted" style="font-size: 0.72rem; text-transform: capitalize;">${escapeHtml(d.weekday)}</div></td>
      <td>${escapeHtml(d.platform)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.country)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.language)}</td>
      <td><ul style="margin: 0; padding-left: 1.1em; font-size: var(--ceo-font-size-sm);">${d.activities.map((a) => `<li>${escapeHtml(a)}</li>`).join('')}</ul></td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.budget)}</td>
      <td style="font-size: var(--ceo-font-size-sm);">${escapeHtml(d.expectedResult)}</td>
      <td style="white-space: nowrap;">${statusBadge(d.status)}</td>
      <td class="ceo-text-muted" style="font-size: 0.75rem; min-width: 160px;">${escapeHtml(d.note)}<div style="margin-top: 2px;">${escapeHtml(d.stage)}</div></td>
    </tr>`).join(''));
}

function statusBadge(status) {
  const s = String(status || 'Planned');
  const cls = s === 'Planned' ? 'ceo-badge-neutral'
    : s.startsWith('In progress') || s === 'Today' ? 'ceo-badge-warning'
    : s === 'No log' ? 'ceo-badge-neutral'
    : 'ceo-badge-success';
  return `<span class="ceo-badge ${cls}">${escapeHtml(s)}</span>`;
}

// --- Physical IB Expansion roadmap --------------------------------------
function appendPhysical(body, res, fresh) {
  if (fresh) {
    body.insertAdjacentHTML('beforeend', `
      <p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin-top: 0;">
        Country: <strong>Pakistan</strong> · cycle: ${res.cycle?.cycleDays || 15} days per area · current: <strong>${escapeHtml(res.cycle?.current || 'not started')}</strong>
      </p>
      <div id="plan-physical-rows"></div>`);
  }
  const holder = body.querySelector('#plan-physical-rows');
  holder.insertAdjacentHTML('beforeend', (res.rows || []).map((r) => `
    <div class="ceo-card" style="margin-bottom: var(--ceo-space-4);">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <span class="ceo-badge ${r.state === 'current' ? 'ceo-badge-warning' : r.state === 'done' ? 'ceo-badge-success' : 'ceo-badge-neutral'}">${escapeHtml(r.state)}</span>
        <strong style="flex: 1; min-width: 12em;">#${r.index + 1} — ${escapeHtml(r.entry)}</strong>
        <span class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm);">${r.windowStart ? `${escapeHtml(r.windowStart)} → ${escapeHtml(r.windowEnd)}` : 'not scheduled'}</span>
      </div>
      <div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin: var(--ceo-space-1) 0 var(--ceo-space-2);">
        ${escapeHtml(r.country)} → ${escapeHtml(r.province)} → ${escapeHtml(r.division)} → ${escapeHtml(r.city)} → ${escapeHtml(r.area)}
        ${r.studentsAcquired ? ` · <strong>${r.studentsAcquired} students acquired</strong>` : ''}
      </div>
      ${(r.institutes || []).length === 0
        ? '<p class="ceo-text-muted" style="font-size: var(--ceo-font-size-sm); margin: 0;">No institutes logged yet — add them from the Growth page when the cycle reaches this area.</p>'
        : r.institutes.map((i) => instituteHtml(i)).join('')}
      <a class="ceo-btn ceo-btn-secondary" style="margin-top: var(--ceo-space-2);" href="/ai-ceo-os/src/presentation/growth/index.html">Open in CRM</a>
    </div>`).join(''));
  wireInstituteForms(holder);
}

function instituteHtml(i) {
  return `
    <div style="border-top: 1px solid var(--ceo-border); padding: var(--ceo-space-2) 0;" data-institute-id="${i.id}" data-notes="${escapeAttr(i.notes || '')}">
      <div class="ceo-flex ceo-items-center ceo-gap-3" style="flex-wrap: wrap;">
        <strong>${escapeHtml(i.name)}</strong>
        <span class="ceo-badge ceo-badge-neutral">${escapeHtml(String(i.stage).replace(/_/g, ' '))}</span>
        ${i.contact_name ? `<span class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm);">${escapeHtml(i.contact_name)}${i.contact_phone ? ' · ' + escapeHtml(i.contact_phone) : ''}</span>` : ''}
        ${i.next_follow_up ? `<span class="ceo-badge ceo-badge-warning">Follow-up ${escapeHtml(i.next_follow_up)}</span>` : ''}
        ${i.students_registered ? `<span class="ceo-badge ceo-badge-success">${i.students_registered} students</span>` : ''}
        <span style="flex: 1;"></span>
        <button class="ceo-btn ceo-btn-secondary" data-log-visit>Log visit</button>
      </div>
      ${i.nextStep ? `<div class="ceo-text-muted" style="font-size: 0.75rem; margin-top: 2px;">Next step: ${escapeHtml(i.nextStep)}</div>` : ''}
      ${i.notes ? `<div class="ceo-text-secondary" style="font-size: var(--ceo-font-size-sm); margin-top: var(--ceo-space-1); white-space: pre-wrap;">History: ${escapeHtml(i.notes)}</div>` : ''}
      <div data-visit-form style="display: none; margin-top: var(--ceo-space-2);"></div>
    </div>`;
}

// Inline visit recorder — one POST to the existing institutes update action:
// appends a dated line to notes (visit note / meeting summary / proposal /
// outcome all live there, per the CRM's v1 design), optionally advances the
// stage, sets the follow-up date, and updates students acquired.
function wireInstituteForms(holder) {
  holder.querySelectorAll('[data-log-visit]:not([data-wired])').forEach((btn) => {
    btn.setAttribute('data-wired', '1');
    btn.addEventListener('click', () => {
      const row = btn.closest('[data-institute-id]');
      const form = row.querySelector('[data-visit-form]');
      if (form.style.display !== 'none') { form.style.display = 'none'; return; }
      form.style.display = '';
      form.innerHTML = `
        <div class="ceo-flex ceo-gap-3" style="flex-wrap: wrap; align-items: end;">
          <div class="ceo-field" style="margin: 0; flex: 2; min-width: 14em;"><label class="ceo-label">Visit note / meeting summary / proposal / outcome</label><input class="ceo-input" data-v-note maxlength="400" placeholder="e.g. Met principal, proposal handed over, wants demo class" /></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Stage</label><select class="ceo-input" data-v-stage><option value="">(keep)</option>${STAGES.map((s) => `<option value="${s}">${s.replace(/_/g, ' ')}</option>`).join('')}</select></div>
          <div class="ceo-field" style="margin: 0;"><label class="ceo-label">Next follow-up</label><input class="ceo-input" type="date" data-v-followup /></div>
          <div class="ceo-field" style="margin: 0; max-width: 8em;"><label class="ceo-label">Students</label><input class="ceo-input" type="number" min="0" data-v-students /></div>
          <button class="ceo-btn ceo-btn-primary" data-v-save>Save</button>
        </div>`;
      form.querySelector('[data-v-save]').addEventListener('click', async () => {
        const note = form.querySelector('[data-v-note]').value.trim();
        const stage = form.querySelector('[data-v-stage]').value;
        const followup = form.querySelector('[data-v-followup]').value;
        const students = form.querySelector('[data-v-students]').value;
        const patch = { action: 'update', id: row.getAttribute('data-institute-id') };
        if (note) {
          const existingNotes = row.getAttribute('data-notes') || '';
          const dated = `[${new Date().toISOString().slice(0, 10)}] ${note}`;
          patch.notes = existingNotes ? `${existingNotes}\n${dated}` : dated;
        }
        if (stage) patch.stage = stage;
        if (followup) patch.next_follow_up = followup;
        if (students !== '') patch.students_registered = parseInt(students, 10);
        if (!note && !stage && !followup && students === '') { showToast('Kuch likhein ya chunein pehle.', 'info'); return; }
        try {
          await postJson('/api/ceo/institutes', patch);
          if (patch.notes) row.setAttribute('data-notes', patch.notes);
          showToast('Visit logged.', 'success');
          form.style.display = 'none';
        } catch (err) {
          showToast('Save fail: ' + err.message, 'critical');
        }
      });
    });
  });
}

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = String(str ?? '');
  return div.innerHTML;
}

function escapeAttr(str) {
  return escapeHtml(str).replace(/"/g, '&quot;');
}
