// functions/api/ceo/plan.js  ->  GET /api/ceo/plan
//
// The "See Complete Plan" data source for both roadmaps, paged 15 days /
// 15 entries at a time (Load More):
//   ?section=growth&offset=0&count=15   — IB Growth Master Plan (365 plan
//     days generated by utils/ceo/plan-logic.js from plan.start_date, the
//     week rhythm, the locked research verdicts, and leave periods; past
//     days carry a real completion status joined from daily_activities).
//   ?section=physical&offset=0&count=15 — Physical IB Expansion roadmap
//     (the live area queue with province/division geography, projected
//     15-day windows, and each area's institutes from the CRM).
//
// Read-only: all writes stay in their owning endpoints (activities.js for
// leave/reset, institutes.js for institute records).

import { rest, json, requireFounder } from '../../utils/ceo/db.js';
import { generateGrowthDays, buildPhysicalRows, PLAN_TOTAL_DAYS, COUNTRY_STRATEGY, ASSUMPTION_NOTE } from '../../utils/ceo/plan-logic.js';
import { currentAreaAssignment } from '../../utils/ceo/physical-logic.js';
import { instituteNextStep } from '../../utils/ceo/coach-logic.js';

const DAY_NAMES = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

// settings.value arrives as parsed jsonb, but rows written through the REST
// helper may hold a JSON-encoded string — accept both (same defense as the
// leave reader in mission.js).
function asArray(v) {
  if (Array.isArray(v)) return v;
  if (typeof v === 'string') {
    try { const p = JSON.parse(v); return Array.isArray(p) ? p : []; } catch { return []; }
  }
  return [];
}
const asDateStr = (v) => {
  const s = String(v ?? '').replace(/"/g, '');
  return /^\d{4}-\d{2}-\d{2}$/.test(s) ? s : null;
};

export async function onRequestGet({ request, env }) {
  const auth = await requireFounder(request, env);
  if (auth.response) return auth.response;
  const db = rest(env, auth.token);
  const uid = auth.user.id;
  const url = new URL(request.url);
  const section = url.searchParams.get('section') === 'physical' ? 'physical' : 'growth';
  const offset = Math.max(0, parseInt(url.searchParams.get('offset'), 10) || 0);
  const count = Math.min(30, Math.max(1, parseInt(url.searchParams.get('count'), 10) || 15));

  try {
    const settings = await db.select('settings', 'select=key,value&scope=eq.global');
    const setting = (k, fallback) => {
      const row = settings.find((s) => s.key === k);
      return row ? row.value : fallback;
    };

    if (section === 'physical') {
      const queue = asArray(setting('physical.area_queue', []));
      const cycleDays = Number(String(setting('physical.cycle_days', 15)).replace(/"/g, '')) || 15;
      const startDate = asDateStr(setting('physical.start_date', null));
      const assignment = currentAreaAssignment(queue, startDate, cycleDays);
      const { rows, hasMore, totalEntries } = buildPhysicalRows(queue, startDate, cycleDays, offset, count);

      // Join each window row's institutes from the CRM (one fetch, grouped
      // client-side — an area entry matches on area, a city entry on city).
      const institutes = await db.select(
        'institutes',
        `select=id,name,institute_type,city,area,contact_name,contact_phone,stage,next_follow_up,batch_end_date,students_registered,notes,updated_at&owner_user_id=eq.${uid}&order=updated_at.desc&limit=300`
      );
      for (const row of rows) {
        const matches = institutes.filter((i) =>
          row.city === row.entry ? i.city === row.entry : i.area === row.entry
        );
        row.institutes = matches.map((i) => ({ ...i, nextStep: instituteNextStep(i.stage) }));
        row.studentsAcquired = matches.reduce((s, i) => s + (i.students_registered || 0), 0);
      }
      // Full queue included so the page can reorder areas (Move Up/Down posts
      // a same-set permutation to institutes.js's existing reorder_queue).
      return json({ section, offset, count, rows, hasMore, totalEntries, queue, cycle: { startDate, cycleDays, current: assignment.current, exhausted: assignment.exhausted } });
    }

    // --- growth section ---
    // Day 1 of the master plan: plan.start_date if set (Reset Plan writes
    // it), else the founder's real first execution day (earliest activity
    // row), else today — never an invented anchor.
    let startDate = asDateStr(setting('plan.start_date', null));
    if (!startDate) {
      const first = await db.select('daily_activities', `select=activity_date&owner_user_id=eq.${uid}&order=activity_date.asc&limit=1`);
      startDate = first[0]?.activity_date || new Date().toISOString().slice(0, 10);
    }
    const productionDay = String(setting('week.production_day', 'monday')).replace(/"/g, '');
    const publishDay = DAY_NAMES[(DAY_NAMES.indexOf(productionDay) + 1) % 7];
    const leavePeriods = asArray(setting('leave.periods', []));

    // Self-optimizing layer (Section 6): learn the last 28 days' winner and
    // loser from real completion history, and let the generator annotate
    // every FUTURE day with FOCUS/REDUCE lines. Fully automatic — no toggle.
    const today = new Date().toISOString().slice(0, 10);
    const learn = await learnActivityWeights(db, uid, today);

    const { days, hasMore, totalDays } = generateGrowthDays(startDate, offset, count, {
      productionDay,
      publishDay,
      leavePeriods,
      todayStr: today,
      focusLabel: learn.focusLabel,
      reduceLabel: learn.reduceLabel,
    });

    // Real completion status for days that have already happened: one
    // range query over daily_activities, aggregated per date.
    const pastDates = days.filter((d) => d.date <= today).map((d) => d.date);
    if (pastDates.length > 0) {
      const acts = await db.select(
        'daily_activities',
        `select=activity_date,status&owner_user_id=eq.${uid}&activity_date=gte.${pastDates[0]}&activity_date=lte.${pastDates[pastDates.length - 1]}`
      );
      const byDate = {};
      for (const a of acts) {
        (byDate[a.activity_date] ||= { done: 0, total: 0 });
        byDate[a.activity_date].total += 1;
        if (a.status === 'completed') byDate[a.activity_date].done += 1;
      }
      for (const d of days) {
        if (d.date > today) { d.status = 'Planned'; continue; }
        const agg = byDate[d.date];
        d.status = d.date === today
          ? (agg ? `In progress (${agg.done}/${agg.total})` : 'Today')
          : (agg ? `${agg.done}/${agg.total} done` : 'No log');
      }
    } else {
      for (const d of days) d.status = 'Planned';
    }

    return json({
      section, offset, count, startDate, days, hasMore,
      totalDays: totalDays || PLAN_TOTAL_DAYS,
      countryStrategy: COUNTRY_STRATEGY,
      assumptionNote: ASSUMPTION_NOTE,
      autoLearn: learn.summary,
    });
  } catch (err) {
    return json({ error: 'plan_load_failed', detail: String(err.message || err).slice(0, 300) }, 500);
  }
}

// 28-day completion learning: the highest-impact reliably-completed activity
// becomes FOCUS; an activity skipped more than done (3+ decisions) becomes
// REDUCE. Pure aggregation over real rows — no model, no randomness, so the
// plan re-weights the same way every time until the founder's behavior
// changes it.
async function learnActivityWeights(db, uid, today) {
  const since = new Date(Date.now() - 28 * 86400000).toISOString().slice(0, 10);
  const rows = await db.select(
    'daily_activities',
    `select=activity_type,description,status&owner_user_id=eq.${uid}&activity_date=gte.${since}&activity_date=lte.${today}&limit=2000`
  );
  const TIER_WEIGHT = { CRITICAL: 3, IMPORTANT: 2, OPTIONAL: 1 };
  const agg = {};
  for (const r of rows) {
    if (r.activity_type === 'daily.shutdown_note' || r.activity_type === 'daily.core_block' || r.activity_type === 'daily.shutdown') continue;
    const tier = String(r.description || '').trim().split('|')[0].trim();
    const a = (agg[r.activity_type] ||= { completed: 0, skipped: 0, weight: TIER_WEIGHT[tier] || 2 });
    if (r.status === 'completed') a.completed += 1;
    else if (r.status === 'skipped') a.skipped += 1;
  }
  const label = (k) => k.replace(/^(daily|weekly|monthly|quarterly)\./, '').replace(/_/g, ' ');
  const entries = Object.entries(agg);
  const focus = entries
    .filter(([, a]) => a.completed >= 3)
    .sort((x, y) => y[1].completed * y[1].weight - x[1].completed * x[1].weight)[0] || null;
  const reduce = entries
    .filter(([, a]) => a.completed + a.skipped >= 3 && a.skipped > a.completed)
    .sort((x, y) => y[1].skipped - x[1].skipped)[0] || null;
  return {
    focusLabel: focus ? label(focus[0]) : null,
    reduceLabel: reduce ? label(reduce[0]) : null,
    summary: focus || reduce
      ? `Auto-learned from your last 28 days: ${focus ? `FOCUS on "${label(focus[0])}" (${focus[1].completed}× completed, highest impact)` : ''}${focus && reduce ? '; ' : ''}${reduce ? `REDUCE "${label(reduce[0])}" (skipped ${reduce[1].skipped}×)` : ''}. Future plan days are annotated accordingly.`
      : 'Auto-learning active — needs ~1 week of completion history before it re-weights the plan.',
  };
}
