// functions/utils/ceo/content-kits.js
//
// The ready-to-use content library (Complete Content Engine). Static,
// curated, auditable copy — same philosophy as execution-kits.js: the
// founder executes, never invents. Complements (does not replace) the 40
// seeded content_library pipeline ideas: those are the production queue;
// these are copy-ready packs across every channel, each with targeting,
// hook, structure, CTA, expected result, and budget where paid applies.
// Voice and rules follow the seeded playbooks: free-course CTA (never
// deposit), losses private / recognition public, education never signals,
// no urgency, halal questions always answered.

export const CONTENT_CATEGORIES = [
  'Video Ideas', 'Short Videos', 'Long Videos', 'Facebook Posts', 'Facebook Ads',
  'Telegram Messages', 'WhatsApp Messages', 'Community Questions', 'Technical Analysis Posts',
  'Educational Threads', 'Retention Messages', 'Live Session Topics', 'Webinar Topics',
  'Lead Magnets', 'Free Course Ideas', 'Follow-up Messages', 'IB Scripts', 'Sales Scripts',
  'Objection Handling', 'Closing Scripts',
];

const PK = { country: 'Pakistan + GCC', language: 'Urdu / Roman-Urdu' };
const EN = { country: 'Nigeria + Kenya (day 91+)', language: 'English' };

export const CONTENT_LIBRARY = [
  // --- Video Ideas ---
  { category: 'Video Ideas', title: 'Scam ki anatomy: 5 asal Pakistani cases', ...PK, audience: 'Beginners (scam-feared)', platform: 'YouTube', hook: '"Yeh 5 log kaise lutay gaye — aur aap kaise bachein ge"', structure: 'Case → red flag → rule; 5x; recap checklist', cta: 'Free course lesson 2: broker verify karna', expected: 'Trust anchor; high shares', budget: 'Organic' },
  { category: 'Video Ideas', title: 'Mera pichla mahina: har call ka hisaab (wins + losses)', ...PK, audience: 'All — trust builders', platform: 'YouTube', hook: '"Is mahine 3 calls ghalat thi — dekhein kaunsi"', structure: 'Month recap → losses FIRST → wins → lesson', cta: 'Track record khud verify karein', expected: 'The moat — monthly ritual', budget: 'Organic' },
  { category: 'Video Ideas', title: 'What $100 can really do in forex (the honest math)', ...EN, audience: 'Small accounts', platform: 'YouTube EN', hook: '"Everyone lies about this. Here is the spreadsheet."', structure: 'Myth → real math → survival plan → realistic year-1', cta: 'Free course, lesson 1', expected: 'EN mirror of proven PK winner', budget: 'Organic' },
  // --- Short Videos ---
  { category: 'Short Videos', title: '30-sec: Stop loss lagana 10 second mein', ...PK, audience: 'Beginners', platform: 'Clips (TG/FB/IG auto-repost)', hook: 'Screen-record: "Yeh button account bachata hai"', structure: 'One action, one screen, one rule', cta: 'Poora lesson: link bio', expected: 'Saves/forwards', budget: 'Organic' },
  { category: 'Short Videos', title: '45-sec: Signal seller ka calculator', ...PK, audience: 'All', platform: 'Clips', hook: '"Agar unke signals sach hote to woh ghar kyun bechte?"', structure: 'Claim → math → punchline', cta: 'Education > signals — free course', expected: 'Positioning clip; viral potential', budget: 'Organic' },
  { category: 'Short Videos', title: '60-sec: Gold ka London open pattern', ...PK, audience: 'Gold traders', platform: 'Clips', hook: '"Roz isi waqt gold yeh karta hai"', structure: 'Chart → pattern → caveat (probability, not promise)', cta: 'Weekly gold outlook — channel join', expected: 'Authority + follows', budget: 'Organic' },
  // --- Long Videos ---
  { category: 'Long Videos', title: 'Gold trading mukammal course-in-one-video (45 min)', ...PK, audience: 'Gold traders + beginners', platform: 'YouTube', hook: '"Ek video, poora foundation"', structure: '5 chapters w/ timestamps: kya/kab/kaise/risk/psychology', cta: 'Structured version: free course', expected: 'Pillar asset; top search target', budget: 'Organic' },
  { category: 'Long Videos', title: 'Prop firm challenge: pass hone walon ka pattern (30 min)', ...PK, audience: 'Intermediate', platform: 'YouTube', hook: '"90% fail hote hain — 10% yeh alag karte hain"', structure: 'Failure data → 4 patterns → drill plan', cta: 'Journal template (lead magnet)', expected: 'Intermediate segment capture', budget: 'Organic' },
  // --- Facebook Posts ---
  { category: 'Facebook Posts', title: 'Scam-alert repost + 2-line group post', ...PK, audience: 'PK FB groups', platform: 'Facebook groups', hook: '"Is hafte ka naya scam — apne group walon ko bacha lein"', structure: 'Clip + 2 lines + no ask (1/3 rule)', cta: 'None (trust post)', expected: 'Group credibility', budget: 'Organic' },
  { category: 'Facebook Posts', title: 'Poll post: "Aap ka sab se bara trading masla?"', ...PK, audience: 'PK FB groups', platform: 'Facebook groups', hook: 'Poll: loss / entry timing / dar / waqt nahin', structure: 'Poll → reply to every comment → next video from winner', cta: 'Soft: "is par video banaun?"', expected: 'Demand signal + engagement', budget: 'Organic' },
  // --- Facebook Ads (gated) ---
  { category: 'Facebook Ads', title: 'Free-course lead ad: "Scam se bachne ka pehla sabaq"', ...PK, audience: 'PK 22-45 interested in investing', platform: 'FB Ads', hook: 'Scam-anatomy clip (proven organic winner as creative)', structure: 'Proven clip → lead form → free course email sequence', cta: 'Free course — never deposit', expected: 'CAC probe baseline', budget: 'GATED until 300 clients; then capped daily probe (cap set at gate review)' },
  { category: 'Facebook Ads', title: 'Retargeting: course-starters who stalled', ...PK, audience: 'Custom audience: course start, no finish', platform: 'FB Ads', hook: '"Aap ka lesson 3 intezaar kar raha hai"', structure: 'Reminder creative → course deep-link', cta: 'Resume course', expected: 'Cheapest conversions in the account', budget: 'GATED; smallest budget line first when opened' },
  // --- Telegram Messages ---
  { category: 'Telegram Messages', title: 'Daily lesson template', ...PK, audience: 'TG community', platform: 'Telegram', hook: '"📊 Aaj ka sabaq: <concept>"', structure: '3 lines + 1 chart/misaal + sawal invite', cta: 'Rotate; 1/3 no-ask', expected: 'Reply-rate; <24h answers', budget: 'Organic' },
  { category: 'Telegram Messages', title: 'Weekly review thread starter', ...PK, audience: 'TG community', platform: 'Telegram', hook: '"Is hafte aap ne kya seekha? Main pehle batata hoon —"', structure: 'Founder goes first (one honest line) → members follow', cta: 'None', expected: 'Culture; member-to-member energy', budget: 'Organic' },
  { category: 'Telegram Messages', title: 'Class replay pin message', ...PK, audience: 'TG community', platform: 'Telegram', hook: '"Kal ki class miss? 3 cheezein jo seekhi gayeen:"', structure: '3 bullets → replay link → next class time', cta: 'Replay + calendar', expected: 'Replay views; ritual reinforcement', budget: 'Organic' },
  // --- WhatsApp Messages ---
  { category: 'WhatsApp Messages', title: 'Day-1 welcome voice-note script', ...PK, audience: 'New activated client', platform: 'WhatsApp', hook: 'Voice, 30s, naam ke sath', structure: 'Welcome → main available hoon → pehla lesson → NO sales', cta: '"Pehla lesson dekh lein"', expected: 'Day-7 activity lift', budget: 'Organic' },
  { category: 'WhatsApp Messages', title: 'At-risk revival message', ...PK, audience: '14d+ silent client', platform: 'WhatsApp', hook: '"Kaafi din ho gaye — sab theek?"', structure: 'Personal line → koi cheez ataki ho to batayein → zero pitch', cta: 'None', expected: 'Response rate; churn save', budget: 'Organic' },
  { category: 'WhatsApp Messages', title: 'Milestone congratulation (recognition public rule)', ...PK, audience: 'Client hitting ladder milestone', platform: 'WhatsApp + TG shoutout (permission first)', hook: '"Aap ne <milestone> mukammal kiya — mubarak!"', structure: 'Personal note → permission poochein → public recognition', cta: 'None', expected: 'Retention + social proof', budget: 'Organic' },
  // --- Community Questions ---
  { category: 'Community Questions', title: 'Engagement question bank (rotate)', ...PK, audience: 'TG community', platform: 'Telegram', hook: '"Ek beginner ko sirf EK cheez sikha sakte to kya?" / "Aap ki pehli trade ka kissa?" / "Loss ke baad aap kya karte hain?"', structure: 'One question, founder replies to every answer', cta: 'None (1/3 rule)', expected: 'Reply-rate; surfacing IB-ready members', budget: 'Organic' },
  { category: 'Community Questions', title: 'Market-reaction question (event days)', ...PK, audience: 'TG community', platform: 'Telegram', hook: '"Aaj ke news candle par kis kis ne trade kiya? Imandari se —"', structure: 'Question → honest founder take → rule reminder', cta: 'News-candle rule lesson link', expected: 'Teaching moment from live market', budget: 'Organic' },
  // --- Technical Analysis Posts ---
  { category: 'Technical Analysis Posts', title: 'Daily gold levels template', ...PK, audience: 'Gold traders', platform: 'Telegram', hook: '"🔍 Gold aaj: <S> support / <R> resistance"', structure: 'Chart + 2 lines + "analysis hai, signal NAHIN"', cta: '"Levels nikalna seekhein — lesson 4"', expected: '1 authority post/day', budget: 'Organic' },
  { category: 'Technical Analysis Posts', title: 'Weekly BTC structure read', ...PK, audience: 'Crypto traders', platform: 'Telegram', hook: '"BTC weekly: structure kya keh rahi hai"', structure: 'HTF chart → 3 scenarios w/ probabilities → risk line', cta: 'Spot-vs-futures lesson', expected: 'Crypto segment retention', budget: 'Organic' },
  // --- Educational Threads ---
  { category: 'Educational Threads', title: '10-message TG series: Risk week', ...PK, audience: 'All', platform: 'Telegram (pinned series)', hook: 'Din 1: "Is hafte sirf risk — roz ek rule"', structure: '10 daily rules, each 3 lines + misaal', cta: 'Series end: free course risk module', expected: 'Week-long retention arc', budget: 'Organic' },
  { category: 'Educational Threads', title: 'FB long-post: "IB kya hota hai" full disclosure', ...PK, audience: 'Warm audience', platform: 'Facebook + website', hook: '"Hum kaise kamate hain — pura sach"', structure: 'Model → hamara incentive → aap ka faida → sawal invite', cta: 'Free course', expected: 'The disclosure piece; conversion-proximate', budget: 'Organic' },
  // --- Retention Messages ---
  { category: 'Retention Messages', title: 'Day-30 check-in', ...PK, audience: '30-day clients', platform: 'WhatsApp', hook: '"Ek mahina ho gaya — 3 sawal:"', structure: 'Kya chal raha / kya nahin / agla goal → listen', cta: 'Personal reply', expected: '30-day retention marker', budget: 'Organic' },
  { category: 'Retention Messages', title: 'Loss-week support (private)', ...PK, audience: 'Client after visible bad week', platform: 'WhatsApp (NEVER public)', hook: '"Mushkil hafta tha — main yahan hoon"', structure: 'Acknowledge → normalize → one concrete next step', cta: 'Journal review offer', expected: 'Churn save at the exact churn moment', budget: 'Organic' },
  // --- Live Session Topics ---
  { category: 'Live Session Topics', title: 'Live journal review (volunteer ka journal)', ...PK, audience: 'Community', platform: 'Live class', hook: '"Aaj kisi ka asli journal dekhen ge (naam ke baghair)"', structure: '30m teach on real journal → 15m market → Q&A', cta: 'Journal template', expected: 'Highest-engagement class format', budget: 'Organic' },
  { category: 'Live Session Topics', title: 'Scam breakdown live (audience submissions)', ...PK, audience: 'Community + guests', platform: 'Live class', hook: '"Apne paas aaye scam messages bhejein — live kholen ge"', structure: 'Submissions → red flags live → rules recap', cta: 'Free course lesson 2', expected: 'Shareable + guest invites', budget: 'Organic' },
  // --- Webinar Topics ---
  { category: 'Webinar Topics', title: 'Institute webinar: "Trading as a skill, not a lottery"', ...PK, audience: 'Institute students (physical funnel)', platform: 'On-site / Zoom', hook: 'Free class the institute hosts', structure: '40m foundation → 10m demo-first doctrine → Q&A', cta: 'Free course + community join', expected: 'Physical→online bridge; students list', budget: 'Organic (travel only)' },
  { category: 'Webinar Topics', title: 'GCC evening webinar: Halal clarity session', country: 'GCC', language: 'Urdu + English', audience: 'Expat professionals', platform: 'Zoom (Gulf evening)', hook: '"Islamic account kya hai — scholarly views, verdict nahin"', structure: 'Views → account mechanics → open Q&A', cta: 'Exness Islamic explainer + free course', expected: 'Highest-LTV segment conversion moment', budget: 'Organic' },
  // --- Lead Magnets ---
  { category: 'Lead Magnets', title: 'Broker Verification Checklist (PDF)', ...PK, audience: 'Scam-feared beginners', platform: 'Website + TG pin', hook: '"7 checks pehle deposit ke"', structure: '1-page checklist, brandmarked', cta: 'Email for delivery → sequence', expected: 'Top-of-funnel email capture', budget: 'Organic' },
  { category: 'Lead Magnets', title: 'Trading Journal Template (the one from class)', ...PK, audience: 'All', platform: 'Website', hook: '"Wohi journal jo live class mein dikhta hai"', structure: 'Sheet template + 5-line how-to', cta: 'Email delivery', expected: 'Highest perceived-value magnet', budget: 'Organic' },
  { category: 'Lead Magnets', title: 'Small Account Survival Plan (EN)', ...EN, audience: 'Small accounts', platform: 'Website EN', hook: '"The $100 survival math, printable"', structure: '1-pager: risk table + 3 rules', cta: 'Email delivery', expected: 'EN list seeding from day 91', budget: 'Organic' },
  // --- Free Course Ideas ---
  { category: 'Free Course Ideas', title: 'Gold Foundation (flagship, exists — keep improving)', ...PK, audience: 'Beginners', platform: 'Website course', hook: 'The main funnel asset', structure: 'Zero→first trade in 8 lessons', cta: 'Community join at lesson 8', expected: 'The course→IB conversion engine', budget: 'Organic' },
  { category: 'Free Course Ideas', title: 'Mini-course: 5-day WhatsApp risk course', ...PK, audience: 'Time-poor (GCC)', platform: 'WhatsApp drip', hook: '"5 din, roz 5 minute — risk mukammal"', structure: '5 daily voice notes + 1-line homework', cta: 'Full course at day 5', expected: 'GCC-friendly micro format', budget: 'Organic' },
  // --- Follow-up Messages ---
  { category: 'Follow-up Messages', title: 'Course-completer follow-up', ...PK, audience: 'Finished course, quiet', platform: 'WhatsApp', hook: '"Course mukammal — mubarak! Ab kya?"', structure: 'Congratulate → poochein kya rukawat → path options', cta: 'Community / demo-first / sawal', expected: 'The IB-trigger conversation opener', budget: 'Organic' },
  { category: 'Follow-up Messages', title: 'Institute proposal follow-up (day 7)', ...PK, audience: 'Institute decision-maker', platform: 'Phone/WhatsApp', hook: '"Proposal par koi sawal? Demo class free kara doon?"', structure: 'Reference proposal → remove risk (free demo) → date poochein', cta: 'Demo class date', expected: 'Proposal→meeting conversion', budget: 'Organic' },
  // --- IB Scripts ---
  { category: 'IB Scripts', title: 'The verification framing (core IB script)', ...PK, audience: 'Trust-ready member', platform: 'WhatsApp personal', hook: '"Aap tayyar lagte hain — ek option batata hoon"', structure: 'Frame: jahan hum khud trade karte hain → verification+supervision → NO pressure → "koi jaldi nahin"', cta: '"Jab tayyar hon, batayein"', expected: '1 stage advance without trust cost', budget: 'Organic' },
  { category: 'IB Scripts', title: 'EN market IB script (day 91+)', ...EN, audience: 'Course-completers EN', platform: 'WhatsApp', hook: '"You finished the course — here is the practical next step"', structure: 'Same verification framing, faster pace, direct tone', cta: 'Setup verification offer', expected: 'EN funnel bottom', budget: 'Organic' },
  // --- Sales Scripts ---
  { category: 'Sales Scripts', title: 'Business-owner conversation (B2B register)', ...PK, audience: 'Business owners', platform: 'WhatsApp/in-person', hook: '"Trading ko business unit ki tarah dekhein"', structure: 'Businessman-to-businessman → education+transparency edge → gold specialization', cta: 'Quarterly business-review framing', expected: 'High-equity segment entry', budget: 'Organic' },
  { category: 'Sales Scripts', title: 'Jeweller conversation (paper-gold literacy)', ...PK, audience: 'Jewellery trade', platform: 'In-person/association', hook: '"Aap gold ke expert hain — paper gold ka farq 10 minute mein"', structure: 'Agree with expertise → position as literacy, not education → hedging misconception fix', cta: 'Dedicated jeweller session', expected: 'Highest untapped LTV lane', budget: 'Organic' },
  // --- Objection Handling ---
  { category: 'Objection Handling', title: '"Yeh bhi scam hoga" — the big one', ...PK, audience: 'Beginners', platform: 'Any', hook: 'Never argue', structure: 'Haath mein track record dein: "khud verify karein" → scam-anatomy video link → wait', cta: 'Self-verification', expected: 'Objection becomes trust moment', budget: 'Organic' },
  { category: 'Objection Handling', title: '"$100 se ameer ban sakta hoon?"', ...PK, audience: 'Small accounts', platform: 'Any', hook: 'The honest-math lesson answers it', structure: 'Honest no → survival math → realistic year-1 → demo-first', cta: 'Honest-math video', expected: 'Filters dreamers, keeps builders', budget: 'Organic' },
  { category: 'Objection Handling', title: '"Aap ka faida kya hai?" (IB disclosure)', ...PK, audience: 'Warm leads', platform: 'Any', hook: 'Full disclosure is the answer', structure: 'IB model explained → incentive alignment → "isi liye education free hai"', cta: 'Disclosure video', expected: 'Transparency = conversion', budget: 'Organic' },
  // --- Closing Scripts ---
  { category: 'Closing Scripts', title: 'The no-close close', ...PK, audience: 'Ready member', platform: 'WhatsApp', hook: '"Main pressure nahin karta — decision aap ka hai"', structure: 'Summarize their own progress → both paths respected → door open', cta: '"Jab tayyar hon, ek message"', expected: 'Closes without closing — the brand', budget: 'Organic' },
  { category: 'Closing Scripts', title: 'Institute batch close', ...PK, audience: 'Institute after demo class', platform: 'In-person', hook: '"Students ne khud poocha hai — batch kab?"', structure: 'Demo feedback → batch proposal → dates + logistics → students list', cta: 'Batch start date', expected: 'Students → community → clients pipeline', budget: 'Organic' },
];
