// functions/utils/ceo/content-ideas.js
//
// Curated content idea bank (300+) for the Content Pipeline. Loaded on
// demand by the founder via the "Load idea bank" button (growth.js action
// 'seed_ideas'), which inserts only titles not already present — so the bank
// COEXISTS with founder-created ideas and never duplicates. Every idea is a
// real, practical, SEO/short-form-friendly topic across the requested pillars
// (forex, gold, BTC, beginner/intermediate, risk, psychology, MT5, Exness,
// IB acquisition, mistakes, education, tools, market structure, TA, FA).
// Titles are Urdu/Roman-Urdu (the founder's audience) with English trading
// terms — the natural code-switch that ranks in Urdu search + converts.
//
// pillar values reuse content_library's seeded set: fundamentals, gold_btc,
// psychology, legitimacy, comparison, advanced.

const BANK = {
  fundamentals: [
    'Forex trading kya hai? Bilkul zero se shuru',
    'Currency pair kya hoti hai — EURUSD, GBPUSD samjhein',
    'Pip, point aur lot: teen bunyadi cheezein',
    'Lot size kaise choose karein (micro/mini/standard)',
    'Bid, ask aur spread ka farq 5 minute mein',
    'Leverage kya hai — 1:100 ka asal matlab',
    'Margin aur free margin: account blow kyun hota hai',
    'Long vs short: buy aur sell dono se kamai kaise',
    'Market order vs limit order vs stop order',
    'Demo account: pehle 30 din ka mukammal plan',
    'Pehla real trade: step-by-step checklist',
    'Trading sessions: Pakistan time se kab trade karein',
    'London aur New York overlap — sab se active waqt',
    'Forex mein "spread cost" kaise kam karein',
    'Swap/rollover charge kya hai — overnight cost',
    'Swap-free (Islamic) account kaise kaam karta hai',
    'Base currency vs quote currency — asaan misaal',
    'Trading account types: cent, standard, pro',
    'Cent account: $10 se practice ka best tareeqa',
    'Trading capital: kitne paise se shuru karein (sach)',
    'Position size calculator kaise use karein',
    'Risk-to-reward ratio: 1:2 ka matlab aur ahmiyat',
    'Win rate vs risk-reward: dono ka rishta',
    'Trading plan kaise banayein (template ke saath)',
    'Trading journal kyun sab se zaroori tool hai',
    'Forex mein profit withdraw kaise karein',
    'Slippage kya hai aur kab hota hai',
    'Requote aur execution: broker ka role',
    'Trading fees: spread, commission, swap — poora hisaab',
    'Volatility kya hai — high vs low volatility pairs',
    'Major, minor aur exotic pairs ka farq',
    'Correlation: kaun se pairs saath chalte hain',
    'Trading ka pehla mahina: realistic expectations',
    'Kya $100 se trading shuru ho sakti hai? Sach',
    'Compounding: chhote account ko kaise barhayein',
    'Trading vs investing: aap ke liye kaunsa behtar',
    'Scalping, day trading, swing: konsa style chunein',
    'Overtrading kya hai aur kaise rukein',
    'Trading routine: rozana ka best schedule',
    'Economic calendar kaise parhein (beginner)',
  ],
  gold_btc: [
    'Gold (XAUUSD) trading: mukammal beginner guide',
    'Gold kis waqt sab se zyada move karta hai',
    'Gold aur US Dollar (DXY) ka ulta rishta',
    'Gold aur interest rates: Fed ka asar',
    'Gold aur inflation: safe-haven kyun kehte hain',
    'XAUUSD ka spread aur lot size samjhein',
    'Gold scalping: chhoti timeframe ki haqeeqat',
    'Gold mein stop loss kahan rakhein',
    'London open par gold ka pattern',
    'New York session mein gold volatility',
    'Gold weekly outlook kaise banayein (educational)',
    'Gold support/resistance nikalna seekhein',
    'Gold aur geopolitics: news ka asar',
    'Central banks gold kyun khareed rahe hain',
    'Eid/shaadi season aur gold price: haqeeqat',
    'Physical gold vs paper gold (CFD): jewellers ke liye',
    'Gold trading ki 5 sab se bari ghaltiyan',
    'Gold ke liye best trading sessions',
    'Bitcoin trading kya hai — spot vs CFD',
    'BTC spot vs futures: farq samjhein',
    'Bitcoin volatility: risk kaise sambhalein',
    'Crypto CFD Exness par kaise trade karein',
    'BTC halving ka price par asar (educational)',
    'Bitcoin aur risk: sirf utna jitna kho saktay hain',
    'Ethereum aur altcoins: basic samajh',
    'Crypto mein leverage kyun khatarnak hai',
    'BTC weekly structure kaise parhein',
    'Gold vs Bitcoin: kaunsa zyada volatile',
    'Crypto funding rate aur liquidation samjhein',
    'Bitcoin news trading: kab door rehna hai',
  ],
  psychology: [
    'Revenge trading: account ka qatil',
    'Loss ke baad kya karein (aur kya nahin)',
    'Overtrading ki 5 nishaniyan',
    'FOMO aur greed: market ke 2 jaal',
    'Fear of loss: entry na le pana',
    'Trading discipline kaise banayein (roz)',
    'Patience: setup ka intezaar karna seekhein',
    'Trading aur ghar walon ka pressure',
    'Emotional trading se bachne ke tareeqe',
    'Confidence vs overconfidence: bareek farq',
    'Losing streak ko kaise handle karein',
    'Winning streak ke baad blow-up kyun hota hai',
    'Trading journal se emotions track karna',
    'Rules follow karna itna mushkil kyun',
    'Screen time aur burnout: solo trader ki thakan',
    'Demo par accha, real par kharab — kyun',
    'Position size aur neend: risk ka psychology',
    'Trading ke baad "just one more trade" ka jaal',
    'Comparison: doosron ke profits dekh kar dukhi',
    'Process vs outcome: sahi paimana',
    'Trading mein sabr aur consistency ka rishta',
    'Ek din ka bara loss: recovery mindset',
    'Trading goals: realistic monthly target set karna',
    'Meditation/breaks: focus barhane ke tareeqe',
    'Accountability partner ya community ka faida',
  ],
  legitimacy: [
    'Scam broker pehchanne ke 7 tareeqe',
    'Fake trading apps: Pakistan mein taaza scams',
    'Signal seller ka sach: agar itne acchay hain to...',
    'Withdrawal problems: broker verify kaise karein',
    'Hamara track record khud verify karein',
    'IB kya hota hai? Hum kaise kamate hain (full disclosure)',
    'Guaranteed profit ka jhoot: red flag',
    'Copy trading ki haqeeqat aur risk',
    'Managed account scams se bachein',
    '"Double your money" schemes: kyun jhoot hain',
    'Regulated vs unregulated broker: farq',
    'Broker withdrawal test: pehle chhoti raqam',
    'Fake screenshots pehchanne ka tareeqa',
    'WhatsApp/Telegram signal groups ka jaal',
    'Deposit se pehle broker ki 5 checks',
    'Ponzi vs real trading: pehchan',
    'Influencer "funded" claims: sach kya hai',
    'Trading education free kyun honi chahiye',
    'Aap ka data aur account: security basics',
    'Chargeback aur refund: kab mumkin hai',
  ],
  comparison: [
    'Exness account kholne ka mukammal tareeqa',
    'Exness deposit JazzCash/Easypaisa se kaise karein',
    'Exness withdrawal Pakistan: step by step',
    'Exness cent account: minimum deposit aur faida',
    'Exness standard vs pro account: kaunsa',
    'Exness swap-free (Islamic) account setup',
    'Exness spread aur commission samjhein',
    'Exness par leverage set karna',
    'Exness partner/IB link kaise kaam karta hai',
    'MT4 vs MT5: kaunsa use karein',
    'MT5 mobile app: mukammal setup guide',
    'MT5 par indicator kaise lagayein',
    'MT5 par pending order kaise lagayein',
    'MT5 par stop loss/take profit set karna',
    'MT5 chart timeframes samjhein',
    'MT5 par lot size aur risk set karna',
    'MT5 par history aur report nikalna',
    'MT5 desktop vs mobile: kab konsa',
    'MT5 templates aur workspace save karna',
    'MT5 par multiple charts manage karna',
    'Exness demo se real par shift kab karein',
    'Exness verification (KYC) documents guide',
    'Islamic account kya hota hai: gold CFD aur scholarly views',
    'Broker comparison: PK se accessible brokers',
    'Exness app par one-click trading',
  ],
  advanced: [
    'Market structure: higher high, lower low samjhein',
    'Support aur resistance sahi tarah nikalna',
    'Trendline kaise draw karein (sahi tareeqa)',
    'Supply aur demand zones ki pehchan',
    'Break of structure (BOS) kya hai',
    'Order block kya hota hai (ICT basics)',
    'Liquidity aur stop hunt samjhein',
    'Fair value gap (FVG) asaan misaal se',
    'Candlestick patterns: top 7 jo kaam ke hain',
    'Pin bar aur engulfing: entry signals',
    'Doji, hammer, shooting star samjhein',
    'Chart patterns: head and shoulders',
    'Double top aur double bottom trade karna',
    'Triangle, flag, wedge patterns',
    'Fibonacci retracement kaise use karein',
    'Fibonacci extension se target lagana',
    'Moving average (MA) basics aur use',
    'EMA crossover strategy samjhein',
    'RSI indicator: overbought/oversold sach',
    'MACD kaise parhein aur use karein',
    'Bollinger Bands: volatility ka indicator',
    'ATR se stop loss lagana',
    'VWAP kya hai aur intraday use',
    'Stochastic oscillator basics',
    'Multi-timeframe analysis ka tareeqa',
    'Trend vs range: market condition pehchanna',
    'Breakout vs fakeout: farq karna',
    'Pullback entry: trend ke saath trade',
    'Confluence: kai signals ka milna',
    'Backtesting: strategy ko test karna',
    'Trading strategy ko forward-test karna',
    'Scalping strategy: 1-5 min timeframe',
    'Swing trading strategy: daily/4H',
    'Breakout trading: session high/low',
    'News trading: NFP aur CPI ki tayyari',
    'Interest rate decisions ka trade par asar',
    'Economic indicators: GDP, CPI, PMI samjhein',
    'Fundamental vs technical: dono ka mel',
    'Correlation trading: gold aur DXY',
    'Prop firm challenge: haqeeqat aur tayyari',
    'Prop firm rules: drawdown aur target',
    'Prop firm pass karne walon ka pattern',
    'Trading ka apna pehla saal review karna',
    'Weekly review: apni trades se seekhna',
    'Trade management: partial close aur trailing stop',
    'Entry, stop, target: teenon pehle likhna',
    'Risk per trade: 1% rule ki ahmiyat',
    'Maximum daily loss limit set karna',
    'Correlation risk: ek jaisi trades ka khatra',
    'Position sizing formula (practical)',
  ],
};

// IB-acquisition + education + tools + short-form angles — cross-pillar,
// tagged to the closest existing pillar so nothing is lost.
const EXTRA = {
  legitimacy: [
    'Free class join karne ke faide (IB funnel)',
    'Community mein sawal poochne se darna nahin',
    'Mentorship free kyun — hamara business model',
    'Aap ka pehla trade hamare saath (live idea)',
    'Trading seekhne ka realistic roadmap (6 mahine)',
  ],
  fundamentals: [
    'Risk calculator tool kaise use karein',
    'Lot size calculator: har trade se pehle',
    'Trading journal template (free) ka use',
    'Economic calendar app setup',
    'Trading watchlist kaise banayein',
    'Alerts set karna: entry miss na ho',
    'Screener/heatmap se pairs chunna',
    'Trading ke liye best free tools',
    'Backtest ke liye free tools',
    'Notebook se digital journal tak',
  ],
  advanced: [
    'Short-form ke liye: 30 sec mein stop loss',
    'Short-form ke liye: signal seller ka calculator',
    'Short-form ke liye: gold London open pattern',
    'Reel idea: "3 ghaltiyan naye traders karte hain"',
    'Reel idea: "Kya trading halal hai?" (scholarly)',
    'Reel idea: 10 second risk management rule',
    'Reel idea: MT5 par 1-click trade',
    'Reel idea: $100 account ka sach',
    'Reel idea: revenge trading ka anjam',
    'Reel idea: candlestick 15 second mein',
    'Reel idea: leverage 15 second mein samjhao',
    'Reel idea: spread kya hota hai (quick)',
    'Reel idea: pip kaise count karein',
    'Reel idea: RSI 20 second mein',
    'Reel idea: support/resistance quick draw',
    'Reel idea: demo se real ka rasta',
    'Reel idea: JazzCash se Exness deposit',
    'Reel idea: 1% risk rule ka jadoo',
    'Reel idea: gold aur dollar ka rishta (quick)',
    'Reel idea: trading journal kyun zaroori',
  ],
  comparison: [
    'Exness demo par first strategy test',
    'Exness app notifications setup',
    'Exness account safety aur 2FA',
    'Exness rebate/cashback samjhein (agar available)',
    'Exness terminal vs MT5: kaunsa behtar',
  ],
  psychology: [
    'Trading ke saath job: time management',
    'Family ko trading kaise samjhayein',
    'Chhoti jeet celebrate karna (discipline)',
    'Bura din: kab screen band kar dena',
    'Long-term mindset: 5 saal ka nazariya',
  ],
};

// Country/expansion angles (English) — for the EN mirror library, tagged to
// pillars; these become the Nigeria/Kenya repurpose set (Phase 3).
const EN_MIRRORS = {
  fundamentals: [
    'What is forex trading? Complete beginner guide',
    'What $100 can really do in forex (the honest math)',
    'Lot size and risk explained simply',
    'How to place your first trade on MT5',
    'Best trading sessions for African traders',
  ],
  gold_btc: [
    'Gold (XAUUSD) trading for beginners',
    'Why gold moves with the US dollar',
    'Bitcoin CFD vs spot: what beginners must know',
  ],
  legitimacy: [
    'How to spot a scam broker (7 red flags)',
    'Signal sellers: the honest truth',
    'How to verify broker withdrawals before you deposit',
  ],
  comparison: [
    'How to open an Exness account (step by step)',
    'Exness deposit and withdrawal in Nigeria',
    'MT4 vs MT5: which should you use?',
  ],
  advanced: [
    'Prop firm challenge: the reality and how to prepare',
    'Risk management: the 1% rule that saves accounts',
    'Support and resistance: how to draw them correctly',
  ],
};

// Batch 2 — deeper practical topics to take the bank comfortably past 300,
// still non-duplicate and execution-focused.
const BANK2 = {
  fundamentals: [
    'Trading ke liye internet aur device ki zaroorat',
    'Broker vs exchange: farq samjhein',
    'Trading ke ghante: 24/5 market kaise chalti hai',
    'Weekend gap kya hai aur kaise handle karein',
    'Spread widening: news ke waqt kyun barhta hai',
    'Trade close kyun nahi ho raha — reasons',
    'Negative balance protection kya hai',
    'Trading ke liye budget planning',
    'Paisa double karne ka lalach: kyun nahi',
    'Trading income par realistic nazariya',
    'Micro-lot se practice ka best plan',
    'Trade size barhane ka sahi waqt',
    'Trading ke pehle 3 mahine: kya expect karein',
    'Consistency kaise measure karein',
    'Break-even: apni psychology par asar',
  ],
  gold_btc: [
    'Gold ka Asian session behavior',
    'Gold aur oil ka rishta (educational)',
    'Silver (XAGUSD) vs gold: farq',
    'Gold intraday levels rozana kaise nikalein',
    'Gold ke liye risk management (volatility zyada)',
    'Bitcoin dominance kya batati hai',
    'Stablecoins kya hain (basic)',
    'Crypto market cap samjhein',
    'BTC ke liye stop loss placement',
    'Gold news events calendar',
  ],
  advanced: [
    'Session-based strategy: Asian range breakout',
    'Trend-following vs mean-reversion',
    'Trade log se edge dhoondna',
    'Expectancy calculate karna (formula)',
    'Drawdown se recover hone ki math',
    'Position sizing: fixed % vs fixed lot',
    'Correlation matrix kaise parhein',
    'Divergence (RSI/price) trade karna',
    'Support becomes resistance concept',
    'Retest entry: safer breakout',
    'Trailing stop kab aur kaise',
    'Partial take-profit strategy',
    'Higher timeframe bias, lower timeframe entry',
    'Killzone/session timing (ICT basics)',
    'Risk-free trade banane ka concept',
  ],
  psychology: [
    'Rule-based trading vs discretionary',
    'Ek trade se identity na jodna',
    'Loss aversion: dukh se faisla',
    'Journaling se pattern pehchanna',
    'Trading ke baad review ritual',
  ],
  legitimacy: [
    'Affiliate vs IB: farq (transparency)',
    'Kaunsi education free honi chahiye',
    'Community rules: safe seekhne ki jagah',
    'Testimonials verify karna',
    'Apni progress publicly track karna',
  ],
  comparison: [
    'Exness leverage limits samjhein',
    'Exness trading instruments list',
    'Exness minimum lot per instrument',
    'MT5 par economic calendar',
    'MT5 par alerts aur notifications',
  ],
};

function merge(...sources) {
  const out = {};
  for (const src of sources) {
    for (const [pillar, titles] of Object.entries(src)) {
      (out[pillar] ||= []).push(...titles);
    }
  }
  return out;
}

const ALL = merge(BANK, BANK2, EXTRA, EN_MIRRORS);

// Flat, de-duplicated list of { title, pillar } — the seed action inserts any
// whose title isn't already in content_library.
export const CONTENT_IDEA_BANK = (() => {
  const seen = new Set();
  const out = [];
  for (const [pillar, titles] of Object.entries(ALL)) {
    for (const title of titles) {
      const key = title.trim().toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({ title: title.trim(), pillar });
    }
  }
  return out;
})();
