// functions/knowledge/equities/concepts.js
// KPOS V3 EXPANSION — STOCKS & EQUITIES (category: equities)
// Fills a verified thin domain (stocks were ~20% covered, mostly passing prose).
// Adds dedicated knowledge assets for stocks, IPOs, penny/blue-chip, dividends,
// short selling, earnings, indices. Related links deliberately point INTO orphan
// nodes (contract-for-difference) to repair graph connectivity while expanding.

const F = (o) => ({
  level: 'beginner', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const EQUITIES_CONCEPTS = [
  F({
    id: 'what-are-stocks', category: 'equities', topic: 'What Are Stocks', title: 'What Are Stocks? Explained for Beginners',
    concepts: ['stocks', 'equities', 'shares'],
    questionPatterns: ['what is a stock', 'what are shares', 'how do stocks work', 'what does owning a stock mean', 'stocks for beginners'],
    canonical: {
      short: 'A stock (or share) is a unit of ownership in a company. When you buy a stock you own a small slice of that business and can profit if its value rises or if it pays dividends — but you also share in its losses if the price falls.',
      deep: 'Stocks represent equity ownership: shareholders own a fraction of a company\'s assets and future earnings. Prices move on the company\'s performance, expectations, and broader market sentiment, so a stock is both a claim on a real business and a traded, volatile instrument. Investors profit two ways — capital appreciation (the price rising) and dividends (a share of profits). Unlike leveraged forex or CFDs, buying a share outright means your maximum loss is what you paid, though trading stocks with margin or via CFDs reintroduces leverage risk. Understanding what a share actually is anchors everything else in equities.',
    },
    marketContext: 'A trader who buys shares of a company outright can only lose their investment, whereas trading the same company as a leveraged CFD magnifies both gains and losses.',
    desiredOutcome: 'understand a stock as fractional business ownership that pays via price appreciation and dividends',
    relevanceTags: ['stocks', 'equities', 'shares', 'beginner'],
    commonMistakes: ['treating individual stocks like lottery tickets instead of ownership in a business'],
    misconceptions: ['that a low share price means a stock is "cheap" in value terms'],
    prerequisites: ['financial-markets'], nextSteps: ['ipo-investing', 'blue-chip-stocks'], related: ['contract-for-difference', 'index-trading', 'dividend-investing'],
    followups: ['blue-chip-stocks'],
    riskNote: 'Owning shares outright caps loss at your stake — trading them on margin or as CFDs does not.',
    seo: { title: 'What Are Stocks? Beginner Guide to Shares', description: 'What a stock is, how shares represent company ownership, and how investors profit through price gains and dividends.', keywords: ['what are stocks', 'what are shares', 'stocks for beginners', 'how stocks work'] },
  }),
  F({
    id: 'blue-chip-stocks', category: 'equities', topic: 'Blue-Chip Stocks', title: 'Blue-Chip Stocks Explained',
    concepts: ['blue-chip', 'equities', 'investing'],
    questionPatterns: ['what are blue chip stocks', 'are blue chip stocks safe', 'blue chip vs growth stocks', 'examples of blue chip stocks', 'why buy blue chip stocks'],
    canonical: {
      short: 'Blue-chip stocks are shares of large, established, financially strong companies with a long track record of stable performance. They are seen as lower-risk, often pay dividends, and form the backbone of many long-term portfolios.',
      deep: 'Blue chips are the market\'s heavyweight, reliable names — companies with durable earnings, strong balance sheets, and often decades of history. They tend to be less volatile than small or speculative stocks and frequently pay consistent dividends, making them popular for stability and income. The trade-off is slower growth: their size means they rarely deliver explosive returns. "Lower risk" is relative, not risk-free — even blue chips fall in bear markets and can decline for years if a business erodes. They suit long-term, diversified investing rather than fast trading.',
    },
    marketContext: 'During a market panic, capital often rotates from speculative small caps into blue chips, which tend to hold up better but still decline.',
    desiredOutcome: 'understand blue chips as stable, dividend-paying core holdings that are lower-risk but not risk-free',
    relevanceTags: ['blue-chip', 'equities', 'investing', 'beginner'],
    commonMistakes: ['assuming blue-chip stocks cannot fall significantly'],
    misconceptions: ['that "blue chip" means guaranteed safety'],
    prerequisites: ['what-are-stocks'], nextSteps: ['dividend-investing', 'stock-market-indices'], related: ['penny-stocks', 'diversification'],
    followups: ['dividend-investing'],
    riskNote: 'Blue chips are lower-risk, not no-risk — they still fall in bear markets and require diversification.',
    seo: { title: 'Blue-Chip Stocks Explained for Beginners', description: 'What blue-chip stocks are, why they are seen as lower-risk and income-friendly, and their growth trade-offs.', keywords: ['blue chip stocks', 'what are blue chip stocks', 'blue chip investing', 'dividend stocks'] },
  }),
  F({
    id: 'penny-stocks', category: 'equities', topic: 'Penny Stocks', title: 'Penny Stocks Explained',
    concepts: ['penny-stocks', 'equities', 'speculation'],
    questionPatterns: ['what are penny stocks', 'are penny stocks a good investment', 'why are penny stocks risky', 'how to trade penny stocks', 'penny stocks for beginners'],
    canonical: {
      short: 'Penny stocks are very low-priced shares of small companies, usually trading below a few dollars. They can move explosively but are among the riskiest equities — thinly traded, easily manipulated, and prone to total loss.',
      deep: 'Penny stocks tempt beginners with the idea that a cheap price means big upside, but low price reflects small, often unproven companies with weak fundamentals. Their dangers are structural: low liquidity means wide spreads and hard exits, low regulation invites "pump-and-dump" schemes, and many simply go to zero. The occasional multi-bagger fuels the hype, but the base rate is brutal. If traded at all, penny stocks demand tiny position sizes, strict stops, and scepticism toward promotion — the same discipline as any high-risk speculation, not investment.',
    },
    marketContext: 'A promoted penny stock can spike on hype and then collapse when insiders sell into the excitement, trapping latecomers with no liquidity to exit.',
    desiredOutcome: 'treat penny stocks as high-risk speculation needing tiny sizing, strict stops, and scepticism',
    relevanceTags: ['penny-stocks', 'equities', 'speculation', 'beginner'],
    commonMistakes: ['assuming a low share price means a stock is cheap or has more upside'],
    misconceptions: ['that penny stocks are an easy path to quick wealth'],
    prerequisites: ['what-are-stocks'], nextSteps: ['short-selling', 'earnings-season'], related: ['blue-chip-stocks', 'market-noise'],
    followups: ['short-selling'],
    riskNote: 'Penny stocks are illiquid and easily manipulated — most go to zero; risk only what you can fully lose.',
    seo: { title: 'Penny Stocks Explained (and Their Risks)', description: 'What penny stocks are, why their low price and liquidity make them so risky, and how pump-and-dump schemes work.', keywords: ['penny stocks', 'what are penny stocks', 'penny stock risks', 'penny stock trading'] },
  }),
  F({
    id: 'dividend-investing', category: 'equities', topic: 'Dividend Investing', title: 'Dividend Investing Explained',
    concepts: ['dividends', 'equities', 'income'],
    questionPatterns: ['what is a dividend', 'how does dividend investing work', 'what is dividend yield', 'are dividend stocks worth it', 'dividend investing for beginners'],
    canonical: {
      short: 'A dividend is a share of a company\'s profits paid to shareholders, usually quarterly. Dividend investing focuses on stocks that pay reliable dividends to generate passive income alongside any price appreciation.',
      deep: 'Dividends turn stock ownership into an income stream: a company distributes part of its earnings per share held, expressed as a dividend yield (annual dividend ÷ price). Dividend investing suits long-term, income-focused investors and benefits powerfully from reinvestment and compounding over time. The cautions matter: a very high yield can be a warning sign of a falling price or an unsustainable payout that may be cut, and chasing yield alone ignores the health of the underlying business. Sustainable, growing dividends from solid companies beat the highest headline yield.',
    },
    marketContext: 'A stock showing a 12% dividend yield often reflects a collapsing share price and a payout at risk of being cut — not a bargain income opportunity.',
    desiredOutcome: 'use dividends for compounding income while judging payout sustainability over headline yield',
    relevanceTags: ['dividends', 'equities', 'income', 'beginner'],
    commonMistakes: ['chasing the highest dividend yield without checking if the payout is sustainable'],
    misconceptions: ['that a high dividend yield is always a good deal'],
    prerequisites: ['what-are-stocks'], nextSteps: ['blue-chip-stocks', 'stock-market-indices'], related: ['blue-chip-stocks', 'compounding'],
    followups: ['stock-market-indices'],
    riskNote: 'A very high yield often signals risk, not reward — dividends can be cut if earnings fall.',
    seo: { title: 'Dividend Investing Explained for Beginners', description: 'What dividends and dividend yield are, how dividend investing compounds income, and why chasing high yields is risky.', keywords: ['dividend investing', 'what is a dividend', 'dividend yield', 'dividend stocks'] },
  }),
  F({
    id: 'ipo-investing', category: 'equities', topic: 'IPO Investing', title: 'IPO Investing Explained',
    concepts: ['ipo', 'equities', 'investing'],
    questionPatterns: ['what is an ipo', 'how does an ipo work', 'should i buy ipo stocks', 'why do ipos pop', 'ipo investing risks'],
    canonical: {
      short: 'An IPO (Initial Public Offering) is when a private company first sells shares to the public and lists on an exchange. IPOs attract attention and can spike on day one, but they are also volatile and hard to value with limited history.',
      deep: 'An IPO lets a company raise capital by going public; for investors it is the first chance to buy shares on the open market. The appeal is getting in early on a growth story, and popular IPOs sometimes "pop" sharply on debut. The risks are real and often underappreciated: hype-driven first-day prices can be far above fair value, insiders and early backers eventually sell (lock-up expiries), and a short public track record makes valuation guesswork. Many high-profile IPOs trade below their opening price within a year. Patience — letting the price and fundamentals settle — usually beats chasing the debut.',
    },
    marketContext: 'A hyped IPO can pop on its first day and then drift lower for months as lock-ups expire and early investors take profits.',
    desiredOutcome: 'approach IPOs with caution, wary of debut hype, lock-up selling, and thin valuation history',
    relevanceTags: ['ipo', 'equities', 'investing', 'beginner'],
    commonMistakes: ['buying an IPO at inflated first-day prices driven by hype'],
    misconceptions: ['that getting into an IPO early guarantees a profit'],
    prerequisites: ['what-are-stocks'], nextSteps: ['earnings-season', 'penny-stocks'], related: ['what-are-stocks', 'market-noise'],
    followups: ['earnings-season'],
    riskNote: 'IPO debut prices are often hype-inflated — let price and fundamentals settle before committing.',
    seo: { title: 'IPO Investing Explained for Beginners', description: 'What an IPO is, why IPOs pop and then fade, and the lock-up and valuation risks of buying new listings.', keywords: ['ipo investing', 'what is an ipo', 'ipo stocks', 'ipo risks'] },
  }),
  F({
    id: 'short-selling', category: 'equities', topic: 'Short Selling', title: 'Short Selling Explained', level: 'intermediate',
    concepts: ['short-selling', 'equities', 'risk'],
    questionPatterns: ['what is short selling', 'how does short selling work', 'is short selling risky', 'what is a short squeeze', 'short selling for beginners'],
    canonical: {
      short: 'Short selling is borrowing shares to sell them now, hoping to buy them back cheaper later and pocket the difference. It profits from falling prices — but the risk is theoretically unlimited, because a stock can rise forever.',
      deep: 'A short seller borrows shares, sells them, and aims to repurchase at a lower price to return them, keeping the difference. It lets traders profit from declines and hedge long positions, but its risk profile is inverted and dangerous: a long trade can only fall to zero, while a short can lose far more if the price keeps rising. "Short squeezes" — where rising prices force shorts to buy back, driving price even higher — can produce catastrophic losses. Short selling also carries borrowing costs and can be recalled. It is an advanced tool demanding hard stops and strict risk control.',
    },
    marketContext: 'A heavily shorted stock can rocket in a short squeeze as trapped sellers scramble to buy back, inflicting outsized losses on the shorts.',
    desiredOutcome: 'understand short selling as profiting from declines with inverted, potentially unlimited risk',
    relevanceTags: ['short-selling', 'equities', 'risk', 'intermediate'],
    commonMistakes: ['shorting without a hard stop and ignoring short-squeeze risk'],
    misconceptions: ['that shorting is just the mirror image of buying with the same risk'],
    prerequisites: ['what-are-stocks'], nextSteps: ['penny-stocks', 'earnings-season'], related: ['going-short', 'risk-of-ruin'],
    followups: ['earnings-season'],
    riskNote: 'Short losses are theoretically unlimited — always use a hard stop and size small.',
    seo: { title: 'Short Selling Explained (and the Short Squeeze)', description: 'How short selling profits from falling prices, why its risk is unlimited, and how short squeezes cause huge losses.', keywords: ['short selling', 'what is short selling', 'short squeeze', 'shorting stocks'] },
  }),
  F({
    id: 'earnings-season', category: 'equities', topic: 'Earnings Season', title: 'Earnings Season Explained',
    concepts: ['earnings', 'equities', 'fundamental'],
    questionPatterns: ['what is earnings season', 'how do earnings affect stocks', 'what is an earnings report', 'why do stocks move after earnings', 'trading earnings for beginners'],
    canonical: {
      short: 'Earnings season is the period each quarter when public companies report their financial results. These reports can cause sharp price moves, as stocks react to whether results beat, meet, or miss expectations.',
      deep: 'Four times a year, companies publish quarterly earnings — revenue, profit, and guidance — and prices often gap violently on the release. Crucially, stocks move relative to expectations, not just absolute numbers: a company can post record profits and still fall if it misses forecasts or gives weak guidance. This makes earnings both an opportunity and a minefield, with elevated volatility, gaps that jump stops, and unpredictable reactions. Many traders avoid holding through earnings entirely, or size down sharply, because the event is closer to a coin flip than a chartable setup.',
    },
    marketContext: 'A company can beat on profit yet drop 15% after earnings because its forward guidance disappointed the market\'s expectations.',
    desiredOutcome: 'understand that earnings move stocks relative to expectations and carry gap risk that jumps stops',
    relevanceTags: ['earnings', 'equities', 'fundamental', 'beginner'],
    commonMistakes: ['holding a full-size position through earnings and getting gapped past the stop'],
    misconceptions: ['that strong absolute earnings always send a stock higher'],
    prerequisites: ['what-are-stocks'], nextSteps: ['stock-market-indices', 'ipo-investing'], related: ['ignoring-news', 'position-correlation'],
    followups: ['stock-market-indices'],
    riskNote: 'Earnings gaps can leap past a stop — reduce size or stand aside through the report.',
    seo: { title: 'Earnings Season Explained for Beginners', description: 'What earnings season is, why stocks move on expectations versus results, and the gap risk of trading through earnings.', keywords: ['earnings season', 'earnings report', 'trading earnings', 'stock earnings'] },
  }),
  F({
    id: 'stock-market-indices', category: 'equities', topic: 'Stock Market Indices', title: 'Stock Market Indices Explained',
    concepts: ['indices', 'equities', 'benchmarks'],
    questionPatterns: ['what is a stock market index', 'what is the s&p 500', 'how do indices work', 'index investing for beginners', 'what does the dow track'],
    canonical: {
      short: 'A stock market index tracks the combined performance of a group of stocks, acting as a benchmark for a market or sector — like the S&P 500 or the Dow. Indices let investors gauge overall market direction and invest in the whole basket at once.',
      deep: 'An index is a weighted basket of stocks that summarises how a market segment is performing; the S&P 500 tracks 500 large US companies, for example. Indices serve three roles: a barometer of market health, a benchmark to measure a portfolio against, and — through index funds and ETFs — a way to own broad diversification cheaply in one instrument. Traders also speculate on indices via futures and CFDs. Because an index spreads risk across many companies, it is generally less volatile than a single stock, which is why broad index investing is a core long-term strategy.',
    },
    marketContext: 'Instead of picking single winners, a long-term investor buys an S&P 500 index fund to own the whole basket and match the market\'s return.',
    desiredOutcome: 'understand indices as weighted benchmarks that enable broad, diversified, lower-volatility exposure',
    relevanceTags: ['indices', 'equities', 'benchmarks', 'beginner'],
    commonMistakes: ['assuming an index cannot have deep drawdowns because it is diversified'],
    misconceptions: ['that an index is a single company rather than a basket'],
    prerequisites: ['what-are-stocks'], nextSteps: ['dividend-investing', 'blue-chip-stocks'], related: ['index-trading', 'indices-vs-forex', 'etf-concepts'],
    followups: ['dividend-investing'],
    riskNote: 'Indices are diversified but still fall hard in bear markets — they reduce, not remove, risk.',
    seo: { title: 'Stock Market Indices Explained (S&P 500, Dow)', description: 'What a stock market index is, how the S&P 500 and Dow work, and how indices enable diversified investing.', keywords: ['stock market index', 's&p 500', 'stock indices', 'index investing'] },
  }),
];
