// functions/knowledge/prop-firms/concepts.js
// CATEGORY: prop-firms (NEW, Phase 2) — funded-account evaluation & rules.

export const PROP_FIRM_CONCEPTS = [
  {
    id: 'prop-firm-basics', category: 'prop-firms', topic: 'Prop Firm Basics', level: 'intermediate',
    title: 'What is a Prop Firm', intent: 'funding',
    concepts: ['prop firm', 'funded account', 'evaluation', 'capital'],
    questionPatterns: ['what is a prop firm', 'how do prop firms work', 'what is a funded account', 'prop firm explained', 'how to get funded trading'],
    canonical: {
      short: 'A prop firm gives disciplined traders access to larger capital in exchange for a profit split, usually after you pass an evaluation that tests risk control. The skill being tested is not big wins — it is not breaking the rules.',
      deep: 'You pay a fee, prove yourself on a simulated evaluation (hit a modest profit target without breaching drawdown limits), and earn a funded account where you keep most of the profit. The entire model rewards consistency and risk discipline, not heroics. Treat the evaluation as a risk exam: small, repeatable trades that respect the limits beat aggressive swings that breach them.',
    },
    responseObjective: 'educate', desiredOutcome: 'understand the funded model as a discipline test',
    relevanceTags: ['prop firm', 'funding'],
    guidance: { tradeProblem: true },
    related: ['evaluation-phase', 'prop-drawdown-rules', 'choosing-prop-firm'], prerequisites: ['risk-per-trade'],
    nextSteps: ['evaluation-phase'], followups: ['prop-drawdown-rules', 'surviving-evaluation'],
    riskNote: 'The evaluation tests risk control, not aggression — size small.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'evaluation-phase', category: 'prop-firms', topic: 'Evaluation Phase', level: 'intermediate',
    title: 'Passing the Evaluation Phase', intent: 'funding',
    concepts: ['evaluation', 'challenge', 'profit target', 'phase', 'prop firm'],
    questionPatterns: ['what is the evaluation phase', 'how to pass a prop firm challenge', 'prop firm evaluation tips', 'how long to pass evaluation', 'how does the challenge work'],
    canonical: {
      short: 'The evaluation is a profit target you must reach without breaching the daily or overall drawdown — usually with no time pressure. The winning approach is to trade as if the target does not exist and only the drawdown does.',
      deep: 'Most failures come from rushing the target, not from inability to trade. Because targets are modest and time limits are generous (or gone), the math favours small risk per trade and patience: risk 0.5–1%, take only your best setups, and the target arrives without ever threatening the drawdown. Flip your focus from "how fast can I hit the target" to "how do I never approach the loss limit" and pass rates climb.',
    },
    responseObjective: 'mentor', desiredOutcome: 'pass by protecting drawdown, not chasing target',
    relevanceTags: ['prop firm', 'evaluation'],
    guidance: { tradeProblem: true },
    related: ['prop-drawdown-rules', 'surviving-evaluation', 'prop-firm-basics'], prerequisites: ['prop-firm-basics', 'daily-loss-limit'],
    nextSteps: ['prop-drawdown-rules'], followups: ['surviving-evaluation', 'prop-payout'],
    riskNote: 'Trade the drawdown, not the target — small risk passes more often.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'prop-drawdown-rules', category: 'prop-firms', topic: 'Prop Drawdown Rules', level: 'intermediate',
    title: 'Understanding Prop Firm Drawdown Rules', intent: 'funding',
    concepts: ['drawdown', 'daily drawdown', 'trailing drawdown', 'rules', 'prop firm'],
    questionPatterns: ['how does prop firm drawdown work', 'what is trailing drawdown', 'daily drawdown explained', 'prop firm rules drawdown', 'why did i breach drawdown'],
    canonical: {
      short: 'Drawdown rules are the real exam: a daily loss limit and a maximum (often trailing) loss from your peak. Breaching either ends the account instantly, so they — not the profit target — must govern every position size.',
      deep: 'Daily drawdown resets each day; the overall/trailing drawdown follows your highest balance up, so giving back profits can also breach it. The implication is precise position sizing: know exactly how many points a trade can lose, keep that well inside the daily buffer, and bank/protect profits so the trailing line does not catch you. Most blown evaluations are a sizing or trailing-drawdown misunderstanding, not bad analysis.',
    },
    responseObjective: 'warn', desiredOutcome: 'size every trade inside both drawdown limits',
    relevanceTags: ['prop firm', 'drawdown', 'rules'],
    guidance: { tradeProblem: true },
    related: ['max-drawdown', 'daily-loss-limit', 'position-sizing'], prerequisites: ['max-drawdown', 'position-sizing'],
    nextSteps: ['prop-payout'], followups: ['surviving-evaluation', 'evaluation-phase'],
    riskNote: 'A single oversized trade can breach drawdown and end the account — size for the limit.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'prop-payout', category: 'prop-firms', topic: 'Prop Payouts', level: 'intermediate',
    title: 'How Prop Payouts Work', intent: 'funding',
    concepts: ['payout', 'profit split', 'withdrawal', 'funded', 'prop firm'],
    questionPatterns: ['how do prop firm payouts work', 'what is a profit split', 'when can i withdraw prop profits', 'prop firm payout explained', 'how much do funded traders keep'],
    canonical: {
      short: 'Once funded, you withdraw your share of profits on the firm\'s payout cycle, keeping a split (often 70–90%). Read the payout terms before choosing a firm — consistency rules and minimum trading days matter as much as the percentage.',
      deep: 'Payouts run on a schedule and often carry conditions: minimum trading days, consistency rules (no single day dominating profits), and a first-payout waiting period. A high split is worthless if the firm makes withdrawals hard or the consistency rules are unrealistic for your style. Treat payout reliability and clear terms as the deciding factor, the same way withdrawal safety decides a broker.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge a firm by payout reliability, not just split %',
    relevanceTags: ['prop firm', 'payout'],
    guidance: { tradeProblem: true },
    related: ['choosing-prop-firm', 'prop-firm-basics', 'withdrawal-safety'], prerequisites: ['prop-firm-basics'],
    nextSteps: ['choosing-prop-firm'], followups: ['prop-scaling', 'choosing-prop-firm'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'prop-scaling', category: 'prop-firms', topic: 'Prop Scaling Plans', level: 'advanced',
    title: 'Prop Firm Scaling Plans', intent: 'funding',
    concepts: ['scaling', 'account growth', 'increase capital', 'consistency', 'prop firm'],
    questionPatterns: ['what is a prop scaling plan', 'how do i scale a funded account', 'prop firm scaling explained', 'how to grow funded capital', 'when does a prop firm increase my account'],
    canonical: {
      short: 'Scaling plans increase your funded capital as you hit consistent profit milestones with no rule breaches. The lever is the same discipline that passed the evaluation — steady, repeatable months, not big spikes.',
      deep: 'Firms reward proven consistency by raising your account size at set intervals, which compounds your earning power without extra evaluation fees. The requirement is almost always disciplined consistency over time, so the strategy is unchanged: small risk, repeatable edge, protect drawdown. Chasing fast growth to scale quicker usually breaches a rule and resets you — patience is literally the scaling strategy.',
    },
    responseObjective: 'mentor', desiredOutcome: 'scale funded capital through proven consistency',
    relevanceTags: ['prop firm', 'scaling', 'growth'],
    guidance: { tradeProblem: true },
    related: ['prop-payout', 'risk-scaling', 'account-growth'], prerequisites: ['prop-payout', 'risk-scaling'],
    nextSteps: ['account-growth'], followups: ['choosing-prop-firm', 'risk-scaling'],
    riskNote: 'Scaling rewards consistency — rushing it breaches rules and resets you.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'choosing-prop-firm', category: 'prop-firms', topic: 'Choosing a Prop Firm', level: 'intermediate',
    title: 'How to Choose a Prop Firm', intent: 'funding',
    concepts: ['choosing prop firm', 'comparison', 'rules', 'reputation', 'prop firm'],
    questionPatterns: ['how do i choose a prop firm', 'best prop firm for beginners', 'what to look for in a prop firm', 'how to compare prop firms', 'is this prop firm legit'],
    canonical: {
      short: 'Choose a prop firm on rules and payout reliability, not marketing: realistic drawdown, fair consistency rules, proven payouts, and a model that fits your style. The cheapest challenge is worthless if the rules are designed to fail you.',
      deep: 'Compare the things that actually decide success: drawdown type (static vs trailing), daily limits, consistency rules, news/weekend restrictions, payout history and split, and whether the platform/instruments suit your strategy. Read independent reviews for payout complaints the way you would vet a broker. A firm with slightly worse splits but transparent, achievable rules and reliable payouts beats a flashy one engineered to keep your fee.',
    },
    responseObjective: 'educate', desiredOutcome: 'pick a firm on rules and payout reliability',
    relevanceTags: ['prop firm', 'selection'],
    guidance: { tradeProblem: true },
    related: ['prop-drawdown-rules', 'prop-payout', 'broker-verification'], prerequisites: ['prop-firm-basics'],
    nextSteps: ['prop-vs-personal'], followups: ['prop-payout', 'surviving-evaluation'],
    riskNote: 'Vet payout history like a broker withdrawal — reputation over marketing.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'prop-vs-personal', category: 'prop-firms', topic: 'Prop vs Personal Account', level: 'intermediate',
    title: 'Prop Account vs Personal Account', intent: 'funding',
    concepts: ['prop vs personal', 'leverage', 'risk', 'capital', 'prop firm'],
    questionPatterns: ['prop firm vs personal account', 'should i trade my own money or get funded', 'is a prop firm better than my own account', 'prop vs personal trading', 'pros and cons of prop firms'],
    canonical: {
      short: 'A prop account offers larger capital and capped personal downside (you risk a fee, not your savings) but imposes strict rules; a personal account gives full freedom but risks your own money. The right choice follows your discipline and capital, not hype.',
      deep: 'Prop suits a disciplined trader with limited capital who can follow rules — bigger size, defined personal loss, profit split. Personal suits those with capital who want full control and no external rules. Many do both: prove and fund the strategy with prop capital while keeping a small personal account. Either way the edge is the same; the account type only changes the constraints, not the need for risk discipline.',
    },
    responseObjective: 'clarify', desiredOutcome: 'choose the account model that fits your situation',
    relevanceTags: ['prop firm', 'comparison'],
    guidance: { tradeProblem: true },
    related: ['choosing-prop-firm', 'prop-firm-basics', 'account-growth'], prerequisites: ['prop-firm-basics'],
    nextSteps: ['account-growth'], followups: ['choosing-prop-firm', 'prop-scaling'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'surviving-evaluation', category: 'prop-firms', topic: 'Surviving the Evaluation', level: 'intermediate',
    title: 'Surviving a Prop Evaluation', intent: 'funding',
    concepts: ['surviving evaluation', 'discipline', 'risk', 'psychology', 'prop firm'],
    questionPatterns: ['how do i survive a prop evaluation', 'how to not fail a prop challenge', 'prop firm survival tips', 'why do i keep failing prop challenges', 'how to pass without blowing the account'],
    canonical: {
      short: 'Survive an evaluation by making the drawdown irrelevant: tiny risk, your best setups only, hard daily stop, and zero revenge trading. The trader who treats it like a marathon of small disciplined trades passes; the one chasing the target blows it.',
      deep: 'Most failures are behavioural, not technical — overtrading, oversizing after a loss, or pushing to finish fast. Build a checklist: fixed sub-1% risk, a daily loss limit well inside the firm\'s, a cap on trades per day, and a rule to stop after your target day. Passing is mostly emotional control under a rulebook, which is exactly the skill that makes a funded account profitable afterwards.',
    },
    responseObjective: 'mentor', desiredOutcome: 'pass via discipline and emotional control',
    relevanceTags: ['prop firm', 'discipline', 'psychology'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['evaluation-phase', 'daily-loss-limit', 'revenge-trading'], prerequisites: ['evaluation-phase', 'trading-discipline'],
    nextSteps: ['prop-payout'], followups: ['trader-assessment', 'daily-loss-limit'],
    riskNote: 'Most evaluations fail on behaviour — cap risk, trades, and stop on tilt.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
