// functions/knowledge/advanced/concepts.js
// CATEGORY: advanced (NEW, Phase 9) — Wyckoff, hedging, derivatives, pro risk/business.

export const ADVANCED_CONCEPTS = [
  {
    id: 'wyckoff-method', category: 'advanced', topic: 'The Wyckoff Method', level: 'advanced',
    title: 'The Wyckoff Method', intent: 'technical',
    concepts: ['wyckoff', 'accumulation', 'distribution', 'composite man'],
    questionPatterns: ['what is the wyckoff method', 'how does wyckoff work', 'wyckoff accumulation distribution', 'wyckoff explained', 'what are wyckoff phases'],
    canonical: {
      short: 'Wyckoff reads the market as a "composite operator" accumulating before markups and distributing before markdowns, through phases marked by springs, tests, and signs of strength. It is the classic framework behind modern smart-money ideas.',
      deep: 'Wyckoff describes cycles: accumulation (quiet buying in a range, ending with a spring that sweeps lows), markup (trend), distribution (quiet selling, ending with an upthrust), markdown. Phases A–E and events like springs and tests map where smart money builds and offloads. It predates ICT/SMC but shares the logic — read effort vs result and where liquidity is taken to anticipate the next leg.',
    },
    marketContext: 'Classic accumulation-then-spring structures appear repeatedly on gold before major rallies, where a final dip below the range traps shorts before the markup.',
    responseObjective: 'educate', desiredOutcome: 'read accumulation/distribution via Wyckoff phases',
    relevanceTags: ['advanced', 'wyckoff', 'structure'],
    guidance: { tradeProblem: true },
    commonMistakes: ['buying the obvious range low instead of waiting for the spring + test'],
    misconceptions: ['Wyckoff is outdated — modern smart-money concepts are largely the same logic'],
    related: ['accumulation-distribution', 'market-maker-model', 'auction-market-theory'], prerequisites: ['accumulation-distribution'],
    nextSteps: ['bank-dealing-desk'], followups: ['market-maker-model', 'liquidity-engineering'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'bank-dealing-desk', category: 'advanced', topic: 'Bank Dealing Desks', level: 'advanced',
    title: 'How Bank Dealing Desks Operate', intent: 'technical',
    concepts: ['dealing desk', 'banks', 'liquidity provider', 'institutional'],
    questionPatterns: ['how do bank dealing desks work', 'what is a dealing desk', 'how do banks trade forex', 'bank dealing desk explained', 'how do banks move price'],
    canonical: {
      short: 'Bank dealing desks manage huge client and proprietary flow, providing liquidity and positioning around key levels and news. They must fill size discreetly, which is why obvious liquidity gets engineered and swept.',
      deep: 'Banks see order flow retail cannot — client hedging, corporate flows, option barriers — and must execute large positions without moving price against themselves. That means accumulating into liquidity pools (obvious highs/lows) and around news. You cannot see their book, but their need to source liquidity explains sweeps, defended levels, and the algorithmic probing of obvious stops. Trade the footprint, not against the flow.',
    },
    marketContext: 'Option expiry "pin" behaviour near round numbers reflects dealing-desk hedging — price is often drawn to and held near large strikes into expiry.',
    responseObjective: 'educate', desiredOutcome: 'understand why institutions engineer and sweep liquidity',
    relevanceTags: ['advanced', 'institutional', 'banks'],
    guidance: { tradeProblem: true },
    commonMistakes: ['assuming the market moves randomly rather than around institutional flow'],
    related: ['institutional-order-flow', 'liquidity-engineering', 'wyckoff-method'], prerequisites: ['institutional-order-flow'],
    nextSteps: ['market-manipulation-models'], followups: ['liquidity-engineering', 'algorithmic-behaviour'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'market-manipulation-models', category: 'advanced', topic: 'Market Manipulation Models', level: 'advanced',
    title: 'Market Manipulation Models', intent: 'technical',
    concepts: ['manipulation', 'traps', 'stop runs', 'institutional'],
    questionPatterns: ['how is the market manipulated', 'what are manipulation models', 'how do institutions trap traders', 'market manipulation explained', 'is the forex market manipulated'],
    canonical: {
      short: 'Manipulation models describe the engineered moves that trap retail: stop runs, fake breakouts, and inducement before the real move. "Manipulation" here means liquidity sourcing, not conspiracy — and recognising it keeps you from being the fuel.',
      deep: 'The repeatable pattern is accumulate → manipulate (sweep obvious liquidity, trap breakout/stop orders) → distribute (the genuine expansion). The retail trap is buying the manipulation high or selling the manipulation low. By expecting the sweep-and-reverse rather than the obvious breakout, you align with the distribution leg. It is mechanical liquidity-seeking by large players, not malice — read it and trade the reclaim.',
    },
    marketContext: 'Pre-news "fakeouts" are classic: price pushes one way to grab liquidity minutes before a release, then reverses hard on the actual data.',
    responseObjective: 'warn', desiredOutcome: 'avoid being trapped by engineered moves',
    relevanceTags: ['advanced', 'manipulation', 'liquidity'],
    guidance: { tradeProblem: true },
    commonMistakes: ['chasing the obvious breakout that institutions engineered as bait'],
    misconceptions: ['manipulation means the market is rigged against you — it is liquidity sourcing you can trade with'],
    related: ['bank-dealing-desk', 'liquidity-engineering', 'inducement'], prerequisites: ['liquidity-engineering'],
    nextSteps: ['volatility-expansion'], followups: ['inducement', 'stop-hunt-model'],
    riskNote: 'The obvious move is often the trap — wait for the reclaim with a defined stop.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'volatility-expansion', category: 'advanced', topic: 'Volatility Expansion', level: 'advanced',
    title: 'Volatility Expansion and Contraction', intent: 'technical',
    concepts: ['volatility expansion', 'contraction', 'squeeze', 'breakout'],
    questionPatterns: ['what is volatility expansion', 'what is a volatility squeeze', 'how to trade volatility expansion', 'contraction before expansion', 'volatility expansion explained'],
    canonical: {
      short: 'Markets cycle between contraction (tight, coiling ranges) and expansion (explosive directional moves). Tight contraction often precedes a large expansion, so a quiet squeeze is a warning that a big move is loading.',
      deep: 'Low-volatility consolidation builds energy as positions accumulate; when one side breaks, volatility expands rapidly into a trend. The play is to prepare during contraction (mark the range edges, reduce noise trades) and trade the confirmed expansion — ideally the break-and-retest, since first breaks of a squeeze can be faked. Recognising the contraction phase positions you ahead of the move rather than chasing it.',
    },
    marketContext: 'Gold frequently coils into tight multi-day ranges before high-impact news, then expands sharply on the release — the squeeze foreshadowed the expansion.',
    responseObjective: 'educate', desiredOutcome: 'anticipate expansion from contraction',
    relevanceTags: ['advanced', 'volatility', 'breakout'],
    guidance: { tradeProblem: true },
    commonMistakes: ['shorting/longing inside the squeeze instead of waiting for expansion'],
    related: ['volatility-models', 'breakout-models', 'range-market'], prerequisites: ['volatility-models'],
    nextSteps: ['hedging'], followups: ['breakout-models', 'volatility-regimes'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'hedging', category: 'advanced', topic: 'Hedging', level: 'advanced',
    title: 'Hedging Basics', intent: 'riskmgmt',
    concepts: ['hedging', 'offset', 'correlation', 'risk reduction'],
    questionPatterns: ['what is hedging', 'how does hedging work', 'should i hedge my trades', 'hedging explained', 'how to hedge risk'],
    canonical: {
      short: 'Hedging offsets risk by holding a position that profits if your main trade loses — for example shorting a correlated asset. It reduces volatility of returns but also caps upside and adds cost, so it is a tool, not a cure for bad trades.',
      deep: 'Real hedging uses correlation: a long in one asset partly offset by a short in a correlated one, or options to cap downside. It smooths the equity curve and protects through events, at the cost of reduced profit and extra complexity/fees. For most retail traders, simply sizing correctly and using stops achieves the same protection more cheaply — hedging matters more for portfolios and event risk than for single trades.',
    },
    marketContext: 'Funds often hedge equity exposure with gold or the yen into uncertain events, accepting lower upside for protection if risk-off hits.',
    responseObjective: 'educate', desiredOutcome: 'understand hedging as a risk-smoothing tool, not a fix',
    relevanceTags: ['advanced', 'hedging', 'risk'],
    guidance: { tradeProblem: true },
    commonMistakes: ['hedging a losing trade instead of just closing it'],
    misconceptions: ['hedging removes risk — it transforms and costs, it does not erase it'],
    related: ['correlation-trading', 'portfolio-risk', 'correlation'], prerequisites: ['correlation', 'portfolio-risk'],
    nextSteps: ['correlation-trading'], followups: ['portfolio-risk', 'options-basics'],
    riskNote: 'Hedging a loser usually just locks in confusion — sizing and stops are cheaper protection.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'correlation-trading', category: 'advanced', topic: 'Correlation Trading', level: 'advanced',
    title: 'Correlation Trading', intent: 'strategy',
    concepts: ['correlation trading', 'pairs', 'divergence', 'relative value'],
    questionPatterns: ['what is correlation trading', 'how to trade correlations', 'pairs trading explained', 'how to use correlation in trading', 'correlation trading strategy'],
    canonical: {
      short: 'Correlation trading uses the relationship between assets — going long the stronger and short the weaker of a correlated pair, or trading a temporary divergence back to its norm. It is relative-value thinking rather than outright direction.',
      deep: 'When two normally-correlated assets diverge, one strategy expects them to converge again (relative value); in strong trends, you express a view by buying strength and selling weakness within a correlated group. It demands understanding that correlations shift with regime and that "correlated" positions concentrate risk. Done carefully it diversifies edge; done carelessly it doubles exposure — always count the net risk.',
    },
    marketContext: 'Traders have expressed dollar views by pairing a long in the strongest major against a short in the weakest, rather than betting on one pair alone.',
    responseObjective: 'educate', desiredOutcome: 'express views via relative strength, controlling net risk',
    relevanceTags: ['advanced', 'correlation', 'relative value'],
    guidance: { tradeProblem: true },
    commonMistakes: ['treating correlated longs as diversification when they are concentration'],
    related: ['correlation', 'hedging', 'portfolio-risk'], prerequisites: ['correlation'],
    nextSteps: ['professional-risk-models'], followups: ['portfolio-risk', 'commodity-correlations'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'options-basics', category: 'advanced', topic: 'Options Basics', level: 'advanced',
    title: 'Options Basics for Traders', intent: 'technical',
    concepts: ['options', 'calls', 'puts', 'premium'],
    questionPatterns: ['what are options', 'how do options work', 'calls and puts explained', 'options basics', 'should i trade options'],
    canonical: {
      short: 'Options give the right (not obligation) to buy (call) or sell (put) at a set price by an expiry, for a premium. They allow defined-risk bets and hedging, but add time decay and complexity that punish casual use.',
      deep: 'A call profits if price rises above the strike plus premium; a put if it falls below. Your max loss as a buyer is the premium (defined risk), which is attractive for events. But options lose value to time decay and depend on volatility, so they reward those who understand the greeks and punish those who treat them like lottery tickets. For most spot/forex traders they are a hedging and event tool to learn carefully, not a shortcut.',
    },
    marketContext: 'Option expiries and large strikes create "pinning" and barrier behaviour in FX and gold that even spot traders benefit from being aware of.',
    responseObjective: 'educate', desiredOutcome: 'grasp options as defined-risk tools with decay',
    relevanceTags: ['advanced', 'options'],
    guidance: { tradeProblem: true },
    commonMistakes: ['buying cheap out-of-the-money options like lottery tickets'],
    misconceptions: ['options are just leveraged bets — time decay and volatility make them very different'],
    related: ['futures-basics', 'hedging', 'volatility-models'], prerequisites: [],
    nextSteps: ['futures-basics'], followups: ['hedging', 'volatility-expansion'],
    riskNote: 'Time decay erodes long options daily — they are not just cheap leverage.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'futures-basics', category: 'advanced', topic: 'Futures Basics', level: 'advanced',
    title: 'Futures Basics for Traders', intent: 'technical',
    concepts: ['futures', 'contracts', 'expiry', 'leverage'],
    questionPatterns: ['what are futures', 'how do futures work', 'futures vs spot', 'futures basics', 'should i trade futures'],
    canonical: {
      short: 'Futures are standardized contracts to buy/sell an asset at a set price on a future date, traded on exchanges with transparent volume. They offer deep liquidity and real volume data, but carry leverage, expiry, and rollover considerations.',
      deep: 'Unlike spot, futures are centralized and show genuine traded volume (useful for volume profile and order-flow analysis). They have expiry dates requiring rollover, and margin-based leverage that demands the same risk discipline as any market. Many institutional and professional traders prefer futures for gold, indices, and oil because of transparency and depth — but the leverage means position sizing rules apply just as strictly.',
    },
    marketContext: 'COMEX gold futures volume and COT positioning give context that pure spot gold traders lack — many read futures data even when trading spot.',
    responseObjective: 'educate', desiredOutcome: 'understand futures as transparent, leveraged, expiring contracts',
    relevanceTags: ['advanced', 'futures'],
    guidance: { tradeProblem: true },
    commonMistakes: ['ignoring expiry/rollover and getting caught at contract change'],
    related: ['options-basics', 'volume-profile', 'cot-report'], prerequisites: [],
    nextSteps: ['professional-risk-models'], followups: ['volume-profile', 'cot-report'],
    riskNote: 'Futures leverage demands the same 1% risk discipline as any market.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'professional-risk-models', category: 'advanced', topic: 'Professional Risk Models', level: 'advanced',
    title: 'Professional Risk Models', intent: 'riskmgmt',
    concepts: ['risk models', 'var', 'kelly', 'portfolio risk'],
    questionPatterns: ['what are professional risk models', 'how do pros manage risk', 'what is value at risk', 'kelly criterion explained', 'advanced risk management'],
    canonical: {
      short: 'Professional risk models move beyond fixed 1% per trade to portfolio-level controls: total open risk caps, correlation-adjusted exposure, drawdown limits, and sizing tied to edge (e.g. fractional Kelly). The goal is the same — survive to compound.',
      deep: 'Pros think in portfolio terms: cap total open risk across correlated positions, adjust size to volatility and conviction, set hard drawdown limits that trigger de-risking, and size by a fraction of Kelly rather than gut feel. Concepts like value-at-risk estimate worst-case exposure. None of this replaces the basics — it scales them — and the through-line remains capital preservation so the edge can compound over years.',
    },
    marketContext: 'Funds cut gross exposure automatically when portfolio VaR or drawdown limits are breached — a systematic version of the retail daily-loss-limit.',
    responseObjective: 'educate', desiredOutcome: 'scale risk control to the portfolio level',
    relevanceTags: ['advanced', 'risk models', 'portfolio'],
    guidance: { tradeProblem: true },
    commonMistakes: ['using only per-trade risk and ignoring total correlated exposure'],
    related: ['portfolio-risk', 'correlation-trading', 'risk-scaling'], prerequisites: ['portfolio-risk'],
    nextSteps: ['trading-business-models'], followups: ['risk-scaling', 'max-drawdown'],
    riskNote: 'Even advanced models exist to preserve capital — survival first, always.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'trading-business-models', category: 'advanced', topic: 'Trading as a Business', level: 'advanced',
    title: 'Trading Business Models', intent: 'career',
    concepts: ['trading business', 'income', 'capital', 'scaling'],
    questionPatterns: ['how to treat trading as a business', 'trading business model', 'how do traders make a living', 'how to scale a trading business', 'trading as a business explained'],
    canonical: {
      short: 'Treating trading as a business means managing it like one: an edge (product), risk controls (operations), capital (inventory), records (accounting), and realistic income expectations. Emotion-driven trading is a hobby; process-driven trading is a business.',
      deep: 'The viable models differ: growing personal capital via compounding, trading firm/prop capital for a split, or building income through consistency and scaling size on a proven edge. All require treating P&L as business results, journaling as bookkeeping, and risk rules as operating procedures. Realistic expectations matter — steady percentage returns compounded, not overnight riches. The professionals who last run trading with the discipline of any serious business.',
    },
    marketContext: 'Funded traders effectively run a "capital rental" business — they supply the edge and discipline, the firm supplies capital, and both share the profit.',
    responseObjective: 'mentor', desiredOutcome: 'run trading with business discipline and realistic income',
    relevanceTags: ['advanced', 'business', 'career'],
    guidance: { traderProblem: true },
    commonMistakes: ['expecting fast riches instead of running steady, compounding business returns'],
    related: ['account-growth', 'prop-firm-basics', 'professional-habits'], prerequisites: ['account-growth'],
    nextSteps: ['advanced-psychology'], followups: ['prop-firm-basics', 'professional-habits'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'advanced-psychology', category: 'advanced', topic: 'Advanced Trading Psychology', level: 'advanced',
    title: 'Advanced Trading Psychology', intent: 'psychology',
    concepts: ['advanced psychology', 'biases', 'identity', 'peak performance'],
    questionPatterns: ['what is advanced trading psychology', 'cognitive biases in trading', 'how to master trading psychology', 'peak performance trading', 'advanced psychology explained'],
    canonical: {
      short: 'Advanced psychology tackles the subtler layer: cognitive biases (confirmation, recency, loss aversion), the role of identity and self-worth, and performing under real pressure at size. The basics fix tilt; this layer builds durable, professional composure.',
      deep: 'Beyond emotional control lies bias management — noticing confirmation bias in your analysis, recency bias after a streak, loss aversion in cutting winners. It also covers detaching self-worth from P&L, managing the heavier emotions of larger size, and building routines for peak performance. This is the work that turns a consistent trader into a resilient professional who can scale without their psychology breaking.',
    },
    marketContext: 'Many talented traders stall not from strategy but from psychology at size — the same edge that worked small unravels when position size triggers fear and greed.',
    responseObjective: 'mentor', desiredOutcome: 'manage biases and perform under pressure at size',
    relevanceTags: ['advanced', 'psychology', 'biases'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    commonMistakes: ['tying self-worth to daily P&L and spiralling after a loss'],
    misconceptions: ['psychology is a beginner topic — it gets harder, not easier, as size grows'],
    related: ['trader-mindset', 'overconfidence', 'mental-capital'], prerequisites: ['trader-mindset'],
    nextSteps: ['professional-habits'], followups: ['mental-capital', 'trader-assessment'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'capital-allocation', category: 'advanced', topic: 'Capital Allocation', level: 'advanced',
    title: 'Capital Allocation', intent: 'riskmgmt',
    concepts: ['capital allocation', 'sizing', 'diversification', 'portfolio'],
    questionPatterns: ['what is capital allocation', 'how to allocate trading capital', 'how much capital per strategy', 'capital allocation explained', 'how to split capital across trades'],
    canonical: {
      short: 'Capital allocation decides how much of your account backs each strategy, market, or trade — balancing conviction against diversification and total risk. Concentrating everything in one idea is fragile; spreading too thin dilutes your edge.',
      deep: 'Allocation links position sizing to portfolio thinking: weight more capital to higher-conviction, proven edges, cap exposure to any single correlated theme, and keep reserve for opportunity and drawdown. It is the bridge between per-trade risk and account-level strategy. The aim is a robust mix where no single market or idea can sink you, while your best edges still get enough weight to matter.',
    },
    marketContext: 'Multi-strategy funds allocate capital across uncorrelated books precisely so a blow-up in one does not threaten the whole — retail can mirror this at small scale.',
    responseObjective: 'educate', desiredOutcome: 'balance conviction and diversification across capital',
    relevanceTags: ['advanced', 'allocation', 'portfolio'],
    guidance: { tradeProblem: true },
    commonMistakes: ['putting all capital behind one correlated theme'],
    related: ['portfolio-risk', 'professional-risk-models', 'correlation-trading'], prerequisites: ['portfolio-risk'],
    nextSteps: ['professional-risk-models'], followups: ['correlation-trading', 'risk-scaling'],
    riskNote: 'Never let one correlated theme hold enough capital to sink the account.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
