// functions/knowledge/automation/concepts.js
// KNOWLEDGE EXPANSION WAVE 2 — TRADING AUTOMATION & CODING (category: automation)
// Fills the verified gap: Pine Script, TradingView alerts, Expert Advisors, copy
// trading, API trading, grid trading, bots, automated backtesting — none previously
// held as concepts. Auto-integrates like every concept. Additive only.

const F = (o) => ({
  level: 'intermediate', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const AUTOMATION_CONCEPTS = [
  F({
    id: 'pine-script', category: 'automation', topic: 'Pine Script', title: 'Pine Script Explained for Beginners', level: 'beginner',
    concepts: ['pine-script', 'automation', 'tradingview'],
    questionPatterns: ['what is pine script', 'how to learn pine script', 'what is pine script used for', 'can you automate with pine script', 'pine script for beginners'],
    canonical: {
      short: 'Pine Script is TradingView\'s programming language for building custom indicators and strategies. It lets you code your own studies, backtest strategy ideas on historical data, and generate alerts — all inside the TradingView charting platform.',
      deep: 'Pine Script is a lightweight, chart-focused language designed to be approachable for traders rather than professional developers. With it you can turn a trading idea into a visible indicator, run a strategy against historical bars to see hypothetical results (the built-in Strategy Tester), and fire alerts on your conditions. Its limits matter: Pine runs inside TradingView and does not place live orders by itself — automated execution requires connecting alerts to a broker or a third-party bridge. It is the most accessible on-ramp to systematising ideas, but backtests must account for realistic fills, fees, and repainting pitfalls.',
    },
    marketContext: 'A Gold trader can code their moving-average-plus-RSI rule in Pine Script, backtest it, and set an alert — validating the idea before ever risking money.',
    desiredOutcome: 'use Pine Script to codify, backtest, and alert on strategy ideas, understanding it does not execute trades alone',
    relevanceTags: ['pine-script', 'automation', 'tradingview', 'beginner'],
    commonMistakes: ['trusting a Pine backtest that ignores fees, slippage, and repainting'],
    misconceptions: ['that Pine Script can place live trades on its own'],
    prerequisites: ['tradingview-basics'], nextSteps: ['tradingview-alerts', 'automated-backtesting'], related: ['expert-advisors', 'system-trading'],
    followups: ['tradingview-alerts'],
    riskNote: 'A backtest is a hypothesis, not a promise — validate forward before risking capital.',
    seo: { title: 'Pine Script Explained for Beginners (TradingView)', description: 'What Pine Script is, how it builds custom indicators and backtests strategies on TradingView, and its limits.', keywords: ['pine script', 'pine script tradingview', 'learn pine script', 'tradingview coding'] },
  }),
  F({
    id: 'tradingview-alerts', category: 'automation', topic: 'TradingView Alerts', title: 'TradingView Alerts & Automation Explained', level: 'beginner',
    concepts: ['tradingview-alerts', 'automation', 'webhooks'],
    questionPatterns: ['how do tradingview alerts work', 'how to automate tradingview alerts', 'what are tradingview webhooks', 'can tradingview place trades', 'tradingview alert to broker'],
    canonical: {
      short: 'TradingView alerts notify you when your chart conditions are met — a price level, an indicator cross, or a custom Pine Script signal. With webhooks, alerts can send a message to an external service that places the trade, turning a signal into automated execution.',
      deep: 'Alerts are the bridge between analysis and action. Basic alerts ping you by app, email, or popup; advanced alerts fire a webhook (an HTTP message) to a server, broker integration, or bot that can execute the order. This is how many retail traders "automate" without full custom infrastructure: Pine strategy → alert → webhook → execution bridge → broker. The risks are real — a webhook can misfire, a bridge can disconnect, and duplicate or delayed alerts can cause unintended orders — so any automated pipeline needs safeguards, position limits, and monitoring.',
    },
    marketContext: 'A trader connects a TradingView alert on a Gold breakout to a webhook bridge so the position opens automatically the moment the level triggers.',
    desiredOutcome: 'use alerts (and webhooks) to convert signals into notifications or automated execution, with safeguards',
    relevanceTags: ['tradingview-alerts', 'automation', 'webhooks', 'beginner'],
    commonMistakes: ['building a live webhook pipeline with no position limits or failure monitoring'],
    misconceptions: ['that alerts execute trades by default without an external bridge'],
    prerequisites: ['pine-script'], nextSteps: ['api-trading', 'trading-bots'], related: ['expert-advisors', 'copy-trading'],
    followups: ['api-trading'],
    riskNote: 'Automated pipelines can misfire — cap position size and monitor every live connection.',
    seo: { title: 'TradingView Alerts & Automation Explained', description: 'How TradingView alerts and webhooks work, and how they turn chart signals into automated trade execution.', keywords: ['tradingview alerts', 'tradingview webhooks', 'automate tradingview', 'alert to broker'] },
  }),
  F({
    id: 'expert-advisors', category: 'automation', topic: 'Expert Advisors', title: 'Expert Advisors (EAs) Explained', level: 'beginner',
    concepts: ['expert-advisor', 'automation', 'metatrader'],
    questionPatterns: ['what is an expert advisor', 'how do forex eas work', 'are expert advisors profitable', 'what is mql', 'expert advisor for beginners'],
    canonical: {
      short: 'An Expert Advisor (EA) is an automated trading program that runs on MetaTrader (MT4/MT5), executing trades based on coded rules without manual input. EAs are written in MQL and can manage entries, exits, and risk around the clock.',
      deep: 'EAs let a trader fully automate a strategy on the popular MetaTrader platforms: the MQL code watches the market and places, manages, and closes trades according to its rules. They remove emotion and run 24/5, which suits systematic forex and Gold strategies. The pitfalls are significant — many marketed "profitable" EAs are curve-fit to past data and fail live, and even sound EAs need a stable VPS, monitoring, and realistic assumptions about spread and slippage. An EA is only as good as its logic and its testing; automation multiplies a bad strategy\'s losses just as fast as a good one\'s gains.',
    },
    marketContext: 'A Gold scalping EA on MT5 can execute a tested rule set continuously on a VPS, but a curve-fit EA bought online often blows the account in live conditions.',
    desiredOutcome: 'understand EAs as MetaTrader automation whose value depends entirely on sound logic and honest testing',
    relevanceTags: ['expert-advisor', 'automation', 'metatrader', 'beginner'],
    commonMistakes: ['buying a marketed EA with a perfect backtest and running it live without validation'],
    misconceptions: ['that an EA is a guaranteed money-making machine'],
    prerequisites: ['mt5-basics'], nextSteps: ['trading-bots', 'automated-backtesting'], related: ['pine-script', 'algorithmic-trading-basics', 'install-indicator-ea'],
    followups: ['trading-bots'],
    riskNote: 'Automation amplifies a bad strategy as fast as a good one — validate live-forward on small size first.',
    seo: { title: 'Expert Advisors (EAs) Explained for Beginners', description: 'What a MetaTrader Expert Advisor is, how MQL automation works, and why most marketed EAs fail live.', keywords: ['expert advisor', 'forex ea', 'metatrader ea', 'mql expert advisor'] },
  }),
  F({
    id: 'copy-trading', category: 'automation', topic: 'Copy Trading', title: 'Copy Trading Explained', level: 'beginner',
    concepts: ['copy-trading', 'automation', 'social-trading'],
    questionPatterns: ['what is copy trading', 'how does copy trading work', 'is copy trading profitable', 'copy trading for beginners', 'risks of copy trading'],
    canonical: {
      short: 'Copy trading automatically mirrors the trades of another trader in your own account. When they open or close a position, the platform replicates it for you proportionally — letting beginners follow experienced traders without making their own decisions.',
      deep: 'Copy trading (a form of social trading) links your account to a chosen "signal provider" so their trades copy into yours automatically, scaled to your capital. Its appeal is hands-off access to strategies you could not build yourself. The risks are frequently underestimated: past performance is often cherry-picked, a provider can blow up with a single reckless trade, high leverage magnifies copied losses, and you inherit their risk management (or lack of it). Sensible use means diversifying across vetted providers, checking real drawdown history, and copying only capital you can afford to lose.',
    },
    marketContext: 'A beginner copies a verified Gold trader, but if that trader over-leverages during a news spike, the copied account takes the same outsized loss.',
    desiredOutcome: 'treat copy trading as inheriting someone else\'s risk profile, requiring vetting and diversification',
    relevanceTags: ['copy-trading', 'automation', 'social-trading', 'beginner'],
    commonMistakes: ['copying a provider based on a cherry-picked return without checking real drawdown'],
    misconceptions: ['that copy trading removes risk because a "pro" is trading'],
    prerequisites: ['risk-management-basics'], nextSteps: ['trading-bots', 'api-trading'], related: ['expert-advisors', 'prop-firm-basics'],
    followups: ['trading-bots'],
    riskNote: 'You inherit the provider\'s risk — one reckless copied trade can hit your account hard.',
    seo: { title: 'Copy Trading Explained for Beginners', description: 'How copy trading mirrors another trader\'s positions, its real risks, and how to vet signal providers.', keywords: ['copy trading', 'social trading', 'copy trading explained', 'copy trading risks'] },
  }),
  F({
    id: 'api-trading', category: 'automation', topic: 'API Trading', title: 'API Trading Explained', level: 'advanced',
    concepts: ['api-trading', 'automation', 'programmatic'],
    questionPatterns: ['what is api trading', 'how does trading api work', 'how to trade with a broker api', 'api trading for beginners', 'rest vs websocket trading api'],
    canonical: {
      short: 'API trading means connecting your own program directly to a broker or exchange through an Application Programming Interface to place, manage, and monitor orders automatically. It gives full control and speed but requires coding and careful risk safeguards.',
      deep: 'A broker or exchange API exposes endpoints your code can call to fetch market data, submit orders, and track positions programmatically — REST for standard requests, WebSocket for real-time streaming. API trading powers everything from personal bots to institutional systems, offering low latency and complete customisation beyond what a chart platform allows. The responsibility shifts entirely to you: an unhandled error, a runaway loop, or a missing rate-limit check can fire dozens of unintended orders. Production API trading demands defensive coding, kill switches, position and loss limits, and constant monitoring.',
    },
    marketContext: 'A quant connects to an exchange API to run a Bitcoin strategy that reacts in milliseconds — but a single unhandled reconnect bug could spam duplicate orders.',
    desiredOutcome: 'understand API trading as full programmatic control that demands rigorous safeguards',
    relevanceTags: ['api-trading', 'automation', 'programmatic', 'advanced'],
    commonMistakes: ['running a live API bot with no kill switch, rate limiting, or loss cap'],
    misconceptions: ['that API access alone makes a strategy profitable'],
    prerequisites: ['algorithmic-trading-basics'], nextSteps: ['trading-bots', 'automated-backtesting'], related: ['expert-advisors', 'tradingview-alerts'],
    followups: ['trading-bots'],
    riskNote: 'Code failures execute in real money — always build kill switches and hard loss limits.',
    seo: { title: 'API Trading Explained', description: 'What API trading is, how broker and exchange APIs let programs place orders, and the safeguards live automation needs.', keywords: ['api trading', 'trading api', 'broker api', 'programmatic trading'] },
  }),
  F({
    id: 'grid-trading', category: 'automation', topic: 'Grid Trading', title: 'Grid Trading Explained', level: 'intermediate',
    concepts: ['grid-trading', 'automation', 'strategy'],
    questionPatterns: ['what is grid trading', 'how does grid trading work', 'is grid trading profitable', 'grid trading strategy', 'grid trading risks'],
    canonical: {
      short: 'Grid trading places a ladder of buy and sell orders at set intervals above and below the current price. It aims to profit from the up-and-down swings of a ranging market by repeatedly buying low and selling high across the grid — often run by a bot.',
      deep: 'A grid strategy systematises range trading: it seeds orders at fixed spacing so that oscillations trigger small, repeated profits regardless of exact direction. It works well in choppy, sideways markets and is easy to automate. Its danger is a strong trend: in a sustained move against the grid, unfilled positions accumulate into a large, growing loss, and naive grids paired with martingale-style sizing can wipe an account. Safe grids require a defined range, a hard stop or invalidation level, and no reliance on "the market will come back."',
    },
    marketContext: 'A grid bot profits nicely while Gold ranges, but a strong sustained breakout leaves it holding a stack of losing positions if there is no invalidation.',
    desiredOutcome: 'use grid trading for defined ranges with a hard invalidation, never assuming price returns',
    relevanceTags: ['grid-trading', 'automation', 'strategy', 'intermediate'],
    commonMistakes: ['running a grid with no stop and letting losing positions pile up in a trend'],
    misconceptions: ['that a grid bot makes money in any market condition'],
    prerequisites: ['range-trading'], nextSteps: ['trading-bots', 'api-trading'], related: ['grid-trading', 'system-trading'],
    followups: ['trading-bots'],
    riskNote: 'Grids bleed in trends — define the range, set a hard invalidation, and cap total exposure.',
    seo: { title: 'Grid Trading Explained', description: 'How grid trading profits from ranging markets with laddered orders, and why trends and no-stop grids are dangerous.', keywords: ['grid trading', 'grid trading strategy', 'grid bot', 'grid trading risks'] },
  }),
  F({
    id: 'trading-bots', category: 'automation', topic: 'Trading Bots', title: 'Trading Bots Explained', level: 'beginner',
    concepts: ['trading-bots', 'automation', 'algorithmic'],
    questionPatterns: ['what is a trading bot', 'how do trading bots work', 'are trading bots profitable', 'trading bots for beginners', 'best trading bot risks'],
    canonical: {
      short: 'A trading bot is software that automatically executes a trading strategy based on preset rules — monitoring the market and placing trades without human intervention. Bots range from simple grid and DCA tools to complex algorithmic systems.',
      deep: 'Trading bots automate execution so a strategy runs consistently and unemotionally, 24/7 for crypto or 24/5 for forex. They can be off-the-shelf (grid, DCA, signal-following) or fully custom via APIs. The core truth is that a bot is only a faithful executor — it does not create edge, it enforces whatever logic it is given. Marketed "profitable bots" are frequently curve-fit or outright scams, and even good bots need monitoring, a stable host, and risk limits. Automation removes emotion and human error but adds technical risk: bugs, outages, and API failures all execute in real money.',
    },
    marketContext: 'A DCA bot steadily accumulating Bitcoin removes emotional timing, but a poorly coded custom bot can spam orders during an exchange outage.',
    desiredOutcome: 'view a bot as a disciplined executor of a strategy, not a source of edge, requiring oversight',
    relevanceTags: ['trading-bots', 'automation', 'algorithmic', 'beginner'],
    commonMistakes: ['buying a "guaranteed profit" bot instead of automating a strategy you have validated'],
    misconceptions: ['that a bot creates a winning edge on its own'],
    prerequisites: ['algorithmic-trading-basics'], nextSteps: ['automated-backtesting', 'api-trading'], related: ['expert-advisors', 'copy-trading'],
    followups: ['automated-backtesting'],
    riskNote: 'A bot enforces logic faithfully — automating a losing strategy just loses faster.',
    seo: { title: 'Trading Bots Explained for Beginners', description: 'What trading bots are, how they automate strategies, why they do not create edge, and the risks of marketed bots.', keywords: ['trading bots', 'trading bot explained', 'automated trading', 'crypto trading bot'] },
  }),
  F({
    id: 'automated-backtesting', category: 'automation', topic: 'Automated Backtesting', title: 'Automated Backtesting Explained', level: 'intermediate',
    concepts: ['automated-backtesting', 'automation', 'validation'],
    questionPatterns: ['what is automated backtesting', 'how to backtest a strategy automatically', 'is backtesting reliable', 'backtesting mistakes', 'walk forward testing'],
    canonical: {
      short: 'Automated backtesting runs a coded strategy against historical data to estimate how it would have performed, without manual chart-by-chart checking. Done honestly it filters bad ideas fast; done carelessly it produces beautiful, misleading results.',
      deep: 'Automated backtesting lets you test thousands of historical trades in seconds, measuring win rate, drawdown, and expectancy. Its value is speed and objectivity — but it is riddled with traps: curve-fitting (optimising until the past looks perfect), survivorship and look-ahead bias, ignoring spread/slippage/fees, and repainting indicators. A backtest is a hypothesis about the past, not a forecast. The disciplined workflow adds out-of-sample and walk-forward testing plus forward (paper) testing before any live capital, because a strategy that only shines on the data it was tuned to is worthless.',
    },
    marketContext: 'A Gold strategy showing a flawless historical curve often collapses in walk-forward testing, revealing it was curve-fit rather than genuinely robust.',
    desiredOutcome: 'use automated backtesting to reject bad ideas while guarding against curve-fitting with out-of-sample and forward tests',
    relevanceTags: ['automated-backtesting', 'automation', 'validation', 'intermediate'],
    commonMistakes: ['optimising a strategy until the backtest is perfect and mistaking that for an edge'],
    misconceptions: ['that a great backtest guarantees future profit'],
    prerequisites: ['backtesting'], nextSteps: ['trading-bots', 'api-trading'], related: ['pine-script', 'system-trading'],
    followups: ['trading-bots'],
    riskNote: 'A backtest describes the past, not the future — require out-of-sample and forward validation before going live.',
    seo: { title: 'Automated Backtesting Explained', description: 'How automated backtesting validates strategies, the biases that make it misleading, and why walk-forward testing matters.', keywords: ['automated backtesting', 'backtesting strategy', 'walk forward testing', 'curve fitting'] },
  }),
];
