// functions/knowledge/planning/concepts.js
// CATEGORY: planning (NEW, Phase 2) — trading plans, roadmaps, account growth.

export const PLANNING_CONCEPTS = [
  {
    id: 'trading-plan', category: 'planning', topic: 'Trading Plan', level: 'beginner',
    title: 'Building a Trading Plan', intent: 'strategy',
    concepts: ['trading plan', 'rules', 'process', 'structure', 'planning'],
    questionPatterns: ['what is a trading plan', 'how do i make a trading plan', 'what should a trading plan include', 'why do i need a trading plan', 'trading plan template'],
    canonical: {
      short: 'A trading plan is your written rulebook: what you trade, when, your setup, your risk per trade, and your daily limits. Without it you are improvising — and improvisation is where discipline quietly dies.',
      deep: 'A usable plan is short and specific: instruments and sessions, the exact setup and confirmation, fixed risk (e.g. 1%), daily/weekly loss limits, and a review routine. Its power is removing in-the-moment decisions where emotion takes over — if a trade is not in the plan, you do not take it. Write it, trade only what it allows, and update it from journaled evidence, not from a single bad day.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade from a written rulebook, not improvisation',
    relevanceTags: ['planning', 'trading plan'],
    guidance: { traderProblem: true },
    recommendedTools: ['journal'],
    related: ['trading-journal', 'edge-definition', 'trading-routine'], prerequisites: ['risk-per-trade'],
    nextSteps: ['trading-journal'], followups: ['beginner-roadmap', 'edge-definition'],
    riskNote: 'If a trade is not in the plan, it is not a trade.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'beginner-roadmap', category: 'planning', topic: 'Beginner Roadmap', level: 'beginner',
    title: 'Beginner Trading Roadmap', intent: 'career',
    concepts: ['beginner', 'roadmap', 'start', 'learning path', 'planning'],
    questionPatterns: ['how should a beginner start trading', 'beginner trading roadmap', 'what should i learn first in trading', 'how do i start trading from scratch', 'trading roadmap for beginners'],
    canonical: {
      short: 'Beginners should learn in order: market basics → risk management → one simple setup → demo practice → tiny live size. Most blow up by skipping risk and going live big — the roadmap exists to stop that.',
      deep: 'Start with how markets and orders work, then master risk per trade and position sizing before any strategy, because survival comes first. Pick one simple setup (e.g. trend continuation at a level), practise it on demo until it is repeatable, then go live with tiny size to learn real emotion cheaply. Journal from day one. Resist the urge to chase signals or jump strategies — depth in one approach beats shallow exposure to many.',
    },
    responseObjective: 'mentor', desiredOutcome: 'follow a survival-first learning order',
    relevanceTags: ['planning', 'roadmap', 'beginner'],
    guidance: { traderProblem: true },
    related: ['intermediate-roadmap', 'demo-vs-live', 'risk-per-trade'], prerequisites: [],
    nextSteps: ['intermediate-roadmap'], followups: ['risk-per-trade', 'trading-plan'],
    riskNote: 'Learn risk before strategy and go live small — survival first.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'intermediate-roadmap', category: 'planning', topic: 'Intermediate Roadmap', level: 'intermediate',
    title: 'Intermediate Trading Roadmap', intent: 'career',
    concepts: ['intermediate', 'roadmap', 'consistency', 'learning path', 'planning'],
    questionPatterns: ['intermediate trading roadmap', 'how do i get better after the basics', 'what to learn at intermediate level', 'how to become consistent trader', 'next steps after beginner trading'],
    canonical: {
      short: 'The intermediate stage is about consistency: refine one edge, journal every trade, fix your repeating mistake, and keep risk fixed. The goal is a flat-to-up equity curve with disciplined execution, not bigger profits yet.',
      deep: 'Once basics and survival are in place, the work shifts from learning more setups to executing one well: track results, find your single most costly repeating error (oversizing, early exits, revenge trades), and remove it. Deepen market structure and trade management, but resist adding complexity. Profitability at this stage is a by-product of consistency — prove a stable process over many trades before thinking about scaling size.',
    },
    responseObjective: 'mentor', desiredOutcome: 'convert basics into consistent execution',
    relevanceTags: ['planning', 'roadmap', 'intermediate'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['beginner-roadmap', 'advanced-roadmap', 'consistency'], prerequisites: ['beginner-roadmap'],
    nextSteps: ['advanced-roadmap'], followups: ['consistency', 'trading-journal'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'advanced-roadmap', category: 'planning', topic: 'Advanced Roadmap', level: 'advanced',
    title: 'Advanced Trading Roadmap', intent: 'career',
    concepts: ['advanced', 'roadmap', 'scaling', 'mastery', 'planning'],
    questionPatterns: ['advanced trading roadmap', 'how do i go from consistent to professional', 'what do advanced traders focus on', 'how to scale as a trader', 'next level trading'],
    canonical: {
      short: 'Advanced traders scale what already works: increase size gradually on a proven edge, manage psychology at larger stakes, and possibly diversify setups or pursue funded capital. The edge stops being the problem — execution at scale does.',
      deep: 'With a documented, consistently profitable process, the advanced focus is controlled scaling: raise risk in small steps tied to evidence, manage the heavier emotions that come with bigger size, and protect the downside even harder as the numbers grow. Some add a second uncorrelated setup or pursue prop capital to scale without personal risk. The failure mode here is ego — letting size outrun discipline — so process and review matter more than ever.',
    },
    responseObjective: 'mentor', desiredOutcome: 'scale a proven edge while managing psychology',
    relevanceTags: ['planning', 'roadmap', 'advanced'],
    guidance: { traderProblem: true },
    related: ['intermediate-roadmap', 'risk-scaling', 'prop-scaling'], prerequisites: ['intermediate-roadmap', 'risk-scaling'],
    nextSteps: ['account-growth'], followups: ['prop-scaling', 'trader-mindset'],
    riskNote: 'At scale, ego is the risk — keep size tied to proven results.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'account-growth', category: 'planning', topic: 'Account Growth', level: 'intermediate',
    title: 'Growing a Trading Account', intent: 'career',
    concepts: ['account growth', 'compounding', 'realistic returns', 'patience', 'planning'],
    questionPatterns: ['how do i grow my trading account', 'how fast can i grow an account', 'realistic account growth trading', 'how to grow a small account', 'account growth strategy'],
    canonical: {
      short: 'Accounts grow from consistent small-percentage gains compounded over time, not from home-run trades. Trying to grow a small account fast by over-risking is the single most common way it goes to zero.',
      deep: 'Realistic growth comes from protecting capital and letting a modest edge compound: steady monthly percentages add up powerfully over a year, while one oversized trade can erase months. Small accounts feel slow, which tempts over-leverage — resist it; the percentage matters, not the dollar amount. If you need more capital faster, the disciplined route is a funded/prop account, not bigger risk on a small balance.',
    },
    responseObjective: 'mentor', desiredOutcome: 'grow via compounding, not over-risking',
    relevanceTags: ['planning', 'growth', 'compounding'],
    guidance: { traderProblem: true },
    related: ['compounding', 'risk-scaling', 'prop-firm-basics'], prerequisites: ['risk-per-trade'],
    nextSteps: ['compounding'], followups: ['risk-scaling', 'prop-firm-basics'],
    riskNote: 'Over-risking a small account to grow it fast is how it reaches zero.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'compounding', category: 'planning', topic: 'Compounding', level: 'intermediate',
    title: 'The Power of Compounding', intent: 'career',
    concepts: ['compounding', 'growth', 'patience', 'math', 'planning'],
    questionPatterns: ['what is compounding in trading', 'how does compounding work', 'why is compounding powerful', 'compounding a trading account', 'how to compound trading profits'],
    canonical: {
      short: 'Compounding means each period\'s gains grow the base for the next, so steady returns snowball over time. Its enemy is the drawdown: a big loss resets the snowball, which is why capital protection is what makes compounding work.',
      deep: 'A consistent few percent per month, reinvested, grows far larger over a year than chasing big erratic wins — but only if drawdowns stay shallow, because losses compound against you too (a 50% loss needs 100% to recover). So compounding is really a discipline story: protect capital, keep returns steady, and let math do the heavy lifting. Patience is the strategy; the boring path compounds, the exciting one resets.',
    },
    responseObjective: 'educate', desiredOutcome: 'let steady returns compound by protecting drawdown',
    relevanceTags: ['planning', 'compounding'],
    guidance: { tradeProblem: true },
    related: ['account-growth', 'max-drawdown', 'account-preservation'], prerequisites: ['account-preservation'],
    nextSteps: ['account-growth'], followups: ['max-drawdown', 'risk-scaling'],
    riskNote: 'Deep drawdowns reset compounding — keep losses shallow.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'goal-setting', category: 'planning', topic: 'Trading Goals', level: 'beginner',
    title: 'Setting Realistic Trading Goals', intent: 'career',
    concepts: ['goals', 'process goals', 'expectations', 'realistic', 'planning'],
    questionPatterns: ['how do i set trading goals', 'what are realistic trading goals', 'should i set profit goals', 'trading goal setting', 'how much can i realistically make trading'],
    canonical: {
      short: 'Set process goals you control (follow the plan, journal every trade, cap risk) rather than profit targets you do not. Dollar goals create pressure that breaks discipline; process goals build the consistency that produces the dollars.',
      deep: 'Outcome goals like "make $X this month" push you to force trades and over-risk when the market is not offering setups. Process goals — execute your checklist, respect limits, review weekly — are fully in your control and directly produce good outcomes over time. Track adherence, not just P&L. Realistic expectations also matter: steady percentage growth, not life-changing money in weeks, keeps you patient and in the game.',
    },
    responseObjective: 'mentor', desiredOutcome: 'set controllable process goals over profit targets',
    relevanceTags: ['planning', 'goals'],
    guidance: { traderProblem: true },
    related: ['trading-plan', 'process-focus', 'account-growth'], prerequisites: [],
    nextSteps: ['trading-plan'], followups: ['process-focus', 'account-growth'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
