// functions/knowledge/coaching/concepts.js
// CATEGORY: coaching (NEW, Phase 6) — pro development, preparation, deliberate practice.

export const COACHING_CONCEPTS = [
  {
    id: 'pre-trade-analysis', category: 'coaching', topic: 'Pre-Trade Analysis', level: 'intermediate',
    title: 'Pre-Trade Analysis', intent: 'strategy',
    concepts: ['pre-trade', 'preparation', 'checklist', 'analysis'],
    questionPatterns: ['what is pre-trade analysis', 'what to check before a trade', 'how to prepare for a trade', 'pre-trade checklist', 'pre-trade analysis explained'],
    canonical: {
      short: 'Pre-trade analysis is the work you do before risking money: confirm bias, level, trigger, stop, and reward. If any box is missing, the honest answer is "no trade" — and that is a winning decision too.',
      deep: 'A strong pre-trade routine is a short checklist run every time: is there a higher-timeframe bias, am I at a real level, is my trigger present, where is invalidation, and is the reward worth the risk? Doing this before entry removes impulse from the moment that matters most. The discipline of walking away from incomplete setups is exactly what separates consistent traders from busy ones.',
    },
    responseObjective: 'mentor', desiredOutcome: 'gate every entry through pre-trade checks',
    relevanceTags: ['coaching', 'preparation'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trade',
    related: ['checklist', 'post-trade-review', 'trade-assessment'], prerequisites: ['checklist'],
    nextSteps: ['post-trade-review'], followups: ['trade-assessment', 'entry-models'],
    riskNote: 'A missing checklist box means no trade — that is a winning decision.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'post-trade-review', category: 'coaching', topic: 'Post-Trade Review', level: 'intermediate',
    title: 'Post-Trade Review', intent: 'psychology',
    concepts: ['post-trade', 'review', 'journal', 'improvement'],
    questionPatterns: ['what is a post-trade review', 'how to review a trade', 'what to review after a trade', 'post-trade analysis', 'how to learn from my trades'],
    canonical: {
      short: 'A post-trade review judges the decision, not just the result: did you follow your plan and manage risk, regardless of whether it won? This is where real improvement happens — outcomes are partly luck, execution is fully yours.',
      deep: 'After each trade, log the setup, your execution, and your emotions, then label it a good or poor decision independent of profit. A losing trade with perfect execution is a win for your process; a winning trade you gambled on is a warning. Reviewing decision quality over a sample trains genuine judgement and filters luck out of your feedback loop — the fastest path to consistency.',
    },
    responseObjective: 'mentor', desiredOutcome: 'learn from decision quality, not just outcomes',
    relevanceTags: ['coaching', 'review'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['pre-trade-analysis', 'decision-quality', 'trading-journal'], prerequisites: ['trading-journal'],
    nextSteps: ['deliberate-practice'], followups: ['decision-quality', 'monthly-review'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'professional-habits', category: 'coaching', topic: 'Professional Trading Habits', level: 'advanced',
    title: 'Professional Trading Habits', intent: 'psychology',
    concepts: ['professional habits', 'discipline', 'routine', 'consistency'],
    questionPatterns: ['what are professional trading habits', 'how do professional traders behave', 'habits of profitable traders', 'how to trade like a professional', 'professional trader habits'],
    canonical: {
      short: 'Professional habits are boring on purpose: fixed risk, a daily routine, honest journaling, and emotional detachment from any single trade. Professionals protect process and capital first; profit is the by-product.',
      deep: 'The pros are not more exciting — they are more consistent. They risk the same small amount every trade, prepare and review daily, never revenge trade, and judge themselves on execution rather than P&L. They treat trading as a probabilistic business, accept losses as a cost, and protect capital relentlessly. These habits, repeated for years, are what separate professionals from talented amateurs who blow up.',
    },
    responseObjective: 'mentor', desiredOutcome: 'adopt the boring, repeatable habits of professionals',
    relevanceTags: ['coaching', 'habits', 'professional'],
    guidance: { traderProblem: true },
    related: ['consistency-system', 'trader-mindset', 'habit-building'], prerequisites: ['trading-discipline'],
    nextSteps: ['consistency-system'], followups: ['trader-mindset', 'edge-building-process'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'edge-building-process', category: 'coaching', topic: 'Building an Edge', level: 'advanced',
    title: 'The Process of Building an Edge', intent: 'strategy',
    concepts: ['edge building', 'testing', 'refinement', 'process'],
    questionPatterns: ['how do i build a trading edge', 'process of building an edge', 'how to develop a profitable strategy', 'how to refine my edge', 'building an edge step by step'],
    canonical: {
      short: 'Building an edge is a loop: define a specific setup, test it on history and demo, trade it small with fixed risk, journal honestly, then refine one variable at a time. Edges are engineered through iteration, not found.',
      deep: 'Start narrow — one defined setup with clear entry, exit, and risk. Backtest it for positive expectancy, forward-test on demo, then trade live small while journaling. Review the data to find the one weak variable, adjust it, and re-test. This deliberate loop, not strategy-hopping, is how a real edge is built and trusted. Resist adding complexity; depth in one process beats shallow exposure to many.',
    },
    responseObjective: 'mentor', desiredOutcome: 'engineer an edge through a test-refine loop',
    relevanceTags: ['coaching', 'edge', 'process'],
    guidance: { traderProblem: true },
    related: ['edge-definition', 'backtesting', 'consistency-system'], prerequisites: ['edge-definition', 'backtesting'],
    nextSteps: ['consistency-system'], followups: ['backtesting', 'win-rate-vs-rr'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'consistency-system', category: 'coaching', topic: 'Consistency System', level: 'advanced',
    title: 'Building a Consistency System', intent: 'psychology',
    concepts: ['consistency system', 'process', 'repeatability', 'discipline'],
    questionPatterns: ['how do i become consistent', 'what is a consistency system', 'how to trade consistently', 'system for consistency', 'how to be a consistent trader'],
    canonical: {
      short: 'A consistency system makes the right action the default: fixed risk, a pre-trade checklist, defined sessions, a daily routine, and weekly review. You do not rise to your goals — you fall to your systems, so build them deliberately.',
      deep: 'Consistency is engineered, not willed. Tie each good behaviour to a trigger: a checklist to opening your platform, fixed risk to every order, a journal entry to closing each trade, a review to each weekend. When the disciplined action is the path of least resistance, you behave consistently even when tired or emotional — and consistent behaviour is what finally produces a consistent equity curve.',
    },
    responseObjective: 'mentor', desiredOutcome: 'engineer consistency through systems, not willpower',
    relevanceTags: ['coaching', 'consistency', 'system'],
    guidance: { traderProblem: true },
    related: ['professional-habits', 'consistency', 'habit-building'], prerequisites: ['consistency'],
    nextSteps: ['deliberate-practice'], followups: ['professional-habits', 'trading-plan'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'deliberate-practice', category: 'coaching', topic: 'Deliberate Practice', level: 'advanced',
    title: 'Deliberate Practice for Traders', intent: 'psychology',
    concepts: ['deliberate practice', 'improvement', 'feedback', 'skill'],
    questionPatterns: ['what is deliberate practice in trading', 'how to practice trading effectively', 'how do i improve fastest as a trader', 'deliberate practice explained', 'how to get better at trading'],
    canonical: {
      short: 'Deliberate practice is focused, feedback-driven repetition aimed at one weakness at a time — not just screen hours. Reviewing your journal to fix a specific recurring error improves you faster than taking more trades.',
      deep: 'Volume of trades is not practice; targeted improvement is. Identify your single most costly habit from journal data, design a concrete rule to fix it, and focus entirely on that for a stretch while measuring adherence. Then move to the next weakness. This tight loop of focus, feedback, and correction is how skill compounds — most traders plateau because they repeat the same mistakes instead of isolating and removing them.',
    },
    responseObjective: 'mentor', desiredOutcome: 'improve by fixing one weakness at a time',
    relevanceTags: ['coaching', 'practice', 'improvement'],
    guidance: { traderProblem: true },
    related: ['post-trade-review', 'performance-analysis', 'screen-time-quality'], prerequisites: ['trading-journal'],
    nextSteps: ['screen-time-quality'], followups: ['performance-analysis', 'decision-quality'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'mental-capital', category: 'coaching', topic: 'Mental Capital', level: 'intermediate',
    title: 'Protecting Your Mental Capital', intent: 'psychology',
    concepts: ['mental capital', 'energy', 'tilt', 'focus'],
    questionPatterns: ['what is mental capital', 'how to protect mental energy trading', 'why do i make mistakes when tired', 'mental capital in trading', 'how to avoid tilt'],
    canonical: {
      short: 'Mental capital is your finite focus and emotional energy — just as real as money. Trading tired, stressed, or on tilt spends it recklessly, so protecting it (rest, limits, stepping away) protects your account.',
      deep: 'Decision quality degrades when you are fatigued, frustrated, or after a big win or loss. Guarding mental capital means trading only when sharp, honouring a daily loss limit, stepping away after emotional trades, and not forcing setups out of boredom. The best traders manage their state as carefully as their risk, because a depleted mind makes the exact errors that empty accounts.',
    },
    responseObjective: 'mentor', desiredOutcome: 'protect focus and state to protect the account',
    relevanceTags: ['coaching', 'mental', 'state'],
    guidance: { traderProblem: true },
    related: ['emotional-control', 'revenge-trading', 'daily-loss-limit'], prerequisites: ['trading-psychology'],
    nextSteps: ['professional-habits'], followups: ['emotional-control', 'daily-loss-limit'],
    riskNote: 'A depleted mind makes account-ending errors — step away when off.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'screen-time-quality', category: 'coaching', topic: 'Quality Over Screen Time', level: 'intermediate',
    title: 'Quality Over Screen Time', intent: 'psychology',
    concepts: ['screen time', 'patience', 'overtrading', 'focus'],
    questionPatterns: ['how many hours should i trade', 'is more screen time better', 'why am i overtrading from watching charts', 'quality vs quantity trading', 'how much should i watch the charts'],
    canonical: {
      short: 'More screen time is not more edge — it usually means more overtrading. A focused hour in your killzone, trading only valid setups, beats staring at charts all day and forcing trades from boredom.',
      deep: 'Watching every tick tempts you into low-quality trades and drains mental capital. Define the few hours when your setups actually appear, prepare beforehand, act only on checklist-valid signals, then step away. Professionals are often less glued to the screen than beginners because they wait for quality. Reframe inactivity as discipline — protecting both your capital and your focus for the trades that matter.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade focused windows, not all-day boredom',
    relevanceTags: ['coaching', 'focus', 'patience'],
    guidance: { traderProblem: true },
    related: ['overtrading', 'patience', 'mental-capital'], prerequisites: ['patience'],
    nextSteps: ['professional-habits'], followups: ['overtrading', 'killzones'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
