// functions/knowledge/indicators/concepts.js
// HOT-SEARCH ARTICLES — TECHNICAL INDICATORS (category: indicators)
// Each concept IS an auto-integrating article: beginner (canonical.short), advanced
// (canonical.deep), mistakes, misconceptions, example (marketContext), related/next
// (chips + learning path), riskNote, FAQ (questionPatterns), SEO metadata. Flows
// through the existing graph/retrieval/chips/University/analytics — no new logic.

const F = (o) => ({
  level: 'beginner', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const INDICATORS_CONCEPTS = [
  F({
    id: 'rsi-indicator', category: 'indicators', topic: 'RSI', title: 'RSI (Relative Strength Index) Explained',
    concepts: ['rsi', 'indicator', 'momentum'],
    questionPatterns: ['what is rsi', 'how does rsi work', 'how to use rsi indicator', 'what does rsi 70 mean', 'is rsi good for beginners'],
    canonical: {
      short: 'RSI is a momentum indicator from 0–100 that shows whether price has moved up or down too fast. Above 70 is often called "overbought", below 30 "oversold" — but in a strong trend RSI can stay extreme for a long time, so it confirms, it does not predict.',
      deep: 'The Relative Strength Index measures the speed of recent gains versus losses on a 0–100 scale (default 14 periods). Classic reads: >70 overbought, <30 oversold, and "divergence" (price makes a new high but RSI does not) hints momentum is fading. The trap is treating 70/30 as automatic sell/buy signals — in a strong uptrend RSI sits above 70 for weeks. Used well, RSI confirms structure and flags divergence; used alone as a reversal trigger, it bleeds an account.',
    },
    marketContext: 'In a strong Gold uptrend, RSI can hold above 70 for days while price keeps rising — shorting it "because it\'s overbought" is a classic loss.',
    desiredOutcome: 'use RSI to confirm momentum/divergence, not as a standalone reversal signal',
    relevanceTags: ['rsi', 'indicator', 'beginner'],
    commonMistakes: ['selling just because RSI is above 70 in a strong trend'],
    misconceptions: ['that RSI predicts reversals on its own'],
    prerequisites: ['technical-analysis-basics'], nextSteps: ['macd-indicator', 'indicator-combination'], related: ['moving-averages', 'what-is-a-trend'],
    followups: ['macd-indicator'],
    riskNote: 'No indicator is a holy grail — RSI confirms, it does not guarantee a turn.',
    seo: { title: 'RSI Indicator Explained for Beginners (2025)', description: 'What RSI is, how the 70/30 levels and divergence work, and the mistake that costs beginners money.', keywords: ['rsi indicator', 'rsi explained', 'overbought oversold', 'rsi divergence'] },
  }),
  F({
    id: 'macd-indicator', category: 'indicators', topic: 'MACD', title: 'MACD Explained',
    concepts: ['macd', 'indicator', 'momentum'],
    questionPatterns: ['what is macd', 'how does macd work', 'how to use macd', 'what is macd crossover', 'macd for beginners'],
    canonical: {
      short: 'MACD shows momentum by comparing two moving averages — when its line crosses above the signal line, momentum is turning up; below, turning down. The histogram shows how strong that momentum is. It lags price, so it confirms moves rather than calling tops and bottoms.',
      deep: 'MACD (Moving Average Convergence Divergence) subtracts a slow EMA from a fast EMA to make the MACD line, then plots a signal line (its own EMA) and a histogram of the gap. Bullish/bearish crossovers and MACD divergence with price are the common reads. Because it is built from moving averages it lags — great for confirming an established trend, poor for fast reversals. Pair it with structure; do not trade crossovers blindly in a range, where they whipsaw.',
    },
    marketContext: 'In a sideways range, MACD crossovers flip back and forth and produce a string of small losses — it works best in a trending market.',
    desiredOutcome: 'use MACD crossovers/divergence to confirm trend momentum, avoid it in ranges',
    relevanceTags: ['macd', 'indicator', 'beginner'],
    commonMistakes: ['trading every MACD crossover, including in choppy ranges'],
    misconceptions: ['that a MACD crossover is a guaranteed entry signal'],
    prerequisites: ['moving-averages'], nextSteps: ['indicator-combination'], related: ['rsi-indicator', 'what-is-a-trend'],
    followups: ['indicator-combination'],
    riskNote: 'MACD lags — it confirms momentum, it does not predict the turn.',
    seo: { title: 'MACD Indicator Explained Simply (Beginner Guide)', description: 'How MACD, the signal line, histogram, crossovers and divergence work — and when MACD fails.', keywords: ['macd indicator', 'macd explained', 'macd crossover', 'macd divergence'] },
  }),
  F({
    id: 'moving-averages', category: 'indicators', topic: 'Moving Averages', title: 'Moving Averages Explained',
    concepts: ['moving-average', 'indicator', 'trend'],
    questionPatterns: ['what is a moving average', 'how to use moving averages', 'what is the 200 ema', 'sma vs ema', 'best moving average for trading'],
    canonical: {
      short: 'A moving average smooths price into a single line that shows the trend direction. Price above a rising average = uptrend bias; below a falling one = downtrend. Common ones are the 20, 50, and 200 — the 200 is widely watched as the big-picture trend line.',
      deep: 'A moving average averages the last N closes (SMA = simple, EMA = exponential, weighting recent prices more). Traders use them three ways: as a trend filter (only buy above a rising 200), as dynamic support/resistance (price reacts to the 20/50), and as crossovers (fast crossing slow). They lag by design, so they define context rather than precise entries. The 200-day/EMA is the most-watched line in any market, Gold included.',
    },
    marketContext: 'Many traders only take Gold longs while price is above the rising 200 EMA, using it as a simple trend filter.',
    desiredOutcome: 'use moving averages as a trend filter and dynamic support/resistance',
    relevanceTags: ['moving-average', 'indicator', 'beginner'],
    commonMistakes: ['buying every touch of a moving average with no other confirmation'],
    misconceptions: ['that one "magic" moving average setting beats the rest'],
    prerequisites: ['what-is-a-trend'], nextSteps: ['rsi-indicator', 'macd-indicator'], related: ['support-resistance', 'indicator-combination'],
    followups: ['rsi-indicator'],
    riskNote: 'Moving averages lag — they give context, not exact entries.',
    seo: { title: 'Moving Averages Explained (SMA vs EMA, 200 EMA)', description: 'How moving averages show trend, act as support/resistance, and how to use the 20/50/200.', keywords: ['moving averages', 'sma vs ema', '200 ema', 'moving average strategy'] },
  }),
  F({
    id: 'bollinger-bands', category: 'indicators', topic: 'Bollinger Bands', title: 'Bollinger Bands Explained',
    concepts: ['bollinger-bands', 'indicator', 'volatility'],
    questionPatterns: ['what are bollinger bands', 'how to use bollinger bands', 'what does it mean when bands squeeze', 'bollinger band strategy', 'are bollinger bands good'],
    canonical: {
      short: 'Bollinger Bands wrap price in a moving average plus two volatility bands. When the bands squeeze tight, volatility is low and a big move often follows; when price rides the upper band, the trend is strong (not an automatic "sell"). They measure volatility, not direction.',
      deep: 'Bollinger Bands plot a 20-period moving average with bands set two standard deviations away, so they widen in volatility and narrow when it falls. A "squeeze" (very narrow bands) warns that a volatility expansion may be coming, in either direction. Price touching a band is not a reversal signal — in a strong trend price "walks the band". Use the squeeze for breakout context and the middle band as a trend reference, never the bands alone as buy/sell triggers.',
    },
    marketContext: 'Before a major Gold breakout, the Bollinger Bands often squeeze tight for hours, then expand sharply as the move begins.',
    desiredOutcome: 'read band squeeze/expansion as volatility context, not direction',
    relevanceTags: ['bollinger-bands', 'indicator', 'beginner'],
    commonMistakes: ['shorting a band touch in a strong trend that is "walking the band"'],
    misconceptions: ['that a touch of the upper band means sell'],
    prerequisites: ['volatility-basics'], nextSteps: ['atr-indicator'], related: ['breakout-trading', 'indicator-combination'],
    followups: ['atr-indicator'],
    riskNote: 'Bands show volatility, not direction — a band touch is not a signal.',
    seo: { title: 'Bollinger Bands Explained (Squeeze & Strategy)', description: 'How Bollinger Bands measure volatility, what a squeeze means, and the band-touch mistake.', keywords: ['bollinger bands', 'bollinger band squeeze', 'bollinger strategy', 'volatility indicator'] },
  }),
  F({
    id: 'fibonacci-retracement', category: 'indicators', topic: 'Fibonacci Retracement', title: 'Fibonacci Retracement Explained',
    concepts: ['fibonacci', 'retracement', 'levels'],
    questionPatterns: ['what is fibonacci retracement', 'how to use fibonacci', 'what is the golden ratio in trading', 'how to draw fibonacci', 'is fibonacci useful in trading'],
    canonical: {
      short: 'Fibonacci retracement marks levels (38.2%, 50%, 61.8%) where a pullback inside a trend often pauses before continuing. You draw it from a swing low to a swing high; the 61.8% "golden" level is the most watched. It shows where to look for entries, not a guaranteed bounce.',
      deep: 'Fibonacci retracement divides a price swing into ratios (23.6, 38.2, 50, 61.8, 78.6%) that traders watch for pullback entries within a trend. Drawn correctly from a clear swing low to high (or vice versa), the 50–61.8% zone is where trend-continuation entries often set up, especially when it lines up with structure or a moving average (confluence). It works because so many traders watch it — but it is a zone of interest, not magic; always pair it with confirmation and a stop beyond the level.',
    },
    marketContext: 'A Gold pullback into the 61.8% retracement that also sits on prior support is a textbook confluence area traders watch for continuation.',
    desiredOutcome: 'use fib levels as pullback zones, confirmed by structure (confluence)',
    relevanceTags: ['fibonacci', 'levels', 'beginner'],
    commonMistakes: ['buying a fib level blindly without confirmation or a stop'],
    misconceptions: ['that price must bounce exactly at a fibonacci level'],
    prerequisites: ['support-resistance'], nextSteps: ['confluence'], related: ['pullback-trading', 'what-is-a-trend'],
    followups: ['pullback-trading'],
    riskNote: 'A fib level is a zone of interest, not a guaranteed bounce — wait for confirmation.',
    seo: { title: 'Fibonacci Retracement Explained for Beginners', description: 'How to draw Fibonacci, what 61.8% means, and how to use fib levels with confluence.', keywords: ['fibonacci retracement', 'fibonacci trading', 'golden ratio', '61.8 fibonacci'] },
  }),
  F({
    id: 'atr-indicator', category: 'indicators', topic: 'ATR', title: 'ATR (Average True Range) Explained',
    concepts: ['atr', 'indicator', 'volatility', 'risk'],
    questionPatterns: ['what is atr', 'how to use atr indicator', 'how to set stop loss with atr', 'what does atr measure', 'atr for stop loss'],
    canonical: {
      short: 'ATR measures how much an instrument typically moves per period — its volatility in price terms. Its best use is sizing your stop loss: a wider ATR means you need a wider stop (and smaller position) so normal noise does not stop you out.',
      deep: 'Average True Range averages the true range (the full high-low move including gaps) over N periods, giving a pure volatility number in the instrument\'s price units. It does not show direction — its power is risk sizing: set the stop a multiple of ATR beyond entry (e.g. 1.5× ATR) so it sits outside normal noise, then size the position so that distance is still only 1–2% of the account. ATR is why the same pip stop is too tight on Gold and too wide on a quiet pair.',
    },
    marketContext: 'If Gold\'s ATR is $25, a $5 stop is inside the noise and will get tagged — ATR tells you to give the trade room and size down.',
    desiredOutcome: 'use ATR to set volatility-appropriate stops and position size',
    relevanceTags: ['atr', 'volatility', 'risk', 'beginner'],
    commonMistakes: ['using a fixed pip stop regardless of the instrument\'s ATR'],
    misconceptions: ['that ATR shows direction (it only shows volatility)'],
    prerequisites: ['volatility-basics'], nextSteps: ['stop-loss-basics', 'position-sizing'], related: ['bollinger-bands', 'pips-to-money'],
    followups: ['stop-loss-basics'],
    riskNote: 'Match your stop to ATR — too tight a stop in high ATR is a guaranteed stop-out.',
    seo: { title: 'ATR Indicator Explained (Stop Loss & Volatility)', description: 'What ATR measures and how to use it to size stops and positions to volatility.', keywords: ['atr indicator', 'average true range', 'atr stop loss', 'volatility stop'] },
  }),
  F({
    id: 'vwap-indicator', category: 'indicators', topic: 'VWAP', title: 'VWAP Explained',
    concepts: ['vwap', 'indicator', 'intraday'],
    questionPatterns: ['what is vwap', 'how to use vwap', 'what does vwap mean in trading', 'is vwap good for day trading', 'vwap strategy'],
    canonical: {
      short: 'VWAP (Volume-Weighted Average Price) is the average price weighted by volume across the day — it shows the "fair value" intraday traders anchor to. Price above VWAP = buyers in control intraday; below = sellers. Day traders use it as a dynamic intraday reference, not a swing tool.',
      deep: 'VWAP resets each session and weights every price by the volume traded there, so it reflects where most business was done. Institutions benchmark fills against it, which makes it a magnet: intraday pullbacks to VWAP in an uptrend are common continuation spots, and being above/below VWAP frames intraday bias. It is an intraday tool (it resets daily) and depends on real volume, so it suits index/stock day trading more than thin instruments. Pair it with structure, not as a lone signal.',
    },
    marketContext: 'An index day trader who only longs while price holds above the rising VWAP uses it as a simple intraday trend filter.',
    desiredOutcome: 'use VWAP as an intraday bias/continuation reference, daily-reset',
    relevanceTags: ['vwap', 'indicator', 'intraday'],
    commonMistakes: ['using VWAP for swing trades when it resets every session'],
    misconceptions: ['that VWAP works the same as a moving average across days'],
    prerequisites: ['moving-averages'], nextSteps: ['indicator-combination'], related: ['day-trading', 'support-resistance'],
    followups: ['indicator-combination'],
    riskNote: 'VWAP is intraday only and needs real volume — it is not a swing tool.',
    seo: { title: 'VWAP Explained for Day Traders', description: 'What VWAP is, why institutions watch it, and how to use it for intraday bias.', keywords: ['vwap', 'vwap indicator', 'vwap day trading', 'volume weighted average price'] },
  }),
  F({
    id: 'stochastic-indicator', category: 'indicators', topic: 'Stochastic', title: 'Stochastic Oscillator Explained',
    concepts: ['stochastic', 'indicator', 'momentum'],
    questionPatterns: ['what is the stochastic indicator', 'how to use stochastic', 'what does stochastic 80 mean', 'stochastic vs rsi', 'stochastic strategy'],
    canonical: {
      short: 'The Stochastic oscillator (0–100) shows where price closed relative to its recent range — high (>80) means closing near the top, low (<20) near the bottom. Like RSI it flags overbought/oversold and divergence, but it is faster and noisier, so it needs trend context.',
      deep: 'Stochastic compares the close to the high-low range over N periods, plotting %K and a slower %D signal line. Crossovers in the <20 or >80 zones, and divergence with price, are the common reads. It is more sensitive (and whippier) than RSI, generating more signals and more false ones. Best in ranges or for spotting momentum exhaustion within a trend; in a strong trend it pins to an extreme just like RSI, so never fade it blindly.',
    },
    marketContext: 'In a tight range, Stochastic turning up from below 20 near support is a cleaner read than in a strong trend where it stays pinned high.',
    desiredOutcome: 'use Stochastic for range momentum/divergence, with trend context',
    relevanceTags: ['stochastic', 'indicator', 'beginner'],
    commonMistakes: ['fading every overbought stochastic reading in a strong trend'],
    misconceptions: ['that stochastic and RSI give identical signals'],
    prerequisites: ['rsi-indicator'], nextSteps: ['indicator-combination'], related: ['range-market', 'rsi-indicator'],
    followups: ['indicator-combination'],
    riskNote: 'Stochastic is fast and noisy — confirm with structure before acting.',
    seo: { title: 'Stochastic Oscillator Explained (vs RSI)', description: 'How the stochastic oscillator works, the 80/20 levels, and how it differs from RSI.', keywords: ['stochastic indicator', 'stochastic oscillator', 'stochastic vs rsi', 'stochastic strategy'] },
  }),
  F({
    id: 'indicator-combination', category: 'indicators', topic: 'Best Indicator Combination', title: 'Best Indicator Combination',
    concepts: ['indicators', 'confluence', 'strategy'],
    questionPatterns: ['what is the best indicator combination', 'which indicators work well together', 'how many indicators should i use', 'best indicators for beginners', 'do i need indicators to trade'],
    canonical: {
      short: 'The best combination is a few indicators that measure DIFFERENT things — e.g. one for trend (moving average), one for momentum (RSI/MACD), and one for volatility (ATR). Stacking five momentum indicators just gives you the same signal five times. Less is more, and structure beats indicators.',
      deep: 'A clean toolkit picks one indicator per job so they confirm rather than repeat: a moving average for trend direction, RSI or MACD for momentum/divergence, and ATR for stop sizing. The classic beginner error is "indicator soup" — many overlapping oscillators that all say the same thing, creating false confidence. Even better, treat indicators as secondary to price structure (trend, support/resistance); they confirm a decision the chart already suggests. Two or three complementary tools, used with structure, beat a screen full of lines.',
    },
    marketContext: 'A simple, durable setup: trade with the 200 EMA trend, enter on a pullback to support with RSI turning up, and size the stop by ATR.',
    desiredOutcome: 'combine one trend + one momentum + one volatility tool, led by structure',
    relevanceTags: ['indicators', 'confluence', 'beginner'],
    commonMistakes: ['stacking many overlapping indicators ("indicator soup")'],
    misconceptions: ['that more indicators equal more accuracy'],
    prerequisites: ['moving-averages', 'rsi-indicator'], nextSteps: ['confluence'], related: ['atr-indicator', 'technical-analysis-basics'],
    followups: ['confluence'],
    riskNote: 'Indicators confirm structure — they never replace reading price.',
    seo: { title: 'Best Indicator Combination for Trading', description: 'Why one trend + one momentum + one volatility indicator beats indicator soup.', keywords: ['best indicator combination', 'indicators that work together', 'best indicators for beginners', 'indicator soup'] },
  }),
];
