// functions/knowledge/smart-money/concepts.js
// CATEGORY: smart-money (NEW, Phase 2) — ICT/SMC institutional concepts.

export const SMART_MONEY_CONCEPTS = [
  {
    id: 'order-block', category: 'smart-money', topic: 'Order Blocks', level: 'advanced',
    title: 'What is an Order Block', intent: 'technical',
    concepts: ['order block', 'institutional', 'supply demand', 'smart money'],
    questionPatterns: ['what is an order block', 'how to trade order blocks', 'order block explained', 'what is a bullish order block', 'how to find order blocks'],
    canonical: {
      short: 'An order block is the last opposing candle before a strong, structure-breaking move — the footprint of where institutions loaded their position. Traders mark it as a zone and look for price to return and react there, with invalidation just beyond it.',
      deep: 'The logic is that large players cannot fill size without leaving an imprint: the final down-candle before an explosive rally (or up-candle before a drop) marks where that buying (or selling) originated. When price retraces to that block, the unfilled orders often defend it. Use it like a refined support/resistance zone — wait for a reaction at the block, enter with structure confirmation, and place the stop beyond the block where the idea is wrong.',
    },
    responseObjective: 'educate', desiredOutcome: 'mark and trade institutional order blocks with defined risk',
    relevanceTags: ['smart money', 'order block', 'structure'],
    guidance: { tradeProblem: true },
    recommendedTools: ['chart'],
    related: ['fair-value-gap', 'break-of-structure', 'market-structure'], prerequisites: ['market-structure', 'break-of-structure'],
    nextSteps: ['fair-value-gap'], followups: ['displacement', 'optimal-trade-entry'],
    riskNote: 'A block is a zone, not a guarantee — react to it with a stop beyond it, risking 1%.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'fair-value-gap', category: 'smart-money', topic: 'Fair Value Gap', level: 'advanced',
    title: 'Fair Value Gaps (FVG)', intent: 'technical',
    concepts: ['fair value gap', 'fvg', 'imbalance', 'inefficiency', 'smart money'],
    questionPatterns: ['what is a fair value gap', 'what is an fvg', 'how to trade fair value gaps', 'fvg explained', 'what is an imbalance'],
    canonical: {
      short: 'A fair value gap is a three-candle imbalance where price moved so fast it left an untraded gap. Price often returns to rebalance that gap before continuing, which makes FVGs useful as both targets and precise entry zones.',
      deep: 'When a strong displacement candle leaves a gap between the wicks of the candles either side of it, that inefficiency tends to get revisited. In a trend, a pullback into an FVG in your direction is a refined entry; an unfilled FVG above or below acts as a magnet/target. Combine it with an order block and structure for confluence rather than trading every gap — the cleaner the displacement that created it, the more reliable the reaction.',
    },
    responseObjective: 'educate', desiredOutcome: 'use imbalances as targets and refined entries',
    relevanceTags: ['smart money', 'fvg', 'imbalance'],
    guidance: { tradeProblem: true },
    recommendedTools: ['chart'],
    related: ['order-block', 'displacement', 'liquidity-void'], prerequisites: ['market-structure'],
    nextSteps: ['displacement'], followups: ['order-block', 'optimal-trade-entry'],
    riskNote: 'Not every gap fills — require structure confluence and a defined stop.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'displacement', category: 'smart-money', topic: 'Displacement', level: 'advanced',
    title: 'Displacement and Intent', intent: 'technical',
    concepts: ['displacement', 'momentum', 'intent', 'expansion', 'smart money'],
    questionPatterns: ['what is displacement in trading', 'what does displacement mean', 'how to spot displacement', 'displacement smart money', 'what is a displacement candle'],
    canonical: {
      short: 'Displacement is a sudden, forceful move that breaks structure and leaves imbalance behind — the signature of real institutional intent rather than aimless drift. It is what validates an order block or a change of character.',
      deep: 'After price sweeps liquidity, a strong displacement leg in the new direction is your confirmation that intent has shifted — it usually breaks a swing point (BOS/CHoCH) and prints a fair value gap. Weak, overlapping candles are not displacement and should not be trusted as a turn. Wait for displacement to confirm the move, then trade the pullback into the order block or FVG it created.',
    },
    responseObjective: 'educate', desiredOutcome: 'confirm intent before trading a turn',
    relevanceTags: ['smart money', 'displacement', 'momentum'],
    guidance: { tradeProblem: true },
    related: ['order-block', 'fair-value-gap', 'choch'], prerequisites: ['break-of-structure'],
    nextSteps: ['optimal-trade-entry'], followups: ['order-block', 'liquidity-sweep'],
    riskNote: 'No displacement, no confirmation — do not pre-empt the move.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'optimal-trade-entry', category: 'smart-money', topic: 'Optimal Trade Entry', level: 'advanced',
    title: 'Optimal Trade Entry (OTE)', intent: 'technical',
    concepts: ['optimal trade entry', 'ote', 'retracement', 'fibonacci', 'smart money'],
    questionPatterns: ['what is optimal trade entry', 'what is ote', 'how to use ote', 'optimal trade entry explained', 'best entry on a pullback'],
    canonical: {
      short: 'Optimal trade entry is entering on the deeper part of a retracement (roughly the 62–79% zone of the displacement leg) where risk is smallest and reward largest. It is a discount entry in an uptrend, a premium entry in a downtrend.',
      deep: 'After displacement creates a new leg, price usually retraces before continuing. Entering shallow gives poor reward; entering in the deep discount/premium zone — often overlapping an order block or FVG — gives a tight stop and a large target. Wait for a reaction in that zone with lower-timeframe confirmation rather than blindly placing a limit, and your reward-to-risk improves dramatically on the same idea.',
    },
    responseObjective: 'educate', desiredOutcome: 'enter from value for maximum reward-to-risk',
    relevanceTags: ['smart money', 'entry', 'ote'],
    guidance: { tradeProblem: true },
    related: ['premium-discount', 'fair-value-gap', 'order-block'], prerequisites: ['premium-discount', 'displacement'],
    nextSteps: ['trade-management'], followups: ['order-block', 'risk-reward'],
    riskNote: 'Even a perfect OTE needs a stop beyond invalidation and 1% risk.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'killzones', category: 'smart-money', topic: 'Killzones', level: 'advanced',
    title: 'Trading Killzones', intent: 'technical',
    concepts: ['killzone', 'session timing', 'london', 'new york', 'smart money'],
    questionPatterns: ['what are killzones', 'what is the london killzone', 'best time for smart money trading', 'killzones explained', 'when do institutions trade'],
    canonical: {
      short: 'Killzones are the high-probability time windows — mainly the London and New York opens — when institutional volume drives the cleanest moves. Concentrating your trading in these windows raises quality and cuts the boredom trades.',
      deep: 'Most of the day is noise; the killzones (roughly the London open and the New York open/overlap) are when liquidity and intent concentrate. Smart-money setups — sweeps, displacement, OTE — work best inside these windows because that is when the volume to drive them exists. Define your two or three killzone hours, prepare the levels beforehand, and let the session deliver the setup instead of forcing trades in dead hours.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade the high-liquidity institutional windows',
    relevanceTags: ['smart money', 'sessions', 'timing'],
    guidance: { tradeProblem: true },
    related: ['forex-sessions', 'london-session-gold', 'liquidity-sweep'], prerequisites: ['forex-sessions'],
    nextSteps: ['liquidity-sweep'], followups: ['displacement', 'order-block'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'market-maker-model', category: 'smart-money', topic: 'Market Maker Model', level: 'advanced',
    title: 'The Market Maker Model', intent: 'technical',
    concepts: ['market maker', 'accumulation', 'manipulation', 'distribution', 'smart money'],
    questionPatterns: ['what is the market maker model', 'how do market makers move price', 'accumulation manipulation distribution', 'market maker model explained', 'how does smart money trap traders'],
    canonical: {
      short: 'The market maker model describes price in three acts: accumulation (building a position quietly), manipulation (a sweep to trap retail and grab liquidity), then distribution (the real move). Recognising the act you are in stops you from being the liquidity.',
      deep: 'Institutions need counterparties, so price is engineered: it ranges to accumulate, then spikes against the eventual direction to trigger retail stops and breakout entries (manipulation), before expanding in the true direction (distribution). The retail trap is buying the manipulation high or selling the manipulation low. By waiting for the sweep-and-reverse rather than the obvious breakout, you align with the distribution leg instead of funding it.',
    },
    responseObjective: 'educate', desiredOutcome: 'avoid being the liquidity in the manipulation phase',
    relevanceTags: ['smart money', 'market maker', 'manipulation'],
    guidance: { tradeProblem: true },
    related: ['liquidity-sweep', 'inducement', 'accumulation-distribution'], prerequisites: ['market-structure', 'liquidity-sweep'],
    nextSteps: ['accumulation-distribution'], followups: ['inducement', 'stop-hunt'],
    riskNote: 'If a move looks obvious to everyone, suspect manipulation — wait for confirmation.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'accumulation-distribution', category: 'smart-money', topic: 'Accumulation and Distribution', level: 'advanced',
    title: 'Accumulation and Distribution', intent: 'technical',
    concepts: ['accumulation', 'distribution', 'ranging', 'wyckoff', 'smart money'],
    questionPatterns: ['what is accumulation and distribution', 'how to spot accumulation', 'accumulation distribution explained', 'what is a distribution phase', 'wyckoff accumulation'],
    canonical: {
      short: 'Accumulation is a quiet range where smart money builds a long position; distribution is the range where they sell into strength. Ranges are not random — they are where positions are built before the expansion you want to ride.',
      deep: 'Before a big move, price often consolidates while institutions accumulate (near lows) or distribute (near highs), sweeping both edges of the range to gather liquidity. The clue to direction is which side gets swept-and-rejected and where displacement appears. Treat extended ranges as preparation: mark the range, watch which boundary fails to hold, and trade the expansion out of accumulation/distribution rather than chopping inside it.',
    },
    responseObjective: 'educate', desiredOutcome: 'read ranges as position-building, then trade the expansion',
    relevanceTags: ['smart money', 'accumulation', 'range'],
    guidance: { tradeProblem: true },
    related: ['market-maker-model', 'range-market', 'liquidity-sweep'], prerequisites: ['range-market'],
    nextSteps: ['displacement'], followups: ['market-maker-model', 'liquidity-sweep'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'breaker-block', category: 'smart-money', topic: 'Breaker Blocks', level: 'advanced',
    title: 'Breaker Blocks', intent: 'technical',
    concepts: ['breaker block', 'failed order block', 'reversal', 'structure', 'smart money'],
    questionPatterns: ['what is a breaker block', 'breaker block explained', 'how to trade breaker blocks', 'difference between order block and breaker', 'what is a failed order block'],
    canonical: {
      short: 'A breaker block is a failed order block: once price breaks through it and shifts structure, that zone flips polarity and becomes support-turned-resistance (or vice versa). It marks where the previous idea was invalidated and a new one began.',
      deep: 'When an order block fails to hold and structure breaks, the same zone often becomes a high-quality entry in the new direction — old demand that failed becomes supply on the retest. The breaker works because trapped traders from the failed block defend their breakeven, fuelling the reversal. Trade the retest of the breaker with structure confirmation, not the initial break.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade polarity flips after a failed block',
    relevanceTags: ['smart money', 'breaker', 'reversal'],
    guidance: { tradeProblem: true },
    related: ['order-block', 'choch', 'break-of-structure'], prerequisites: ['order-block', 'choch'],
    nextSteps: ['trade-management'], followups: ['order-block', 'displacement'],
    riskNote: 'Wait for the retest with confirmation — not the first break through the block.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'smt-divergence', category: 'smart-money', topic: 'SMT Divergence', level: 'advanced',
    title: 'SMT Divergence', intent: 'technical',
    concepts: ['smt divergence', 'correlation', 'divergence', 'confirmation', 'smart money'],
    questionPatterns: ['what is smt divergence', 'smart money technique divergence', 'how to use smt divergence', 'correlated pairs divergence', 'smt divergence explained'],
    canonical: {
      short: 'SMT divergence is when two correlated markets disagree at a key level — one makes a new high/low and the other fails to. That failure is an early tell that the sweep was liquidity, not continuation.',
      deep: 'Correlated instruments (for example EURUSD and GBPUSD, or gold and the dollar inverted) usually move together. When one sweeps a high but the correlated one does not confirm, it signals the move lacks broad intent — often a liquidity grab before reversal. Used as confluence with a sweep and displacement, SMT divergence sharpens reversal timing; used alone it is just a hint.',
    },
    responseObjective: 'educate', desiredOutcome: 'confirm reversals via correlated-market disagreement',
    relevanceTags: ['smart money', 'divergence', 'correlation'],
    guidance: { tradeProblem: true },
    related: ['correlation', 'liquidity-sweep', 'displacement'], prerequisites: ['correlation', 'liquidity-sweep'],
    nextSteps: ['displacement'], followups: ['liquidity-sweep', 'market-maker-model'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'power-of-three', category: 'smart-money', topic: 'Power of Three', level: 'advanced',
    title: 'Power of Three (AMD)', intent: 'technical',
    concepts: ['power of three', 'amd', 'open high low close', 'daily range', 'smart money'],
    questionPatterns: ['what is power of three', 'what is amd in trading', 'power of three explained', 'accumulation manipulation distribution daily', 'how does the daily candle form'],
    canonical: {
      short: 'Power of Three is the idea that each candle (especially the daily) forms in three phases — accumulation near the open, a manipulation wick against the trend, then distribution toward the close. It helps you anticipate the daily range rather than chase it.',
      deep: 'Reading the daily through accumulation–manipulation–distribution lets you expect the false move before the real one: price often dips below the open to grab liquidity early in the session, then expands the other way into the close. Knowing this, you avoid buying the manipulation low or selling the manipulation high, and instead position for the distribution phase with the higher-timeframe bias.',
    },
    responseObjective: 'educate', desiredOutcome: 'anticipate the daily range via AMD phases',
    relevanceTags: ['smart money', 'amd', 'daily range'],
    guidance: { tradeProblem: true },
    related: ['market-maker-model', 'killzones', 'accumulation-distribution'], prerequisites: ['market-maker-model'],
    nextSteps: ['killzones'], followups: ['accumulation-distribution', 'displacement'],
    riskNote: 'Bias is a lean, not certainty — still trade with a defined stop.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
