// functions/knowledge/research/concepts.js
// CATEGORY: research (NEW, Phase 8) — macro models, indicators, regimes. Each carries
// a marketContext (real-market illustration) for the 6-part research coach.

export const RESEARCH_CONCEPTS = [
  {
    id: 'gold-macro-model', category: 'research', topic: 'Gold Macro Model', level: 'advanced',
    title: 'A Macro Model for Gold', intent: 'macro',
    concepts: ['gold macro', 'real yields', 'dollar', 'safe haven'],
    questionPatterns: ['what drives gold long term', 'gold macro model', 'what is the macro picture for gold', 'how to analyse gold fundamentally', 'gold fundamentals explained'],
    canonical: {
      short: 'Gold\'s macro picture rests on three pillars: real yields (inverse), the dollar (inverse), and safe-haven demand (risk-off positive). When two or three align, the macro tailwind is strong; when they conflict, expect chop.',
      deep: 'Model gold top-down: falling real yields and a weakening dollar are bullish; rising real yields and a strong dollar are bearish; risk-off panic can override both and lift gold regardless. Read these together rather than in isolation — the cleanest trends come when the pillars agree. Use the macro model for bias and conviction, then let structure time the entry.',
    },
    marketContext: 'In 2022 the Fed hiked aggressively: real yields and the dollar surged, and gold fell for much of the year despite multi-decade-high inflation — the rate pillar overpowered the inflation narrative.',
    responseObjective: 'educate', desiredOutcome: 'build a multi-pillar macro bias for gold',
    relevanceTags: ['research', 'gold', 'macro'],
    guidance: { tradeProblem: true },
    commonMistakes: ['buying gold on inflation headlines while real yields are rising'],
    misconceptions: ['gold always rises with inflation — short-term real yields often matter more'],
    related: ['gold-dxy-correlation', 'gold-yields-correlation', 'intermarket-analysis'], prerequisites: ['gold-yields-correlation'],
    nextSteps: ['forex-macro-model'], followups: ['intermarket-analysis', 'interest-rates'],
    riskNote: 'Macro sets bias, not timing — still enter on structure with 1% risk.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'forex-macro-model', category: 'research', topic: 'Forex Macro Model', level: 'advanced',
    title: 'A Macro Model for Forex', intent: 'macro',
    concepts: ['forex macro', 'rate differential', 'growth', 'currency strength'],
    questionPatterns: ['what drives currency pairs', 'forex macro model', 'how to analyse forex fundamentally', 'what makes a currency strong', 'forex fundamentals explained'],
    canonical: {
      short: 'A currency strengthens on relatively higher/rising rates, stronger growth, and risk sentiment that favours it. Trade strength against weakness: pair a hawkish, growing economy\'s currency with a dovish, slowing one.',
      deep: 'Currencies are relative, so model the differential: which central bank is more hawkish, which economy is growing faster, and how risk sentiment treats each (safe havens vs higher-yielders). The cleanest forex trends come from divergence — one bank tightening while another eases. Use the model to pick the strong-vs-weak pairing, then time with structure.',
    },
    marketContext: 'In 2014–2015 the Fed moved toward tightening while the ECB eased into QE — EURUSD fell from ~1.39 to ~1.05 as the rate-and-policy divergence played out.',
    responseObjective: 'educate', desiredOutcome: 'pair strength vs weakness from the macro differential',
    relevanceTags: ['research', 'forex', 'macro'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading a pair without considering both currencies\' policy stance'],
    misconceptions: ['a strong economy always means a strong currency — rate expectations and risk flows matter too'],
    related: ['gold-macro-model', 'interest-rates', 'correlation'], prerequisites: ['interest-rates'],
    nextSteps: ['rate-cycles'], followups: ['correlation', 'intermarket-analysis'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'nfp', category: 'research', topic: 'Non-Farm Payrolls (NFP)', level: 'intermediate',
    title: 'Non-Farm Payrolls (NFP)', intent: 'macro',
    concepts: ['nfp', 'jobs', 'employment', 'volatility'],
    questionPatterns: ['what is nfp', 'how to trade nfp', 'what is non farm payrolls', 'why does nfp move markets', 'nfp explained'],
    canonical: {
      short: 'NFP is the monthly US jobs report — one of the highest-impact releases. It moves the dollar, gold, and indices in seconds by reshaping rate expectations. Be flat or protected into it; trade the aftermath.',
      deep: 'Released the first Friday of most months, NFP reports job creation, unemployment, and wages. Strong data can lift the dollar and pressure gold (rate-hike odds rise); weak data does the reverse — but the reaction often hinges on wages and revisions versus expectations, not just the headline. Spreads blow out at release; the edge is patience for the real move after structure reforms.',
    },
    marketContext: 'On many NFP Fridays gold and EURUSD have whipsawed 50–100+ pips within minutes of the 8:30 ET print before settling into the genuine move.',
    responseObjective: 'warn', desiredOutcome: 'survive NFP volatility and trade the aftermath',
    relevanceTags: ['research', 'nfp', 'news'],
    guidance: { tradeProblem: true },
    commonMistakes: ['entering just before the NFP print', 'chasing the first spike'],
    misconceptions: ['the headline jobs number is all that matters — wages and revisions often drive the reaction'],
    related: ['cpi-release', 'fomc', 'economic-news-impact'], prerequisites: ['economic-news-impact'],
    nextSteps: ['cpi-release'], followups: ['fomc', 'economic-calendar'],
    riskNote: 'Spreads gap on NFP — be flat or reduced, never full size into the print.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'cpi-release', category: 'research', topic: 'CPI Release', level: 'intermediate',
    title: 'Trading the CPI Release', intent: 'macro',
    concepts: ['cpi', 'inflation data', 'volatility', 'rates'],
    questionPatterns: ['what is cpi release', 'how to trade cpi', 'why does cpi move markets', 'cpi trading explained', 'how does cpi affect gold'],
    canonical: {
      short: 'CPI is the headline inflation report and arguably the single biggest scheduled mover of rate expectations. Hotter-than-expected CPI lifts the dollar and pressures gold short-term; cooler does the reverse. High volatility — trade the aftermath.',
      deep: 'CPI reshapes the market\'s rate path more than almost any release, so the reaction is about the surprise versus expectations, not the absolute number. A hot print raises hike odds (dollar up, gold down short-term); a cool print eases them. Spreads widen sharply at release. Be flat or protected, watch the initial reaction, then trade the first clean structure once liquidity normalises.',
    },
    marketContext: 'The November 2022 cooler-than-expected US CPI triggered a violent risk-on move — the dollar dropped and gold and indices spiked hundreds of points within the hour.',
    responseObjective: 'warn', desiredOutcome: 'trade CPI aftermath, not the headline spike',
    relevanceTags: ['research', 'cpi', 'inflation'],
    guidance: { tradeProblem: true },
    commonMistakes: ['holding full size through the CPI print'],
    misconceptions: ['the absolute CPI figure moves price — the surprise vs expectations does'],
    related: ['nfp', 'inflation', 'fomc'], prerequisites: ['inflation'],
    nextSteps: ['ppi'], followups: ['fomc', 'economic-calendar'],
    riskNote: 'CPI is a top-tier event — reduce size or stand aside.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'ppi', category: 'research', topic: 'Producer Price Index (PPI)', level: 'advanced',
    title: 'Producer Price Index (PPI)', intent: 'macro',
    concepts: ['ppi', 'wholesale inflation', 'leading indicator', 'rates'],
    questionPatterns: ['what is ppi', 'how does ppi affect markets', 'ppi vs cpi', 'why does ppi matter', 'ppi explained'],
    canonical: {
      short: 'PPI measures wholesale (producer) inflation and often leads CPI, since producer costs feed into consumer prices. It is a medium-impact release that refines the inflation and rate outlook.',
      deep: 'Because producers pass costs to consumers, PPI can foreshadow CPI direction, making it useful context ahead of the bigger inflation print. Its market impact is smaller than CPI/NFP but still meaningful around rate-sensitive assets. Use it as a supporting data point in your inflation read rather than a standalone trade trigger.',
    },
    marketContext: 'In disinflation phases, several months of falling PPI preceded softer CPI prints, giving macro traders early confirmation the inflation trend was cooling.',
    responseObjective: 'educate', desiredOutcome: 'use PPI as a leading inflation signal',
    relevanceTags: ['research', 'ppi', 'inflation'],
    guidance: { tradeProblem: true },
    commonMistakes: ['treating PPI as a high-impact standalone trigger like CPI'],
    related: ['cpi-release', 'inflation', 'interest-rates'], prerequisites: ['inflation'],
    nextSteps: ['fomc'], followups: ['cpi-release', 'economic-calendar'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'fomc', category: 'research', topic: 'FOMC Meetings', level: 'intermediate',
    title: 'FOMC Meetings and Decisions', intent: 'macro',
    concepts: ['fomc', 'fed', 'rate decision', 'dot plot'],
    questionPatterns: ['what is fomc', 'how to trade fomc', 'what happens at an fomc meeting', 'why does fomc move markets', 'fomc explained'],
    canonical: {
      short: 'The FOMC sets US interest rates eight times a year; its decision, statement, projections, and press conference are top-tier market movers. The tone (hawkish vs dovish) versus expectations usually matters more than the rate itself.',
      deep: 'Markets pre-price the likely decision, so the explosive moves come from the statement wording, the dot-plot projections, and the chair\'s press conference relative to expectations. Gold, the dollar, and indices can swing twice — once on the decision, again on the conference. Be flat or protected, and trade the genuine move once the dust settles rather than the initial knee-jerk.',
    },
    marketContext: 'Markets have repeatedly reversed sharply mid-FOMC: an initial move on the statement, then a larger opposite move during the press conference as the chair\'s tone shifted expectations.',
    responseObjective: 'warn', desiredOutcome: 'respect FOMC volatility; trade the settled move',
    relevanceTags: ['research', 'fomc', 'rates'],
    guidance: { tradeProblem: true },
    commonMistakes: ['trading the first FOMC spike before the press conference'],
    misconceptions: ['the rate decision is the whole event — the statement and conference often move more'],
    related: ['central-banks', 'interest-rates', 'rate-cycles'], prerequisites: ['central-banks'],
    nextSteps: ['rate-cycles'], followups: ['nfp', 'cpi-release'],
    riskNote: 'FOMC can whipsaw both ways — be flat or reduced into it.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'rate-cycles', category: 'research', topic: 'Interest Rate Cycles', level: 'advanced',
    title: 'Interest Rate Cycles', intent: 'macro',
    concepts: ['rate cycle', 'hiking', 'cutting', 'pause'],
    questionPatterns: ['what is a rate cycle', 'how do interest rate cycles work', 'hiking vs cutting cycle', 'where are we in the rate cycle', 'rate cycle and gold'],
    canonical: {
      short: 'Rates move in cycles — hiking, pausing, then cutting — each phase shaping the dollar, gold, and risk assets for months. Knowing the phase tells you the dominant macro lean behind shorter-term trades.',
      deep: 'Hiking cycles tend to support the dollar and pressure gold and risk assets; the pause/pivot often marks turning points; cutting cycles ease conditions and frequently lift gold and risk. These phases unfold over many months, so they set the backdrop, not the entry. Position your bias with the phase and treat pivots as high-volatility regime changes.',
    },
    marketContext: 'As markets anticipated the end of the 2022–2023 hiking cycle and eventual cuts, gold rallied strongly into new highs while the dollar softened — a classic late-cycle pivot trade.',
    responseObjective: 'educate', desiredOutcome: 'align bias with the rate-cycle phase',
    relevanceTags: ['research', 'rate cycle', 'macro'],
    guidance: { tradeProblem: true },
    commonMistakes: ['fighting the rate cycle with counter-trend positional trades'],
    related: ['monetary-policy', 'interest-rates', 'market-regimes'], prerequisites: ['interest-rates'],
    nextSteps: ['market-regimes'], followups: ['monetary-policy', 'gold-macro-model'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'commodity-correlations', category: 'research', topic: 'Commodity Correlations', level: 'advanced',
    title: 'Commodity Correlations', intent: 'macro',
    concepts: ['commodities', 'correlation', 'oil', 'gold', 'aud'],
    questionPatterns: ['how are commodities correlated', 'what is the gold oil relationship', 'commodity correlations explained', 'how do commodities affect forex', 'commodity currency correlation'],
    canonical: {
      short: 'Commodities and currencies are linked: commodity exporters\' currencies (AUD, CAD) track their key commodities, and metals/energy reflect growth and inflation. These correlations add macro confluence and warn of hidden exposure.',
      deep: 'AUD often tracks metals and Chinese growth; CAD tracks oil; gold and silver share drivers but silver is more industrial. Knowing these links sharpens bias (a commodity move can confirm a currency idea) and prevents stacking correlated risk (long AUD and long copper is one bet). Treat correlations as regime-dependent context, not fixed laws.',
    },
    marketContext: 'During oil spikes, USDCAD has frequently fallen as the petro-currency strengthened — traders used the oil move as confluence for shorting the pair.',
    responseObjective: 'educate', desiredOutcome: 'use commodity links for confluence and exposure control',
    relevanceTags: ['research', 'commodities', 'correlation'],
    guidance: { tradeProblem: true },
    commonMistakes: ['stacking correlated commodity-currency trades as if independent'],
    misconceptions: ['correlations are constant — they shift with the macro regime'],
    related: ['intermarket-analysis', 'correlation', 'portfolio-risk'], prerequisites: ['intermarket-analysis'],
    nextSteps: ['volatility-models'], followups: ['portfolio-risk', 'correlation'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'volatility-models', category: 'research', topic: 'Volatility Models', level: 'advanced',
    title: 'Volatility Models and the VIX', intent: 'macro',
    concepts: ['volatility', 'vix', 'fear gauge', 'risk'],
    questionPatterns: ['what is a volatility model', 'what is the vix', 'how does volatility affect markets', 'volatility models explained', 'what is the fear gauge'],
    canonical: {
      short: 'Volatility models gauge how turbulent markets are (the VIX is the famous "fear gauge"). Rising volatility signals risk-off stress and demands smaller size and wider stops; calm signals risk-on and tighter ranges.',
      deep: 'Volatility clusters — calm follows calm, storms follow storms — and spikes coincide with risk-off events that lift safe havens. Reading the regime tells you how to size (smaller when volatile) and what behaviour to expect (sharp, gappy moves in high-vol; grind in low-vol). It is risk context layered over structure, helping you adapt exposure as conditions change.',
    },
    marketContext: 'During the March 2020 crash the VIX spiked above 80 as equities collapsed and the dollar surged — a textbook high-volatility, risk-off regime.',
    responseObjective: 'educate', desiredOutcome: 'adapt size and expectations to the volatility regime',
    relevanceTags: ['research', 'volatility', 'vix'],
    guidance: { tradeProblem: true },
    commonMistakes: ['using normal position size during a volatility spike'],
    related: ['volatility-regimes', 'crisis-behaviour', 'risk-on-risk-off'], prerequisites: ['volatility-regimes'],
    nextSteps: ['crisis-behaviour'], followups: ['risk-on-risk-off', 'portfolio-risk'],
    riskNote: 'Cut size hard when volatility spikes — gaps and slippage punish full size.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'market-regimes', category: 'research', topic: 'Market Regimes', level: 'advanced',
    title: 'Identifying Market Regimes', intent: 'technical',
    concepts: ['market regime', 'trending', 'ranging', 'volatile'],
    questionPatterns: ['what is a market regime', 'how to identify the market regime', 'trending vs ranging regime', 'market regimes explained', 'how to adapt to market conditions'],
    canonical: {
      short: 'A market regime is the prevailing character — trending, ranging, or high-volatility/crisis. Identifying it first tells you which playbook to run, so you stop applying trend tactics in a range or normal size in a storm.',
      deep: 'Regimes combine direction (trend vs balance) and volatility (calm vs turbulent). Trend regimes reward continuation; ranges reward fading edges; high-volatility/crisis regimes demand defensive sizing and safe-haven awareness. Diagnosing the regime is a higher-order skill that sits above any single setup — match tactic, size, and expectation to the regime and your edge survives changing conditions.',
    },
    marketContext: 'Gold in 2023 alternated between multi-week trending legs and tight consolidation ranges — traders who switched tactics by regime fared far better than those forcing one style.',
    responseObjective: 'educate', desiredOutcome: 'diagnose the regime before choosing tactics',
    relevanceTags: ['research', 'regime'],
    guidance: { tradeProblem: true },
    commonMistakes: ['running one strategy regardless of whether the market is trending or ranging'],
    related: ['market-cycles', 'volatility-models', 'trend-models'], prerequisites: ['market-cycles'],
    nextSteps: ['trend-models'], followups: ['range-trading', 'volatility-models'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'trend-models', category: 'research', topic: 'Trend Models', level: 'advanced',
    title: 'Trend Models', intent: 'technical',
    concepts: ['trend model', 'trend strength', 'continuation', 'momentum'],
    questionPatterns: ['what is a trend model', 'how to model a trend', 'how to measure trend strength', 'trend models explained', 'how to know if a trend will continue'],
    canonical: {
      short: 'A trend model defines, objectively, when a market is trending and worth following: clean structure (higher highs/lows), shallow pullbacks, and momentum respecting key levels. It keeps you with strong trends and out of weak ones.',
      deep: 'Rather than guessing, score the trend: are swings extending, are pullbacks shallow and quickly rejected, is price holding above/below its key structure? Strong scores mean press continuation; deteriorating scores (deeper pullbacks, failed continuations) mean tighten or stand aside. A trend model turns "it looks trendy" into a repeatable read that scales your aggression to the trend\'s actual health.',
    },
    marketContext: 'Strong USD uptrends in 2022 showed shallow pullbacks and relentless higher highs — a high trend-strength score that rewarded continuation buyers for months.',
    responseObjective: 'educate', desiredOutcome: 'objectively score trend health before pressing',
    relevanceTags: ['research', 'trend'],
    guidance: { tradeProblem: true },
    commonMistakes: ['fading a strong, high-momentum trend because it "looks overextended"'],
    related: ['market-regimes', 'gold-trend-strength', 'trend-trading'], prerequisites: ['market-regimes'],
    nextSteps: ['crisis-behaviour'], followups: ['trend-trading', 'trend-continuation'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'crisis-behaviour', category: 'research', topic: 'Crisis Market Behaviour', level: 'advanced',
    title: 'How Markets Behave in a Crisis', intent: 'macro',
    concepts: ['crisis', 'panic', 'correlation spike', 'safe haven'],
    questionPatterns: ['how do markets behave in a crisis', 'what happens to gold in a crisis', 'crisis market behaviour', 'how to trade a market crash', 'what is a flight to safety'],
    canonical: {
      short: 'In a crisis, correlations spike toward 1, liquidity evaporates, and capital flees to safe havens (dollar, yen, sometimes gold). Normal setups break down — survival and reduced size matter far more than being clever.',
      deep: 'Panic regimes behave differently: diversification fails as everything sells together, spreads gap, and even gold can drop initially in a liquidity scramble before its safe-haven bid returns. The lesson is defensive: cut size dramatically or step aside, expect violent two-way moves, and never assume a "safe" trade is immune. Crises end careers built on leverage — capital preservation is the only edge that matters.',
    },
    marketContext: 'In March 2020 nearly everything sold off together — even gold dipped sharply during the liquidity crunch before rallying as havens regained their bid.',
    responseObjective: 'warn', desiredOutcome: 'prioritise survival and small size in crisis regimes',
    relevanceTags: ['research', 'crisis', 'risk'],
    guidance: { tradeProblem: true },
    commonMistakes: ['assuming diversification or "safe havens" protect you in a liquidity crisis'],
    misconceptions: ['gold always rises in a crisis — it can drop first in a liquidity scramble'],
    related: ['volatility-models', 'risk-on-risk-off', 'capital-protection'], prerequisites: ['volatility-models'],
    nextSteps: ['gold-macro-model'], followups: ['capital-protection', 'portfolio-risk'],
    riskNote: 'In a crisis, correlations go to 1 — cut size hard; survival is the only edge.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
