// functions/knowledge/instruments/concepts.js
// CATEGORY: instruments (NEW, Phase 12) — markets, styles, quant thinking, systems.

const C = (o) => ({ status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en', guidance: { tradeProblem: true }, ...o });

export const INSTRUMENTS_CONCEPTS = [
  C({
    id: 'commodity-trading', category: 'instruments', topic: 'Commodity Trading', level: 'intermediate', intent: 'macro',
    title: 'Commodity Trading Basics',
    concepts: ['commodities', 'gold', 'oil', 'supply demand'],
    questionPatterns: ['what is commodity trading', 'how to trade commodities', 'commodity trading explained', 'are commodities good to trade', 'how do commodities move'],
    canonical: {
      short: 'Commodities — gold, oil, metals, agriculture — are driven by physical supply and demand plus the dollar and macro cycles. They trend strongly but can be volatile and seasonal, rewarding macro-aware, risk-disciplined traders.',
      deep: 'Each commodity has its own drivers (oil: production and demand; gold: yields, dollar, haven flows; agriculture: weather and seasons) layered over the dollar and growth cycle. They often trend hard, which suits trend and swing styles, but volatility and gaps demand careful sizing. Reading the macro and supply backdrop gives bias; structure still times the entry.',
    },
    marketContext: 'Oil swung from negative prices in 2020 to multi-year highs in 2022 as supply/demand and macro shifts whipsawed the commodity complex.',
    commonMistakes: ['trading a commodity purely on the chart while ignoring its supply/macro driver'],
    misconceptions: ['all commodities move together — each has distinct drivers'],
    riskNote: 'Commodities gap and trend hard — size for volatility, respect the macro backdrop.',
    related: ['commodity-correlations', 'gold-macro-model', 'index-trading'], prerequisites: ['gold-analysis'],
    nextSteps: ['index-trading'], followups: ['commodity-correlations', 'seasonal-cycles'],
  }),
  C({
    id: 'index-trading', category: 'instruments', topic: 'Index Trading', level: 'intermediate', intent: 'technical',
    title: 'Stock Index Trading',
    concepts: ['indices', 'sp500', 'nasdaq', 'risk sentiment'],
    questionPatterns: ['what is index trading', 'how to trade indices', 'how to trade the sp500', 'index trading explained', 'indices vs forex'],
    canonical: {
      short: 'Indices like the S&P 500 and Nasdaq track baskets of stocks and are pure risk-sentiment instruments — they rise in risk-on, fall in risk-off. They trend cleanly but are highly sensitive to rates, earnings, and macro news.',
      deep: 'Index prices reflect aggregate equity sentiment, so they move with rate expectations, earnings seasons, and risk appetite. They often trend smoothly (good for trend/swing styles) but react violently to FOMC, CPI, and major earnings. Trading them well means combining the macro/risk backdrop with structure, and respecting that overnight gaps and news can be large.',
    },
    marketContext: 'Indices rallied relentlessly through 2023–2024 on AI optimism and rate-cut hopes — a clean risk-on uptrend punctuated by sharp news-driven dips.',
    commonMistakes: ['shorting a strong index uptrend because it "looks expensive"'],
    misconceptions: ['indices and forex trade the same — indices are far more sentiment- and earnings-driven'],
    riskNote: 'Indices gap on news and earnings — manage overnight and event risk.',
    related: ['etf-concepts', 'risk-on-risk-off', 'commodity-trading'], prerequisites: ['market-structure'],
    nextSteps: ['etf-concepts'], followups: ['risk-on-risk-off', 'trend-trading'],
  }),
  C({
    id: 'etf-concepts', category: 'instruments', topic: 'ETF Concepts', level: 'beginner', intent: 'technical',
    title: 'ETF Basics for Traders',
    concepts: ['etf', 'basket', 'diversification', 'index'],
    questionPatterns: ['what is an etf', 'how do etfs work', 'etf basics', 'should i trade etfs', 'etf vs stock'],
    canonical: {
      short: 'An ETF (exchange-traded fund) holds a basket of assets — an index, sector, or commodity — and trades like a single stock. ETFs give instant diversification and are popular for longer-horizon, lower-maintenance exposure.',
      deep: 'ETFs bundle many holdings into one tradable instrument, so buying an index ETF gives broad exposure without picking individual stocks. They suit position and investment styles more than fast intraday trading, offer built-in diversification, and carry small fees. For traders they are a way to express macro or sector views simply, and to hold longer-term exposure alongside active trades.',
    },
    marketContext: 'Broad index ETFs let traders hold long-term market exposure while running shorter-term tactical trades separately.',
    commonMistakes: ['scalping illiquid ETFs as if they were major pairs'],
    misconceptions: ['ETFs are risk-free because they are diversified — they still carry market risk'],
    riskNote: 'ETFs still fall in a market downturn — diversification is not protection from direction.',
    related: ['index-trading', 'diversification', 'position-trading'], prerequisites: [],
    nextSteps: ['indices-vs-forex'], followups: ['index-trading', 'asset-allocation'],
  }),
  C({
    id: 'indices-vs-forex', category: 'instruments', topic: 'Indices vs Forex', level: 'intermediate', intent: 'technical',
    title: 'Indices vs Forex: Which to Trade',
    concepts: ['indices vs forex', 'comparison', 'volatility', 'sessions'],
    questionPatterns: ['indices vs forex', 'should i trade indices or forex', 'difference between indices and forex', 'is forex or indices better', 'indices or forex for beginners'],
    canonical: {
      short: 'Forex is relative (one currency vs another), liquid around the clock, and rate/sentiment driven; indices are directional risk-sentiment plays with strong trends but earnings and overnight gap risk. Choose by your style, schedule, and temperament.',
      deep: 'Forex trades 24/5 with tight spreads on majors and is driven by rate differentials and risk flows — good for session-based and intraday styles. Indices trend cleanly and suit trend/swing traders but carry earnings and overnight gap risk and concentrate in their cash-session hours. Neither is "better"; the right market is the one whose hours, volatility, and drivers fit how you actually trade.',
    },
    marketContext: 'A trader with evening availability might prefer US indices in the NY session over chasing thin late-session forex moves.',
    commonMistakes: ['switching markets chasing volatility instead of mastering one that fits your schedule'],
    misconceptions: ['one market is universally easier — fit to your style matters more'],
    related: ['index-trading', 'forex-macro-model', 'trading-style-fit'], prerequisites: ['trading-style-fit'],
    nextSteps: ['algorithmic-trading-basics'], followups: ['index-trading', 'forex-sessions'],
  }),
  C({
    id: 'algorithmic-trading-basics', category: 'instruments', topic: 'Algorithmic Trading Basics', level: 'advanced', intent: 'strategy',
    title: 'Algorithmic Trading Basics',
    concepts: ['algorithmic trading', 'automation', 'rules', 'systems'],
    questionPatterns: ['what is algorithmic trading', 'how does algo trading work', 'algorithmic trading basics', 'how to automate a strategy', 'should i automate my trading'],
    canonical: {
      short: 'Algorithmic trading automates a fully-defined rule set so trades execute without emotion or hesitation. It demands a precisely specified, backtested edge — you can only automate what you can exactly define.',
      deep: 'An algo turns explicit rules (entry, exit, risk, filters) into code that executes mechanically, removing emotion and enabling speed and consistency. The prerequisite is a strategy defined with zero ambiguity and validated by backtesting — automation amplifies a real edge and amplifies a flawed one just as fast. Start by codifying and testing rules manually; automation is the final step, not a shortcut to an edge.',
    },
    marketContext: 'Much of modern volume is algorithmic, which is why obvious stop levels get probed mechanically — retail can codify simpler rule-based systems.',
    commonMistakes: ['automating a vague strategy that was never defined or backtested'],
    misconceptions: ['algos print money — they only execute an edge you must already have'],
    riskNote: 'Automation amplifies a flawed edge as fast as a good one — validate first.',
    related: ['system-trading', 'edge-definition', 'backtesting-advanced'], prerequisites: ['edge-definition'],
    nextSteps: ['quantitative-thinking'], followups: ['system-trading', 'backtesting-advanced'],
  }),
  C({
    id: 'quantitative-thinking', category: 'instruments', topic: 'Quantitative Thinking', level: 'advanced', intent: 'strategy',
    title: 'Quantitative Thinking for Traders',
    concepts: ['quantitative', 'data', 'probability', 'expectancy'],
    questionPatterns: ['what is quantitative thinking in trading', 'how to think quantitatively', 'quantitative trading mindset', 'using data in trading', 'how to be more data driven'],
    canonical: {
      short: 'Quantitative thinking judges trading by data and probability, not feelings: expectancy over samples, base rates, and tested assumptions. It replaces "I think" with "the data shows," which is how edges are found and trusted.',
      deep: 'A quant mindset asks: what is the expectancy, the sample size, the base rate, and what does the data actually say versus my bias? It treats each trade as one draw from a distribution and judges the process over many. This protects against recency bias and story-driven decisions, and it underpins backtesting, statistical edges, and systems. You need not be a programmer — just disciplined about evidence over narrative.',
    },
    marketContext: 'A trader who tracks that their "gut" trades have negative expectancy over 100 samples can finally cut them — data overruled the story.',
    commonMistakes: ['drawing conclusions from a handful of trades instead of a meaningful sample'],
    misconceptions: ['quant thinking requires advanced math — it mainly requires evidence over narrative'],
    related: ['statistical-edge', 'trading-statistics', 'edge-definition'], prerequisites: ['trading-statistics'],
    nextSteps: ['statistical-edge'], followups: ['system-trading', 'backtesting-advanced'],
  }),
  C({
    id: 'statistical-edge', category: 'instruments', topic: 'Statistical Edge', level: 'advanced', intent: 'strategy',
    title: 'Finding a Statistical Edge',
    concepts: ['statistical edge', 'expectancy', 'sample', 'probability'],
    questionPatterns: ['what is a statistical edge', 'how to find a statistical edge', 'statistical edge explained', 'how to prove my edge statistically', 'do i have a real edge'],
    canonical: {
      short: 'A statistical edge is a positive expectancy proven over a meaningful sample — not a good feeling or a few wins. If the numbers over many trades are positive and repeatable, you have an edge; if not, you have a hope.',
      deep: 'Establish an edge with data: define the setup precisely, gather a large enough sample (back- and forward-tested), and confirm positive expectancy with acceptable drawdown. Beware small samples and curve-fitting that flatter the past. A genuine statistical edge is what lets you execute through losing streaks calmly, because you trust the math over the recent outcomes.',
    },
    marketContext: 'Many "great" discretionary setups reveal negative expectancy once logged over 200 trades — the edge was imagined until measured.',
    commonMistakes: ['claiming an edge from a small or cherry-picked sample'],
    misconceptions: ['a winning week proves an edge — only a large sample does'],
    riskNote: 'No proven expectancy means no measurable edge — size minimally until proven.',
    related: ['quantitative-thinking', 'edge-definition', 'backtesting-advanced'], prerequisites: ['edge-definition'],
    nextSteps: ['mean-reversion'], followups: ['trading-statistics', 'win-rate-vs-rr'],
  }),
  C({
    id: 'mean-reversion', category: 'instruments', topic: 'Mean Reversion', level: 'advanced', intent: 'strategy',
    title: 'Mean Reversion Strategies',
    concepts: ['mean reversion', 'overextension', 'range', 'fade'],
    questionPatterns: ['what is mean reversion', 'how does mean reversion work', 'mean reversion strategy', 'mean reversion vs momentum', 'how to fade overextended moves'],
    canonical: {
      short: 'Mean reversion bets that overextended price snaps back toward an average — fading stretched moves in ranging conditions. It is the opposite of momentum and works in balance, not in strong trends.',
      deep: 'Mean-reversion strategies enter against an overextended move expecting a pull back to value (a moving average, range midpoint, or volume point of control). They shine in ranging, balanced markets and get crushed in strong trends, so regime identification is essential. Tight, defined risk is critical because fading a move that keeps trending is dangerous — the edge lives in balance, not breakout, conditions.',
    },
    marketContext: 'In quiet ranges, fading the extremes back to the mean works repeatedly — until a regime shift turns the range into a trend and punishes the fade.',
    commonMistakes: ['fading a strong trend instead of restricting mean reversion to ranges'],
    misconceptions: ['mean reversion always works — it fails badly in trending regimes'],
    riskNote: 'Fading trends is dangerous — restrict mean reversion to ranging regimes with tight risk.',
    related: ['momentum-trading', 'range-trading', 'market-regimes'], prerequisites: ['market-regimes'],
    nextSteps: ['momentum-trading'], followups: ['range-trading', 'volatility-models'],
  }),
  C({
    id: 'momentum-trading', category: 'instruments', topic: 'Momentum Trading', level: 'intermediate', intent: 'strategy',
    title: 'Momentum Trading',
    concepts: ['momentum', 'trend', 'continuation', 'strength'],
    questionPatterns: ['what is momentum trading', 'how does momentum trading work', 'momentum strategy explained', 'momentum vs mean reversion', 'how to trade momentum'],
    canonical: {
      short: 'Momentum trading buys strength and sells weakness, betting that what is moving keeps moving. It is the trend-aligned opposite of mean reversion and thrives in trending regimes with clear directional conviction.',
      deep: 'Momentum strategies enter in the direction of strong, established moves — joining trends on continuation rather than guessing reversals. They excel when regimes trend and underperform in choppy ranges, so pairing them with regime identification is key. The discipline is going with strength even when it feels extended, and using structure-based stops, because the edge is in persistence, not prediction of the turn.',
    },
    marketContext: 'Strong 2022 dollar and 2023–2024 index trends rewarded momentum traders who kept buying strength while reversion traders fought the move.',
    commonMistakes: ['fading strong momentum because it "looks overextended"'],
    misconceptions: ['momentum and trend trading are gambling on continuation — they exploit a real persistence edge'],
    related: ['mean-reversion', 'trend-trading', 'trend-models'], prerequisites: ['trend-trading'],
    nextSteps: ['system-trading'], followups: ['trend-models', 'market-regimes'],
  }),
  C({
    id: 'seasonal-cycles', category: 'instruments', topic: 'Seasonal Cycles', level: 'advanced', intent: 'macro',
    title: 'Seasonal Market Cycles',
    concepts: ['seasonality', 'cycles', 'recurring patterns', 'tendency'],
    questionPatterns: ['what are seasonal cycles in trading', 'does seasonality work', 'seasonal patterns explained', 'how to use seasonality', 'is there a best month to trade gold'],
    canonical: {
      short: 'Seasonal cycles are recurring calendar tendencies — certain months or periods that historically favour a market. They are a tilt in the odds and context for bias, never a standalone signal to trade blindly.',
      deep: 'Some markets show statistical seasonal tendencies (e.g. historical gold strength in certain months, equity "sell in May" lore). These are probabilistic tilts derived from many years, useful as background context that nudges bias — not guarantees. Any given year can defy the average, so seasonality layers onto structure and macro rather than overriding them. Treat it as a weak confluence factor, weighted accordingly.',
    },
    marketContext: 'Gold has shown seasonal strength in some autumn/new-year windows historically, but plenty of years broke the pattern — a tilt, not a rule.',
    commonMistakes: ['trading a seasonal tendency as a guaranteed signal ignoring price'],
    misconceptions: ['seasonality is reliable timing — it is a probabilistic tilt that often fails in a given year'],
    related: ['market-cycles', 'commodity-trading', 'quantitative-thinking'], prerequisites: ['market-cycles'],
    nextSteps: ['system-trading'], followups: ['commodity-trading', 'statistical-edge'],
  }),
  C({
    id: 'system-trading', category: 'instruments', topic: 'System Trading', level: 'advanced', intent: 'strategy',
    title: 'Rule-Based System Trading',
    concepts: ['system trading', 'mechanical', 'rules', 'consistency'],
    questionPatterns: ['what is system trading', 'what is mechanical trading', 'system trading vs discretionary', 'how to trade a system', 'rule based trading explained'],
    canonical: {
      short: 'System trading follows a fixed, mechanical rule set with no discretion at the decision point — every entry, exit, and size is pre-defined. It maximises consistency and removes emotion, at the cost of flexibility.',
      deep: 'A mechanical system specifies exactly what to do in every situation, so execution is repeatable and emotion-free, and results are measurable and improvable. The trade-off is rigidity — it cannot adapt to context a discretionary trader might read. Many professionals blend the two: systematic rules for risk and entries, with limited discretion within guardrails. Either way, the system must be backtested and trusted before it is traded.',
    },
    marketContext: 'Systematic trend-following funds mechanically rode major 2022 trends with zero discretionary second-guessing — consistency was the edge.',
    commonMistakes: ['overriding a tested system on a gut feeling, breaking its statistical edge'],
    misconceptions: ['systems remove all judgment — building and trusting one still requires skill'],
    related: ['algorithmic-trading-basics', 'edge-definition', 'backtesting-advanced'], prerequisites: ['edge-definition'],
    nextSteps: ['backtesting-advanced'], followups: ['algorithmic-trading-basics', 'consistency-system'],
  }),
  C({
    id: 'backtesting-advanced', category: 'instruments', topic: 'Advanced Backtesting', level: 'advanced', intent: 'strategy',
    title: 'Advanced Backtesting',
    concepts: ['backtesting', 'validation', 'overfitting', 'forward test'],
    questionPatterns: ['how to backtest properly', 'advanced backtesting', 'how to avoid overfitting', 'what is forward testing', 'how to validate a strategy properly'],
    canonical: {
      short: 'Advanced backtesting validates an edge honestly: large samples, out-of-sample and forward testing, realistic costs, and guarding against curve-fitting. The goal is truth about the strategy, not a pretty past equity curve.',
      deep: 'Robust backtesting includes enough trades to be meaningful, reserves out-of-sample data the rules never saw, forward-tests on demo, and models real spread/slippage. The cardinal sin is overfitting — tweaking until the past looks perfect, which never survives live. A strategy that holds up out-of-sample with realistic costs earns trust; one optimised to historical noise will disappoint. Honest testing is what lets you execute through drawdowns.',
    },
    marketContext: 'Strategies curve-fitted to look flawless on past data routinely collapse live — out-of-sample testing exposes the illusion beforehand.',
    commonMistakes: ['optimising parameters until the past looks perfect (overfitting)'],
    misconceptions: ['a great backtest guarantees live results — only out-of-sample robustness suggests it'],
    riskNote: 'Model real costs and reserve out-of-sample data — a fitted backtest lies.',
    related: ['backtesting', 'system-trading', 'statistical-edge'], prerequisites: ['backtesting'],
    nextSteps: ['calendar-mastery'], followups: ['system-trading', 'quantitative-thinking'],
  }),
  C({
    id: 'calendar-mastery', category: 'instruments', topic: 'Economic Calendar Mastery', level: 'intermediate', intent: 'macro',
    title: 'Economic Calendar Mastery',
    concepts: ['economic calendar', 'workflow', 'events', 'preparation'],
    questionPatterns: ['how to master the economic calendar', 'economic calendar workflow', 'how do pros use the economic calendar', 'building a news routine', 'economic calendar mastery'],
    canonical: {
      short: 'Calendar mastery is a repeatable workflow: filter for the high-impact events on your instruments, mark their times in your timezone, and pre-decide how each affects your trading day. It turns the calendar from a list into a plan.',
      deep: 'Beyond just checking the calendar, mastery means a system: weekly, scan the high-impact releases (NFP, CPI, FOMC, central banks) for your markets; daily, note the exact times and your protocol (flat/reduced into red-folder events, trade the aftermath). Knowing what is coming and exactly how you will respond removes news surprises and the temptation to gamble around releases. It is the calendar integrated into your routine, not consulted ad hoc.',
    },
    marketContext: 'A trader who maps the week\'s CPI/FOMC times into their plan calmly stands aside, while the unprepared trader gets caught oversized in the spike.',
    commonMistakes: ['checking the calendar only after a surprise move has already hit'],
    misconceptions: ['the calendar is just a list — mastery is a pre-planned response workflow'],
    riskNote: 'Pre-decide your response to each high-impact event — do not improvise in the spike.',
    related: ['economic-calendar', 'news-desk-protocol', 'daily-routine'], prerequisites: ['economic-calendar'],
    nextSteps: ['professional-journaling'], followups: ['news-desk-protocol', 'daily-routine'],
  }),
];
