// functions/knowledge/execution/concepts.js
// CATEGORY: execution (NEW, Phase 4) — entries, exits, scaling, stop management.

export const EXECUTION_CONCEPTS = [
  {
    id: 'entry-models', category: 'execution', topic: 'Entry Models', level: 'intermediate',
    title: 'Trade Entry Models', intent: 'strategy',
    concepts: ['entry model', 'trigger', 'confirmation', 'execution'],
    questionPatterns: ['what is an entry model', 'how do i enter a trade', 'best entry models', 'how to time an entry', 'what is a trade trigger'],
    canonical: {
      short: 'An entry model is your pre-defined trigger for getting into a trade — a sweep-and-reclaim, a structure break, or a rejection at a level. Naming the exact trigger removes guesswork and makes entries repeatable.',
      deep: 'Strong entry models share three parts you can point to: a level or zone you are reacting at, a trigger (break of minor structure, reclaim of a swept level, or a clear rejection candle), and a defined invalidation for the stop. Pick one or two models and master them rather than collecting many. The point is to pre-decide what a valid entry looks like so you act on rules, not impulse.',
    },
    responseObjective: 'educate', desiredOutcome: 'enter on a named, repeatable trigger',
    relevanceTags: ['execution', 'entry'],
    guidance: { tradeProblem: true },
    related: ['exit-models', 'gold-entry-confirmation', 'optimal-trade-entry'], prerequisites: ['market-structure'],
    nextSteps: ['exit-models'], followups: ['trade-management', 'optimal-trade-entry'],
    riskNote: 'No defined trigger, no trade — and always set the stop at invalidation.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'exit-models', category: 'execution', topic: 'Exit Models', level: 'intermediate',
    title: 'Trade Exit Models', intent: 'strategy',
    concepts: ['exit model', 'take profit', 'target', 'execution'],
    questionPatterns: ['what is an exit model', 'how do i exit a trade', 'where should i take profit', 'best exit strategy', 'how to set a target'],
    canonical: {
      short: 'An exit model is how you take profit — a fixed structure-based target, partials at set levels, or a structure trail. Decide it before entry, because mid-trade emotion makes the worst exit decisions.',
      deep: 'Common models: a single target at the next structural level, scaling out partials at preset reward multiples, or trailing the stop behind new structure to ride trends. Each suits a different style — fixed targets for range/scalp, trailing for trends. The discipline is choosing the model in advance and executing it mechanically, rather than grabbing profit from fear or holding from greed.',
    },
    responseObjective: 'mentor', desiredOutcome: 'exit by a pre-set model, not emotion',
    relevanceTags: ['execution', 'exit'],
    guidance: { tradeProblem: true },
    related: ['entry-models', 'partial-profits', 'trailing-stop'], prerequisites: ['risk-reward'],
    nextSteps: ['partial-profits'], followups: ['trailing-stop', 'trade-management'],
    riskNote: 'Plan the exit before entry — emotion makes poor exit choices.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'scaling-in', category: 'execution', topic: 'Scaling Into Trades', level: 'advanced',
    title: 'Scaling Into a Position', intent: 'strategy',
    concepts: ['scaling in', 'pyramiding', 'adding', 'execution'],
    questionPatterns: ['what is scaling into a trade', 'should i add to a winning trade', 'how to scale in', 'what is pyramiding', 'scaling in explained'],
    canonical: {
      short: 'Scaling in is adding to a position as it moves in your favour, building size on a winner — never on a loser. It only works when total risk is fixed in advance and each add has its own logic.',
      deep: 'Done right, you add at new confirmations (a fresh structure break or pullback hold) while moving the stop up so combined risk never exceeds your limit. Done wrong — adding to losers to average down — it magnifies risk on a trade already proven wrong. Scaling in is an advanced tool: pre-plan the add points and the blended stop so the position can never breach your fixed risk.',
    },
    responseObjective: 'warn', desiredOutcome: 'add to winners with fixed total risk, never to losers',
    relevanceTags: ['execution', 'scaling'],
    guidance: { tradeProblem: true },
    related: ['scaling-out', 'averaging-down', 'trade-management'], prerequisites: ['risk-per-trade', 'trade-management'],
    nextSteps: ['scaling-out'], followups: ['trade-management', 'risk-per-trade'],
    riskNote: 'Only scale into winners with a blended stop — never average down into losers.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'scaling-out', category: 'execution', topic: 'Scaling Out of Trades', level: 'intermediate',
    title: 'Scaling Out of a Position', intent: 'strategy',
    concepts: ['scaling out', 'partials', 'taking profit', 'execution'],
    questionPatterns: ['what is scaling out', 'should i take partial profits', 'how to scale out of a trade', 'scaling out explained', 'when to take partials'],
    canonical: {
      short: 'Scaling out means taking partial profit at one level and letting the rest run — it locks in gains while keeping upside. The trade-off is slightly lower expectancy for a smoother equity curve and easier psychology.',
      deep: 'Closing part of the position at a set reward (e.g. 1:1 or 1:2) and moving the stop to breakeven removes risk and reduces the emotional pressure to bail early, while the remainder targets a larger move. It is not mathematically optimal versus a single target, but the psychological benefit often improves real-world execution. Define the levels in advance so it is mechanical, not a fear reaction.',
    },
    responseObjective: 'educate', desiredOutcome: 'lock gains while keeping upside, by plan',
    relevanceTags: ['execution', 'partials'],
    guidance: { tradeProblem: true },
    related: ['partial-profits', 'breakeven-stop', 'exit-models'], prerequisites: ['risk-reward'],
    nextSteps: ['breakeven-stop'], followups: ['trailing-stop', 'cutting-winners-early'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'partial-profits', category: 'execution', topic: 'Taking Partial Profits', level: 'intermediate',
    title: 'Taking Partial Profits', intent: 'strategy',
    concepts: ['partial profits', 'partials', 'profit taking', 'execution'],
    questionPatterns: ['what are partial profits', 'should i take partial profit', 'how to take partials', 'when to take partial profit', 'partial profit strategy'],
    canonical: {
      short: 'Partial profits mean banking some of the position at a target while letting the rest run. It is a tool for managing emotion and securing gains — best applied by a pre-set rule, not by nerves.',
      deep: 'A common approach: take half at 1:1 or 1:2, move the stop to breakeven, and let the remainder aim for a structural target. This guarantees the trade cannot become a loss and reduces the urge to exit the whole position early. The risk is doing it impulsively, which caps your winners; tie partials to defined levels so the method is consistent across trades.',
    },
    responseObjective: 'educate', desiredOutcome: 'bank partial gains by rule, not nerves',
    relevanceTags: ['execution', 'partials'],
    guidance: { tradeProblem: true },
    related: ['scaling-out', 'breakeven-stop', 'cutting-winners-early'], prerequisites: ['risk-reward'],
    nextSteps: ['breakeven-stop'], followups: ['exit-models', 'trade-management'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'breakeven-stop', category: 'execution', topic: 'Breakeven Stops', level: 'intermediate',
    title: 'Moving Stops to Breakeven', intent: 'strategy',
    concepts: ['breakeven', 'stop management', 'risk free', 'execution'],
    questionPatterns: ['when should i move my stop to breakeven', 'what is a breakeven stop', 'how to make a trade risk free', 'should i move to breakeven', 'breakeven stop explained'],
    canonical: {
      short: 'Moving the stop to breakeven removes risk once a trade proves itself — but doing it too early just gets you tagged out before the move. Tie it to a structural event, not to fear.',
      deep: 'A good rule is to move to breakeven only after price forms a new structure point in your favour (a fresh higher low in an uptrend), so the stop sits behind real support, not arbitrarily under entry. Moving it the instant you are slightly green guarantees frequent breakeven stop-outs right before continuation. Make the trigger objective and consistent so it protects capital without strangling winners.',
    },
    responseObjective: 'mentor', desiredOutcome: 'de-risk on a structural trigger, not too early',
    relevanceTags: ['execution', 'stop management'],
    guidance: { tradeProblem: true },
    related: ['trailing-stop', 'scaling-out', 'trade-management'], prerequisites: ['market-structure'],
    nextSteps: ['trailing-stop'], followups: ['exit-models', 'trade-management'],
    riskNote: 'Move to breakeven on structure, not the moment you are green — early moves get tagged.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'trailing-stop', category: 'execution', topic: 'Trailing Stops', level: 'intermediate',
    title: 'Trailing Stops to Ride Trends', intent: 'strategy',
    concepts: ['trailing stop', 'ride trend', 'stop management', 'execution'],
    questionPatterns: ['what is a trailing stop', 'how do i trail my stop', 'how to ride a trend', 'trailing stop strategy', 'when to use a trailing stop'],
    canonical: {
      short: 'A trailing stop follows price by structure (behind each new swing) so you ride a trend while protecting open profit. It is how you capture big moves without guessing the exact top or bottom.',
      deep: 'Rather than a fixed target, trail the stop under each new higher low (uptrend) or above each lower high (downtrend), exiting only when structure finally breaks. This lets winners run for several times the initial risk during strong trends, at the cost of giving back some profit at the turn. Trail by structure, not an arbitrary pip distance, so the stop respects how the market actually moves.',
    },
    responseObjective: 'educate', desiredOutcome: 'ride trends by trailing behind structure',
    relevanceTags: ['execution', 'trailing'],
    guidance: { tradeProblem: true },
    related: ['breakeven-stop', 'trend-trading', 'exit-models'], prerequisites: ['market-structure', 'trend-trading'],
    nextSteps: ['trade-management'], followups: ['exit-models', 'trend-continuation'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
