// functions/knowledge/orders/concepts.js
// PHASE 21 — BEGINNER KNOWLEDGE FOUNDATION (category: orders)
// How orders actually get placed: market, limit, stop, and the four pending types.

const F = (o) => ({
  level: 'beginner', responseObjective: 'educate', journeyStages: ['journey-foundation'],
  status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en', ...o,
});

export const ORDERS_CONCEPTS = [
  F({
    id: 'order-types-overview', category: 'orders', topic: 'Order Types (Overview)', title: 'Order Types Overview',
    concepts: ['orders', 'execution', 'basics'],
    questionPatterns: ['what are the types of orders', 'what order types are there', 'market vs limit vs stop order', 'how do i place an order', 'what is an order in trading'],
    canonical: {
      short: 'An order is your instruction to buy or sell. The two families are market orders (execute now at the current price) and pending orders (wait for a price you choose — limit and stop orders). Choosing the right one controls your entry price and slippage.',
      deep: 'Every trade is placed through an order. A market order fills immediately at the best available price (fast, but you accept the current spread and possible slippage). Pending orders wait for a specific price: limits enter at a better price than now, stops enter once price moves past a level. Learning when to use each lets a beginner enter with discipline — at a planned level — instead of impulsively clicking the market.',
    },
    desiredOutcome: 'pick market vs pending orders deliberately for a planned entry',
    relevanceTags: ['orders', 'execution', 'beginner'],
    commonMistakes: ['always using market orders and chasing price impulsively'],
    misconceptions: ['that all orders fill instantly at the price you see'],
    prerequisites: ['what-is-trading'], nextSteps: ['market-order', 'pending-order'], related: ['entry-models', 'execution-models'],
    followups: ['market-order'],
  }),
  F({
    id: 'market-order', category: 'orders', topic: 'Market Order', title: 'Market Order',
    concepts: ['market-order', 'execution', 'basics'],
    questionPatterns: ['what is a market order', 'what does market order mean', 'how does a market order work', 'should i use a market order', 'market order vs limit order'],
    canonical: {
      short: 'A market order buys or sells immediately at the current best price. It guarantees you get in, but not the exact price — in fast or thin markets you may get slippage. Use it when getting in matters more than a perfect entry.',
      deep: 'A market order executes right away at whatever price is available, so it prioritises certainty of execution over price. In liquid conditions the fill is close to what you see; around news or on illiquid instruments it can slip several pips worse. Market orders suit confirmed setups where you want in now; for precise level entries, a pending order is usually better.',
    },
    desiredOutcome: 'use market orders for immediacy, knowing slippage is possible',
    relevanceTags: ['market-order', 'execution', 'beginner'],
    commonMistakes: ['firing market orders into news and getting heavy slippage'],
    misconceptions: ['that a market order always fills at the exact displayed price'],
    prerequisites: ['order-types-overview'], nextSteps: ['limit-order', 'stop-order'], related: ['slippage', 'bid-ask-price'],
    followups: ['limit-order'],
    riskNote: 'Avoid market orders in the seconds around high-impact news — slippage can be severe.',
  }),
  F({
    id: 'limit-order', category: 'orders', topic: 'Limit Order', title: 'Limit Order',
    concepts: ['limit-order', 'pending-order', 'basics'],
    questionPatterns: ['what is a limit order', 'what does limit order mean', 'how does a limit order work', 'buy limit vs sell limit', 'when to use a limit order'],
    canonical: {
      short: 'A limit order waits to enter at a better price than the current one — a buy limit sits below price, a sell limit sits above. You get your chosen price if it is reached, but the trade may never trigger if price runs away.',
      deep: 'A limit order is a pending order set at a more favourable price than the current market: a buy limit below price (to buy a dip into support), a sell limit above price (to sell a rally into resistance). The benefit is a precise, planned entry and no chasing; the trade-off is that price may not reach your level, so you miss the move. Limits suit traders who plan entries at specific levels in advance.',
    },
    desiredOutcome: 'enter at a planned level with a limit instead of chasing',
    relevanceTags: ['limit-order', 'pending-order', 'beginner'],
    commonMistakes: ['placing limits at random prices instead of real support/resistance'],
    misconceptions: ['that a limit order guarantees the trade will happen'],
    prerequisites: ['order-types-overview'], nextSteps: ['stop-order', 'pending-order'], related: ['support-resistance', 'buy-limit-sell-limit'],
    followups: ['stop-order'],
  }),
  F({
    id: 'stop-order', category: 'orders', topic: 'Stop Order', title: 'Stop (Entry) Order',
    concepts: ['stop-order', 'pending-order', 'basics'],
    questionPatterns: ['what is a stop order', 'what is a stop entry order', 'how does a stop order work', 'buy stop vs sell stop', 'stop order vs stop loss'],
    canonical: {
      short: 'A stop (entry) order triggers once price moves past a level you set — a buy stop sits above price, a sell stop sits below. Traders use it to enter on a breakout, only getting in if momentum confirms. (Note: this is different from a stop loss.)',
      deep: 'A stop entry order activates when price trades through your chosen level, in the direction of the move: a buy stop above current price (to join an upside breakout), a sell stop below (to join a breakdown). It is the classic breakout-entry tool — you only participate if price proves momentum by reaching the level. Do not confuse it with a stop loss, which is the order that closes a trade to cap a loss.',
    },
    desiredOutcome: 'use stop orders to enter breakouts on confirmation',
    relevanceTags: ['stop-order', 'breakout', 'beginner'],
    commonMistakes: ['confusing a stop entry order with a stop loss'],
    misconceptions: ['that a stop order and a stop loss are the same thing'],
    prerequisites: ['order-types-overview'], nextSteps: ['pending-order', 'stop-loss-basics'], related: ['breakout-basics', 'buy-stop-sell-stop'],
    followups: ['pending-order'],
  }),
  F({
    id: 'pending-order', category: 'orders', topic: 'Pending Orders', title: 'Pending Orders',
    concepts: ['pending-order', 'execution', 'basics'],
    questionPatterns: ['what is a pending order', 'what does pending order mean', 'types of pending orders', 'how do pending orders work', 'pending order vs market order'],
    canonical: {
      short: 'A pending order waits at a price you set and only fills if price gets there. The four types are buy limit and sell limit (better price than now) and buy stop and sell stop (breakout past a level). They let you trade your plan without watching the screen.',
      deep: 'Pending orders automate disciplined entries: you decide the level in advance and the broker triggers the trade if price reaches it. Limits enter at a more favourable price (buy limit below, sell limit above); stops enter on breakout (buy stop above, sell stop below). Pending orders free a beginner from impulse-clicking and let setups execute even while away — paired with a pre-set stop loss and take profit, the whole trade is planned before it starts.',
    },
    desiredOutcome: 'pre-place planned entries so trades execute without screen-watching',
    relevanceTags: ['pending-order', 'execution', 'beginner'],
    commonMistakes: ['setting pending orders but forgetting to attach a stop loss'],
    misconceptions: ['that a pending order will always be filled'],
    prerequisites: ['limit-order', 'stop-order'], nextSteps: ['buy-limit-sell-limit', 'buy-stop-sell-stop'], related: ['trading-plan', 'entry-models'],
    followups: ['buy-limit-sell-limit'],
  }),
  F({
    id: 'buy-limit-sell-limit', category: 'orders', topic: 'Buy Limit & Sell Limit', title: 'Buy Limit and Sell Limit',
    concepts: ['limit-order', 'pending-order', 'basics'],
    questionPatterns: ['what is a buy limit', 'what is a sell limit', 'buy limit vs sell limit', 'where do i place a buy limit', 'how to use sell limit'],
    canonical: {
      short: 'A buy limit is placed below the current price to buy a dip (often at support); a sell limit is placed above to sell a rally (often at resistance). Both aim for a better entry, assuming price comes back to your level first.',
      deep: 'Buy limit and sell limit are the two "better-price" pending orders. A buy limit below price suits buying a pullback into support within an uptrend; a sell limit above price suits selling a pullback into resistance within a downtrend. They reward patience with a tighter stop and better risk-to-reward, at the cost of sometimes missing trades that never pull back. Anchor them to real levels, not arbitrary prices.',
    },
    desiredOutcome: 'place limits at real support/resistance for better entries',
    relevanceTags: ['limit-order', 'pending-order', 'beginner'],
    commonMistakes: ['placing a buy limit into a strong downtrend hoping to catch a falling knife'],
    misconceptions: ['that limits work anywhere rather than at meaningful levels'],
    prerequisites: ['limit-order'], nextSteps: ['buy-stop-sell-stop'], related: ['support-resistance', 'optimal-trade-entry'],
    followups: ['buy-stop-sell-stop'],
  }),
  F({
    id: 'buy-stop-sell-stop', category: 'orders', topic: 'Buy Stop & Sell Stop', title: 'Buy Stop and Sell Stop',
    concepts: ['stop-order', 'pending-order', 'breakout', 'basics'],
    questionPatterns: ['what is a buy stop', 'what is a sell stop', 'buy stop vs sell stop', 'how to use a buy stop', 'where do i place a sell stop'],
    canonical: {
      short: 'A buy stop sits above price to join an upside breakout; a sell stop sits below price to join a downside breakout. Both enter only when momentum carries price through your level, so you trade confirmation rather than prediction.',
      deep: 'Buy stop and sell stop are the breakout pending orders. A buy stop above resistance enters once price breaks up through it; a sell stop below support enters once price breaks down. They suit traders who want to participate only when the market proves direction, with the stop loss placed back inside the broken level. The risk is the false breakout, so combining them with a close-confirmation or retest plan improves the odds.',
    },
    desiredOutcome: 'join confirmed breakouts with stop entries and a protective stop',
    relevanceTags: ['stop-order', 'breakout', 'beginner'],
    commonMistakes: ['placing breakout stops so close to the level that normal noise triggers them'],
    misconceptions: ['that a stop entry guarantees the breakout will follow through'],
    prerequisites: ['stop-order', 'breakout-basics'], nextSteps: ['stop-loss-basics'], related: ['breakout-trading', 'false-breakout-trading'],
    followups: ['stop-loss-basics'],
    riskNote: 'False breakouts happen — keep the stop loss back inside the broken structure.',
  }),
  F({
    id: 'entry-and-exit', category: 'orders', topic: 'Entry and Exit', title: 'Entries and Exits',
    concepts: ['entry', 'exit', 'execution', 'basics'],
    questionPatterns: ['what is an entry and exit', 'how do i enter and exit a trade', 'when should i exit a trade', 'what is a trade entry', 'how to exit a trade'],
    canonical: {
      short: 'An entry is where you open a trade; an exit is where you close it — either at your stop loss (idea wrong) or take profit (idea worked). A complete trade plans all three before entering: entry, stop, and target.',
      deep: 'Entries and exits are the bookends of every trade. A disciplined trade defines, in advance: the entry (the level and trigger), the stop loss (where the idea is proven wrong), and the take profit (a logical target, ideally giving at least 1.5–2x the risk). Planning exits before entering removes emotion at the moment it matters most — you simply follow the plan instead of reacting to each candle.',
    },
    desiredOutcome: 'plan entry, stop and target before opening any trade',
    relevanceTags: ['entry', 'exit', 'beginner'],
    commonMistakes: ['entering with no pre-planned stop or target and improvising under pressure'],
    misconceptions: ['that a good entry matters more than a planned exit'],
    prerequisites: ['order-types-overview'], nextSteps: ['stop-loss-basics', 'take-profit-basics'], related: ['trading-plan', 'risk-reward'],
    followups: ['stop-loss-basics'],
    riskNote: 'Never enter without already knowing where your stop loss goes.',
  }),
];
