// functions/knowledge/institutional/concepts.js
// CATEGORY: institutional (NEW, Phase 6) — order flow, liquidity engineering, traps.

export const INSTITUTIONAL_CONCEPTS = [
  {
    id: 'institutional-order-flow', category: 'institutional', topic: 'Institutional Order Flow', level: 'advanced',
    title: 'Institutional Order Flow', intent: 'technical',
    concepts: ['order flow', 'institutional', 'big players', 'smart money'],
    questionPatterns: ['what is institutional order flow', 'how do institutions move price', 'what is order flow', 'how does smart money trade', 'institutional order flow explained'],
    canonical: {
      short: 'Institutional order flow is the footprint of large players who must build positions in pieces — they cannot fill size without leaving clues in liquidity sweeps, displacement, and order blocks. Reading it means following the size, not fighting it.',
      deep: 'Because big orders move price, institutions accumulate quietly, engineer liquidity to fill (running obvious highs/lows), then expand in their true direction. You cannot see their orders, but you can read the footprint: sweeps of obvious levels, sharp displacement that breaks structure, and the order blocks left behind. Trading with that flow — entering on pullbacks into the zones they defended — aligns you with the only participants big enough to move the market.',
    },
    responseObjective: 'educate', desiredOutcome: 'align with institutional flow instead of fighting it',
    relevanceTags: ['institutional', 'order flow', 'smart money'],
    guidance: { tradeProblem: true },
    related: ['liquidity-engineering', 'order-block', 'market-maker-model'], prerequisites: ['market-structure', 'liquidity-sweep'],
    nextSteps: ['liquidity-engineering'], followups: ['order-block', 'displacement'],
    riskNote: 'You cannot see their orders — trade the footprint with a defined stop.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'liquidity-engineering', category: 'institutional', topic: 'Liquidity Engineering', level: 'advanced',
    title: 'How Liquidity Is Engineered', intent: 'technical',
    concepts: ['liquidity engineering', 'manipulation', 'stops', 'institutional'],
    questionPatterns: ['what is liquidity engineering', 'how is liquidity created', 'how do institutions create liquidity', 'how does smart money engineer traps', 'liquidity engineering explained'],
    canonical: {
      short: 'Liquidity engineering is how big players manufacture the orders they need: pushing price to form obvious highs, lows, and equal levels so retail stops and breakout orders cluster there — then sweeping them to fill. The "obvious" level is often the bait.',
      deep: 'Markets need counterparties for size, so price is nudged to create pools: equal highs/lows, trendlines, and round numbers attract stops and breakout entries. Institutions then run those pools (the sweep) to fill their position, before reversing. Recognising engineered liquidity flips your perspective — the cleaner and more obvious a level looks, the more likely it is a target. Trade the sweep-and-reclaim, and place your own stops away from the obvious pool.',
    },
    responseObjective: 'educate', desiredOutcome: 'spot engineered liquidity and avoid being the bait',
    relevanceTags: ['institutional', 'liquidity', 'manipulation'],
    guidance: { tradeProblem: true },
    related: ['institutional-order-flow', 'inducement', 'stop-hunt-model'], prerequisites: ['liquidity-sweep', 'inducement'],
    nextSteps: ['stop-hunt-model'], followups: ['inducement', 'market-maker-model'],
    riskNote: 'The most obvious level is often the target — hide stops beyond the pool.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'stop-hunt-model', category: 'institutional', topic: 'Stop Hunt Model', level: 'advanced',
    title: 'The Stop Hunt Model', intent: 'technical',
    concepts: ['stop hunt model', 'liquidity grab', 'reversal', 'institutional'],
    questionPatterns: ['what is the stop hunt model', 'how to trade stop hunts', 'stop hunt model explained', 'how do institutions hunt stops', 'why does price hit my stop then reverse'],
    canonical: {
      short: 'The stop-hunt model trades the predictable run on obvious stops: price sweeps beyond a high or low, fails, and reverses. The setup is the reclaim — enter as price comes back inside, stop beyond the sweep extreme.',
      deep: 'Stops cluster in obvious places, so a reliable institutional pattern is to spike through them, fill, and reverse. The model: identify the obvious liquidity, wait for the sweep, require a fast reclaim and a minor structure shift, then enter the reversal toward the opposite liquidity with a tight stop beyond the extreme. This turns the move that stops out retail into a high-probability, well-defined entry.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade the reclaim after a stop run, not the spike',
    relevanceTags: ['institutional', 'stop hunt', 'reversal'],
    guidance: { tradeProblem: true },
    related: ['stop-hunt', 'liquidity-engineering', 'reversal-models'], prerequisites: ['stop-hunt', 'liquidity-sweep'],
    nextSteps: ['institutional-footprint'], followups: ['reversal-models', 'inducement'],
    riskNote: 'Enter on the reclaim with a stop beyond the sweep extreme — never the spike.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'institutional-footprint', category: 'institutional', topic: 'Institutional Footprint', level: 'advanced',
    title: 'Reading the Institutional Footprint', intent: 'technical',
    concepts: ['footprint', 'institutional', 'evidence', 'intent'],
    questionPatterns: ['what is the institutional footprint', 'how to read institutional activity', 'signs of institutional trading', 'how to spot smart money', 'institutional footprint explained'],
    canonical: {
      short: 'The institutional footprint is the visible evidence big players leave: liquidity sweeps, sharp displacement, fair value gaps, and defended order blocks. You read intent from these clues rather than from any single candle.',
      deep: 'No retail trader sees institutional orders, but their size leaves a trail: a sweep of obvious liquidity, a violent displacement leg that breaks structure and leaves an imbalance, then a return to the originating order block. Stacking these clues at one location reveals genuine intent. The skill is patience — waiting for the full footprint to print before entering, rather than reacting to noise.',
    },
    responseObjective: 'educate', desiredOutcome: 'read intent from stacked institutional clues',
    relevanceTags: ['institutional', 'footprint'],
    guidance: { tradeProblem: true },
    related: ['institutional-order-flow', 'displacement', 'fair-value-gap'], prerequisites: ['displacement', 'order-block'],
    nextSteps: ['absorption'], followups: ['order-block', 'fair-value-gap'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'absorption', category: 'institutional', topic: 'Absorption', level: 'advanced',
    title: 'Absorption (Stalling Momentum)', intent: 'technical',
    concepts: ['absorption', 'stalling', 'large orders', 'institutional'],
    questionPatterns: ['what is absorption in trading', 'what does absorption mean', 'how to spot absorption', 'absorption explained', 'why does price stall at a level'],
    canonical: {
      short: 'Absorption is when heavy selling (or buying) hits a level but price barely moves — large hidden orders are soaking it up. It often precedes a reversal, because the side doing the absorbing is winning quietly.',
      deep: 'When you see strong effort (big candles or repeated pushes) into a level but little result (price stalls), a large participant is absorbing the flow. That mismatch between effort and result is a classic clue: the absorbing side is accumulating against the obvious move. Combined with a level and a subsequent structure shift, absorption helps you anticipate reversals before they are obvious on price alone.',
    },
    responseObjective: 'educate', desiredOutcome: 'spot effort-vs-result mismatches before reversals',
    relevanceTags: ['institutional', 'absorption'],
    guidance: { tradeProblem: true },
    related: ['institutional-footprint', 'exhaustion', 'rejection-wick'], prerequisites: ['institutional-footprint'],
    nextSteps: ['exhaustion'], followups: ['rejection-wick', 'reversal-models'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'exhaustion', category: 'institutional', topic: 'Trend Exhaustion', level: 'advanced',
    title: 'Trend Exhaustion', intent: 'technical',
    concepts: ['exhaustion', 'climax', 'reversal', 'momentum'],
    questionPatterns: ['what is trend exhaustion', 'how to spot exhaustion', 'signs a trend is ending', 'exhaustion explained', 'what is a buying climax'],
    canonical: {
      short: 'Exhaustion is the end-of-move climax: a sharp, often emotional push that runs into a wall and stalls, signalling the trend is running out of fuel. It marks where late buyers (or sellers) are trapped.',
      deep: 'Trends end when the last participants pile in — a steep, accelerating move into obvious liquidity, followed by a stall and rejection. That climax often coincides with absorption and a liquidity sweep, trapping the latecomers who chased. Exhaustion is a warning to stop adding and watch for a structure shift, not an instant short — wait for the change of character to confirm the turn.',
    },
    responseObjective: 'warn', desiredOutcome: 'recognise climaxes and stop chasing late',
    relevanceTags: ['institutional', 'exhaustion', 'reversal'],
    guidance: { tradeProblem: true },
    related: ['absorption', 'gold-trend-strength', 'trend-reversal'], prerequisites: ['absorption'],
    nextSteps: ['reversal-models'], followups: ['trend-reversal', 'chasing-price'],
    riskNote: 'Exhaustion warns you to stop chasing — wait for structure to confirm the turn.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
];
