// functions/knowledge/strategy/concepts.js
// CATEGORY: strategy (NEW, Phase 2) — styles, breakouts, edge construction.

export const STRATEGY_CONCEPTS = [
  {
    id: 'scalping', category: 'strategy', topic: 'Scalping', level: 'intermediate',
    title: 'Scalping Strategy', intent: 'strategy',
    concepts: ['scalping', 'short term', 'fast', 'low timeframe', 'strategy'],
    questionPatterns: ['what is scalping', 'how does scalping work', 'is scalping good for beginners', 'scalping strategy explained', 'how to scalp trade'],
    canonical: {
      short: 'Scalping takes many small, fast trades on low timeframes, aiming for tiny moves with tight risk. It demands sharp execution, low spreads, and emotional control — costs and slippage eat careless scalpers alive.',
      deep: 'Because targets are small, scalping lives or dies on execution and cost: tight spreads, fast fills, and a broker with clean execution are non-negotiable, and a single oversized loss can wipe many wins. It suits focused traders in high-liquidity sessions who can follow a rigid checklist without hesitation. For most beginners a slower style is kinder while discipline is still forming.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge whether scalping fits your costs and temperament',
    relevanceTags: ['strategy', 'scalping'],
    guidance: { tradeProblem: true },
    related: ['swing-trading', 'trading-style-fit', 'spread'], prerequisites: ['timeframe-selection'],
    nextSteps: ['trading-style-fit'], followups: ['swing-trading', 'forex-sessions'],
    riskNote: 'One oversized loss erases many scalps — fixed small risk is mandatory.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'swing-trading', category: 'strategy', topic: 'Swing Trading', level: 'intermediate',
    title: 'Swing Trading Strategy', intent: 'strategy',
    concepts: ['swing trading', 'multi day', 'higher timeframe', 'patience', 'strategy'],
    questionPatterns: ['what is swing trading', 'how does swing trading work', 'is swing trading good for beginners', 'swing trading strategy explained', 'swing vs day trading'],
    canonical: {
      short: 'Swing trading holds positions for days to weeks, trading higher-timeframe structure for larger moves. It needs patience and wider stops but far less screen time — often the most realistic style for people with jobs.',
      deep: 'By trading the daily and 4-hour structure, swing traders ride bigger legs and avoid intraday noise, accepting wider stops in exchange for fewer, higher-quality trades. The trade-offs are overnight risk (news, swap) and the patience to hold through pullbacks. For beginners with limited screen time, swing trading\'s slower pace makes discipline easier to build than the pressure of scalping.',
    },
    responseObjective: 'educate', desiredOutcome: 'decide if swing trading fits your schedule and patience',
    relevanceTags: ['strategy', 'swing'],
    guidance: { tradeProblem: true },
    related: ['scalping', 'trend-trading', 'trading-style-fit'], prerequisites: ['timeframe-selection'],
    nextSteps: ['trend-trading'], followups: ['trading-style-fit', 'swap'],
    riskNote: 'Wider stops mean smaller lots — keep risk at ~1% and mind overnight news.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'trend-trading', category: 'strategy', topic: 'Trend Trading', level: 'beginner',
    title: 'Trend Trading Strategy', intent: 'strategy',
    concepts: ['trend trading', 'with trend', 'momentum', 'pullback', 'strategy'],
    questionPatterns: ['what is trend trading', 'how to trade with the trend', 'trend trading strategy', 'how does trend following work', 'is trend trading profitable'],
    canonical: {
      short: 'Trend trading joins an established direction on pullbacks and holds until structure breaks. It is the most forgiving edge because momentum and the crowd are on your side — the hard part is patience for the pullback.',
      deep: 'Identify the trend from structure, wait for a retracement to a higher low (uptrend) or lower high (downtrend), enter on continuation confirmation, and ride to the next swing. The discipline is resisting the urge to pick tops/bottoms — until structure clearly breaks, the trend is the high-probability side. Trend trading pairs naturally with risk-reward because trends offer room for targets several times your stop.',
    },
    responseObjective: 'educate', desiredOutcome: 'ride trends on pullbacks rather than fading them',
    relevanceTags: ['strategy', 'trend'],
    guidance: { tradeProblem: true },
    related: ['trend-continuation', 'range-trading', 'trending-market'], prerequisites: ['market-structure'],
    nextSteps: ['range-trading'], followups: ['breakout-trading', 'risk-reward'],
    riskNote: 'Trade with the trend until structure breaks — fading strength is low-probability.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'range-trading', category: 'strategy', topic: 'Range Trading', level: 'intermediate',
    title: 'Range Trading Strategy', intent: 'strategy',
    concepts: ['range trading', 'sideways', 'support resistance', 'mean reversion', 'strategy'],
    questionPatterns: ['what is range trading', 'how to trade a range', 'range trading strategy', 'how to trade sideways markets', 'range vs trend trading'],
    canonical: {
      short: 'Range trading fades the edges of a sideways market — selling resistance, buying support — and avoids the chop in the middle. It works only while the range holds, so respecting a clean breakout is part of the strategy.',
      deep: 'In balanced markets price oscillates between a defined top and bottom; the edge is reacting at the boundaries with stops just beyond them, targeting the opposite edge. The killer is treating every market as a range — once a decisive break occurs, the range is dead and forcing reversion donates money. Identify range vs trend first, trade the edges while it holds, and switch to breakout logic when it ends.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade range edges and respect the break',
    relevanceTags: ['strategy', 'range'],
    guidance: { tradeProblem: true },
    related: ['range-market', 'trend-trading', 'breakout-trading'], prerequisites: ['range-market', 'support-resistance'],
    nextSteps: ['breakout-trading'], followups: ['false-breakout-trading', 'trend-trading'],
    riskNote: 'Trade the edges, not the middle, and exit the bias when the range breaks.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'breakout-trading', category: 'strategy', topic: 'Breakout Trading', level: 'intermediate',
    title: 'Breakout Trading Strategy', intent: 'strategy',
    concepts: ['breakout', 'range break', 'continuation', 'momentum', 'strategy'],
    questionPatterns: ['what is breakout trading', 'how to trade breakouts', 'breakout strategy explained', 'how to trade a range breakout', 'are breakouts profitable'],
    canonical: {
      short: 'Breakout trading enters as price escapes a level or range with momentum, aiming to ride the expansion. The edge depends on filtering real breaks from traps — a clean close and follow-through, not just a poke past the line.',
      deep: 'A genuine breakout shows displacement and holds on a retest; a trap pokes through, fails to follow, and reclaims the range. The two reliable entries are the momentum break with a close beyond the level, or — safer — the retest-and-hold of the broken level. Trading every break blindly is how traders get repeatedly stop-hunted; pairing breakouts with liquidity awareness (where stops sit) sharply improves the win rate.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade confirmed breaks, not every poke past a level',
    relevanceTags: ['strategy', 'breakout'],
    guidance: { tradeProblem: true },
    related: ['false-breakout-trading', 'range-trading', 'gold-breakout-failure'], prerequisites: ['support-resistance'],
    nextSteps: ['false-breakout-trading'], followups: ['liquidity-sweep', 'trend-trading'],
    riskNote: 'Require a close + follow-through (or retest) — blind breakout entries get trapped.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'false-breakout-trading', category: 'strategy', topic: 'False Breakouts', level: 'intermediate',
    title: 'Trading False Breakouts', intent: 'strategy',
    concepts: ['false breakout', 'fakeout', 'trap', 'reversal', 'strategy'],
    questionPatterns: ['what is a false breakout', 'how to trade false breakouts', 'how to avoid fakeouts', 'false breakout strategy', 'why do breakouts fail'],
    canonical: {
      short: 'A false breakout is a break that fails and reverses back inside the range — a trap that, once recognised, becomes a high-probability reversal setup. The tell is no follow-through and a fast reclaim of the level.',
      deep: 'Obvious levels attract breakout orders and stops, so price often runs them to grab liquidity, then snaps back. Instead of chasing the break, wait: if price breaks, fails to extend, and reclaims the level, enter the reversal with a stop beyond the false-break extreme, targeting the opposite side of the range. This flips the trap that catches breakout traders into your edge, and it pairs directly with liquidity-sweep logic.',
    },
    responseObjective: 'educate', desiredOutcome: 'turn failed breaks into reversal entries',
    relevanceTags: ['strategy', 'false breakout'],
    guidance: { tradeProblem: true },
    related: ['breakout-trading', 'liquidity-sweep', 'gold-breakout-failure'], prerequisites: ['breakout-trading', 'liquidity-sweep'],
    nextSteps: ['confluence'], followups: ['stop-hunt', 'range-trading'],
    riskNote: 'Enter on the reclaim with a stop beyond the false-break high/low.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'trading-style-fit', category: 'strategy', topic: 'Finding Your Trading Style', level: 'beginner',
    title: 'Finding the Right Trading Style', intent: 'strategy',
    concepts: ['trading style', 'personality', 'schedule', 'fit', 'strategy'],
    questionPatterns: ['which trading style is best for me', 'how do i find my trading style', 'scalping swing or day trading', 'what trading style suits beginners', 'how to choose a trading style'],
    canonical: {
      short: 'The best trading style is the one that fits your schedule, temperament, and capital — not the one that looks most exciting online. A style you can execute calmly and consistently beats a "better" one you cannot follow.',
      deep: 'If you have a day job, swing trading\'s slower pace fits; if you can focus intensely for short windows, intraday may suit. Impatient personalities struggle with swing holds; anxious ones struggle with scalping speed. Match the style to your real life and nature, then commit to it long enough to build a track record — constant style-hopping is one of the biggest reasons traders never become consistent.',
    },
    responseObjective: 'mentor', desiredOutcome: 'choose a sustainable style and commit to it',
    relevanceTags: ['strategy', 'style', 'fit'],
    guidance: { traderProblem: true },
    related: ['scalping', 'swing-trading', 'consistency'], prerequisites: [],
    nextSteps: ['timeframe-selection'], followups: ['consistency', 'trading-plan'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'timeframe-selection', category: 'strategy', topic: 'Timeframe Selection', level: 'beginner',
    title: 'Choosing Your Timeframes', intent: 'strategy',
    concepts: ['timeframe', 'multi timeframe', 'higher timeframe', 'entry timeframe', 'strategy'],
    questionPatterns: ['which timeframe should i trade', 'what is multi timeframe analysis', 'best timeframe for beginners', 'how to choose a timeframe', 'higher timeframe vs lower timeframe'],
    canonical: {
      short: 'Use a higher timeframe for direction and a lower one for entries — bias from above, timing from below. Trading a single timeframe in isolation is how traders fight the bigger picture without realising it.',
      deep: 'A simple, robust approach is top-down: read structure and bias on the daily/4-hour, then drop to the 1-hour/15-minute to time entries that agree with that bias. The higher timeframe keeps you on the right side; the lower one gives precise risk. Beginners often over-zoom into tiny timeframes and drown in noise — anchoring to a higher timeframe first filters most bad trades automatically.',
    },
    responseObjective: 'educate', desiredOutcome: 'align entries on a lower timeframe with higher-timeframe bias',
    relevanceTags: ['strategy', 'timeframe'],
    guidance: { tradeProblem: true },
    related: ['structural-bias', 'trading-style-fit', 'confluence'], prerequisites: ['market-structure'],
    nextSteps: ['confluence'], followups: ['structural-bias', 'trend-trading'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'confluence', category: 'strategy', topic: 'Confluence', level: 'intermediate',
    title: 'Trading With Confluence', intent: 'strategy',
    concepts: ['confluence', 'confirmation', 'stacking evidence', 'probability', 'strategy'],
    questionPatterns: ['what is confluence in trading', 'how to use confluence', 'what does confluence mean', 'how many confirmations do i need', 'confluence trading explained'],
    canonical: {
      short: 'Confluence is several independent signals agreeing at one price — trend, level, and a trigger lining up. It raises probability, but too many filters cause paralysis, so aim for a few strong factors, not a checklist of twenty.',
      deep: 'A trade with trend direction, a tested level, and a clean entry trigger all aligned is far stronger than any single factor alone. The art is balance: enough confluence to filter low-quality setups, not so much that no trade ever qualifies. Define your two or three core confluences in advance and take the trade when they stack — this removes hindsight bias and keeps your decisions consistent.',
    },
    responseObjective: 'educate', desiredOutcome: 'stack a few strong factors without over-filtering',
    relevanceTags: ['strategy', 'confluence'],
    guidance: { tradeProblem: true },
    related: ['timeframe-selection', 'edge-definition', 'gold-entry-confirmation'], prerequisites: ['market-structure'],
    nextSteps: ['edge-definition'], followups: ['backtesting', 'gold-entry-confirmation'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'edge-definition', category: 'strategy', topic: 'Defining Your Edge', level: 'advanced',
    title: 'Defining a Trading Edge', intent: 'strategy',
    concepts: ['edge', 'expectancy', 'system', 'rules', 'strategy'],
    questionPatterns: ['what is a trading edge', 'how do i find my edge', 'what makes a strategy profitable', 'how to define a trading edge', 'do i really have an edge'],
    canonical: {
      short: 'An edge is a repeatable set of conditions that produces positive expectancy over many trades — not a magic indicator. If you cannot describe your entry, exit, and risk in a sentence, you do not yet have an edge.',
      deep: 'Edge comes from a defined, testable process: specific conditions to enter, a rule to exit, fixed risk, and a positive expectancy (win rate × average reward minus losses) proven over a sample. It does not require a high win rate — a 40% strategy at 1:2 is a strong edge. Define it precisely, test it, then execute it consistently; vague "I trade what looks good" has no measurable edge and cannot be improved.',
    },
    responseObjective: 'mentor', desiredOutcome: 'define a testable, positive-expectancy process',
    relevanceTags: ['strategy', 'edge', 'expectancy'],
    guidance: { traderProblem: true },
    related: ['win-rate-vs-rr', 'backtesting', 'risk-reward'], prerequisites: ['risk-reward'],
    nextSteps: ['backtesting'], followups: ['win-rate-vs-rr', 'trading-plan'],
    riskNote: 'No defined edge means no measurable risk — define before you scale.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'backtesting', category: 'strategy', topic: 'Backtesting', level: 'intermediate',
    title: 'Backtesting a Strategy', intent: 'strategy',
    concepts: ['backtesting', 'testing', 'data', 'validation', 'strategy'],
    questionPatterns: ['what is backtesting', 'how do i backtest a strategy', 'why is backtesting important', 'how to backtest trading', 'backtesting explained'],
    canonical: {
      short: 'Backtesting checks a strategy against past price to see if it actually has an edge before you risk money. It builds both data and the confidence to follow your rules when live emotions hit.',
      deep: 'Manually or with software, run your exact rules over historical data and a forward demo period, logging win rate, average reward-to-risk, and worst drawdown. The goal is honest validation, not curve-fitting — beware tweaking until past data looks perfect. A backtested edge you trust is what lets you keep executing through a losing streak instead of abandoning the plan at the worst moment.',
    },
    responseObjective: 'educate', desiredOutcome: 'validate an edge before risking capital',
    relevanceTags: ['strategy', 'backtesting'],
    guidance: { tradeProblem: true },
    related: ['edge-definition', 'win-rate-vs-rr', 'trading-journal'], prerequisites: ['edge-definition'],
    nextSteps: ['trading-plan'], followups: ['win-rate-vs-rr', 'trading-journal'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'win-rate-vs-rr', category: 'strategy', topic: 'Win Rate vs Risk Reward', level: 'intermediate',
    title: 'Win Rate vs Risk-Reward', intent: 'strategy',
    concepts: ['win rate', 'risk reward', 'expectancy', 'tradeoff', 'strategy'],
    questionPatterns: ['win rate vs risk reward', 'is win rate or risk reward more important', 'do i need a high win rate', 'how do win rate and rr work together', 'what is expectancy'],
    canonical: {
      short: 'Win rate and reward-to-risk are two halves of expectancy — neither matters alone. A low win rate with big winners can crush a high win rate with tiny ones; what counts is their product over many trades.',
      deep: 'Expectancy = (win rate × average win) − (loss rate × average loss). A 40% win rate at 1:3 is highly profitable; a 70% win rate at 1:0.4 bleeds out. Chasing a high win rate often means cutting winners early and holding losers — the opposite of an edge. Decide which side your strategy leans on (frequent small wins vs rarer big ones) and build the rules to match, rather than obsessing over win rate alone.',
    },
    responseObjective: 'educate', desiredOutcome: 'judge a strategy by expectancy, not win rate alone',
    relevanceTags: ['strategy', 'expectancy', 'risk reward'],
    guidance: { tradeProblem: true },
    related: ['risk-reward', 'edge-definition', 'becoming-profitable'], prerequisites: ['risk-reward'],
    nextSteps: ['trading-plan'], followups: ['edge-definition', 'becoming-profitable'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'trade-management', category: 'strategy', topic: 'Trade Management', level: 'intermediate',
    title: 'Managing an Open Trade', intent: 'strategy',
    concepts: ['trade management', 'stop loss', 'take profit', 'breakeven', 'strategy'],
    questionPatterns: ['how do i manage a trade', 'when should i move my stop to breakeven', 'how to manage an open position', 'should i take partial profits', 'trade management explained'],
    canonical: {
      short: 'Trade management is everything after entry: where to take profit, when (if ever) to move the stop, and whether to scale out. Plan it before you enter, because mid-trade emotion makes terrible management decisions.',
      deep: 'Decide your management rules in advance: a fixed target from structure, optional partials at a set reward level, and clear criteria for moving to breakeven (e.g. after a new structure point forms, not out of fear). Moving a stop early "to be safe" often just guarantees getting tagged before the move; widening it to avoid a loss is worse. Pre-committed, mechanical management is what turns a good entry into a good result.',
    },
    responseObjective: 'mentor', desiredOutcome: 'manage trades by a pre-set plan, not emotion',
    relevanceTags: ['strategy', 'trade management'],
    guidance: { tradeProblem: true },
    related: ['risk-reward', 'execution-discipline', 'greed'], prerequisites: ['risk-reward'],
    nextSteps: ['trading-plan'], followups: ['execution-discipline', 'greed'],
    riskNote: 'Never widen a stop to avoid a loss — manage by the plan set before entry.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
