-- 028_notifications.sql
-- AI CEO OS — Cross-cutting
--
-- The five-class notification engine the Settings UI already names verbatim
-- ("Info/Reminder/Warning/Critical/Approval-Required" — src/presentation/
-- settings/index.html). `notification_class` is a real enum for the same
-- reason `client_lifecycle_stage` and `content_status` are: the value set is
-- already committed to on disk by a built UI, not merely conceptual.
-- No DELETE, no dismiss-by-removal: `is_read = true` is how a notification
-- leaves the active feed, consistent with the no-hard-deletes rule applied
-- to every other table.

create type public.notification_class as enum ('info', 'reminder', 'warning', 'critical', 'approval_required');

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references public.users (id) on delete cascade,
  class public.notification_class not null,
  title text not null,
  body text,
  action_url text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Certain access pattern: the notification feed is always "unread first,
-- most recent first."
create index notifications_owner_read_created_idx
  on public.notifications (owner_user_id, is_read, created_at desc);

alter table public.notifications enable row level security;

create policy notifications_owner_select
  on public.notifications for select
  using (owner_user_id = auth.uid() or public.is_admin());

create policy notifications_owner_update
  on public.notifications for update
  using (owner_user_id = auth.uid() or public.is_admin())
  with check (owner_user_id = auth.uid() or public.is_admin());

-- No INSERT policy for authenticated/anon — notifications are generated by
-- server-side logic (L4 automation, L3 mentor) via the service_role key, not
-- self-authored by the founder through the app. No DELETE policy
-- (no-hard-deletes rule) — see header note.
