// functions/knowledge/portfolio/concepts.js
// CATEGORY: portfolio (NEW, Phase 12) — portfolio management, allocation, multi-account.

const C = (o) => ({ status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en', guidance: { tradeProblem: true }, ...o });

export const PORTFOLIO_CONCEPTS = [
  C({
    id: 'portfolio-management', category: 'portfolio', topic: 'Portfolio Management', level: 'advanced', intent: 'riskmgmt',
    title: 'Portfolio Management for Traders',
    concepts: ['portfolio management', 'positions', 'exposure', 'diversification'],
    questionPatterns: ['what is portfolio management', 'how to manage a trading portfolio', 'portfolio management for traders', 'how to balance multiple trades', 'managing a book of trades'],
    canonical: {
      short: 'Portfolio management means running all your positions as one book — total exposure, correlation, and drawdown — rather than as isolated trades. The job is balancing return against risk across the whole, not maximising any single trade.',
      deep: 'A portfolio view caps total open risk, counts correlated trades as one bet, and judges performance by the equity curve, not individual wins. It shifts focus from "is this trade good?" to "what does this do to my overall risk?" That perspective prevents hidden concentration and emotional, position-by-position decisions, and is the foundation for scaling capital responsibly.',
    },
    marketContext: 'A trader long gold, silver, and AUD feels diversified but holds one big "weak-dollar" bet — portfolio thinking exposes that concentration.',
    commonMistakes: ['treating each trade in isolation and ignoring total correlated exposure'],
    misconceptions: ['more positions always means more diversification — correlated ones concentrate risk'],
    riskNote: 'Judge the book, not the trade — cap total exposure, not just per-trade risk.',
    related: ['portfolio-risk', 'asset-allocation', 'diversification'], prerequisites: ['portfolio-risk'],
    nextSteps: ['asset-allocation'], followups: ['diversification', 'capital-allocation'],
  }),
  C({
    id: 'asset-allocation', category: 'portfolio', topic: 'Asset Allocation', level: 'advanced', intent: 'riskmgmt',
    title: 'Asset Allocation',
    concepts: ['asset allocation', 'weighting', 'capital', 'diversification'],
    questionPatterns: ['what is asset allocation', 'how to allocate capital across assets', 'asset allocation explained', 'how much capital per market', 'allocating between gold forex indices'],
    canonical: {
      short: 'Asset allocation decides how your capital is weighted across markets and strategies — balancing higher-conviction edges against diversification. It is the strategic layer above individual position sizing.',
      deep: 'Allocation assigns capital weight by conviction, edge quality, and correlation: more to proven, uncorrelated edges, less to marginal or overlapping ones, with reserve for opportunity and drawdown. It connects per-trade risk to account strategy so no single market or theme can dominate the outcome while your best edges still carry enough weight to matter.',
    },
    marketContext: 'Multi-strategy funds allocate across uncorrelated books precisely so a blow-up in one cannot sink the whole — retail can mirror this at small scale.',
    commonMistakes: ['allocating all capital to one correlated theme or market'],
    misconceptions: ['allocation is only for big funds — small accounts benefit from it too'],
    riskNote: 'No single market or theme should hold enough weight to sink the account.',
    related: ['capital-allocation', 'portfolio-management', 'risk-parity'], prerequisites: ['portfolio-management'],
    nextSteps: ['diversification'], followups: ['risk-parity', 'multi-account-management'],
  }),
  C({
    id: 'diversification', category: 'portfolio', topic: 'Diversification', level: 'intermediate', intent: 'riskmgmt',
    title: 'Diversification in Trading',
    concepts: ['diversification', 'uncorrelated', 'risk reduction', 'spread'],
    questionPatterns: ['what is diversification in trading', 'how to diversify my trades', 'does diversification reduce risk', 'diversification explained', 'how many uncorrelated trades'],
    canonical: {
      short: 'Diversification spreads risk across uncorrelated ideas so one losing theme cannot sink you — but only genuine non-correlation helps. Holding five correlated longs is concentration dressed as diversification.',
      deep: 'True diversification requires uncorrelated return sources: different strategies, instruments that do not move together, and varied timeframes. Correlation tightens in crises, so even "diversified" books can move as one in panic. Used honestly it smooths the equity curve; used naively (many correlated positions) it amplifies risk. Always measure real correlation, not just the number of positions.',
    },
    marketContext: 'In March 2020 nearly all "diversified" risk assets fell together as correlations spiked to 1 — diversification failed exactly when it was needed.',
    commonMistakes: ['mistaking many correlated positions for diversification'],
    misconceptions: ['diversification always protects you — correlations rise in crises'],
    riskNote: 'Only genuine non-correlation diversifies — count real correlation, not position count.',
    related: ['portfolio-management', 'correlation', 'crisis-behaviour'], prerequisites: ['correlation'],
    nextSteps: ['rebalancing'], followups: ['portfolio-risk', 'asset-allocation'],
  }),
  C({
    id: 'rebalancing', category: 'portfolio', topic: 'Rebalancing', level: 'advanced', intent: 'riskmgmt',
    title: 'Portfolio Rebalancing',
    concepts: ['rebalancing', 'weights', 'drift', 'discipline'],
    questionPatterns: ['what is rebalancing', 'how to rebalance a portfolio', 'when to rebalance trades', 'rebalancing explained', 'how to manage position drift'],
    canonical: {
      short: 'Rebalancing returns your allocations to target after winners and losers shift the weights. It enforces "trim strength, add to plan" discipline so no position quietly grows into an oversized risk.',
      deep: 'As trades move, a winner can balloon into an outsized share of risk while losers shrink — drifting from your intended allocation. Rebalancing on a schedule or threshold trims the overweight and restores targets, mechanically taking profit from winners and preventing concentration. For active traders it mostly means capping how large any single position or theme is allowed to become.',
    },
    marketContext: 'A trend trader who lets one runaway winner become 60% of risk is one reversal from a large drawdown — rebalancing would have trimmed it.',
    commonMistakes: ['letting a winning position grow into an oversized share of total risk'],
    misconceptions: ['rebalancing means closing winners early — it means capping their risk share'],
    riskNote: 'Trim positions that drift into oversized risk — do not let one trade dominate.',
    related: ['asset-allocation', 'portfolio-management', 'trade-allocation'], prerequisites: ['asset-allocation'],
    nextSteps: ['multi-account-management'], followups: ['trade-allocation', 'portfolio-risk'],
  }),
  C({
    id: 'multi-account-management', category: 'portfolio', topic: 'Multi-Account Management', level: 'advanced', intent: 'riskmgmt',
    title: 'Managing Multiple Accounts',
    concepts: ['multi account', 'aggregate risk', 'prop', 'consistency'],
    questionPatterns: ['how to manage multiple trading accounts', 'multi account management', 'how to trade several prop accounts', 'managing multiple accounts risk', 'should i have multiple accounts'],
    canonical: {
      short: 'Managing multiple accounts (personal + prop, or several funded) demands aggregate risk thinking: the same trade across accounts multiplies exposure. Treat them as one book for risk, even if executed separately.',
      deep: 'Copying one setup across five accounts is five times the exposure to a single idea — the classic multi-account trap. Manage aggregate risk: cap how much of one trade hits across all accounts, respect each account\'s rules (especially prop drawdown), and keep execution consistent. The benefit is more capital and redundancy; the danger is hidden concentration if you forget the accounts share your one edge.',
    },
    marketContext: 'Traders running the same trade on multiple prop accounts have breached several at once on a single bad day — correlated by their own hand.',
    commonMistakes: ['copying one trade across many accounts and multiplying exposure unknowingly'],
    misconceptions: ['more accounts means more diversification — same trades across them is concentration'],
    riskNote: 'The same trade across accounts multiplies risk — manage aggregate exposure.',
    related: ['prop-firm-basics', 'portfolio-risk', 'asset-allocation'], prerequisites: ['portfolio-risk'],
    nextSteps: ['institutional-risk-management'], followups: ['prop-drawdown-rules', 'capital-allocation'],
  }),
  C({
    id: 'risk-parity', category: 'portfolio', topic: 'Risk Parity', level: 'advanced', intent: 'riskmgmt',
    title: 'Risk Parity',
    concepts: ['risk parity', 'equal risk', 'volatility weighting', 'allocation'],
    questionPatterns: ['what is risk parity', 'how does risk parity work', 'risk parity explained', 'equal risk allocation', 'how to weight by volatility'],
    canonical: {
      short: 'Risk parity allocates so each position contributes equal risk, not equal capital — sizing down volatile markets and up calm ones. It prevents one high-volatility instrument from dominating the portfolio\'s risk.',
      deep: 'Allocating equal dollars to a calm and a wild market means the wild one drives almost all the risk. Risk parity instead sizes by volatility so each contributes the same risk, producing a more balanced, smoother book. For traders it translates to: size positions by their volatility (ATR), not a fixed lot, so a quiet pair and a violent one carry comparable risk.',
    },
    marketContext: 'Equal-lot positions in EURUSD and a gold or exotic pair are not equal risk — the volatile instrument dominates the drawdown.',
    commonMistakes: ['using equal lot sizes across very different-volatility instruments'],
    misconceptions: ['equal capital means equal risk — volatility breaks that'],
    riskNote: 'Size by volatility so each position contributes balanced risk.',
    related: ['volatility-regimes', 'position-sizing', 'asset-allocation'], prerequisites: ['volatility-regimes', 'position-sizing'],
    nextSteps: ['kelly-sizing'], followups: ['portfolio-risk', 'asset-allocation'],
  }),
  C({
    id: 'kelly-sizing', category: 'portfolio', topic: 'Kelly Sizing', level: 'advanced', intent: 'riskmgmt',
    title: 'Kelly Criterion Sizing',
    concepts: ['kelly criterion', 'optimal sizing', 'edge', 'fractional kelly'],
    questionPatterns: ['what is the kelly criterion', 'how to use kelly sizing', 'kelly criterion explained', 'optimal position size', 'what is fractional kelly'],
    canonical: {
      short: 'The Kelly criterion calculates the mathematically optimal bet size from your edge (win rate and reward-to-risk). Most traders use a fraction of it (e.g. quarter-Kelly) because full Kelly is too volatile to trade comfortably.',
      deep: 'Kelly maximises long-run growth by sizing larger when the edge is bigger, but full Kelly produces stomach-churning swings and assumes you know your edge precisely — which you do not. So practitioners use fractional Kelly (a half or quarter) for smoother growth and a safety margin against overestimated edge. It formalises "bigger edge, slightly bigger size," but never overrides the survival-first ~1% discipline for most retail traders.',
    },
    marketContext: 'Full-Kelly position sizing can imply 20%+ per trade on a strong edge — far too volatile, which is why professionals scale it down to a fraction.',
    commonMistakes: ['using full Kelly and suffering huge swings, or overestimating the edge'],
    misconceptions: ['Kelly tells you to bet big — full Kelly is usually too aggressive to trade'],
    riskNote: 'Use a fraction of Kelly at most — overestimated edge plus full Kelly courts ruin.',
    related: ['risk-of-ruin', 'risk-per-trade', 'risk-parity'], prerequisites: ['risk-of-ruin'],
    nextSteps: ['capital-efficiency'], followups: ['professional-risk-models', 'risk-per-trade'],
  }),
  C({
    id: 'capital-efficiency', category: 'portfolio', topic: 'Capital Efficiency', level: 'advanced', intent: 'riskmgmt',
    title: 'Capital Efficiency',
    concepts: ['capital efficiency', 'margin', 'return on capital', 'leverage'],
    questionPatterns: ['what is capital efficiency', 'how to use capital efficiently', 'capital efficiency in trading', 'return on capital trading', 'how to make capital work harder'],
    canonical: {
      short: 'Capital efficiency is getting the most risk-adjusted return per dollar deployed — using margin and prop capital wisely without over-leveraging. The goal is higher return on capital, not higher risk.',
      deep: 'Efficient capital use means not tying up more margin than needed, possibly using funded/prop capital to free personal funds, and allocating to your highest-expectancy edges. But efficiency must never become over-leverage: the aim is better return per unit of risk, with survival still first. It is the bridge between pure risk control and the business goal of growing capital.',
    },
    marketContext: 'A trader using prop capital for size while keeping personal funds in reserve improves capital efficiency without risking savings.',
    commonMistakes: ['confusing capital efficiency with over-leverage'],
    misconceptions: ['efficient means using maximum leverage — it means best return per unit of risk'],
    riskNote: 'Efficiency is return per unit of risk — never a euphemism for over-leverage.',
    related: ['kelly-sizing', 'prop-firm-basics', 'capital-allocation'], prerequisites: ['capital-allocation'],
    nextSteps: ['institutional-risk-management'], followups: ['prop-firm-basics', 'risk-parity'],
  }),
  C({
    id: 'institutional-risk-management', category: 'portfolio', topic: 'Institutional Risk Management', level: 'advanced', intent: 'riskmgmt',
    title: 'Institutional Risk Management',
    concepts: ['institutional risk', 'var', 'limits', 'controls'],
    questionPatterns: ['what is institutional risk management', 'how do institutions manage risk', 'institutional risk controls', 'value at risk explained', 'professional risk management systems'],
    canonical: {
      short: 'Institutional risk management runs on hard, systematic controls: position limits, value-at-risk, drawdown triggers that force de-risking, and independent oversight. The principles scale down to any serious trader — rules enforced, not negotiated.',
      deep: 'Institutions cap exposure per position and per theme, estimate worst-case loss (VaR), and automatically cut gross risk when drawdown limits trip — with risk managers independent of traders. The retail equivalent is pre-set, non-negotiable rules: total-risk caps, daily/weekly limits, and a drawdown protocol you follow without exception. The lesson is enforcement: institutions survive because limits are policy, not willpower.',
    },
    marketContext: 'Funds automatically reduce gross exposure as portfolio VaR or drawdown limits are breached — a systematic version of the retail daily-loss-limit.',
    commonMistakes: ['having risk rules but not enforcing them when it is inconvenient'],
    misconceptions: ['institutional risk tools replace the basics — they scale them, not replace them'],
    riskNote: 'Institutions survive on enforced limits, not willpower — make your rules policy.',
    related: ['professional-risk-models', 'risk-budgeting', 'drawdown-protocol'], prerequisites: ['professional-risk-models'],
    nextSteps: ['portfolio-management'], followups: ['risk-budgeting', 'drawdown-protocol'],
  }),
  C({
    id: 'position-correlation', category: 'portfolio', topic: 'Position Correlation', level: 'intermediate', intent: 'riskmgmt',
    title: 'Managing Position Correlation',
    concepts: ['position correlation', 'exposure', 'concentration', 'risk'],
    questionPatterns: ['how does position correlation affect risk', 'what is correlated exposure', 'managing correlated positions', 'are my trades correlated', 'how to avoid correlated risk'],
    canonical: {
      short: 'Correlated positions move together, so several "separate" trades can secretly be one big bet. Counting that hidden correlation is essential to knowing your true risk before you add another trade.',
      deep: 'Long EURUSD and long GBPUSD is largely a single short-dollar position; long gold and silver is one precious-metals bet. Before adding a trade, check whether it duplicates exposure you already hold — if so, it adds risk without diversification. Managing position correlation means capping how much total risk sits in any one theme, so a single market move cannot hit your whole book at once.',
    },
    marketContext: 'A trader "spreading risk" across five USD pairs takes a full hit when the dollar moves — five trades, one bet.',
    commonMistakes: ['adding a correlated trade thinking it diversifies when it concentrates'],
    misconceptions: ['different instruments mean independent risk — correlation links them'],
    riskNote: 'Count correlated trades as one position — that is your real exposure.',
    related: ['correlation', 'portfolio-risk', 'diversification'], prerequisites: ['correlation'],
    nextSteps: ['diversification'], followups: ['portfolio-management', 'risk-budgeting'],
  }),
  C({
    id: 'drawdown-budgeting', category: 'portfolio', topic: 'Drawdown Budgeting', level: 'advanced', intent: 'riskmgmt',
    title: 'Drawdown Budgeting',
    concepts: ['drawdown budget', 'maximum loss', 'planning', 'survival'],
    questionPatterns: ['what is drawdown budgeting', 'how to budget for drawdown', 'how much drawdown should i plan for', 'drawdown budgeting explained', 'planning maximum loss'],
    canonical: {
      short: 'Drawdown budgeting plans your acceptable maximum loss in advance — monthly and overall — and sizes risk so normal losing streaks stay well within it. You decide your worst case before the market does.',
      deep: 'Knowing a strategy\'s expected losing streaks lets you set a drawdown budget (e.g. comfortable to -10%, hard stop at -15%) and size so a realistic run of losses never breaches it. This reverses the usual order: instead of discovering your max drawdown the hard way, you design for it. It connects risk-of-ruin math to a concrete plan and pairs with the drawdown protocol that governs how you de-risk inside the budget.',
    },
    marketContext: 'Prop firms hand you a drawdown budget (the max loss) — internalising that discipline on a personal account produces the same survival edge.',
    commonMistakes: ['not planning a max drawdown and discovering it during a blowup'],
    misconceptions: ['drawdown just happens — it can be budgeted and sized for in advance'],
    riskNote: 'Design for your worst realistic streak so it never breaches your limit.',
    related: ['max-drawdown', 'risk-budgeting', 'drawdown-protocol'], prerequisites: ['max-drawdown'],
    nextSteps: ['institutional-risk-management'], followups: ['drawdown-protocol', 'risk-of-ruin'],
  }),
  C({
    id: 'scaling-portfolio', category: 'portfolio', topic: 'Scaling a Portfolio', level: 'advanced', intent: 'career',
    title: 'Scaling a Trading Portfolio',
    concepts: ['scaling portfolio', 'growth', 'allocation', 'diversification'],
    questionPatterns: ['how to scale a trading portfolio', 'scaling a portfolio explained', 'how to grow multiple strategies', 'when to add a second strategy', 'how to diversify strategies'],
    canonical: {
      short: 'Scaling a portfolio means growing beyond one edge — adding size on proven strategies and introducing a second uncorrelated edge — while keeping total risk controlled. Growth comes from more quality edges, not more risk on one.',
      deep: 'Once a single strategy is consistently profitable, scaling can mean increasing its size by proven milestones and, eventually, adding an uncorrelated second strategy to smooth returns. Each addition must earn its place with a track record, and total portfolio risk stays capped. This is how serious traders compound — diversifying edges and capital deliberately rather than just risking more on the original idea.',
    },
    marketContext: 'A trader who masters one gold setup then adds an uncorrelated forex strategy smooths their equity curve versus doubling size on the original.',
    commonMistakes: ['adding a second strategy before the first is proven and consistent'],
    misconceptions: ['scaling means bigger size only — adding uncorrelated edges is the safer path'],
    riskNote: 'Each new edge must earn its place with a track record; keep total risk capped.',
    related: ['asset-allocation', 'risk-scaling', 'trading-business-growth'], prerequisites: ['risk-scaling'],
    nextSteps: ['portfolio-management'], followups: ['trading-business-growth', 'asset-allocation'],
  }),
];
