// functions/knowledge/discipline/concepts.js
// CATEGORY: discipline (NEW) — routines, rules, consistency, execution quality.

export const DISCIPLINE_CONCEPTS = [
  {
    id: 'trading-routine', category: 'discipline', topic: 'Trading Routine', level: 'beginner',
    title: 'Building a Trading Routine', intent: 'psychology',
    concepts: ['routine', 'preparation', 'habit', 'consistency', 'process'],
    questionPatterns: ['how do i build a trading routine', 'what should a trading routine include', 'why do i need a trading routine', 'daily routine for traders', 'how to prepare before trading'],
    canonical: {
      short: 'A trading routine is the repeatable set of steps you run before, during and after the session — it turns trading from improvisation into a process. Consistency of behaviour is what eventually produces consistency of results.',
      deep: 'A solid routine has three parts: preparation (mark key levels, check the calendar, set your bias and risk), execution (follow your checklist, take only valid setups, honour your limits), and review (journal trades and how you behaved). Running the same routine every day removes decision fatigue and emotional improvisation, so your good habits fire automatically. It also makes problems visible — when results slip, you can examine which part of the routine broke. Process consistency comes first; performance consistency follows it, not the other way around.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade from a repeatable process, not improvisation',
    relevanceTags: ['discipline', 'routine', 'process'],
    guidance: { traderProblem: true },
    related: ['checklist', 'habit-building', 'consistency'], prerequisites: ['trading-discipline'],
    nextSteps: ['checklist'], followups: ['habit-building', 'consistency'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'checklist', category: 'discipline', topic: 'Trading Checklist', level: 'beginner',
    title: 'Using a Trading Checklist', intent: 'psychology',
    concepts: ['checklist', 'rules', 'criteria', 'execution', 'discipline'],
    questionPatterns: ['what should be on my trading checklist', 'why use a trading checklist', 'how to make a trade checklist', 'trading checklist for beginners', 'how to check a setup before entering'],
    canonical: {
      short: 'A checklist turns your strategy into a few yes/no questions you must answer before risking money — trend, level, trigger, risk defined. It removes impulse from the moment of entry, which is exactly where most mistakes happen.',
      deep: 'Even pilots with thousands of hours use checklists, because they prevent skilled people from skipping steps under pressure. Yours should be short and specific: is there a trend I am following, am I at a real level, is my trigger present, is my stop defined and risk ≤1%? If every box is ticked, you take the trade; if not, you pass without debate. The power is in pre-deciding what a valid trade looks like so you are not negotiating with yourself when emotions are highest. A few honest checks at entry save a lot of regret later.',
    },
    responseObjective: 'mentor', desiredOutcome: 'gate every entry through a short objective checklist',
    relevanceTags: ['discipline', 'checklist', 'rules'],
    guidance: { traderProblem: true },
    related: ['trading-routine', 'rule-following', 'trade-assessment'], prerequisites: ['trading-discipline'],
    recommendedAssessment: 'trade',
    nextSteps: ['rule-following'], followups: ['trading-routine', 'trade-assessment'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'rule-following', category: 'discipline', topic: 'Following Rules', level: 'beginner',
    title: 'Following Your Trading Rules', intent: 'psychology',
    concepts: ['rules', 'discipline', 'consistency', 'self-trust', 'execution'],
    questionPatterns: ['why cant i follow my trading rules', 'how to stick to my trading rules', 'i break my own rules trading', 'how to be disciplined with rules', 'following trading rules'],
    canonical: {
      short: 'Breaking your own rules is the most common reason good strategies still lose money. The fix is fewer, clearer rules you can actually keep, plus reviewing whether you followed them — not just whether you won.',
      deep: 'Most traders do not have a strategy problem, they have a rule-following problem: they know what to do and do something else under pressure. Two things help enormously. First, make the rules few and unambiguous, because a long, vague rulebook is impossible to honour. Second, grade yourself on adherence — at review, mark each trade as "rules followed" or not, separate from its profit. This shifts the scoreboard to behaviour you control, and every kept rule builds the self-trust that makes the next one easier. Discipline is a stack of small promises kept to yourself.',
    },
    responseObjective: 'mentor', desiredOutcome: 'keep rules by making them few and self-graded',
    relevanceTags: ['discipline', 'rules', 'consistency'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['checklist', 'decision-quality', 'consistency'], prerequisites: ['trading-discipline'],
    nextSteps: ['consistency'], followups: ['decision-quality', 'trader-assessment'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'consistency', category: 'discipline', topic: 'Consistency', level: 'intermediate',
    title: 'Achieving Consistency', intent: 'psychology',
    concepts: ['consistency', 'process', 'repeatability', 'discipline', 'growth'],
    questionPatterns: ['how do i become a consistent trader', 'why am i not consistent trading', 'how to be consistent in trading', 'what makes a trader consistent', 'consistency in trading'],
    canonical: {
      short: 'Consistency comes from doing the same right things repeatedly — same risk, same setups, same routine — not from chasing variety. It is a by-product of disciplined process, which is why boring traders so often outperform clever ones.',
      deep: 'Inconsistent results almost always trace back to inconsistent behaviour: changing risk, jumping between strategies, trading different sizes by mood. The path to consistency is narrow on purpose — one or two setups, fixed risk, a repeatable routine, and honest review — applied for long enough that an edge can show through the noise. It feels unexciting, and that is the point: excitement is usually the sign of an unrepeatable decision. Aim to make your trading boringly the same day to day, and the equity curve gradually starts to reflect that stability.',
    },
    responseObjective: 'mentor', desiredOutcome: 'make behaviour repeatable so results stabilise',
    relevanceTags: ['discipline', 'consistency', 'process'],
    guidance: { traderProblem: true },
    related: ['rule-following', 'habit-building', 'becoming-profitable'], prerequisites: ['trading-discipline'],
    nextSteps: ['becoming-profitable'], followups: ['habit-building', 'process-focus'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'habit-building', category: 'discipline', topic: 'Building Good Habits', level: 'intermediate',
    title: 'Building Good Trading Habits', intent: 'psychology',
    concepts: ['habits', 'routine', 'discipline', 'repetition', 'systems'],
    questionPatterns: ['how do i build good trading habits', 'how to develop trading discipline habits', 'building habits as a trader', 'how to make discipline automatic', 'good habits for traders'],
    canonical: {
      short: 'Good habits beat willpower because willpower runs out and habits do not. Build trading discipline the way you build any habit — small, repeated, and tied to your existing routine — until the right action becomes the automatic one.',
      deep: 'Relying on motivation to be disciplined fails on the days you need it most. Instead, design habits: attach a checklist to opening your platform, a journal entry to closing each trade, a fixed risk to every order. Start small and keep the chain unbroken, because the goal is automaticity — making the disciplined action the path of least resistance. Over weeks these habits compound into a system that runs even when you are tired or emotional. You do not rise to the level of your goals; you fall to the level of your systems, so build the systems deliberately.',
    },
    responseObjective: 'mentor', desiredOutcome: 'make discipline automatic through habit design',
    relevanceTags: ['discipline', 'habits', 'systems'],
    guidance: { traderProblem: true },
    related: ['trading-routine', 'consistency', 'trading-journal'], prerequisites: ['trading-discipline'],
    nextSteps: ['process-focus'], followups: ['consistency', 'trading-journal'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'process-focus', category: 'discipline', topic: 'Process Over Outcome', level: 'intermediate',
    title: 'Focusing on Process Over Outcome', intent: 'psychology',
    concepts: ['process', 'outcome', 'detachment', 'discipline', 'mindset'],
    questionPatterns: ['why focus on process not profit', 'process over outcome trading', 'how to stop obsessing over profit', 'should i focus on money or process', 'process focused trading'],
    canonical: {
      short: 'Focusing on process means judging yourself on how well you executed, not on whether the trade won — because outcome is partly random while execution is fully yours. Get the process right repeatedly and good outcomes follow on their own.',
      deep: 'Any single trade can lose with perfect execution or win despite a sloppy one, so scoring yourself on profit teaches the wrong lessons and feeds emotional swings. Shift the scoreboard to process: did I follow my plan, manage risk, and execute the checklist? When you win on process, you reinforce good behaviour regardless of the result, and you stop chasing or revenge-trading after losses. This detachment is freeing — it lets you take the next valid setup calmly, knowing your job is execution and that the math rewards good process over a large enough sample.',
    },
    responseObjective: 'mentor', desiredOutcome: 'judge yourself by execution, not by P&L',
    relevanceTags: ['discipline', 'process', 'mindset'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['decision-quality', 'trader-mindset', 'consistency'], prerequisites: ['trading-discipline'],
    nextSteps: ['decision-quality'], followups: ['trader-mindset', 'becoming-profitable'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'decision-quality', category: 'discipline', topic: 'Decision Quality', level: 'advanced',
    title: 'Improving Decision Quality', intent: 'psychology',
    concepts: ['decision quality', 'process', 'review', 'judgement', 'discipline'],
    questionPatterns: ['how do i make better trading decisions', 'what is decision quality in trading', 'how to improve trading judgement', 'separating good decisions from good outcomes', 'decision quality trading'],
    canonical: {
      short: 'Decision quality is about whether a choice was sound given what you knew at the time — separate from whether it happened to work. Judging decisions instead of outcomes is how you actually learn, because you reward good thinking and fix bad thinking regardless of luck.',
      deep: 'In a probabilistic game, good decisions sometimes lose and bad ones sometimes win, so outcome-based learning is misleading — it can punish a great trade that lost and reward a reckless one that paid off. The professional habit is to review the decision: given the information and your rules at entry, was this the right action? Label trades as good or poor decisions in your journal, independent of result. Over time this trains genuine judgement, filters luck out of your feedback loop, and steadily raises the quality of your choices, which is the only thing that compounds reliably.',
    },
    responseObjective: 'mentor', desiredOutcome: 'learn from decision quality, not lucky outcomes',
    relevanceTags: ['discipline', 'decision', 'review'],
    guidance: { traderProblem: true },
    related: ['process-focus', 'execution-discipline', 'trading-journal'], prerequisites: ['trading-discipline'],
    nextSteps: ['execution-discipline'], followups: ['process-focus', 'trading-journal'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'execution-discipline', category: 'discipline', topic: 'Execution Discipline', level: 'intermediate',
    title: 'Disciplined Trade Execution', intent: 'psychology',
    concepts: ['execution', 'discipline', 'entries', 'exits', 'consistency'],
    questionPatterns: ['how do i execute trades with discipline', 'why do i mess up execution', 'how to follow my plan when executing', 'disciplined trade execution', 'sticking to entries and exits'],
    canonical: {
      short: 'Execution discipline is doing exactly what your plan says at entry and exit — no widening stops, no skipping the trigger, no early exits from fear. The plan is only as good as your willingness to follow it in the moment.',
      deep: 'A sound plan fails the instant execution drifts: you move the stop to avoid being wrong, exit a winner early from anxiety, or enter before the trigger from impatience. Tightening execution starts with small risk (so emotion stays low) and a clear plan written before the trade, then practising mechanical follow-through on every order. Treat each correctly executed trade as a win in itself, win or lose, because that is the behaviour you are training. Over time, disciplined execution becomes your default, and the gap between your strategy on paper and your results in reality finally closes.',
    },
    responseObjective: 'mentor', desiredOutcome: 'execute the plan exactly, every time',
    relevanceTags: ['discipline', 'execution', 'consistency'],
    guidance: { traderProblem: true },
    recommendedAssessment: 'trader',
    related: ['decision-quality', 'rule-following', 'consistency'], prerequisites: ['trading-discipline'],
    nextSteps: ['consistency'], followups: ['decision-quality', 'trader-assessment'],
    riskNote: 'Never widen a stop to avoid being wrong — that is execution discipline breaking down.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
