// functions/knowledge/forex/concepts.js
// CATEGORY: forex (NEW) — fundamentals through correlations. Same KOS shape as anchors.

export const FOREX_CONCEPTS = [
  {
    id: 'forex-basics', category: 'forex', topic: 'Forex Basics', level: 'beginner',
    title: 'Forex Trading Basics', intent: 'technical',
    concepts: ['forex', 'currency', 'pairs', 'exchange rate', 'basics'],
    questionPatterns: ['what is forex trading', 'how does forex work', 'forex basics for beginners', 'how do currency pairs work', 'explain forex simply'],
    canonical: {
      short: 'Forex is simply trading one currency against another — you are always betting that one side of a pair will strengthen versus the other. Start by understanding that every trade is a relationship, not a single asset, and the mechanics (pips, lots, leverage) all flow from that.',
      deep: 'In forex you trade pairs like EURUSD, where buying means betting the euro rises against the dollar. Prices move in tiny increments called pips, your trade size is measured in lots, and brokers let you control larger positions with leverage. None of this is complicated once you see the structure: pick a pair, decide which currency you expect to lead, size the position for your risk, and manage it with a stop. Master the basics here and the rest of forex is just depth on the same foundation.',
    },
    responseObjective: 'educate', desiredOutcome: 'a clear mental model of what forex actually is',
    relevanceTags: ['forex', 'basics'],
    guidance: { tradeProblem: true },
    related: ['pip-value', 'lot-size', 'major-pairs'], prerequisites: [],
    nextSteps: ['pip-value'], followups: ['lot-size', 'major-pairs'],
    riskNote: 'Start on demo or tiny live size until the mechanics feel automatic.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'pip-value', category: 'forex', topic: 'Pip Value', level: 'beginner',
    title: 'Understanding Pip Value', intent: 'technical',
    concepts: ['pip', 'pip value', 'price movement', 'profit', 'forex'],
    questionPatterns: ['what is a pip', 'how is pip value calculated', 'what is pip value in forex', 'how much is a pip worth', 'explain pips'],
    canonical: {
      short: 'A pip is the standard small unit a currency pair moves — usually the 4th decimal. Pip value is just how much money each pip is worth for your position size, and it is the bridge between "the chart moved 20 pips" and "I made or lost X dollars".',
      deep: 'For most pairs a pip is 0.0001 of price; for yen pairs it is 0.01. The money you make or lose per pip depends on your lot size: roughly $10 per pip on a standard lot, $1 on a mini, $0.10 on a micro for USD-quoted pairs. Knowing pip value matters because it lets you translate a stop-loss distance directly into a dollar risk — which is exactly the calculation that drives correct position sizing. Get comfortable here and risk control stops being abstract.',
    },
    responseObjective: 'educate', desiredOutcome: 'translate pip distance into real money risk',
    relevanceTags: ['forex', 'pips'],
    guidance: { tradeProblem: true },
    related: ['lot-size', 'forex-basics', 'position-sizing'], prerequisites: ['forex-basics'],
    nextSteps: ['lot-size'], followups: ['leverage', 'position-sizing'],
    riskNote: 'Always convert your stop distance to a dollar amount before entering.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'lot-size', category: 'forex', topic: 'Lot Size', level: 'beginner',
    title: 'Forex Lot Sizes', intent: 'riskmgmt',
    concepts: ['lot size', 'standard lot', 'mini lot', 'micro lot', 'position size'],
    questionPatterns: ['what is a lot in forex', 'standard mini micro lot difference', 'what lot size should i use', 'how big is a forex lot', 'explain lot sizes'],
    canonical: {
      short: 'A lot is your trade size: standard (100k units), mini (10k), or micro (1k). The lot you choose should fall out of your risk math, not your excitement — pick the size that keeps a stop-out to about 1% of your account.',
      deep: 'Lot size decides how much each pip is worth, which is why it should be the LAST thing you set, not the first. The professional order is: decide the percent you will risk, measure the stop in pips, then choose the lot that makes that stop equal your risk amount. Beginners reverse this — they pick a round lot, then discover the loss is huge. Anchor on the money, let the lot follow, and the same trade that blows accounts becomes survivable.',
    },
    responseObjective: 'educate', desiredOutcome: 'let risk choose the lot, not the other way round',
    relevanceTags: ['forex', 'lot size', 'risk'],
    guidance: { tradeProblem: true },
    related: ['pip-value', 'position-sizing', 'leverage'], prerequisites: ['pip-value'],
    nextSteps: ['position-sizing'], followups: ['leverage', 'margin'],
    riskNote: 'If the lot size feels exciting, it is too big.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'leverage', category: 'forex', topic: 'Leverage', level: 'beginner',
    title: 'Leverage in Forex', intent: 'riskmgmt',
    concepts: ['leverage', 'margin', 'buying power', 'risk', 'forex'],
    questionPatterns: ['what is leverage in forex', 'how does leverage work', 'is high leverage dangerous', 'what leverage should i use', 'explain leverage simply'],
    canonical: {
      short: 'Leverage lets you control a large position with a small deposit — it multiplies both profit and loss. It is a tool, not free money: high leverage does not increase your edge, it only increases how fast a mistake hurts.',
      deep: 'Leverage of 1:100 means $1,000 controls $100,000 of currency. The trap is thinking more leverage means more opportunity — in reality your real risk is set by your position size and stop, not the leverage number. Two traders on different leverage who risk 1% per trade have identical risk; the high-leverage trader just has more rope to hang themselves if they oversize. Use leverage as access, keep risk per trade small, and it becomes a non-issue.',
    },
    responseObjective: 'warn', desiredOutcome: 'treat leverage as access, not as bigger edge',
    relevanceTags: ['forex', 'leverage', 'risk'],
    guidance: { tradeProblem: true },
    related: ['margin', 'lot-size', 'risk-per-trade'], prerequisites: ['lot-size'],
    nextSteps: ['margin'], followups: ['risk-per-trade', 'capital-protection'],
    riskNote: 'Leverage magnifies losses first — your stop and size are what actually control risk.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'margin', category: 'forex', topic: 'Margin', level: 'beginner',
    title: 'Margin and Margin Calls', intent: 'riskmgmt',
    concepts: ['margin', 'free margin', 'margin call', 'stop out', 'leverage'],
    questionPatterns: ['what is margin in forex', 'what is a margin call', 'how does free margin work', 'why did i get a margin call', 'explain margin'],
    canonical: {
      short: 'Margin is the deposit your broker locks to hold a position; free margin is what is left to absorb losses. A margin call means you are running out of cushion — almost always a symptom of positions that are too big, not bad luck.',
      deep: 'When you open a trade, the broker reserves margin based on size and leverage. As trades move against you, your free margin shrinks; cross the broker\'s threshold and you get a margin call or an automatic stop-out at the worst possible time. The fix is never "deposit more to survive" — it is sizing so that no realistic drawdown ever threatens your margin. If margin calls are happening, the account is telling you the positions are too large for it.',
    },
    responseObjective: 'warn', desiredOutcome: 'avoid margin calls by sizing within your cushion',
    relevanceTags: ['forex', 'margin', 'risk'],
    guidance: { tradeProblem: true },
    related: ['leverage', 'lot-size', 'account-preservation'], prerequisites: ['leverage'],
    nextSteps: ['account-preservation'], followups: ['risk-per-trade', 'max-drawdown'],
    riskNote: 'A margin call is an oversizing alarm — reduce size, do not just top up funds.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'spread', category: 'forex', topic: 'Spread', level: 'beginner',
    title: 'The Spread', intent: 'broker',
    concepts: ['spread', 'bid ask', 'cost', 'liquidity', 'forex'],
    questionPatterns: ['what is the spread in forex', 'how does spread affect my trades', 'why is the spread important', 'what is bid and ask', 'why did my spread widen'],
    canonical: {
      short: 'The spread is the gap between the buy and sell price — your first cost on every trade. Tight, stable spreads on liquid pairs are a sign of healthy conditions; spreads that balloon around news or on a shady broker quietly eat your edge.',
      deep: 'You enter every trade slightly in loss by the size of the spread, so it matters most for short-term and high-frequency styles. Major pairs in active sessions carry the tightest spreads; exotics, illiquid hours and news events widen them sharply, which is one reason chasing trades into a release is expensive. When comparing brokers, watch real spreads during normal AND news conditions, not just the marketing number — a broker that widens unpredictably is costing you on every fill.',
    },
    responseObjective: 'educate', desiredOutcome: 'treat spread as a managed cost of every trade',
    relevanceTags: ['forex', 'spread', 'cost'],
    guidance: { tradeProblem: true },
    related: ['swap', 'execution-models', 'spread-comparison'], prerequisites: ['forex-basics'],
    nextSteps: ['swap'], followups: ['spread-comparison', 'execution-models'],
    riskNote: 'Spreads widen in news and thin hours — factor that cost in or step aside.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'swap', category: 'forex', topic: 'Swap', level: 'intermediate',
    title: 'Swap and Overnight Fees', intent: 'broker',
    concepts: ['swap', 'rollover', 'overnight', 'interest', 'carry'],
    questionPatterns: ['what is swap in forex', 'what are overnight fees', 'how does swap work', 'why was i charged swap', 'is swap good or bad'],
    canonical: {
      short: 'Swap is the interest you pay or earn for holding a trade overnight, based on the rate difference between the two currencies. For short-term traders it is a small detail; for swing and position traders it quietly adds up, and it is also the reason swap-free accounts exist.',
      deep: 'Every currency carries an interest rate, and holding a pair overnight means you are long one rate and short the other — the net is your swap, charged or credited at rollover (and often tripled mid-week to cover the weekend). Positive carry can pay you to hold; negative carry bleeds a long-term position. If you trade intraday it rarely matters, but if you swing trades for days, factor swap into the plan. For traders avoiding interest on religious grounds, swap-free accounts remove it entirely.',
    },
    responseObjective: 'educate', desiredOutcome: 'account for overnight cost in longer holds',
    relevanceTags: ['forex', 'swap', 'cost'],
    guidance: { tradeProblem: true },
    related: ['rollover', 'carry-trade', 'islamic-overview'], prerequisites: ['forex-basics'],
    nextSteps: ['rollover'], followups: ['carry-trade', 'islamic-overview'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'rollover', category: 'forex', topic: 'Rollover', level: 'intermediate',
    title: 'Rollover Explained', intent: 'broker',
    concepts: ['rollover', 'swap', 'settlement', 'overnight', 'forex'],
    questionPatterns: ['what is rollover in forex', 'when does rollover happen', 'rollover vs swap', 'why is rollover charged at 5pm', 'how does rollover work'],
    canonical: {
      short: 'Rollover is the daily moment (typically 5pm New York) when open trades are rolled to the next settlement day and swap is applied. It is the "when" behind the swap cost — useful to know so an overnight charge never surprises you.',
      deep: 'Spot forex technically settles in two days, so brokers roll open positions forward each day at the rollover time rather than delivering currency. That roll is when your swap is debited or credited, and because weekends do not trade, the Wednesday rollover is usually charged triple to account for them. None of this changes your strategy, but understanding it removes the confusion of seeing a balance tick at 5pm and helps swing traders plan around the heavier mid-week charge.',
    },
    responseObjective: 'educate', desiredOutcome: 'understand when and why overnight charges hit',
    relevanceTags: ['forex', 'rollover', 'swap'],
    guidance: { tradeProblem: true },
    related: ['swap', 'carry-trade', 'forex-sessions'], prerequisites: ['swap'],
    nextSteps: ['carry-trade'], followups: ['forex-sessions', 'swap'],
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'major-pairs', category: 'forex', topic: 'Major Pairs', level: 'beginner',
    title: 'Major Currency Pairs', intent: 'technical',
    concepts: ['major pairs', 'eurusd', 'gbpusd', 'usdjpy', 'liquidity'],
    questionPatterns: ['what are major forex pairs', 'which pairs should a beginner trade', 'what are the majors', 'best forex pairs to start with', 'why trade major pairs'],
    canonical: {
      short: 'The majors are the most-traded pairs — all involving the US dollar, like EURUSD, GBPUSD and USDJPY. They offer the tightest spreads and cleanest behaviour, which is exactly why beginners should start here before touching anything exotic.',
      deep: 'Major pairs dominate global volume, so they are liquid, relatively well-behaved and cheap to trade. EURUSD is the most liquid pair on earth and a sensible first instrument; GBPUSD moves more; USDJPY ties closely to yields and risk sentiment. Focusing on one or two majors while you learn beats spreading attention across dozens of pairs — depth of familiarity with a single market compounds into an edge faster than shallow exposure to many.',
    },
    responseObjective: 'educate', desiredOutcome: 'start on liquid, well-behaved markets',
    relevanceTags: ['forex', 'pairs', 'majors'],
    guidance: { tradeProblem: true },
    related: ['minor-pairs', 'exotic-pairs', 'correlation'], prerequisites: ['forex-basics'],
    nextSteps: ['minor-pairs'], followups: ['correlation', 'forex-sessions'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'minor-pairs', category: 'forex', topic: 'Minor Pairs', level: 'intermediate',
    title: 'Minor (Cross) Pairs', intent: 'technical',
    concepts: ['minor pairs', 'crosses', 'eurgbp', 'eurjpy', 'no usd'],
    questionPatterns: ['what are minor forex pairs', 'what are cross pairs', 'difference between major and minor pairs', 'should i trade crosses', 'examples of minor pairs'],
    canonical: {
      short: 'Minor pairs (crosses) are liquid pairs that skip the US dollar — think EURGBP or EURJPY. They open up cleaner trends when the dollar is messy, but they move a bit more and cost a bit more, so they suit traders past the beginner stage.',
      deep: 'Crosses let you trade currency strength directly without the dollar in the middle, which is powerful when USD is choppy but two other economies are clearly diverging. They are still liquid but typically carry slightly wider spreads and sharper moves than the majors. The smart use is currency-strength logic: pair a strong currency against a weak one (e.g. a hawkish central bank versus a dovish one) and you often get cleaner trends than fighting dollar noise.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade currency strength without dollar noise',
    relevanceTags: ['forex', 'pairs', 'crosses'],
    guidance: { tradeProblem: true },
    related: ['major-pairs', 'exotic-pairs', 'correlation'], prerequisites: ['major-pairs'],
    nextSteps: ['correlation'], followups: ['exotic-pairs', 'forex-volatility'],
    riskNote: 'Crosses move more than majors — size for the wider range.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'exotic-pairs', category: 'forex', topic: 'Exotic Pairs', level: 'advanced',
    title: 'Exotic Currency Pairs', intent: 'technical',
    concepts: ['exotic pairs', 'usdtry', 'usdzar', 'illiquid', 'wide spread'],
    questionPatterns: ['what are exotic forex pairs', 'should i trade exotics', 'why are exotic pairs risky', 'examples of exotic pairs', 'exotic pairs spreads'],
    canonical: {
      short: 'Exotic pairs match a major currency with an emerging-market one (like USDTRY or USDZAR). They can trend hard, but wide spreads, thin liquidity and sudden gaps make them unforgiving — they reward respect and punish casual size.',
      deep: 'Exotics are where political and economic shocks hit hardest, producing huge moves and equally huge spreads. Liquidity can vanish, slippage is real, and overnight swaps are often steep. They are not "beginner pairs with bigger profits" — they demand smaller size, wider stops and full awareness that a gap can blow past your risk. Trade them only once your risk discipline is automatic, and even then treat position size as the main control, not the stop.',
    },
    responseObjective: 'warn', desiredOutcome: 'respect exotic risk with smaller size',
    relevanceTags: ['forex', 'pairs', 'exotics'],
    guidance: { tradeProblem: true },
    related: ['minor-pairs', 'forex-volatility', 'major-pairs'], prerequisites: ['minor-pairs'],
    nextSteps: ['forex-volatility'], followups: ['correlation', 'forex-volatility'],
    riskNote: 'Exotics gap and slip — size down hard and never assume your stop fills exactly.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'correlation', category: 'forex', topic: 'Currency Correlation', level: 'intermediate',
    title: 'Currency Pair Correlation', intent: 'technical',
    concepts: ['correlation', 'positive correlation', 'negative correlation', 'exposure', 'risk'],
    questionPatterns: ['what is currency correlation', 'how does forex correlation work', 'which pairs are correlated', 'why does correlation matter for risk', 'positive and negative correlation forex'],
    canonical: {
      short: 'Correlation describes pairs that tend to move together (positive) or opposite (negative). It matters most for risk: taking two strongly correlated trades is secretly one big trade, doubling your exposure without you noticing.',
      deep: 'EURUSD and GBPUSD often move together; EURUSD and USDCHF often move opposite. The danger is hidden concentration — long EURUSD and long GBPUSD is effectively a double-sized short-dollar bet, so a single dollar move hits both. Use correlation two ways: avoid stacking correlated risk, and use it as confluence (if related markets agree with your read, conviction rises). Checking correlation before adding a position is a simple habit that prevents accidental over-exposure.',
    },
    responseObjective: 'educate', desiredOutcome: 'avoid hidden double exposure from correlated trades',
    relevanceTags: ['forex', 'correlation', 'risk'],
    guidance: { tradeProblem: true },
    related: ['major-pairs', 'minor-pairs', 'risk-per-trade'], prerequisites: ['major-pairs'],
    nextSteps: ['carry-trade'], followups: ['risk-per-trade', 'forex-sessions'],
    riskNote: 'Two correlated positions = one bigger position — count the real exposure.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'carry-trade', category: 'forex', topic: 'Carry Trade', level: 'advanced',
    title: 'The Carry Trade', intent: 'macro',
    concepts: ['carry trade', 'interest rate differential', 'swap', 'positive carry', 'forex'],
    questionPatterns: ['what is a carry trade', 'how does the carry trade work', 'carry trade explained', 'is the carry trade profitable', 'risks of carry trade'],
    canonical: {
      short: 'A carry trade earns the interest-rate gap between two currencies — you hold a higher-yielding currency against a lower-yielding one and collect positive swap. It pays you to wait, but it can unwind violently when sentiment turns, so it is a macro game, not a free lunch.',
      deep: 'The carry trade buys a high-rate currency funded by a low-rate one, banking the daily swap while ideally riding the trend in your favour. It works beautifully in calm, risk-on conditions and is brutal in risk-off shocks, when crowded carry positions unwind all at once and the "safe" income trade gaps hard. Treat carry as a positional, macro-aware strategy with conservative size and a genuine stop — the yield is real, but so is the tail risk.',
    },
    responseObjective: 'educate', desiredOutcome: 'understand carry income and its tail risk',
    relevanceTags: ['forex', 'carry', 'macro'],
    guidance: { tradeProblem: true },
    related: ['swap', 'correlation', 'economic-news-impact'], prerequisites: ['swap', 'correlation'],
    nextSteps: ['forex-sessions'], followups: ['economic-news-impact', 'forex-volatility'],
    riskNote: 'Carry unwinds fast in risk-off — keep size small and a real stop in place.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'forex-sessions', category: 'forex', topic: 'Forex Sessions', level: 'beginner',
    title: 'The Forex Trading Sessions', intent: 'technical',
    concepts: ['sessions', 'london', 'new york', 'asia', 'overlap'],
    questionPatterns: ['what are the forex sessions', 'best forex session to trade', 'when do forex sessions open', 'london new york overlap', 'what time should i trade forex'],
    canonical: {
      short: 'Forex runs 24/5 across the Asia, London and New York sessions, but the action concentrates in the London–New York overlap. Trading when your pair is liquid — not at 3am out of boredom — is one of the easiest edges to give yourself.',
      deep: 'Each session has a character: Asia is quieter and range-bound, London brings the first real volume and direction, and the London–New York overlap is the highest-liquidity window of the day. Matching your strategy to the right session matters — breakout styles like the London open, while range styles prefer quieter hours. Picking two or three high-quality hours that fit your pair and life beats staring at charts all day; quality of timing beats quantity of screen time.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade when your market is actually liquid',
    relevanceTags: ['forex', 'sessions', 'timing'],
    guidance: { tradeProblem: true },
    related: ['forex-volatility', 'major-pairs', 'london-session-gold'], prerequisites: ['forex-basics'],
    nextSteps: ['forex-volatility'], followups: ['major-pairs', 'trading-routine'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'forex-volatility', category: 'forex', topic: 'Forex Volatility', level: 'intermediate',
    title: 'Forex Volatility', intent: 'technical',
    concepts: ['volatility', 'atr', 'range', 'risk', 'forex'],
    questionPatterns: ['what is forex volatility', 'why does volatility matter in forex', 'how to measure forex volatility', 'which pairs are most volatile', 'how to trade volatile pairs'],
    canonical: {
      short: 'Volatility is how much a pair typically moves — and it should set your stops and size, not your fear. A volatile pair is not "better", it just needs wider stops and smaller positions so the same 1% risk still applies.',
      deep: 'Different pairs and sessions carry different volatility: GBP and JPY crosses and exotics swing more than EURUSD; news and overlaps spike it temporarily. Measuring typical range (ATR is a quick proxy) lets you place stops beyond the noise and then shrink the lot so risk stays constant. The mistake is using the same fixed stop and size everywhere — that quietly over-risks the volatile pairs and under-utilises the calm ones. Adapt size to volatility and your risk becomes consistent across every market.',
    },
    responseObjective: 'educate', desiredOutcome: 'adapt stop and size to each pair\'s volatility',
    relevanceTags: ['forex', 'volatility', 'risk'],
    guidance: { tradeProblem: true },
    related: ['forex-sessions', 'exotic-pairs', 'risk-per-trade'], prerequisites: ['forex-basics'],
    nextSteps: ['risk-per-trade'], followups: ['forex-sessions', 'position-sizing'],
    riskNote: 'Match position size to volatility so 1% risk stays 1% on every pair.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
