// functions/knowledge/price-action/concepts.js
// CATEGORY: price-action (NEW, Phase 5) — candles, signals, reversal/breakout models.

export const PRICE_ACTION_CONCEPTS = [
  {
    id: 'price-action-basics', category: 'price-action', topic: 'Price Action Basics', level: 'beginner',
    title: 'Price Action Trading Basics', intent: 'technical',
    concepts: ['price action', 'candles', 'naked chart', 'reading price'],
    questionPatterns: ['what is price action', 'how does price action trading work', 'price action basics', 'how to read price action', 'is price action better than indicators'],
    canonical: {
      short: 'Price action is reading raw price — candles, structure, and levels — instead of relying on lagging indicators. It teaches you to see what the market is doing now, not what an indicator says it did.',
      deep: 'Price action focuses on the story candles tell at meaningful levels: who is in control, where reactions happen, and how momentum behaves. Indicators are derived from price and always lag it, so price-action traders read the source directly. Start with structure and key levels, then learn the candle signals that mark reactions — the chart becomes a narrative rather than a tangle of lines.',
    },
    responseObjective: 'educate', desiredOutcome: 'read raw price instead of leaning on lagging indicators',
    relevanceTags: ['price action', 'candles'],
    guidance: { tradeProblem: true },
    related: ['candlestick-psychology', 'market-structure', 'support-resistance'], prerequisites: ['market-structure'],
    nextSteps: ['candlestick-psychology'], followups: ['support-resistance', 'reversal-models'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'candlestick-psychology', category: 'price-action', topic: 'Candlestick Psychology', level: 'beginner',
    title: 'The Psychology Behind Candlesticks', intent: 'technical',
    concepts: ['candlestick psychology', 'buyers sellers', 'wicks', 'bodies'],
    questionPatterns: ['what do candlesticks tell you', 'candlestick psychology explained', 'what does a candle body mean', 'how to read candle wicks', 'what is the psychology of a candle'],
    canonical: {
      short: 'Every candle is a battle between buyers and sellers: a long body shows conviction, a long wick shows rejection. Reading that psychology tells you who won the period and who is likely in control.',
      deep: 'The body shows the net result (who closed in control), while wicks show where price was rejected. A long lower wick at support means sellers pushed down and buyers slammed it back — rejection. Big bodies with little wick show one-sided conviction; small indecisive candles show balance. Reading candles as the footprint of a fight, especially at key levels, is the foundation of price-action signals.',
    },
    responseObjective: 'educate', desiredOutcome: 'interpret candles as buyer/seller intent',
    relevanceTags: ['price action', 'candlestick'],
    guidance: { tradeProblem: true },
    related: ['price-action-basics', 'pin-bar', 'engulfing-candle'], prerequisites: ['price-action-basics'],
    nextSteps: ['pin-bar'], followups: ['engulfing-candle', 'rejection-wick'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'pin-bar', category: 'price-action', topic: 'Pin Bar', level: 'intermediate',
    title: 'The Pin Bar (Rejection Candle)', intent: 'technical',
    concepts: ['pin bar', 'rejection', 'reversal candle', 'wick'],
    questionPatterns: ['what is a pin bar', 'how to trade a pin bar', 'what does a pin bar mean', 'pin bar reversal', 'is a pin bar reliable'],
    canonical: {
      short: 'A pin bar is a candle with a long wick and small body, showing price was pushed to a level and firmly rejected. At a meaningful level it signals a potential reversal — but location is everything.',
      deep: 'The long wick is the story: price probed a level and was rejected, leaving a small body at the other end. A pin bar at a strong support/resistance or after a liquidity sweep is high-quality; the same candle in the middle of nowhere is noise. Trade it with a stop beyond the wick and confirmation from structure, not in isolation.',
    },
    responseObjective: 'educate', desiredOutcome: 'trade pin bars only at meaningful levels',
    relevanceTags: ['price action', 'pin bar'],
    guidance: { tradeProblem: true },
    related: ['rejection-wick', 'engulfing-candle', 'support-resistance'], prerequisites: ['candlestick-psychology'],
    nextSteps: ['engulfing-candle'], followups: ['reversal-models', 'liquidity-sweep'],
    riskNote: 'A pin bar only matters at a level — stop goes beyond the wick.',
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'engulfing-candle', category: 'price-action', topic: 'Engulfing Candle', level: 'intermediate',
    title: 'Engulfing Candles', intent: 'technical',
    concepts: ['engulfing', 'momentum', 'reversal', 'candle'],
    questionPatterns: ['what is an engulfing candle', 'how to trade engulfing candles', 'bullish engulfing meaning', 'engulfing candle reversal', 'is an engulfing candle reliable'],
    canonical: {
      short: 'An engulfing candle fully covers the prior candle\'s body, showing a sharp shift in control. At a key level it signals momentum flipping — strongest when paired with a structure break.',
      deep: 'A bullish engulfing closes above the previous candle\'s open after a down move, meaning buyers overwhelmed sellers; the bearish version mirrors it. Like all candle signals, location decides quality: at support after a sweep, an engulfing is powerful; mid-range it is noise. Best treated as confirmation of a reversal idea you already have from structure and level, not a standalone trigger.',
    },
    responseObjective: 'educate', desiredOutcome: 'use engulfing candles as level-based confirmation',
    relevanceTags: ['price action', 'engulfing'],
    guidance: { tradeProblem: true },
    related: ['pin-bar', 'reversal-models', 'break-of-structure'], prerequisites: ['candlestick-psychology'],
    nextSteps: ['reversal-models'], followups: ['pin-bar', 'displacement'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'rejection-wick', category: 'price-action', topic: 'Rejection Wicks', level: 'beginner',
    title: 'Reading Rejection Wicks', intent: 'technical',
    concepts: ['rejection wick', 'wick', 'liquidity', 'level'],
    questionPatterns: ['what is a rejection wick', 'what does a long wick mean', 'how to read wicks', 'rejection wick trading', 'why do wicks matter'],
    canonical: {
      short: 'A rejection wick is a long tail showing price reached a level and got slammed back — proof that the level held. Clusters of rejection wicks at a zone mark where strong hands are defending.',
      deep: 'Wicks reveal where price was tried and refused. A long lower wick at support shows buyers stepped in hard; repeated wicks at the same zone confirm its strength. Wicks beyond an obvious high or low often mark a liquidity sweep before reversal. Reading wicks tells you where reactions are real, helping you place entries and stops around levels that actually matter.',
    },
    responseObjective: 'educate', desiredOutcome: 'use wicks to confirm which levels hold',
    relevanceTags: ['price action', 'wick'],
    guidance: { tradeProblem: true },
    related: ['pin-bar', 'support-resistance', 'liquidity-sweep'], prerequisites: ['candlestick-psychology'],
    nextSteps: ['pin-bar'], followups: ['support-resistance', 'stop-hunt'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
  {
    id: 'reversal-models', category: 'price-action', topic: 'Reversal Models', level: 'intermediate',
    title: 'Reversal Trading Models', intent: 'strategy',
    concepts: ['reversal model', 'turning point', 'change of character', 'reversal'],
    questionPatterns: ['what is a reversal model', 'how to trade reversals', 'best reversal setups', 'how to catch a reversal safely', 'reversal trading explained'],
    canonical: {
      short: 'A reversal model is a defined way to trade a turn — typically a liquidity sweep, a change of character (structure break against trend), then an entry on the pullback. It stops you from blindly guessing tops and bottoms.',
      deep: 'High-quality reversals are not single candles; they are a sequence: price sweeps liquidity beyond an obvious level, breaks short-term structure in the new direction (change of character), then offers a pullback entry into an order block or rejection level. Waiting for that confirmed sequence — rather than catching the falling knife — is what makes reversal trading survivable. Pair with a stop beyond the sweep extreme.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade confirmed reversal sequences, not guesses',
    relevanceTags: ['price action', 'reversal'],
    guidance: { tradeProblem: true },
    related: ['breakout-models', 'choch', 'trend-reversal'], prerequisites: ['choch', 'liquidity-sweep'],
    nextSteps: ['breakout-models'], followups: ['trend-reversal', 'entry-models'],
    riskNote: 'Wait for sweep + change of character — never catch the knife blindly.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'breakout-models', category: 'price-action', topic: 'Breakout Models', level: 'intermediate',
    title: 'Breakout Trading Models', intent: 'strategy',
    concepts: ['breakout model', 'continuation', 'expansion', 'breakout'],
    questionPatterns: ['what is a breakout model', 'how to trade breakouts safely', 'best breakout setups', 'breakout model explained', 'momentum vs retest breakout'],
    canonical: {
      short: 'A breakout model is a defined way to trade expansion: either the momentum break (close beyond a level with displacement) or the safer retest-and-hold of the broken level. The model filters real breaks from traps.',
      deep: 'Two robust models: (1) momentum — enter on a decisive close beyond the level with follow-through; (2) retest — wait for price to break, return to the level, and hold before entering, giving a tighter stop. Both demand confirmation so you avoid the false breaks that hunt stops. Combine with liquidity awareness (where stops sit) and you turn breakouts from a coin flip into a defined edge.',
    },
    responseObjective: 'mentor', desiredOutcome: 'trade breaks by a defined model, not blindly',
    relevanceTags: ['price action', 'breakout'],
    guidance: { tradeProblem: true },
    related: ['reversal-models', 'breakout-trading', 'false-breakout-trading'], prerequisites: ['breakout-trading'],
    nextSteps: ['entry-models'], followups: ['false-breakout-trading', 'trend-trading'],
    riskNote: 'Require a close + follow-through or a retest hold — blind breakouts get trapped.',
    status: 'published', origin: 'authored', confidence: 'MEDIUM', lang: 'en',
  },
  {
    id: 'doji-candle', category: 'price-action', topic: 'Doji Candle', level: 'beginner',
    title: 'The Doji (Indecision Candle)', intent: 'technical',
    concepts: ['doji', 'indecision', 'balance', 'candle'],
    questionPatterns: ['what is a doji candle', 'what does a doji mean', 'how to trade a doji', 'is a doji bullish or bearish', 'doji candle explained'],
    canonical: {
      short: 'A doji is a candle that opens and closes at nearly the same price — a sign of indecision and balance between buyers and sellers. It matters most at the end of a strong move, hinting momentum is stalling.',
      deep: 'On its own a doji is just a pause, but after an extended move into a key level it warns that the prevailing momentum is exhausting and a reversal or consolidation may follow. It is a context candle, not a trigger: use it to raise caution and wait for a confirming signal (pin bar, engulfing, or structure break) before acting.',
    },
    responseObjective: 'educate', desiredOutcome: 'read indecision but wait for confirmation',
    relevanceTags: ['price action', 'doji'],
    guidance: { tradeProblem: true },
    related: ['candlestick-psychology', 'pin-bar', 'engulfing-candle'], prerequisites: ['candlestick-psychology'],
    nextSteps: ['reversal-models'], followups: ['pin-bar', 'engulfing-candle'],
    status: 'published', origin: 'authored', confidence: 'HIGH', lang: 'en',
  },
];
